### ISSUE TITLE
Change url in the reverse proxy will cause a hydrate error

### ISSUE THREAD

**Issue by Capricair** [nuxt/nuxt.js#10054]
### Versions
- nuxt: 2.15.8
- node: 14.17.6

### Reproduction
1. create page `/m/index` and `/pc/index` listening port 3000
2. run a reverse proxy listening port 3001
3. reverse proxy resolve `/` to `localhost:3000/m/index`
4. visit localhost:3001

### What is Expected?
Render the page correctly

### What is actually happening?
Server render is correct, but throw error in hydrate

**Comment by dabrowiecki** [comment]
We have the same issue. @Capricair did you manage to work around it?

**Comment by danielroe** [comment]
I would guess this is because `vue-router` expects the URL to be `/m/index` (or, to put it the other way, the content it expects for route `/` doesn't match with the content that was SSRed at `/m/index`).

This is how Vue hydration works - the client state should match the server state. Effectively changing the route is one thing that can lead to a hydration error.

You might be able to set up your routes within your app so this isn't an issue, but that's really quite specific to your project.

**Comment by dabrowiecki** [comment]
Hi @danielroe,

url rewrite is quite a basic feature and it can be achieved also within Nuxt.js by using a simple middleware:
```
export default (req, res, next) => {
    if (req.url == "/rewrite-from")
    {
        req.url = "/rewrite-to";
    }

    next()
}
```

Is there a way to tell the hydrator to use a different url?

**Comment by danielroe** [comment]
You'll need to dive into the documentation for vue-router: https://v3.router.vuejs.org/

More advanced routing customisation is possible in Nuxt using https://github.com/nuxt-community/router-extras-module/ or https://github.com/nuxt-community/router-module.
