### ISSUE TITLE
Cannot read properties of undefined (reading '_isDestroyed')

### ISSUE THREAD

**Issue by FIDIMALALA** [nuxt/nuxt.js#10102]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
![image](https://user-images.githubusercontent.com/36688229/144432166-de60c33e-3ce4-4561-a2f8-0920c9a4fe8a.png)

**Comment by niubaobaozsy** [comment]
I have the same problem

**Comment by Quineone** [comment]
I have the same problem too

**Comment by apowellnz** [comment]
Yep same problem here too., been fighting this for the last month.  Works perfectly in build and generate locally, but when I commit changes and it's pushed to cloudflare. The issues occur. Tried many ways to reproduce locally, but failed. 

Will be moving away from nuxt and having to rewrite soon. Because the only way I can debug it, is by committing and waiting ~5 minutes to build. Just to see the small change I did had done nothing. I have time pressure from the client now.

I attempted to do this suggestion. https://stackoverflow.com/questions/61733478/typeerror-cannot-read-property-isdestroyed-of-undefined-vuejs 
But it's far too slow to work out. One thing I noted was. If you create a style that references a dom element outside the scope of the application. It'll cause it. but it is not limited too. 
e.g. in the app you have 
`http, body { overflow:hidden; }` 
within a component that uses slots, and nuxtpage...
But other that that, I have not been able to nail it down further. It just seems random. 

Will watch this ticket as well, but looking at the rate it has been moving I don't think it'll go anywhere.
