### ISSUE TITLE
Nuxt 2 is now broken due to dependencies being deprecated. 

### ISSUE THREAD

**Issue by 23brewert** [nuxt/nuxt.js#10108]
### Versions

- nuxt: v2.15.7
- node: v16.13.1
- npm: v8.2.0 

### Reproduction
Run `npx create-nuxt-app test`
use the following configuration:
![df06f9b58f2c44abfbde5f697ec6c901-png](https://user-images.githubusercontent.com/40927593/144757718-6af634dd-b270-40f7-9487-d2e8fb527d5e.jpg)

then cd into the test directory
then run `npm run dev`.
The terminal will warn you that a lot of the dependencies are deprecated. The remove the warning when it finishes. so when you go to the web page in your browser it looks like 
![Screenshot_2021-12-03_1 06 09_PM](https://user-images.githubusercontent.com/40927593/144757703-770a94c3-fa97-4f4d-bdb1-af39f25a41b9.png)

**Comment by danielroe** [comment]
I can't reproduce this. Would you provide a reproduction please? 🙏

**Comment by eli-me** [comment]
Nuxt 2.xx is not compatible with node 16x

Node gyp fails install because the node-gyp version used to build nuxt is 3.x

I've had to reinstall Node 14 to run Nuxt2

as for reproduction, you can try installing Node 16 first, then create a new Nuxt project.
old Nuxt projects compiled with previous node versions run unless you remove package.lock and node_modules

**Comment by treboryx** [comment]
Can confirm nuxt 2 won't run with node LTS version (v16). I usually get node-fibers errors myself, and node-fibers is broken as of v16 because of a breaking change.
