### ISSUE TITLE
TypeError undefined is not an object (evaluating 'l.fetch') in  mixins/fetch.client.js

### ISSUE THREAD

**Issue by filippolcr** [nuxt/nuxt.js#10209]
### Versions
- nuxt: ex: v2.15.8 
- node: v14.17.0

### Reproduction
At the moment is impossible to provide a minimal reproduction repo. 

### Steps to reproduce
I've a normal page with fetch hook and some api calls to retrieve some data.
In template:
`<div v-if="$fetchState.pending"/> <div v-else> ... </div>`

When normal navigation (nuxt-link) happens the error does not occur. 
Clicking the refresh button the js breaks without error in console. (it is impossible to click on the links or open the menu for example)
Thanks to Sentry I've found the exact error:

**TypeError undefined is not an object (evaluating 'l.fetch') in  node_modules/.cache/mixins/fetch.client.js at line 42**

`const data = nuxtState.fetch[this._fetchKey]`

### What is Expected?
When refresh happens JS must not break as per normal navigation aka nuxt-link

### What is actually happening?
Js breaks without errors in console

### Questions
What do you need to know about my nuxt configuration/implementation?

**Comment by azpery** [comment]
Hey @filippolcr , 

I also have this problem in production, it seems to be problem a problem with window.__NUXT__ not instantiated. In my opinion it happens only in ssr. The problem seems to occur mainly on safari. 

But, maybe this can help : I'm adding this on my default layout  (I'm working in typescript): 

 beforeCreate() {
    if (process.client && (window as any).__NUXT__ === undefined) {
      ;(window as any).__NUXT__ = { fetch: {} }
    }
  }

Since in client.js there is a fallback on empty object I think they forgot to add it in fetch.client.js
<img width="321" alt="Capture d’écran 2022-03-02 à 18 48 52" src="https://user-images.githubusercontent.com/9019431/156418972-f06fa8c8-c9e9-4e6f-b22f-05ed5861830b.png">

**Comment by azpery** [comment]
I pushed this to my production and we don't have this error flowing on Sentry. I don't know yet if it just silenced the error or really fixed it..

**Comment by filippolcr** [comment]
Hey @azpery thanks for your tips. let's give it a try.
