### ISSUE TITLE
Memory issues on production ( big app )

### ISSUE THREAD

**Issue by gkatsanos** [nuxt/nuxt.js#10244]
We have a mid-large application running in a container on AWS, we noticed our instances periodically die because of memory issues.  We have a lot of sessions/users (enterprise app)

I managed to run our app in inspect mode, 
```
     "dev:debug": "DEBUG=nuxt:* node --inspect node_modules/.bin/nuxt",
``` 
and attach to it, got a memory snapshot.. but no clue how to link this to actual source code. (it's compiled of course).

Anyone has any hint?

**Comment by treboryx** [comment]
I think a bit more information here is required, in order to get proper help.

Usually, they'll ask for a repo where the issue can be reproduced, however here's some questions that may help.

Are you sure there's no code issues?
Is it running on SSR or generate mode?
Have you fried disabling the crawler if it's in generate mode?
Have you tried using no-prefetch on your nuxt-links (if they're too many)?
Are you using a large dependency that could potentially cause this?

Hopefully these questions help you find what's wrong, because otherwise the Nuxt team will ask for a repo where they can reproduce. They're also very busy working on nuxt 3 (which I would recommend upgrading to, with nuxt bridge)

**Comment by gkatsanos** [comment]
The issue was a Nuxt Plugin (based on the sentry module) that was apparently exhibiting a memory leak.

**Comment by matthewfee** [comment]
@gkatsanos I have the same question as above. How did you end up debugging this?
