### ISSUE TITLE
Instagram iOS in-app browser has no history when using NuxtLink

### ISSUE THREAD

**Issue by leefroese** [nuxt/nuxt.js#10324]
I've found that NuxtLink doesn't seem to set the browser history when using Instagram on iOS in-app browser. The next/prev browser buttons don't work at all. 

### Versions

- nuxt: 2.15.8
- node: 14.17.0

### Reproduction

- On iOS, open Instagram App
- Go to @rugandweave profile and click the link to their shop
- Navigate through a number of pages
- See the browser Back / Next buttons don't work or activate when pages change

Here's an example of NuxtLink usage when linking to a product on the site:

```
<NuxtLink :to="{ name: 'shop-handle', params: { handle: product.node.handle } }" class="w-full block">
    <picture class="[ block ]">
          <source :srcset="product.node.images.edges[0].node.webp" type="image/webp">
          <source :srcset="product.node.images.edges[0].node.default" type="image/jpeg">
          <img :src="product.node.images.edges[0].node.default" :alt="product.node.title" class="w-full" width="380" height="380" loading="lazy" />
    </picture>
    <span class="product-card-view">View</span>
</NuxtLink>
```

Here's an example from the menu

```
<NuxtLink :to="item.url">{{item.label}}</NuxtLink>
```

Switching from using `NuxtLink` to traditional anchor links has fixed the problem. This seems to be an issue in Next.js as well https://stackoverflow.com/questions/67200158/nextjs-back-forward-button-not-working-in-in

**Comment by danielroe** [comment]
This sounds like an issue with the Instagram iOS in-app browser, rather than Nuxt.

Vue Router (which is what handles navigation) interacts with [`window.history`](https://developer.mozilla.org/en-US/docs/Web/API/Window/history). You could try using a different router mode, like `hash` mode - see more at https://nuxtjs.org/docs/configuration-glossary/configuration-router/#mode - with the difference between hash and history modes explained at https://v3.router.vuejs.org/guide/essentials/history-mode.html#html5-history-mode.
