### ISSUE TITLE
v-html not working on dynamic tag 

### ISSUE THREAD

**Issue by m0ksem** [nuxt/nuxt.js#10333]
### Versions

- nuxt:  Latest version: 3.0.0-27457132.e67ed55
- node:  14.18.0

### Reproduction

https://codesandbox.io/s/nuxt-component-is-html-qfoqdk?file=/app.vue

### Steps to reproduce
Create a block with :is and try to use v-html directive

### What is Expected?
HTML rendered inside dynamic tag (worked well in vue cli spa project)

### What is actually happening?
HTML inside dynamic tag not rendering.

**Comment by vampics** [comment]
@danielroe Bug ist not fixed yet and a annoying issue in Nuxt 3.x not 2.x (Tagged as 2 :D).

Version: Nuxt 3.1.2 with Nitro 2.1.2 
node: v16.16.0

It seems that it only occurs in Nuxt 3 and not in Vue 3. I only notice the error in Dev Mode (but only because I didn't get any further). The v-html content is just empty (not undefined) at the first site load. As soon as the HRM is hydrating the page, v-html shows the given content.

**Comment by danielroe** [comment]
Would you open a new issue with a reproduction, and first check that it's not replicable on Vue 3 SSR without Nuxt, via https://stackblitz.com/github/nuxt-contrib/vue3-ssr-starter/tree/main ? 🙏

**Comment by vampics** [comment]
Ah! Intresting.

Vue3 SSR Starter has these issue too:
https://stackblitz.com/edit/github-bd1lay?file=src/components/Testvue.vue

But not the offical Vue 3 Playground:
https://sfc.vuejs.org/#eNp9ksFugzAMhl/FyqWbVODO0k57gx16zIWBKanAiRKXTqp49znAJrpJQwglv60P+7fv6s37fLyiKpWOdbCeISJf/dGQYTt4FxjuELCFCdrgBthJ8s4QwBo8YWSRlqBRebEKCWrUiyFdLNxEJM04+L5ilBtAtjzpqL85XJ0PRjV2NAoYP1ku2h9PnY0gryPoXdUAOamzczehS6kKikeeLn7+o/ZqqTQbKp9foiNp9Z6yzRqIRpUwK0mbyy7l0DH7WBZFbOvUyyXmLpyL1Fm4kliDOcYh+wjuFjEI2Kj9hlGIOGLIAlKDAcN/zF+pf7gJOxmapJWNuWliD27q2kk/hMRQ2ii+iZVizZh1PPTpKm6uVm38maeynTz0FaURJF8kaokxtFWN8B6cj4tRQn4tIXKwdJYRiyDsrSLlGqodxbQ9kg0H2MlMd/s5U3bpAA22lnCG6vl7fHp+XBc1fQHhGuYu

@danielroe Looks für me like a problem in Vite?!? The error is also present in the static generation in the nuxt. Unfortunately, I'm not sure exactly where the bug comes from and where I should set the issue. Vite, vite-vue-plugin, vue. A little bit confusing. Any Idea?

**Comment by danielroe** [comment]
I would think it's likely a behaviour of Vue 3 SSR, which is not being used in the Vue 3 playground. You can raise at https://github.com/vuejs/core.

**Comment by vampics** [comment]
Thanks Daniel! 

Looks like an old bug that still open :/

https://github.com/vuejs/core/issues/6435

**Comment by parigi-n** [comment]
It seems than Evan You doesn't want to fix this as he doesn't want that v-html attribute to be supported in Vue 3.
Technically, is this something we could patch on the Nuxt side?

**Comment by nparigi-ledger** [comment]
It seems than Evan You doesn't want to fix this as he doesn't want that v-html attribute to be supported in Vue 3.
Technically, is this something we could patch on the Nuxt side?

**Comment by Arthur-Chevron** [comment]
Do you have any news about this bug ?

**Comment by hecktarzuli** [comment]
I seem to have ran into this too, trying to use v-html in nuxt-link (this worked fine in Nuxt2/Vue2)

**Comment by EvgenyWas** [comment]
This problem is still actual for me on Nuxt 3.5.2. If I use v-html on NuxtLink component in runtime I have rendered a value that was passed via this directive, but if a page is rendered on server the link is empty.

**Comment by danieldanielecki** [comment]
@danielroe please reopen the issue. I'm still facing the same issue on nuxt `3.7.2`. I had the `v-html` perfectly working on `Nuxt2`, but performing the migration right now and I can reproduce the same issue as previous contributors.

**Comment by dimnik70** [comment]
> @danielroe please reopen the issue. I'm still facing the same issue on nuxt `3.7.2`. I had the `v-html` perfectly working on `Nuxt2`, but performing the migration right now and I can reproduce the same issue as previous contributors.

I have just faced the same behavior on 3.8.0

**Comment by danielroe** [comment]
To be clear, this is Vue 3 behaviour.

**Comment by manniL** [comment]
Ah sorry. Yes, on components it is really an anti pattern 🙈

**Comment by nikneym** [comment]
I feel like I've also found a workaround via render functions:
```vue
<script setup lang="ts">
const level = ref<number>(3);

const Heading = computed(() => {
  // create the tag (h1, h2, h3, ...)
  const tag = "h" + level.value;

  // set innerHTML here (you might want to sanitize it through sanitize-html or alike)
  return h(tag, { innerHTML: "<b>hello world</b>" });
});
</script>

<!-- don't use <Heading /> here since it ends up rendering on the client -->
<template>
  <component :is="Heading" />
</template>
```
