### ISSUE TITLE
Get store in an external js file.

### ISSUE THREAD

**Issue by wushan** [nuxt/nuxt.js#1155]
I searched some informations about this and almost all store relative issues is about getting store in a plugin file. Please see my case here: I am importing an simple js file from `assets` folder and using some functions from it, but can I use store in that file ?

I am using 1.0.0-alpha5

Thanks for helping !

```demo.vue```
```
import Parser from '~assets/util/Parser.js'
Parser.parse(a, b, () => {
// ...
})
```
```Parser.js```
```
export default {
   parse (a, b) {
     // Need use store here  
   }
}
```

**Comment by walleXD** [comment]
I would suggest changing your approach a little bit. With the vuex architecture, the whole idea is that vue will communicate with the store and then the store will dispatch appropriate actions & mutations while the component will only receive the state.  So, the general approach of one way data follow looks like this:
```
component -> dispatch action -> mutation -> store changes
   ^                                                |
   |________________________________________________|
```
Actions are aync functionsand so that's where you would wanna call the parse function and inside the action you also can access the store but make sure to mutate the store only using mutations

**Comment by wushan** [comment]
@walleXD thanks for your input.
I was saving an config object to the store like: 
```
preferences: {
  '10001': {
     size: x
   },
   '10002': {
     size: x
   },
   .
   .
   .
}
```
I am not trying to modify any of this preferences but expecting that using this via a getter or something like `preference['10001']` to get the value when need it.

My current solution is simply pass the whole object into the external function which I don't know if there will be any side effects but solved my problem for now at least.

```
Parser.parse(a, b, preference) ......
```
