### ISSUE TITLE
Check logged user in firebase with middleware

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/nuxt.js#1157]
I've built some auth middleware:

```
import api from '~/api/Api.js'

export default function ({router, store}) {
  return api.auth().onAuthStateChanged(function (user) {
    store.state.user = user
    if (user) {

    } else {

    }
  })
}
```

Now, how to actually get access to the user object? When i'm doing this from normal component it's working correctly. Passing to store simple string also works, but any other action no, is there need of some kind of promise? Thx for help.

**Comment by ChavaSobreyra** [comment]
It's hard to tell whats going on here, because we don't know whats in your api.js file. 

But from what I gather, you're doing an API request every time you want to get information about your current auth state. 

This is probably not the best way of doing things. Ideally, when authenitcating with firebase, you'd save your auth token in a cookie (so that it persists in memory even after refresh). You'd save your auth info in the store. 

When the nuxt boots after a refresh, you'd want to check the status of auth using that saved token, and then store your auth info in the store once. 

Once you have that type of setup, all you'd need to do in your middleware is check the current auth state in your store

```
export default function ({ store, error }) {
  if (!store.state.authUser) {

  }
}
```

**Comment by BjornMelgaard** [comment]
Also check @nuxtjs/auth and  @nuxtjs/axios in community modules

**Comment by lukasborawski** [comment]
@ChavaSobreyra ok, the way that i'm using store is a second party thing, right now i can't resolve Firebase request. I think this must be a Promise before the compiler will go further. So when i'm doing this the Promise never finish. My example for now:

```
import api from './../api/Api.js'

export default function ({store, router}) {
  return new Promise((resolve, reject) => {
    api.auth().onAuthStateChanged((user) => {
      if (user) {
        store.state.user = user
        resolve(user)
      } else {
        reject(Error('It broke'))
      }
    })
  })
}
```

What is wrong? @Atinux maybe you can help?

**Comment by Atinux** [comment]
Hi @lukasborawski 

Can you print a `console.log` inside the callback of `onAuthStateChanged` to make sure it's called by Firebase?

**Comment by lukasborawski** [comment]
@Atinux well i can pass new value to this store object but i can't reach user object from FB. And just like i've said the promise freezing my app.

**Comment by Atinux** [comment]
I know that the Promise is freezing your app, the question is if `onAuthStateChanged` is never called, the promise is never resolved so it's normal.

I believe that it should not be a middleware but a plugin @lukasborawski 

`plugins/auth.js`
```js
import api from '../api/Api.js'

export default function ({store, router}) {
  api.auth().onAuthStateChanged((user) => {
     store.commit('SET_USER', user)
  })
}
```

in your `nuxt.config.js`:
```js
module.exports = {
  plugins: ['~/plugins/auth.js']
}
```

Then you can have a middleware to check if `store.state.user` exists, and if not, redirect to `/login` for example.

it should work with 1.0.0-rc3 since you can have access to context in your plugins by exporting a function.

**Comment by lukasborawski** [comment]
@Atinux but from which place i should call the plugin?

**Comment by Atinux** [comment]
When do you need to call `api.auth()`?

**Comment by lukasborawski** [comment]
@Atinux just before render the page, i want to present private/public content. So the middleware is perfect for this.

**Comment by lukasborawski** [comment]
@Atinux OK, i've used the plugin for this, and it seams to work fine, but when i'm doing the redirect i have an error: `ERR_TOO_MANY_REDIRECTS`, my code for now:
```
import api from '~/api/Api.js'
import { getUser } from '~/api/AuthService'

export default function ({store, redirect}) {
  if (store.getters.loggedUser) {
    return
  } else {
    if (getUser()) {
      store.commit('SET_USER', getUser())
    } else {
      api.auth().signOut()
      redirect('/auth/signup')
    }
  }
}
```

**Comment by lukasborawski** [comment]
OK, upgreade to 1.0.0.rc-3 solved this issue.

**Comment by Nayir** [comment]
Hey @lukasborawski, same issue for me, can you please share with us your code in api folder ? Thanks a lot
