### ISSUE TITLE
webpackJsonp is not defined

### ISSUE THREAD

**Issue by jasmineY** [nuxt/nuxt.js#1158]
#### Uncaught ReferenceError: webpackJsonp is not defined and the error can block my project
But when I refresh the browser again，the error disappear

**Comment by pi0** [comment]
Hi @jasmineY . If you still have this issue, Please provide more details about which version of nuxt and what template using and possibly sharing your project and reopen.

**Comment by gangsthub** [comment]
I have this issue when I launch it from a linux production environment under an http server.

Some chunks of my js files are missing.

**Comment by gangsthub** [comment]
this may be related:
https://github.com/webpack/webpack/issues/5002#issuecomment-306280559

**Comment by gangsthub** [comment]
and this is quite related:
https://stackoverflow.com/questions/48736923/errors-when-publishing-my-nuxtjs-website-on-ssr-mode

**Comment by gangsthub** [comment]
I'm getting this error now, launching in an environment were I cannot specify the cache of the HTTP server so easily. **`webpackJsonp`** is not defined because `manifest` file is not being loaded. And in my case it had to do with https://github.com/nuxt/nuxt.js/issues/574 app bootstrap JS files hashes not being updated. My guess is server cache.

As a workaround I was [setting](https://github.com/nuxt/nuxt.js/pull/600/files) the same hashes (hard-coded) to the `app`, `vendor` and `manifest` files. But, for sure, is not a definitive solution... Maybe @pi0 can expand the reasons.

**Comment by mstrlaw** [comment]
In my case, restarting [PM2](http://pm2.keymetrics.io/) and Nginx did it.

**Comment by mstrlaw** [comment]
@Erigers what I ended up doing:

- completely removing the old build from from PM2 (_pm2 delete <app-name>_)
- make a new build
- starting it again on PM2 (for me, _pm2 start npm --name "webapp" -- start_)
- setting up PM2 to boot on server restart (_pm2 save_ & _pm2 startup systemd_)
- Restart Nginx

Following code updates didn't throw this issue anymore. A hassle, but for now, t'works.
