### ISSUE TITLE
[Vue warn]: Hydration node mismatch:

### ISSUE THREAD

**Issue by kylemod** [nuxt/nuxt.js#12266]

**Comment by Maximus1000** [comment]
I got this error by using conditional logic inside a named slot in a base container template, like this:
``` 
<BaseContainer.vue>
  <slot name="loading">
      <template v-if="loading">
        loading...
        <!--<BaseLoadingFeather />-->
      </template>
    </slot>
    ...other slots
 </BaseContainer>
```

Note how I thought like others that it might have been the feather library (loading in a separate component) that was the issue. Negative, removing that library had no effect.  The issue was having the v-if="loading" inside the named slot.  Upon removing the conditional logic from the Base template and moving that up to the parent template, no hydration error. Note in the above, I'm receiving loading as a prop.  I may have been wrong here in the first place regarding conditional rendering inside a slot but still thought this was worth sharing in case someone else encounters the same.  No v-if / conditional rendering inside named slots (or at least not in this example).

**Comment by khalilbensaid96** [comment]
Not exactly the wanted fix for the issue, but it can be fixed by disabling SSR while **development**.

// in nuxt.config.js
{
  ssr: process.env.NODE_ENV !== "development"
}

**Comment by Livijn** [comment]
I'm using `<client-only>` as well but that results in flickering on load. Also using `<font-awesome-icon>`.

**Comment by snimavat** [comment]
> I had this problem with font-awesome icons. My workaround was this:
> 
> ```
> <font-awesome-icon
>     v-if="!loading"
>     icon="fa-solid fa-phone"
> />
> ```
> 
>  ```js
> <script lang="ts" setup>
> const loading = ref(true);
> 
> const nuxtApp = useNuxtApp();
> nuxtApp.hook("page:finish", () => {
>   loading.value = false;
> });
> </script>
> ```
> 
> This waits for the page to finish, i.e. the content to be present client-side.

This fixed the issue for me
I had   `<Icon name="fa-brands:github" class="w-5 h-5" />` which was causing the issue

I am new to nuxt, can you confirm tht this works with SSR !

**Comment by Aleksandr-JS-Developer** [comment]
@henningko

This is a fairly common hydration mistake.
Making these mistakes comes from a misunderstanding of how SSR and hydration actually work.

So, I'll try to explain briefly.

Your code:
```html
<template>
  <div class=".1">
    <div v-if="isAuthenticated()">
      <logout />
      <h1 class=".2">.3</h1>
      <Content />
    </div>
    <div class="auth" v-else>.4</div>
  </div>
</template>

<script setup lang="ts">
  const { $supabase } = useNuxtApp();
  const loading = ref(false);
  const { isAuthenticated } = await useAuth();
</script>
```

When `Nuxt` does an `SSR` for this page, it generates an `HTML` structure:

```html
<div class=".1">
  <div class="auth">.4</div>
</div>
```

Because `isAuthenticated` will always be `false` because the work happens on the server, and there are no `cookies` on the server, no tokens, nothing to do with authentication.

Next, `Nuxt` will pass this code to the client as `HTML` and `JS`.

But the trick is that the `HTML` structure is now "dead". That is, it is not connected in any way with the state, there are no listeners on it.
It's just non-interactive `HTML`. The process of "revitalizing" the `HTML` structure is called "hydration".

When hydrated, `Vue` doesn't re-render the `HTML`, but rather "picks up".

The pickup goes like this: `Vue` has a `virtual component tree (virtual DOM)` and just recursively goes through it, connecting the real `DOM` node to the `virtual DOM` node along the way.

The `v-if` directive doesn't just add `style="display: none"` (as the `v-show` directive does), but completely cuts the node physically from the `DOM`.

Also, the setup code is executed **BEFORE** hydration or rendering. That is, the authorized client receives true in `v-if`, unlike the server.

So if the client is authorized, when `Vue` tries to hydrate your component, it will try to synchronize the next `virtual DOM`:

```html
<div class=".1">
   <div>
     <logout />
     <h1 class=".2">.3</h1>
     <Content />
   </div>
</div>
```

With the actual (which came from the server):
```html
<div class=".1">
   <div class="auth">.4</div>
</div>
```

Which will cause a sync error.

---

As a quick fix, consider using `v-show` instead of `v-if`. But this solution is bad for several reasons. For example, there is no `v-show-else`. Secondly, `style="display: none"` will solve the hydration problem, but if you have a lot of elements that depend on authorization, then using `v-show` will significantly increase both the number of `DOM` nodes, which will slow down the page, and the virtual size `DOM`, each node of which is served by reactivity.

As the right solution, it is worth considering the migration of authorization to the client in full:

```html
<template>
   <div class=".1">
     <div v-if="isAuthenticated">
       <logout />
       <h1 class=".2">.3</h1>
       <Content />
     </div>
     <div class="auth" v-else>.4</div>
   </div>
</template>

<script setup lang="ts">
   import { ref } from 'vue';

   const { $supabase } = useNuxtApp();
   const loading = ref(false);
   const { isAuthenticated: checkIsAuthenticated } = await useAuth();
   const isAuthenticated = ref(false);

   onMounted(() => {
     isAuthenticated.value = checkIsAuthenticated();
   });
</script>
```

The `onMounted` hook only runs on the client.

Even better, wrap your component in a custom `<ClientOnly></ClientOnly>` tag.

Hope it's a little clearer.)

**Comment by yjm020811** [comment]
Will there still be SEO effects if clientOnly is used?

**Comment by danielroe** [comment]
If you are using `<ClientOnly>`, then these components and their HTML will not be rendered on the server. So, yes.

**Comment by Aleksandr-JS-Developer** [comment]
> Will there still be SEO effects if clientOnly is used?

In general, the question is rather complex.

On the one hand, if you answer the question "will there be a disaster for SEO if I use Client Side Rendering?", then I think that most likely not.
Hasn't Google learned how to index Client Side Rendering in 10 years? Sounds unbelievable.
It is worth noting, however, that I did not find a single study on this topic.
You can run two sites (SSR and CSR) with almost the same content and look at the SEO metrics.

On the other hand, SSR greatly affects SEO metrics.
For example, on the speed of displaying content.

So the answer is something like this: SSR is very likely to improve SEO performance, but even without SSR, you will not have a disaster.

**Comment by sanjarbarakayev** [comment]
@Aleksandr-JS-Developer what can I do if I am using the `computed` property for the condition?

```
<script setup lang="ts">
...
const loading computed(() => notificationStore.loading
...
<script>

<template>
  <Dropdown>
    <template name="content">
      <Transition name="fade" mode="out-in">
            <div v-if="!loading"> ... </div>
            <div v-else> ... </div>
       <Transition />
    </template>
  </Dropdown>
</template>
```

I am also getting a warning hydration mismatch with a div element

**Comment by Aleksandr-JS-Developer** [comment]
@sanjarbarakayev,

Let's simplify the context to focus on the problem.
Let's look at the following problematic component `pages/page.vue`:

`/app.vue`
```html
<template>
  <NuxtPage />
</template>
```

`pages/page.vue`
```html
<template>
  <div>
    <p>Data...</p>
    <div v-if="loading">loading</div>
    <div v-else>not loading</div>
  </div>
</template>

<script lang="ts" setup>
  // Some random value, like loading, etc
  const someComputedValue = ref(Math.random() > 0.5);

  const loading = computed(() => someComputedValue.value);
</script>
```

When reloading the page, sometimes (with a ~50% chance) a hydration error will occur.
About the same as yours.

You need to synchronize the `loading` value on the server and client.

So, there are three ways to implement this synchronization, depending on your context:

- ClientOnly
- onMounted
- load only on client

## ClientOnly

Disable SSR altogether for the problem area.

`pages/page.vue`
```html
<template>
  <div>
    <p>Data...</p>

    <ClientOnly>
      <div v-if="loading">loading</div>
      <div v-else>not loading</div>

      <template #fallback>
        <Loading />
      </template>
    </ClientOnly>
  </div>
</template>

<script lang="ts" setup>
  // Some random value, like loading, etc
  const someComputedValue = ref(Math.random() > 0.5);

  const loading = computed(() => someComputedValue.value);
</script>
```

## onMounted

`pages/page.vue`
```html
<template>
  <div>
    <p>Data...</p>

    <div v-if="loading">loading</div>
    <div v-else>not loading</div>
  </div>
</template>

<script lang="ts" setup>
  // Some random value, like loading, etc
  const someComputedValue = ref(Math.random() > 0.5);

  const clientEnv = ref(false);
  onMounted(() => (clientEnv.value = true));

  const loading = computed(() => {
    if (!clientEnv.value) {
      return true;
    }

    return someComputedValue.value;
  });
</script>
```

You might figure out that the code is executed differently on the client, but in general the method looks like this.
Essentially the same as ClientOnly, but your `<div>loading</div>` will be rendered on the server.
Do you need your `<div>loading</div>` in SEO? This is a big question.

## load only on client

In this case, you ensure that `notificationStore.loading` on the server is always the same as in setup on the client. This is achieved, for example, this way:

`/app.vue`
```html
<template>
  <NuxtPage />
</template>

<script setup>
  import useNotificationStore from '~/stores/notification';

  const notificationStore = useNotificationStore();
  onMounted(() => notificationStore.loadNotifications());
</script>
```

Now throughout the entire project you won't have hydration problems due to `notificationStore.loading`.

---

References:
- [ClientOnly](https://nuxt.com/docs/api/components/client-only);
- [onMounted](https://vuejs.org/api/composition-api-lifecycle.html#onmounted);

---

Which to choose?

Without knowing your context, I suspect that `notificationStore` is needed to display *client* notifications.
In this case, rendering loaders will be useless for SEO, and the SEO bot will always be without an account, i.e. it will see something like: 'You have no notifications.'

In this case, the option with `ClientOnly` is suitable for you.

If you need SEO to display notifications, then I recommend the `load only on client` option.

**Comment by AliGhasami** [comment]
This problem is solved by set :disabledOverflow="true" on the menu.
 <Menu :selectedKeys="current" mode="horizontal"  :disabledOverflow="true" >

**Comment by Ramdeep-zentral** [comment]
import * as flowbite from 'flowbite';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("flowbite", flowbite);
});

Working perfectly

**Comment by insub** [comment]
Can there be an option to turn off hydration warnings? To be honest, we don't really care about the minor differences between client-side HTML and server-side HTML.

**Comment by manniL** [comment]
@insub yes and no. "Minor differences" can lead to your app not being functional at all. There are escape hatches by now that you can use but you probably shouldn't unless it is about e.g. a date.

**Comment by oleksandr-dukhovnyy** [comment]
> Can there be an option to turn off hydration warnings? To be honest, we don't really care about the minor differences between client-side HTML and server-side HTML.

@insub, no, you can't and that's very good.

The correspondence between the virtual DOM and the real DOM is necessary not only for you, but also for Vue to work correctly.

Do not turn off the warning, because you will hide the problem. In this case, quite serious. I wrote earlier in this issue about how the hydration error occurs. Vue, when picking up static HTML, throws an inconsistency error. This means that Vue cannot adequately grab the markup. This can cause Vue to manipulate element A thinking it is element B for example. Or simply the element will not be interactive. For you, it will look, conditionally, like this - you hang @click on an element, click, but the element does not react. I am sure that solving such a problem can take an incredible amount of time and nerves.
