### ISSUE TITLE
All styles from layouts and pages being loaded in dev mode – Nuxt 3

### ISSUE THREAD

**Issue by ashleynolan** [nuxt/nuxt.js#12919]

**Comment by matiaslauriti** [comment]
This is still happening, I am not sure what to do as it is messing with some stuff, not nice 😢

**Comment by danielroe** [comment]
If you are experiencing something you think is a bug, please open an issue with a minimal reproduction. 🙏

**Comment by matiaslauriti** [comment]
> If you are experiencing something you think is a bug, please open an issue with a minimal reproduction. 🙏

To be honest, it is exactly the same issue, it is still happening 😅 with latest versions from yesterday, but I guess I will have to open a new ticket 😅

**Comment by danielroe** [comment]
Thank you. Although it might seem the exact same big, it is rather a newer regression.

**Comment by martinvilche98** [comment]
At the moment you need to use `scoped` in the styles tag, LAYOUTS INCLUDED, otherwise they will be added as global styles.
If you want your styles to be loaded only alongside your component, use `scoped`.
I made this mistake, I have 3 layouts and I had to add `scoped` to two of them, so the styles wouldn't load where they shouldn't.

Example:
`index-layout`
```html
<style lang="scss">
@import '../assets/scss/main.scss';

</style>
```

`home-layout`
```html
<style lang="scss" scoped> <!-- Notice the scoped added. -->
@import '../assets/scss/main.scss';

main{
    width: 100% !important;
    max-width: 100% !important;
    padding-left: 42px !important;
    padding-right: 42px !important;
}
</style>
```

Also, developers, I am really disappointment by the absolute lack of communication on this issue, it got passed around and suddenly closed.

**Comment by martinvilche98** [comment]
HI, @matthew-dean I deleted the comment since it was late and night and this solution is not optimal (And might result in repeated imports too, since I don't know how it is handled in SSR for sure).

The solution that worked for me is to add all styles you want to use everywhere in the <style> tag of the entry point component, in `app.vue`.
Then, for styles you only use in your layouts, add them there **using** `scoped`.
same things for pages, and components.

This way you won't have styles mixed between layouts, the same way they don't between other components.

Remember, although it is called a "layout" it is still a vue component.

**Comment by rublev** [comment]
> HI, [@matthew-dean](https://github.com/matthew-dean) I deleted the comment since it was late and night and this solution is not optimal (And might result in repeated imports too, since I don't know how it is handled in SSR for sure).
> 
> The solution that worked for me is to add all styles you want to use everywhere in the <style> tag of the entry point component, in `app.vue`. Then, for styles you only use in your layouts, add them **using** `scoped`. same things for pages, and components.
> 
> This way you won't have styles mixed between layouts, the same way they don't between other components.
> 
> Remember, although it is called a "layout" it is still a vue component.

you misunderstood. all scoped styles are loaded in all pages.
