### ISSUE TITLE
CSS classes order changes when generating site

### ISSUE THREAD

**Issue by couellet** [nuxt/nuxt.js#1331]
I'm having an issue when I generate the website. I am using [semantic-ui](https://semantic-ui.com) and the order of the CSS classes is important.

My template looks like this:

```html
<template>
<section class="row">
  <div class="ui equal width grid">
    <div class="column" v-for="p in products">
      <small-product :product="p" />
    </div>
  </div>
</section>
</template>
```

When I generate the site, the classes `ui equal width grid` order is changed and it becomes: `ui equal grid width`.

Is there a way to prevent that? It makes it impossible to use semantic-ui properly.

**Comment by pimlie** [comment]
I would rather expect this to be an upstream issue with Vue then with Nuxt? Can you confirm that this behaviour does not occur in plain vue?

**Comment by alexchopin** [comment]
Hi @couellet, it's due to the default config when Nuxt minify the HTML during the generate.
It'll be disabled in the next release. 
Until the next release, you can change the default configuration in the `nuxt.config.js` file with the `generate.minify` option.
https://nuxtjs.org/api/configuration-generate#minify
