### ISSUE TITLE
nuxtjs + cordova

### ISSUE THREAD

**Issue by jvbianchi** [nuxt/nuxt.js#1334]
Is there any way to integrate Nuxt with Cordova?

**Comment by dotneet** [comment]
What if use `nuxt generate` ?

**Comment by jvbianchi** [comment]
The only example that I found was https://github.com/allanroger/nuxt-cordova but it is outdated, it looks like it uses `nuxt generate` like you said.

I don't know if it's the right way though (I don't know much about cordova).

**Comment by bayssmekanique** [comment]
You certainly could.  You would setup a basic cordova app first (which is basically a `config.xml` file and a few directories for building) and then setup a cordova hook that would run `nuxt generate` before the cordova build started.  You would have to be certain to use `nuxt-link` elements for all links and you wouldn't be able to jump to any external links without making a custom component that calls one of the native APIs, but for the most part I think it would work.

For that particular use case, I don't know that you are gaining much by using Nuxt over just a simple Vue app since you aren't going to be making server requests, so the code splitting and modular structure is going to be a wash.

**Comment by jvbianchi** [comment]
@bayssmekanique I think that you are right

**Comment by brianshepanek** [comment]
Here's the config I ended up using in nuxt.config.js to get this to work:

mode : 'spa'
route.mode : 'hash'
build.publicPath : '/nuxt/'
Then install "replace" and update your package.json script to:

nuxt generate && replace '/nuxt/' 'nuxt/' cordova -r

The comment about directories prefixed with underscores is correct, the real addition is replacing the paths in the generated index.html and manifest.js to not include the first slash which cordova can't find.

Hope this helps!
