### ISSUE TITLE
css w'ont load on refresh

### ISSUE THREAD

**Issue by jaubut** [nuxt/nuxt.js#1336]
I don't know if i'm doing something wrong but when I refresh a another directory then the principal one the css won't load.. I got to go back to the main route and click from the menu so that the page render correctly..

**Comment by bayssmekanique** [comment]
This is likely a result of the CSS files not being linked to correctly from other pages because you are using a relative path rather than an absolute path.  Take a look at your network log when you navigate to those pages and compare the paths for your CSS files with those that get loaded when you are at the root location.  (Just a hunch.  Please provide a little more info if that's not the case)

**Comment by Atinux** [comment]
Feel free to re-open if @bayssmekanique did not solve your answer.

**Comment by rlam3** [comment]
@bayssmekanique were you able to find out what your problem is? I'm having a similar situation..

**Comment by bayssmekanique** [comment]
@jaubut was the user having the issue.  He has not responded as to whether this resolved the issue or not.
