### ISSUE TITLE
useAsyncData and useFetch run twice if page uses layout

### ISSUE THREAD

**Issue by lukaszflorczak** [nuxt/nuxt.js#13369]

**Comment by Nicolas-Nmedia** [comment]
So, FWIW... I've stumbled upon this behavior while working on a simple app to test out Nuxt 3 and I've noticed that it exists even without a template going on. I tested a couple of solutions others have mentionned but to no avail so I tried something; used a reactive value instead of constant to generate my API url and lo and behold, it ended up working. Sadly, I'm no nuxt/Vue wizard, but I thought I'd share this with you guys as it could maybe help you guys out figuring the root of this.

Here's a [StackBlitz example](https://stackblitz.com/edit/nuxt-starter-q4nfuc?file=pages%2Fproducts%2Findex.vue&iniitialpath=products), you'll see the second Pokemon flashing on the client side fetching.

PS: see, this is what happens when you have a 4 year run old in your house, all your test cases end up being about Pokemons ;x

**Comment by MrSunshyne** [comment]
@Nicolas-Nmedia @milelazar @danielroe 
I've been struggling with this issue since a couple of months now. I run a CMS on my local machine, and I wanted to use Nuxt SSG to build the site and ship that to vercel/netlify. The fact that the api call happens on the client side is not only an inconvenience for me, but its completely breaking, as in my case the CMS is not accessible online after deployment. 

I've tried countless things trying to debug this but just can't seem to figure it out. So far what I've noticed is that: 

1. In two routes I have an api call to `/api/posts` through a simple useFetch which returns a bunch posts. I want to list posts on a page. After ssg build, `npm run generate`

`const { data: posts } = await useFetch("/api/posts");`

Route 1: `/`
- Client side api call to `/api/posts` happens. Wrong behaviour

Route 2: `/blog`
- Client side api call to `/api/posts` doesn't happened on `/blog`. Correct behaviour.

Both pages contain the exact same code.

I've tried removing `layout` and useing `app.vue` to avoid the Suspense error.

You can see the behavior on this [link](https://sandeep.ramgolam.com/). Inspect and see network tab. You'll notice the "Recent blog posts" section appear and the disappear because a client side call happened and didn't hit any endpoints because this is SSG.

**Comment by danielroe** [comment]
@MrSunshyne would you create a new issue with a reproduction? That should not be happening.

**Comment by MrSunshyne** [comment]
@danielroe I managed to narrow it down to [this](https://github.com/harlan-zw/nuxt-og-image/issues/35). It appears the problem is not nuxt3 itself but looks like something could be related to this issue https://github.com/nuxt/nuxt/issues/19887

**Comment by milelazar** [comment]
@MrSunshyne have you tried [useNuxtData](https://nuxt.com/docs/api/composables/use-nuxt-data)? Maybe you can build a caching logic. Fetch some data with useFetch and then useNuxtData pulls that cached data without fetching again. This solved my problem with refetching.

Take a look at this: https://github.com/nuxt/nuxt/discussions/19912#discussioncomment-5422794

**Comment by treb00** [comment]
In my project useFetch only runs twice when it gets 500 response. Does this maybe relates to this issue? Also using layout and running with nuxt 3.3.3

**Comment by NeoKms** [comment]
> > @danielroeкакое бы вы рекомендовали решение тогда? Не используете Пинию?
> 
> То, как я это сделал, выглядит так:
> 
> ```ts
> const { data: user } = await useAsyncData(username, async () => {
>   await usersStore.getUser(username); // <- this is calling the getUser action from the usersStore
>   return usersStore.user; // <- this returns the actual state value from the store once the above promise resolves
> });
> ```

This really worked for me. I still don't understand why, but thanks.

**Comment by pawmanaloto** [comment]
Hi @danielroe , this issue is still happening. I just wanted to know if there is a workaround. Thank you

**Comment by m-shum** [comment]
How do you avoid this behavior when using Pinia actions though? 
For example – I want to run 3 requests using Promise.allSettled, but I really don't need them to go out twice. Wrapping them in useAsyncData doesn't work even if you return the promise, or the value, or the store state the actions commit to. Not sure if I'm just really dense and missing something obvious.

**Comment by devCrossNet** [comment]
@m-shum this works for me: 

```
await useLazyAsyncData(async () => {
  pageLoading.value = true;

  await Promise.all([
    store1.fetchData(route.params.id1.toString()),
    store2.fetchData(route.params.id2.toString()),
  ]);

  if (store1.getData) {
    await store3.fetchData(route.params.id1.toString());
  }

  pageLoading.value = false;

  return [store1.getData, store2.getData, store3.getData];
});
```

works as well with `useAsyncData` in my experience, I hope it works for you, too.

**Comment by CasperSocio** [comment]
I tried replacing `useFetch` with `useLazyFetch` and it worked! I also introduced rendering logic for good measure:

### Before

```vue
<script setup lang="ts">
import type { ServiceConfig } from '~/shared/types/services'

const { data: services } = await useFetch<ServiceConfig[]>('/api/services', {
  method: 'GET',
})
</script>

<template>
  <div v-for="service in services" :key="service.id">
    // ...
  </div>
</template>
```

### After

```vue
<script setup lang="ts">
import type { ServiceConfig } from '~/shared/types/services'

const { data: services, status } = await useLazyFetch<ServiceConfig[]>('/api/services', {
  method: 'GET',
})
</script>

<template>
  <p v-if="status === 'pending'">Loading...</p>
  <template v-else-if="status === 'success'">
    <div v-for="service in services" :key="service.id">
      // ...
    </div>
  </template>
</template>
```

**Comment by Endermanch** [comment]
I was using a custom `useFetch()` instance within `<script setup>` in my Nuxt 3.15.4 project and faced the same issue. Unfortunately, the solution provided by Mr. @CasperSocio didn't work for me. The only fix I found was to use `useAsyncData()` calling a custom `$fetch` instance in order to specify a **static key**. 

### Before
```ts
const {
  data: url,
  status,
  error,
} = await useAPI<URLInfo>(
  `/x?y=${config.public.url}/z`,
)
```

### After
```ts
const {
  data: url,
  status,
  error,
} = await useAsyncData<URLInfo>('unique_key', () =>
  useNuxtApp().$api(`/x?y=${config.public.url}/z`),
)
```

**Comment by zerostechnology** [comment]
I faced the same issue after upgrading to Nuxt 3.16, I have a page where I set different components there to handle desktop and mobile devices, I have custom useFetch in both components, now I am getting an infinite loop of fetch requests https://prnt.sc/r49rHrwOQpz5

**Comment by parkerisme** [comment]
I faced the same issue。i use nuxt 3.16.1，remove all layouts and pages，then my app.vue。
<template>
	<div>
	</div>
</template>

<script setup>

const { data } = await useFetch('http://localhost:9200/hello2', {
  key: 'fetchKey',
})
console.log('sfsfsf',data.value, new Date())

</script>

when i visit http://localhost:3000/sfsf
the console i found

sfsfsf { message: 'hello2' } 2025-05-27T12:10:15.323Z
sfsfsf { message: 'hello2' } 2025-05-27T12:10:26.897Z

i want to know how to solve this?

**Comment by parkerisme** [comment]
> [@parkerisme](https://github.com/parkerisme) try ±
> 
> ```
> const { data } = await useAsyncData('hello2', async () => $fetch("http://localhost:9200/hello2"));
> console.log('sfsfsf',data.value, new Date())
> ```

not work.and i see the api end log out twice also.

**Comment by demoncome** [comment]
Is there a perfect solution to this problem? I've also encountered this issue, and it has been bothering me for several days
