### ISSUE TITLE
Test utils support progress

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#13372]

**Comment by procrates** [comment]
Hi! What is the status on this package? Looking to use it in production on multiple applications. 

Thanks!

**Comment by ThomasBerne** [comment]
Same question as @procrates. Any news on this? We need to add testing on a production application.

**Comment by maxdzin** [comment]
Hi guys,
I'm confused about the Nuxt 3 testing. I don't see clear explanations of what to expect from the Nuxt 3 test utils, especially when I found this module: [nuxt-vitest](https://github.com/danielroe/nuxt-vitest) that is in active development.

I've not tried yet to test with all of that but will try to do it soon.

So, my question is what is the difference between test-utils and nuxt-vitest (since all of them using vitest) and what to expect in near future regarding that?

For me it is should be flexible to change the testing techniques/tools accordingly for now, but I will appreciate it if someone can point me direction and make it a bit more clear at least.

Thank you!
