### ISSUE TITLE
Custom URL for i18n

### ISSUE THREAD

**Issue by Julien76** [nuxt/nuxt.js#1339]
Hi,

I'm trying to get understand how can I set-up a custom URL name that depends on the language selected.

In the i18n example provided:

* when english is selected, the url is for the  **"about"** page:
https://i18n.nuxtjs.org/about

* when french is selected, the url is for the  **"about"** page:
https://i18n.nuxtjs.org/fr/about
I think it will make more sense to translate as well the url as follow:
https://i18n.nuxtjs.org/fr/a-propos
where the french translation of **"about"** would be **"à propos"** made url friendly, so **"a-propos"**

How can I achieve this while keeping the set-up as proposed in the example ?
https://nuxtjs.org/examples/i18n

Thanks

**Comment by epartipilo** [comment]
Hi @Julien76 
I'm in the same path as you, I want to use vue-router aliases for that. I think that the actual version of Nuxt.js allow this. This week I'll give it a try. 

If you find any solution for this let me know please, I hope this week find a solution to that.

Cheers!

**Comment by alexchopin** [comment]
Hi @Julien76,
In your case, a middleware with an array of routes depending on the language selected by the current route parameter could be a good solution.

**Comment by epartipilo** [comment]
Hi @alexchopin 

What you suggest is the basic approach but I think what we are trying to achieve is:
```
pages/
- _lang/
--page1.vue
--page2.vue 
```

with these routes:
`es/pagina1` and `en/page1`
to show the same content in different languages.

What I'm working on is using the router aliases that in the 0.10.6 version where not applying because Nuxt doesn't allowed more than *path* and *name* modification on the *extenRouter* method.

I'm I in the correct path?

Cheers!!

**Comment by nilssolanki** [comment]
Hi, where does this issue stand today? I'm facing the same challenge at the moment.

**Comment by paulgv** [comment]
@nilssolanki I made a module for this, maybe give it a try? https://github.com/paulgv/nuxt-i18n
@njam did something similar that you can find here: https://github.com/njam/nuxt-i18n-module
