### ISSUE TITLE
[Enhancement] Handle data() promise errors

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxt.js#134]
If any error occurs inside component's `data()` an ugly and unhanded SSR error occurs like this:

TypeError: Converting circular structure to JSON
![image](https://cloud.githubusercontent.com/assets/5158436/21966045/46aa420a-db81-11e6-82f9-7efb0335e394.png)

Also trying to handle errors in every single page seems so extra work and not possible always consider my dashboard's data :
```js
async data({redirect, error}){
            try {
                let {stats} = await $http.get('admin/dashboard');
                return { stats: stats }
            } catch {
                 error({message:'Something bad happened!'}); 
                 return {stats: {} }
            }
        },
``` 

**Suggestion:** Why we don't simply catch all returned promises in data and passing proper error object to user land?

**Comment by uptownhr** [comment]
Adding on to this but I'm also seeing a vuejs warning, "[Vue warn]: data functions should return an object:
https://vuejs.org/v2/guide/components.html#data-Must-Be-a-Function 
(found in anonymous component at /Users/uptown/Projects/Personal/dev-journal/app/pages/index.vue)", when using async data function. 

This only occurs on hot reload - during development, and is not a problem on initial load.

**Comment by pi0** [comment]
@uptownhr About warning that's true, see my solution (you have to return an object even if redirecting inside data) . That circuar thing is even happening on SSR mode on production anyway.

**Comment by uptownhr** [comment]
@pi0 this is how my data section looks like

```
async data () {
      let data = await request.get('http://localhost:3000/test')
      console.log('wtfzz', data)
      return {
        test: 'asdf'
      }
    }
```
i am always returning an object ...

**Comment by pi0** [comment]
@uptownhr Things are good unless localhost:3000 get's unavailable or just current user rejects by /test (for example access denied)! The way async/await works it throws exception and data may return null :))

**Comment by husayt** [comment]
This circular error exception is indeed very difficult to debug. Last week
I spent a day to fix one. Extra information would be very useful.

Nuxt is great and easy to start with ,  until you hit a problem. Is there a
debug mode we can enable perhaps?

Thanks

On 16 Jan 2017 05:21, "Pooya Parsa" <notifications@github.com> wrote:

@uptownhr <https://github.com/uptownhr> Things are good unless
localhost:3000 get's unavailable or just current user rejects by /test (for
example access denied)! The way async/await works it throws exception and
data may return null :))

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nuxt/nuxt.js/issues/134#issuecomment-272776298>, or mute
the thread

**Comment by Atinux** [comment]
I'll take a look at it, I know that sometimes the errors from the server-side can be hard to debug.

It's mostly because of the SSR provided by Vue.js itself, we are looking with the Vue team to improve the stack trace in the future.

It's planned to improve the experience of the `data` method to avoid returning a data when using `redirect` or `error` methods. Also, I'll add the feature to transform the error got from the rejected promise reject to be a non-recursive JSON.

**Comment by Atinux** [comment]
The `Converting circular structure to JSON` will disappear in the next release to display instead the message thrown by the rejected promise.

**Comment by Atinux** [comment]
Error handling is now improved in the latest release [0.9.7](https://github.com/nuxt/nuxt.js/releases/tag/v0.9.7)

**Comment by developius** [comment]
I'm having this circular dependency issue with Nuxt v1.4.0 when my API returns a 404 response.

```javascript
asyncData ({ params, $api, error }) {
  return $api.getSomeData()
    .then(data => {
      // return { data } // to prove it's the second API call
      return $api.getMoreData(data.property).then(data2 => { // 404 triggered
        return { data, data2 }
      })
    }).catch(error)
}
```

Throws:

```
TypeError
Converting circular structure to JSON
```

Not entirely sure what I've done wrong here, if anything?

**Comment by husayt** [comment]
The issue is with the object you have. Try
To find out by debugging  which call returns in the error and then
carefully inspect parameters and results.


On 22 Mar 2018 08:50, "Finnian Anderson" <notifications@github.com> wrote:

I'm having this circular dependency issue with Nuxt v1.4.0 when my API
returns a 404 response.

asyncData ({ params, $api, error }) {
  return $api.getSomeData()
    .then(data => {
      // return { data } // to prove it's the second API call
      return $api.getMoreData(data.property).then(data2 => { // 404 triggered
        return { data, data2 }
      })
    }).catch(error)
}

Throws:

TypeError
Converting circular structure to JSON

Not entirely sure what I've done wrong here, if anything?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nuxt/nuxt.js/issues/134#issuecomment-375221336>, or mute
the thread
