### ISSUE TITLE
Support for explicit import global components

### ISSUE THREAD

**Issue by xiaoxiangmoe** [nuxt/nuxt.js#13413]

**Comment by zsilbi** [comment]
My dev server hangs on specific routes on page reload when I import and use components imported from `#components`. It seems like a Vite issue, but if I import the same component from it's direct location the issue is gone. It also applies to built-in components like `NuxtLink`. 

I was able to create a small reproduction of the issue, you can find it here: https://stackblitz.com/edit/nuxt-starter-azudzq?file=pages%2Findex.vue

**Comment by slacktracer** [comment]
Did you find a way to do it, @xiaoxiangmoe? Right now having to import things from #imports or #app is the worst thing about Nuxt for me. In particular it messes with auto sorting of imports.

**Comment by TimofeyBiryukov** [comment]
+1

**Comment by AngeloSchulerPiletti** [comment]
In my scenario, I want to import `NuxtLink` to use it in a dynamic component.

I found two different approaches for this:

1. The first one is to import the NuxtLink as:

```vue
<script lang="ts" setup>
import NuxtLink from '#app/components/nuxt-link.js'
</script>

<template>
   <component
       :is="item.callback ? 'button' : NuxtLink"
   >
        Other stuff here
    </component>
</template>
```

2. The second is to define nuxt link using the `defineNuxtLink`:

```vue
<script lang="ts" setup>
const nuxtLink = defineNuxtLink({})
</script>

<template>
   <component
       :is="item.callback ? 'button' : nuxtLink"
   >
        Other stuff here
    </component>
 </template>
```


Which is the correct approach? Both are working fine

**Comment by danielroe** [comment]
I would import from `#components` instead.

**Comment by brendonmatos** [comment]
Just to add, this is super useful when passing the component as a variable in Shadcn Vue. Just tested it and works perfectly 

```vue
<script lang="ts" setup>
import { NuxtLink } from '#components'
</script>
<template>
   <UiButton :as="NuxtLink" :as="NuxtLink" :to="`/song/${id}`">Go to song page</UiButton>
</template>
 ```

**Comment by AdrianFahrbach** [comment]
I guess that the `#components` import kind of solves this problem, but I still agree with @slacktracer that the `#` imports are a bad practice.
I usually disable auto-imports because when I want full control over my imports. Those `#` imports don't give me full control, they just cut the middleman. If the auto-generation of the import files isn't working for me or can't be used in my scenario, then I'm basically screwed.
Same goes for Nuxt modules btw! There are lots of modules that don't even tell you where to import their components from. 

Working without the Nuxt auto-imports is hard right now. It is opinionated towards that feature.
I think DX features like that should build on top of the regular way of doing things and therefore would wish for normal imports of the global components outside of the auto-generation magic.

**Comment by AdrianFahrbach** [comment]
@danielroe  The linked PR sadly does not solve this issue for us.

We got a monorepo setup with two different Nuxt projects and a shared component library. The file structure basically looks like this:

```
apps/
├─ nuxt-project-1/
│  ├─ .nuxt/
│  ├─ [...]
├─ nuxt-project-2/
│  ├─ .nuxt/
│  ├─ [...]
packages/
├─ shared-ui/
│  ├─ components/
```

How are we supposed to import from `#components` in our shared components here?
Our current `NuxtLink` import therefore looks like this:

```ts
import NuxtLink from '../../../../../node_modules/nuxt/dist/app/components/nuxt-link';
```

But this now (after upgrading) throws errors with `@click` handlers not being recognized.

**Comment by danielroe** [comment]
can you create a new issue with a reproduction? 🙏

**Comment by AdrianFahrbach** [comment]
> can you create a new issue with a reproduction? 🙏

I sadly can't share our code, but I created a minimal reproduction in #33304.
