### ISSUE TITLE
Nuxt instance unavailable on all pages

### ISSUE THREAD

**Issue by tiborpino** [nuxt/nuxt.js#13739]

**Comment by taksugit** [comment]
`useNuxtApp()` and `useRuntimeConfig()` can currently be defined freely outside of the setup function, making it difficult to notice errors.
Due to this error, accidents have occurred in my team.
In the future, it would be desirable to be able to detect such errors with Nuxt-specific ESLint or similar tools.

**Comment by nhan-ho-saltovn** [comment]
<img width="577" alt="image" src="https://github.com/nuxt/nuxt/assets/109122792/6cd6be19-fb91-4f1d-880c-659bda6c0373">
Can we run `useRuntimeConfig` in `useAsyncData`, since I also got the error `nuxt instance unavailable`

<img width="901" alt="image" src="https://github.com/nuxt/nuxt/assets/109122792/1202ad5f-f9b5-49be-b932-6146e1a0a017">

**Comment by danielroe** [comment]
You should run it outside of `useAsyncData` and use the configuration within it.
