### ISSUE TITLE
generate html with static data

### ISSUE THREAD

**Issue by fwchen** [nuxt/nuxt.js#1382]
I want to generate a site with static data.

So i put data in static folder `/static/data `

When i run dev, i can get data through api `http://localhost:3000/data/apple.json`, but when i use the generate command, I have to serve data on `http:/localhost:3000`,  the base url has to be changed as   the "generate" cammand is finished。

Any idea for reducing serve data and change base url?

**Comment by Atinux** [comment]
Hi @fwchen 

Actually when you use `nuxt generate`, Nuxt will render every route, so you have to make sure your server is running in the same time.

To do so:
1. Open 1 terminal and launch `npm run dev` (`nuxt`), when server is listening, step 2
2. Open a second terminal and launch `npm run generate` (`nuxt generate`)
3. When generate done, you can close the server on terminal 1

When generated, the axios call won't be made on server-side since every page generated (html file) will already have the data inside itself.

So what you have to do is to set the full URL (`http://localhost:3000`) **only on server-side**:

```js
const baseURL = (process.browser ? '/data' : 'http://localhost:3000/data')
```

I recommend you to use [axios-module](https://github.com/nuxt-community/axios-module), it handle using full url only on server-side (made by @pi0, core team member of Nuxt.js).

**Comment by fwchen** [comment]
thanks you very much, but that's what i've done :p

**Comment by fwchen** [comment]
I found answer.
```
    asyncData ({ params }) {
      if (process.browser) {
        return axios({
          method: 'get',
          timeout: 1000,
          url: `${baseURL}/${params.category}.json`
        }).then(res => {
          return { category: res.data }
        })
      } else {
        return {
          category: JSON.parse(require('fs').readFileSync(`./static/data/${params.category}.json`, 'utf-8'))
        }
      }
    }
```
