### ISSUE TITLE
NuxtLink active-classes are not applied on parents of non-nested pages 

### ISSUE THREAD

**Issue by vanling** [nuxt/nuxt.js#14042]

**Comment by frank-laemmer** [comment]
( Last discussion link broken )

**Comment by danielroe** [comment]
Apologies. While GitHub correctly redirects issue URLs this feature seems not to have been implemented for discussions. The discussion is present in this repo, but one would have to find it afresh. 🙁

**Comment by septatrix** [comment]
> The key question is whether the routes generated are correct.

The current state at least seems confusing/unintuitive. Why should a `foobar.vue` behave different from a `foobar/index.vue`? I could understand differences in how `/foobar` vs `/foobar/` would be rendered but do not expect a difference in the way routes are constructed. To the contrary, intuitively I would say `foobar/[id].vue` is better suited to be a child of `foobar/index.vue` than when `foobar.vue` is used instead.

Personally I would welcome it if the behaviour would be changed. This would also help reduce the clutter (several files with only a `<NuxtPage />` inside them) and prevent files coming out of sync (directories are sorted at the top usually, renaming or deleting a directory could result in a misnamed or leftover file).

Regardless of whether or not this behaviour should be changed (would it be breaking?) there are two measures which would help and improve the situation in the meantime.

1. Properly document how and in which way routes are constructed/nested.
2. Provide a small snippet for the `pages:extend` hook which creates corresponding parent routes automatically. This could either be a helper or simply an example in the documentation, possibly in conjunction with 1.

Currently I am investigating 2 for our current project as we would like to avoid creating parent files manually due to the disadvantages stated above. Once I got a satisfying snipped ready I am happy to contribute it for 2.

**Comment by FabianEllenberger** [comment]
Although this issue has been closed I can't get this to work with a [Catch-All Route](https://nuxt.com/docs/guide/directory-structure/pages/#catch-all-route): (`[...slug].vue`) when having a 2-level dynamic navigation using `NuxtLink`.

Example:
When navigating to `/foo/bar` only the `NuxtLink` for the route `/foo/bar` is getting the `router-link-active` class but the link for it's parent route `/foo`.

How would I implement a `<NuxtPage />` in a folder structure like `pages/[...slug.vue]` to let the router now that each child slug has a dynamic parent route?

The rendered `NuxtLinks`:
```html
<a href="/foo" class="">Foo</a> // no active class
```
```html
<a href="/foo/bar" class="router-link-active">Foo Bar</a>
```

The router seems to add the slugs correctly in an array:
```javascript
"route": {
  "params": {
    "slug": ["foo","bar"]
  }
}
```

Thanks for any help 🙏

**Comment by luksak** [comment]
I came up with this pretty generic approach, which also works for catch-all routes:

```vue
<script setup lang="ts">
interface MenuItem {
  path: string
  title: string
}

interface Props {
  items?: MenuItem[]
  modifier: string
}

defineProps<Props>()

const route = useRoute()
</script>

<template>
  <NuxtLink
    v-for="(item, i) in items"
    :key="i"
    :to="item.path"
    :class="{
      'router-link-active': route.path.startsWith(item.path),
    }"
  >
    {{ item.title }}
  </NuxtLink>
</template>
```
