### ISSUE TITLE
global component

### ISSUE THREAD

**Issue by wargt** [nuxt/nuxt.js#1405]
## How set global components on every pages?

nuxt.config.js

`
plugins: ['~/plugins/global.js']
`

plugins/global.js

```
import Vue from 'vue'
import Grids from '../components/Grids.vue'

Vue.component('grids', Grids)
```

pages/index.vue

`<grids />
`

Error:

```
NuxtServerError

render function or template not defined in component: grids
```

**Comment by gtso86** [comment]
I'm having a similar issue using a different component (vue-svgicon) but after the first reload seems back to normal. I can't decide if this is caused by the component itself or how Nuxt is handling components.

In my case the problem only occurs when I try to access the server for the first time:

![](http://i.imgur.com/jAFUgZC.png)

Terminal console:
```
[Vue warn]: Error in beforeCreate hook: "ReferenceError: document is not defined"

found in

---> <Svgicon>
       <ElCol>
         <ElRow>
           <Pages/account/login.vue> at pages/account/login.vue
             <Nuxt> at .nuxt/components/nuxt.vue
               <ElCol>
                 <ElRow>
                   <Default> at layouts/default.vue
                     <Root>
```

The problem only happen when SSR is enabled. I also tried to load the component locally (calling under the same page I need to use it) and the problem persists.

If I remove the `vue-svgicon` everything runs normal. In my case, I have other custom global components under my globals.js loading inside plugins and works without this error. That's why I'm thinking is something related how the plugins/components was coded and/or some incompatibility with SSR Nuxt features.

---

In the other hand, if I try to disable SSR I'm receiving a warning saying **Client-side rendered virtual DOM tree is not matching server-rendered content**

**Comment by appinteractive** [comment]
Hey, don't ask me why but now you need to manually pass the "default" module to Vue.component like so: ```Vue.component(name, component.default)```

That way it's working for me again.

**Comment by bskimball** [comment]
I'm having the same issue as @gtso86 I'm running a plugin as client-side only
```javascript
  plugins: [
    {src: '~/plugins/vue-waypoint', ssr: false}
  ]
```
When running npm run start or npm run generate, everything works as expected. However in dev mode I get the mismatch error which makes sense because the client-side code is different than what was on the server.

**Comment by gtso86** [comment]
Hey @bskimball , my problem in the end was caused by the component itself, not related with nuxt. But even when I followed the instructions to create alias inside webpack I couldn't fix the problems.

**Comment by bskimball** [comment]
thanks @gtso86 . I just wanted to note that the mismatch warning is only a warning since the plugin is client-side only. Everything still works, and you can actually subdue the warning using Vue.config.warningHandler

**Comment by rAugustos** [comment]
Hi @wargt,

# Version
`nuxt: rc8`

# Code

**plugins/components.js**
```
import Vue from 'vue'
import Grids from '~/components/Grids.vue' 

Vue.component('grids', Grids)
```
**Index.vue**

`<grids/>`

It's works fine for me! But see I'm using the alias `~/components`.

Please give us your feedback about this issue! xD

@appinteractive  nice code !

Thanks in advanced man!

**Comment by langtudatinh117** [comment]
add 
```
module.exports = {
  target: 'node'
};
```
to webpack.config.js of component to solve problem for sever side rendering

**Comment by Extarys** [comment]
Thanks @rAugustos I was looking for this. Was this in the docs somewhere ? I though I read all the vue js doc :\ lol
