### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by lunchspider** [nuxt/nuxt.js#14174]

**Comment by GoToBoy** [comment]
i have same problem  in vite react project using antd 3.x, and i found the problem was relate same with @ant-design/icons

<img width="1391" alt="image" src="https://github.com/nuxt/nuxt/assets/2384105/06ea24af-ea8f-43f6-ad10-ae0ae232eff1">

line 9 cause the gcc  , after  up node stack-size max-old-space-size,  it could build  success , but  in browser   has error 

index-BH1lW1HL.js:3  Uncaught RangeError: Maximum call stack size exceeded
    at __require (index-BH1lW1HL.js:3:50)
    at index-BH1lW1HL.js:16:16
