### ISSUE TITLE
Very bad flash of unstyled content when trying the starter template

### ISSUE THREAD

**Issue by ryancole** [nuxt/nuxt.js#143]
I'm checking out nuxt.js for the first time. I just used the vue-cli to install the starter project. I run the project and notice that with every refresh the page has a pretty bad flash of unstyled content. Everything starts off left-aligned and then finally snaps into proper place.

Is this an issue with the starter template or something deeper with nuxt.js?

![node](https://cloud.githubusercontent.com/assets/484801/22003303/222d3724-dc18-11e6-87a5-db3741900db8.gif)

**Comment by SkaterDad** [comment]
That happens in development mode because Webpack is injecting the styles with Javascript.  This allows Webpack to update your styles as you code.  

The production builds don't have that flash of unstyled content because CSS gets extracted to its own file and is imported directly from the served HTML.

**Comment by ryancole** [comment]
Oh I gotcha. I guess with all of the hot reloading, the idea is that you don't need to refresh frequently anyways.
