### ISSUE TITLE
`useFetch` does not account for params change

### ISSUE THREAD

**Issue by nlhkh** [nuxt/nuxt.js#14342]

**Comment by Donny2333** [comment]
It seems that `nuxt@3.5.1` still has the same question. This is my code:
`
  const key = hash([
    method,
    url,
    params,
  ]);
  const res = await useFetch("/request-url", {
    key,
    method: "get",
    params,
    initialCache: false,
  });
`
When I start my nuxt3 project use `nuxt dev`. useFetch functon works well.
But I build my project use `nuxt build`. then start it by `npx nuxt start`. useFetch function seems to cache my HTTP request.
Is it because the generation environment caches data？
I need someone's help, PLZ.

> Resolved! I use this code:
> 
> import { hash } from 'ohash'
> 
> and send key with this code 'key' : hash(['api-fetch', url, params]),
