### ISSUE TITLE
store.replaceState(initalState) did not replace store state

### ISSUE THREAD

**Issue by apiep** [nuxt/nuxt.js#1440]
I am trying to "feed" my vuex store with an initial data that has been stored on localStorage. I have try to use vuex-persiststate and write my own plugin which is just get the localStorage state, and calling `store.replaceState`.
But, it did not replace vuex store, after digging into `.nuxt` directory I found that the store will be feed with `window.__NUXT__.state`

The question are, why my `store.replaceState` did not replace the state? Or, is there any better way to set initial state? Without `store.commit("init", initialState)` if possible.

**Comment by Atinux** [comment]
Hi @apiep 

You cannot use `replaceState` with universal application since `localStorage` is only available on client-side, this will give different render between client-side and server-side.

If you want, you can use `spa` mode with `rc6` to use it:
- Demo: http://nuxt-spa-persisted-state.surge.sh/
- Code: https://github.com/nuxt/nuxt.js/tree/dev/examples/vuex-persistedstate

**Comment by rAugustos** [comment]
@Atinux , 

I'm vuex-persistedstate example and in the rc6  with `mode: 'spa'` it`s works fine.

Man, just... thanks a lot!!!

**Comment by apiep** [comment]
Yup, just noticed that client side render and server side rendered should match. And I found a work around, that I can get the local state, if I save it on cookies, so the server can retrive those cookies, and set the initial state based on those cookies :)

I know already about `mode: spa` but, I was using nuxt, so I need the SSR

**Comment by pi0** [comment]
@apiep for SSR maybe the only possible solution having fully working persisted state is to store it in cookies. As SSR renderer may need that state too.
