### ISSUE TITLE
navigateTo and useRouter path change with different layouts doesn't load dom elements in client side mode (no ssr)

### ISSUE THREAD

**Issue by Cpaczek** [nuxt/nuxt.js#14450]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.14.1`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `yarn@1.22.18`
- Builder:          `vite`
- User Config:      `css`, `build`, `vite`, `ssr`, `runtimeConfig`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/cpaczek/nuxt-nav-bug

### Describe the bug

When SSR is set to false and you are using `useRouter` or `navigateTo` and the layout is changing, for example when the layout changes from `foolayout` to `default` none of the content loads on the second page. There is a vue warn in console.

![image](https://user-images.githubusercontent.com/25715982/181404207-344fc4eb-de84-426a-9bdd-fa42c3411105.png)

If the layout doesn't change this issue does not occur, also if you are in SSR mode the issue does not occur.

If you refresh the page the content does load so the issue is to do with programmatic navigation.

**Comment by patrickdorival** [comment]
I'm experiencing this too, every page/layout has a single root node, but parts of the previous layout are coming across on to the new route.

The main root node for the previous layout is being used on the page too.

Its as if its trying to merge the two layouts instead of replacing.

I've wrapped everything in my first layout with a new single node (just a div) and this seems to have solved it pulling other elements in.

**Comment by danielroe** [comment]
Would you open a new issue with a reproduction? Happy to take a look.
