### ISSUE TITLE
Page component is created twice when navigating to it from page which uses different layout

### ISSUE THREAD

**Issue by samuelbednarcik** [nuxt/nuxt.js#14573]

**Comment by tada5hi** [comment]
I can not confirm that this is fixed :/

**Comment by IsraelOrtuno** [comment]
I think this should be opened as it's not fixed. In my case this is happening when navigating from a page with 

```
layout: false
```

To a page with layout that also contains a `NuxtPage` for nested views. Those nested views are loaded twice. Found a workaround with works in my case and it's creating an "empty.vue" layout and instead of using `layout:false` I use `layout:"empty"`.

**Comment by tada5hi** [comment]
@danielroe

**Comment by DesertCookie** [comment]
Was there a new issue opened somewhere? I've just encountered this issue after having accessing the app via a domain and Nginx Proxy Manager for the first time.

**Comment by bit4craft** [comment]
I also encountered the same situation, but it was a simple mistake. I was outputting the slot twice within the layout. It's natural for onMounted to be called twice in that case.
