### ISSUE TITLE
global.__VUE_SSR_CONTEXT__ is now undefined

### ISSUE THREAD

**Issue by mrcatman** [nuxt/nuxt.js#1464]
I used to get cookies for API requests (both on server and client) with
`process.browser ? document.cookie : global.__VUE_SSR_CONTEXT__.req.headers.cookie`

But now, after updating, it doesn't work. Console logging shows that `global.__VUE_SSR_CONTEXT__` (and just `__VUE_SSR_CONTEXT__`) is undefined. 
I'm using the latest versions of all (nuxt@1.0.0-rc6,vue@2.4.2,vue-server-renderer@2.4.2).

**Comment by Atinux** [comment]
Hi @mrcatman 

You should not use `global.__VUE_SSR_CONTEXT__` since it can changes (and it was the case with new version of vue-server-renderer, see [this line](https://github.com/vuejs/vue/blob/8ff77a243cae0627a651fe852a6c07f7bcfce2a3/src/server/bundle-renderer/create-bundle-runner.js#L120))

We now offers a way to get the context in plugins by exporting a method directly:

`nuxt.config.js`:
```js
module.exports = {
  plugins: ['~/plugins/cookies']
}
```

`plugins/cookies.js`:
```js
export default ({ isServer, req }) => {
  cookies = isServer ? req.headers.cookie : document.cookie
}
```
