### ISSUE TITLE
cannot import package @vue/composition-api 

### ISSUE THREAD

**Issue by gurpindersinghgill** [nuxt/nuxt.js#14789]

**Comment by devinschumacher** [comment]
Install pinia and then install @pinia/nuxt (its not in the docs that i could fine)

`pnpm i pinia @pinia/nuxt`

**Comment by gabrielmoris** [comment]
> Install pinia and then install @pinia/nuxt (its not in the docs that i could fine)
> 
> `pnpm i pinia @pinia/nuxt`
Thank you, this was my solution.
I faced the same issue even If I installed pinia through the modules of nuxt dev.

Then I went to the documentation and found the coment:
```json
"overrides": {
  "vue": "latest"
}
```
It still didn't work. I uninstalled the node__modules, tried yarn and same... They definitively need to find a solution for this because made me loose time.
