### ISSUE TITLE
useFetch is not using new value from reactive object

### ISSUE THREAD

**Issue by Aietes** [nuxt/nuxt.js#15359]

**Comment by noopurphalak** [comment]
> That is not reactive because you are 'freezing' the value of the url when you call `useFetch`. Instead, try this:
> 
> ```js
> const rfid = ref('Value1')
> rfid.value = 'Value2'
> 
> const { data, refresh } = await useFetch<IOrderPopulated[]>(
>   '/api/orders/find',
>   { query: { rfid } }
> )
> ```

@danielroe What if I am trying to do a `useFetch` on server route with dynamic route parameters, how do I do it in that case?

**Comment by Nepmia** [comment]
> > That is not reactive because you are 'freezing' the value of the url when you call `useFetch`. Instead, try this:
> > ```js
> > const rfid = ref('Value1')
> > rfid.value = 'Value2'
> > 
> > const { data, refresh } = await useFetch<IOrderPopulated[]>(
> >   '/api/orders/find',
> >   { query: { rfid } }
> > )
> > ```
> 
> @danielroe What if I am trying to do a `useFetch` on server route with dynamic route parameters, how do I do it in that case? I need to use a ref value as the dynamic route parameter.

Simply set the URL string using a function like so:

```ts
const param = ref('p1')

const { data, refresh } = await useFetch<IOrderPopulated[]>(() => `/api/orders/find/${param}`)

// Change the value of the url and re-fetch using refresh()
param.value = 'p2'
refresh()
```

**Comment by lmc3s3f0r** [comment]
Sorry for bumping the thread, but I'm having the same problem and maybe you could shed some light.

This is my useFetch call:

```
const {
  data ,
  error
} = await useFetch<TransportDestinationFiltersOptions>(`/api/core`, {
  params: {
    path: `transport_destination/lot/${activeTransportsPageStore.getLotId}/filters`,
    watch: [() => activeTransportsPageStore.getLotId]
  }
})
```

activeTransportsPageStore is a Pinia store. However, when activeTransportsPageStore.lotId is updated, the path in the API call in Network tab doesn't change (lotId is always the same number).

I tried using the variable (activeTransportsPageStore.lotId) instead of the getter (activeTransportsPageStore.getLotId), but no change either.

Any hint is greatly appreciated.

**Comment by danielroe** [comment]
@lmc3s3f0r that's not reactive.... you are 'fixing' the path string at the moment it's called. Instead, you can use a computed property, e.g.:

```ts
path: () => `transport_destination/lot/${activeTransportsPageStore.getLotId}/filters`
```

**Comment by lmc3s3f0r** [comment]
> [@lmc3s3f0r](https://github.com/lmc3s3f0r) that's not reactive.... you are 'fixing' the path string at the moment it's called. Instead, you can use a computed property, e.g.:
> 
> path: () => `transport_destination/lot/${activeTransportsPageStore.getLotId}/filters`

Thanks for the quick reply. I tried that, but "path" seems to be returned as undefined when you open the page, therefore the API call returning 404. 

Is it maybe because I'm using useFetch directly in <script> and not in "onMounted"? Although I thought in onMounted you should use fetch and not useFetch... Also, not using useFetch direcly in <script> would cause its variables to not be present when loading the page, therefore crashing directly.


If it helps, this would be the full code. I noticed that the console log "auxPath" I put in the middle, is printed in browser console before the message "Pinia store installed", so I'm guessing I shouldn't call useFetch before that.

```
const route = useRoute()

const activeTransportsPageStore = useActiveTransportsPageStore()

if (props.singleLotMode) {
  activeTransportsPageStore.setLotId(route.params.id as string)
} else {
  activeTransportsPageStore.setLotId('32') // fixed value just for testing purposes
}

// console.log('activeTransportsPageStore:', activeTransportsPageStore.getLotId)

const auxPath = () =>
  `transport_destination/lot/${activeTransportsPageStore.lotId}/filters`
console.log('auxPath:', auxPath())

const {
  data: transportDestinationFiltersOptionsData,
  error: transportDestinationFiltersOptionsError
} = await useFetch<TransportDestinationFiltersOptions>(`/api/core`, {
  params: {
    path: `transport_destination/lot/${activeTransportsPageStore.lotId}/filters`,
    filters: {
      transport_order_status: ['enTransito']
    },
    watch: [() => activeTransportsPageStore.lotId]
  }
})
```

**Comment by danielroe** [comment]
Yes, that will be specific to your app logic. But don't call `useFetch` in onMounted. Instead, use `$fetch` directly (maybe + a watcher).

**Comment by lmc3s3f0r** [comment]
Thanks! I'll try as soon as possible and get back to this thread to report :)

**Comment by danielroe** [comment]
if you destructure the values (`props.timeFrom` makes the value non-reactive), then it won't use fresh data. you have to pass the _ref_ or reactive object directly, e.g. `from: computed(() => props.timeFrom)`.
