### ISSUE TITLE
useFetch sends double Request in nested component ( Under some conditions )

### ISSUE THREAD

**Issue by rohrig** [nuxt/nuxt.js#15528]

**Comment by TimGuendel** [comment]
> Yes, you should only use `useFetch` within setup directly, not within a helper function later on. `$fetch` is correct.
Imho this very distinction should be emphasized more in the docs: https://nuxt.com/docs/getting-started/data-fetching

The wording of the following is confusing at best:

_[useFetch](https://nuxt.com/docs/api/composables/use-fetch) is the most straightforward way to handle data fetching in a component setup function.
[$fetch](https://nuxt.com/docs/api/utils/dollarfetch) is great to make network requests based on user interaction._

vs 

_When using a framework like Nuxt that can perform calls and render pages on both client and server environments, some challenges must be addressed. This is why Nuxt provides composables to wrap your queries, instead of letting the developer rely on $fetch calls alone._

Just my 2 cents 😅
