### ISSUE TITLE
Inject plugin in $root state & context

### ISSUE THREAD

**Issue by ruslankonev** [nuxt/nuxt.js#1554]
I was try to write and inject `horizon.io` plugin in the $root (app) with documented way:

```js
export default ({ app, store }) => {
  app.$horizon = horizon
}
```

but something was wrong and the injected props will append into `$store` key:

![image](https://user-images.githubusercontent.com/2588730/29969618-91099cf4-8f29-11e7-81f2-7350cd9e834d.png)

As you can see, `$horizon` will added into `$store` -> `$store.$horizon`, and into `$store.app` -> `$store.app.$horizon`.

If I test like firebase example, the result will be the same:
![image](https://user-images.githubusercontent.com/2588730/29969685-e63bf01e-8f29-11e7-93f9-6abfc562cedf.png)

**Comment by alexchopin** [comment]
```js
export default (context, inject) => {
  inject('horizon', horizon)
}
```
will create `$horizon`, the documentation need to be completed (WIP).

**Comment by YvanDaSilva** [comment]
@alexchopin Hello !
Thanks for the info.

Did you close the issue because it has been documented properly ?

At the moment https://nuxtjs.org/guide/plugins is not reflecting your comment.
There is an example of the usage of inject, but the inject function itself is not documented like you state here (key,value) will be available as $key 

Let me know if you want me to open another issue to improve the documentation.
