### ISSUE TITLE
Many 404 requests when deploy static files on github

### ISSUE THREAD

**Issue by wi-cuckoo** [nuxt/nuxt.js#1559]
Just try to open https://wi-cuckoo.github.io/blog/. You will find many 404 error in console. But the file exists in my repo and the path is correct. Why? I generated these by  **"generate": "NODE_ENV=production nuxtent generate"**

**Comment by alterhu2020** [comment]
hi @wi-cuckoo , I think the problem is because your base router path is `/` ,please have a look at your `router.js` file ,should be like below:
```
export function createRouter () {
  return new Router({
    mode: 'history',
    base: '/',
```
Here you can see the base is `/` ,it should be `/blog` here. 
after that it should be ok ,i think.

**Comment by wi-cuckoo** [comment]
@alterhu2020, Hello, no router.js file in my project. But you give a hint. I will check the mode of router to see if something different

**Comment by NicoPennec** [comment]
I found the issue, `.nojekyll` is missing

@wi-cuckoo  you have forgotten to commit  the empty file called .nojekyll from `dist` to your github project.

This is because GitHub Pages will by default ignore any files and folders prefixed by an underscore (like _nuxt), as documented here: https://github.com/blog/572-bypassing-jekyll-on-github-pages

**Comment by wi-cuckoo** [comment]
@NicoPennec  Thank you very much. Also I hope the tips can be add into the official document.
