### ISSUE TITLE
jQuery code stops working after navigating the routes without rebooting the page

### ISSUE THREAD

**Issue by Jussiadev** [nuxt/nuxt.js#1758]
I have jQuery code that is responsible for the select. The problem is that if I switch over routes, then this select does not work. How can I fix this?
```
$(function () {
        $('.select_list_radio').on('click', function(){
            var current = $(this).find('label span').text();
            $(this).parents('.select_list_wrapper').find('.select_list_current .select_list_current_item').text(current);
            $(this).parents('.select_list_wrapper').removeClass('open');
            $(this).parents('.select_list_wrapper').find('.select_list').css('display', 'block');
        });
    })
```

**Comment by LlinksRechts** [comment]
If I understood correctly, you load a select element over ajax, which then does not trigger the jquery code. If that is the problem, you need to re-execute this jquery code after the select is loaded since it only adds an onclick handler to existing elements.

**Comment by Jussiadev** [comment]
@LlinksRechts This code is in the file from the client side (in static).

**Comment by LlinksRechts** [comment]
@Jussiadev exactly, and as far as I understood it does not work after you load some content after the page is reloaded. This is because the code is executed when the page is initially loaded and some elements may not exist at that time and are therefore not affected/the handler is not applied to them.

**Comment by Jussiadev** [comment]
@LlinksRechts Thank you, I also thought about the same. Could you explain in some detail how to solve this problem. I do not really understand how to do this yet

**Comment by LlinksRechts** [comment]
The code you posted here adds an event handler to all existing elements with the class `select_list_radio`. This means that the `click`-event of these elements is associated with the function you defined there. However, this is not the case with any elements created after this code is executed (the code does not create a handler for every select_list_radio element, but just for existing ones). Therefore, you need to re-execute the code once the new elements have been loaded.
However, I think if you execute the exact same code again, the elements which existed before will be associated with a second click handler, which means that the code will be called twice when you click on these elements (although I'm not 100% sure that will happen). If that is the case, a solution would be to eg. remove the select_list_radio class from elements which were already processed (if this class is also used for other purposes, introduce another independent class for this purpose).
I hope that this clears everything up, if something is still not clear feel free to just ask

**Comment by Jussiadev** [comment]
@LlinksRechts Thank you very much, I will try 👍

**Comment by cesasol** [comment]
The best way to work with frameworks like this is using vue based solutions for any frontend requirement. For I can see from the code you are sharing you need to toggle classes and displays within a form. If so, then you can make a component for that functionality, with some state data to toggle from true to false in order to show/hide and toggle classes based on the state of that data.

It's kind of hard at the beginning but is really worth it, you would be able to make things quicker using that kind of solutions. jQuery is good, but vue is great.
