### ISSUE TITLE
Guidance For Rendering Lightweight Static HTML

### ISSUE THREAD

**Issue by DonFuego** [nuxt/nuxt.js#1793]
We are using Nuxt to render out static html. 

During that process, the data that is being retrieved in the async data method is being stored with the html as part of the nuxt object.  We no longer need this data and it's adding to our page weight.  We need to remove it from the nuxt state.  

How do we properly render the html so that we don't store the hydration data on the outputted source html?

**Comment by dsandor** [comment]
@DonFuego @alexchopin I created a PR that addresses this concern.  I have also seen others with similar requests.  It would be great to have this ability.  If there is a better way to implement please provide me some guidance and I will gladly correct the PR.  Thanks ~DS

**Comment by DonFuego** [comment]
Nice!  Thanks @dsandor.  @alexchopin let us know your thoughts on the PR?

**Comment by Atinux** [comment]
Hi @DonFuego 

Actually it's a **bad idea** to remove `__NUXT__.data` since Vue will not be able to *hydrate* the page and make it reactive.

But there is a property called `beforeNuxtRender` where you receive the `nuxt` context (equivalent to `__NUXT__` when server-rendered (https://nuxtjs.org/api/context at the bottom)

Here an example:

`plugins/version.js`
```js
export default ({ beforeNuxtRender }) => {
  // Only for server-side
  // We use process.server to avoid requiring package.json on client-side bundle
  if (process.server) {
    const pkg = require('../package')
    beforeNuxtRender(({ nuxtState }) => {
      nuxtState.version = pkg.version
    })
  }
}
```

And in your `nuxt.config.js`:
```js
module.exports = {
  plugins: [
    { src: '~/plugins/version' }
  ]
}
```

**Comment by dsandor** [comment]
Thanks @Atinux that worked well.
