### ISSUE TITLE
Fetch from multiple api's on page refresh using fetch method

### ISSUE THREAD

**Issue by neeraj022** [nuxt/nuxt.js#1833]
I have 3 level of nesting in my pages (subject/topic/subtopic/content). If a user navigates in correct sequence i.e starting from subject to content,  all data is fetched on page change and everything works well.

But If a user refreshes the browser on content or subtopic page, how do I fetch all the previous data ? I am using fetch method to get data for each page, should I use fetch to get data for all the previous pages ? How do I do it? I am using vuex store, so every data fetch is written in actions of vuex.

How do I avoid fetching the duplicate data when client doesn't refresh the page but simply navigate from client side page to another page?

Any help will be highly appreciated.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1647">#c1647</a>)</em></sub></div>

**Comment by AndruxaSazonov** [comment]
If you are working with SSR, you should check in fetch the store. If the subtopic data is empty, you should fetch it too. 

I do the following in asyncData of the last page in chain, somewhat as you need
```
async asyncData ({ app, params }) {
  if (!!app.store.state.CatalogData.length) {
   app.store.commit('SetCatalog', await app.$axios.$get('/api/catalog'))
  }
  return {
    catalog: app.store.state.CatalogData,
    content: await app.$axios.$get('/api/content/' + params.id)
  }
}
```

**Comment by uptownhr** [comment]
I also ran into this problem and I believe the issue is that the your fetches, all run in parallel and sequentially by it's nestedness. 

Given that, I'm blanking on the solution I used to solve the problem. I will get back you.

**Comment by neeraj022** [comment]
@AndruxaSazonov Thanks for the help. Somehow I didn't got your reply's notification and implemented promise.all to make all my fetches in parellel. Fetching data in asyncData would also, but since I am picking data only from my store, local data component data is meaningless for me, then what do I return in asyncData method ?

About nuxtServerInit method, since I am following module approach for defining my store, and nuxtServerInit can only be defined in index.js inside the store directory, then how can I set data for other store module (other than index) ?

**Comment by AndruxaSazonov** [comment]
@neeraj022, asyncData was for an example only, certanly you may use fetch to populate the store. The idea was in fetching needed previous pages data when corresponding store data is empty or `process.server` is defined. You have to fetch all data of page every time on the server, since server has no sessions data (probably this is possible, but redundant).

Store with modules - I don't use them, but [docs](https://nuxtjs.org/guide/vuex-store#the-nuxtserverinit-action) says that

> If you are using the Modules mode of the Vuex store, only the primary module (in store/index.js) will receive this action. You'll need to chain your module actions from there.

**Comment by manniL** [comment]
When using `Vuex`, you can specify actions to request data conditionally if eg. `state.xyz` is empty and execute the actions in the `fetch` method.

---

Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
