### ISSUE TITLE
How I can look my webpack config? example alias

### ISSUE THREAD

**Issue by ouyangxiaoai** [nuxt/nuxt.js#1841]
I want to look my webpack config,example:
in nuxt.config.js my code console.log('my alias:',config.resolve.alias)
but i don't have log in chrome,just see some log in terminal and not all
so how can i look this all ?

**Comment by dotneet** [comment]
you can see output log in terminal. but `npm run dev`  command clears terminal output so I recommend to use `npm run build` to show log.

**Comment by qm3ster** [comment]
AFAIK (at least in gnome-terminal) `nuxt` doesn't clear logs, just scrolls down so that the console looks clean.

You will never get build logs in the browser, though. 

Only:
 - Errors during SSR rendering (which actually show a lot more info in the browser pretty HTML error than in terminal) 
- Actual clientside errors (in the browser console)

**Comment by ouyangxiaoai** [comment]
Thanks
