### ISSUE TITLE
_lang param for all pages

### ISSUE THREAD

**Issue by neeraj022** [nuxt/nuxt.js#1879]
I have used the nuxt example of i18n internationalization.  My webapp operates for 3 languages (en, kk, ru). I have the language switch in the header section of my application, meaning that a user can change the locale at any page. User can also change the locale by manually calling a url with locale parameter in the url.

Now suppose a user goes from index page to study ('/study') page and the selected locale was kk. Going to study is done from a nuxt-link. host/kk changes to host/study. 
Locale is somehow omitted from the url. 

How should I handle this? Can I change the base url of nuxt from / to kk/, so that all pages are prefixed with kk/.

**Comment by paulgv** [comment]
I solved this using small functions responsible for generating URLs based on current or requested locale.

This mixin is used globally in the app:

```js
// ~/plugins/i18n-mixin.js

import Vue from 'vue';


import { LOCALES } from '~~/config';
import { getLocalizedPathUtil } from '~/utils/i18n';

Vue.mixin({
  data: () => ({
    locales: LOCALES,
  }),
  methods: {
    getLocalizedPath (path, locale) {
      // Handle case where path is passed as route params
      if (typeof path === 'object') {
        const resolved = this.$router.resolve(path);
        path = resolved.href;
      }
      locale = locale || this.$i18n.locale;
      return getLocalizedPathUtil(path, locale);
    },
    switchLocale (locale) {
      const regexp = new RegExp(`^/${this.$i18n.locale}`);
      const path = this.$route.path.replace(regexp, '');
      this.$nuxt.$router.push(this.getLocalizedPath(path, locale));
    },
  },
});
```

Here is the utility function that simply returns the route with the locale prefix (or only the route without the locale if default locale is requested):
```js
// ~/utils/i18n.js

import { DEFAULT_LOCALE } from '~~/config';

/**
 * Returns the localized path for a given base path and locale
 * @param  {String} path   The base path that should be localized (does not contain locale)
 * @param  {String} locale Requested locale
 * @return {String}        Localized path
 */
export const getLocalizedPathUtil = (path = '', locale = DEFAULT_LOCALE) =>
  (locale === DEFAULT_LOCALE ? path : `/${locale}${path}`);
```

And in your `.vue` files:
```vue
<nuxt-link :to="getLocalizedPath('/study')">Study</nuxt-link>
<nuxt-link :to="getLocalizedPath('/study', 'ru')">Study (RU)</nuxt-link>
```

**Comment by neeraj022** [comment]
I tried applying the plugin given by you. 

Now when I go from /study to /kk/study, I get page not found nuxt error. But when I refresh the same page (/kk/study), the page loads successfully. 

This means that nuxt is not able to fetch /kk/study page dynamically. But the same page in english (/ to /study) is successfully loaded by nuxt. 

Is this a nuxt bug, why is this happening?

**Comment by paulgv** [comment]
I've had similar issues in the past with nuxt-express template's default pages but I couldn't figure it out and it works fines with my own pages.
Can you share your code in a repo to help reproduce the issue?

**Comment by neeraj022** [comment]
You can access the sample code repo at the below given url: 
[](https://github.com/neeraj022/vue-i18n-bug.git)
https://github.com/neeraj022/vue-i18n-bug.git
Try navigating from / to study. It will say that nuxt error: page doesn't exist. But if you refresh the same url, page gets loaded. 

The above behaviour is happening because of nuxt link with selected locale (written in component/header.vue). If you remove the selected locale form header.vue, all pages loads correctly. 

Though the logic for selected locale+link is not written correctly, but it serves the purpose for reproducing the bug.

**Comment by paulgv** [comment]
I see, this is indeed very similar to some issues I had, this happens because your links are not correctly formed when generated in the Vue component.
In your case, this code:
```js
$store.state.locale.selectedLocale+'/'+header.link
```
might results in links looking like `kk//study`, which won't work once rendered client-side, it should look like this instead: `/kk/study`.
You could solve this using a small helper function in the component to sanitize the links that you pass to `<nuxt-link>`, here's an example:

```js
export default {
  methods: {
    // ...
    makeLink (link) {
      let l = '/' + this.$store.state.locale.selectedLocale
      if (link.match(/^\//) === null) {
        l += '/'
      }
      l += link
      return l
    }
  }
}
```
Use it in the template:
```vue
<nuxt-link :to="makeLink(header.link)"><i class="material-icons" v-html="materialIconCode(header)"></i>{{$t(`index.${header.name}`)}}</nuxt-link>
```

This should help, but you might have to do additional work to make it work everywhere.
Also, I ended up creating a basic project that shows how I deal with i18n and routing with Nuxt, you might find some interesting stuff in there: https://github.com/paulgv/nuxt-i18n-routing
With the method I use currently, the `_lang` directory is not required anymore and you could translate `/study` in Russian/Kazakh in addition to having the lang prefix in the URL.

**Comment by sudhir600** [comment]
How you solve meta data issue ?
Consider this scenario.
after `"npm run generate"` head executed only a time. (server side execution).
now user change the locale, then how to change the metadata?

**Comment by paulgv** [comment]
I think this should be handled in the router's config file, it could be extended to provide multiple aliases for a single page, as well as the meta for each language. The config would look like this:

```js
const ROUTES = {
  about: {
    fr: {
      aliases: ['/a-propos', '/apropos'],
      meta: { foo: 'bar' }
    }
    en: {
      aliases: '/about-us',
      meta: { foo: 'bar' }
    }
  }
}
```

It would have to be handled when generating the routes.

**Comment by sudhir600** [comment]
i wanted to host one `build `for multiple sub-domain such as `in.abc.com`, `uk.abc.com`, `us.abc.com`
now when i share `in.abc.com/about` , crawler will fetch meta data. so of course meta data should be render on server side (in this case `nodeJs`). any changes happen on client side doesn't effect crawler. right ?

so the issue is how to manage meta data for all three sub-domains, considering one `build `only.
is it possible?

**Comment by tmorehouse** [comment]
See related issue and possible solution for multi language sites: https://github.com/nuxt/nuxt.js/issues/112#issuecomment-340574312
