### ISSUE TITLE
titleTemplate with function not working

### ISSUE THREAD

**Issue by homerjam** [nuxt/nuxt.js#1886]
The following in nuxt.config doesn't work as expected:

```
titleTemplate: titleChunk => titleChunk ? `${titleChunk} - Nuxt.js` : 'Nuxt.js',
```

I think it might have something to do with the options not being brought into vue-meta properly ie. maybe options are being cloned in a way which removes functions?

PR with failing test: #1961

**Comment by Atinux** [comment]
I will take a look at it, I believe it comes from the last version of vue-meta.

**Comment by Atinux** [comment]
Fixed in https://github.com/nuxt/nuxt.js/commit/bf72a35634e084c08be6126a4281520caf259288

Release coming soon :)

**Comment by Atinux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#1886](https://trello.com/c/6udO24yj/38-1886)

**Comment by benmccallum** [comment]
Nice one, had this issue too and always nice to see an issue already logged and in this case even fixed pending deployment. 👍

**Comment by mfulop** [comment]
Does this fix work for any of you guys? For me (even in nuxt 1.2.1 on Mac), most function formats for titleTemplate in nuxt.config.js results in duplicated "function" in the generated code. Any of the following:
titleTemplate: function (title) { return `---${title}---` }
titleTemplate (title) { return `---${title}---` }
titleTemplate: (title) => { return `---${title}---` }
... becomes head: {"titleTemplate":function function(title) ... in the compiled code.

The reason is that in nuxt/lib/app/App.js:   
head: <%=serialize(head).replace('head(','function(').replace('titleTemplate(', 'function(') %>
... and serialize-javascript (1.4.0) already returns "{"titleTemplate":function titleTemplate(title) { return title ? title + ' - Logiscool' : 'Logiscool'; }}".

A workaround for now is to set up a named function as titleTemplate value:
titleTemplate: function foo (title) { return `---${title}---` }
