### ISSUE TITLE
external plugin variable

### ISSUE THREAD

**Issue by ImmanuelSamuel** [nuxt/nuxt.js#1938]
I have a js plugin script.
If I add it as a plugin it is taking too long to compile.

Is there a way to use head tag to incorporate the plugin and then use the variable set by the plugin.
If I try to access the variable in the component I get variable not defined.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1729">#c1729</a>)</em></sub></div>

**Comment by pauldariye** [comment]
can you share your code for the component @ImmanuelSamuel ?

**Comment by ImmanuelSamuel** [comment]
So first I tried creating a plugin as follows:
```
import Vue from 'vue'
import pg from '~/plugins/plug.js'
Vue.use(pg)
```
plug.js is a large ~10Mb file. So compiling is taking forever. (Javascript Heap out of memory eventually)

So I tried to put that inside head in config: plug.js file is in static directory.
```
script: [ { src: '/plug.js' } ]
```
This file sets a global variable called ```pg``` which I cannot use inside the component.
The component is simple
```
<template></template>
<script>
pg -- error since it is not defined
</script>
```

**Comment by f15gdsy** [comment]
Hi, you can use [webpack external](https://webpack.js.org/configuration/externals/#externals) to handle this. And how to change webpack config in Nuxt can be found [here](https://nuxtjs.org/api/configuration-build#extend)
And you should not use *import* in to import pg, instead, you should use require.
```javascript
let pg
if (typeof window !== 'undefined') {
  pg = require('plug.js')    // Hepends on how you set webpack alias
 Vue.use(pg)
}
```
The reason is that plug.js is actually set in HTML header, which means during server rendering, Nuxt could not know plug.js' existence, and you have to use it in client side.

Hope it helps.

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
