### ISSUE TITLE
axios-module is there a tutorial available

### ISSUE THREAD

**Issue by simonjcarr** [nuxt/nuxt.js#1968]
Hi, I want to use axios-module but even after reading the git hub readme page, I am not sure how to use it. Does any one know of a tutorial anywhere that gives a more detailed step by step guide on it use.

More specifically I want  to be able to store a authentication key for use with a remote api and include it in a centralised axios configuration along with other headers.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1753">#c1753</a>)</em></sub></div>

**Comment by Zip753** [comment]
From what I see, you could store the authentication key in vuex store somewhere and use it in axios request/response interceptors, since you're given the access to Nuxt context [as described here](https://github.com/nuxt-community/axios-module#requestinterceptor). I believe the latter example is actually quite similar to what you're trying to achieve.

**Comment by manniL** [comment]
There is a great documentation available [here](https://axios.nuxtjs.org/)

**Comment by manniL** [comment]
There is a great documentation available [here](https://axios.nuxtjs.org/)
