### ISSUE TITLE
Can I build locally and pass environment variables only when starting server ?

### ISSUE THREAD

**Issue by f15gdsy** [nuxt/nuxt.js#1983]
Hi,

I'm wondering if I could build a Nuxt project locally,
and on server I pass in environment variables when starting the server ?

I know that I can define environment variables in nuxt.config.js, but they have to be passed in during compilation.
For speed and stability's sake, I prefer to build locally.
So can I pass in environment variables when starting the server like HOST & PORT.

Thanks!

**Comment by Atinux** [comment]
It depends what can of environment variables @f15gdsy 

If these variables are used into your application files (by using `env` from `context`), they have to be given on build.

If it's environment variables specific to server (HOST & PORT) it can be used only for starting the app, but keep in mind that these variables can be used by some modules (axios-module for example). I usually recommend to build your app on your server :)

**Comment by jakubsacha** [comment]
I'd like to raise my concerns here. I put nuxtjs app in the docker image, next to the rest api (separate image) that it relies on. Then I employ them in my CI/CD pipeline. I start the nuxtjs app container and configure it (via environment variables) to use stage rest endpoint. Once i'm happy - i'd like to use the same image in the production environment. That means that the only one thing to adjust is to use prod rest endpoint, instead of stage one. Right now seems like i can not do it, since env variables are parsed on the build time.

Any ideas how to address this? cc @Atinux ?

**Comment by f15gdsy** [comment]
@jakubsacha I have the same usage scenario.
To my understanding, the current Nuxt env variables are used in both server & client side. And client side has no access to the env variables passed in when starting the server, like POST & HOST. So it's the reason why Nuxt cannot achieve our scenario.

**Comment by f15gdsy** [comment]
I think of a possible way to solve this problem.

1. Config the env variable;
2. Build without env variables;
3. Start using env variable, say VAR_1=123;
4. Server uses the VAR_1 to do whatever processing work;
5. Server embeds the VAR_1 to a script tag in the HTML file rendered;
6. Client receives the HTML file and uses the VAR_1 to do whatever processing work.

I'm wondering if this is possible? @Atinux

**Comment by jakubsacha** [comment]
Just to add a little bit of context to that discussion:

This is my dockerfile:
```
FROM node:8
ENV HOST 0.0.0.0
EXPOSE 3000
WORKDIR /app

COPY package.json yarn.lock /app/

RUN yarn install --pure-lockfile

COPY . /app/

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/app/entrypoint.sh"]
```
entrypoint.sh
```
#!/bin/bash
yarn run build
yarn run start
```

this gives me a chance to pass in the env variable on the container startup. The downside is that i have to rebuild the application everytime container is started (long startup times).

It would be perfect for me to be able to perform env substitution on the `yarn run start` step instead of `build`

**Comment by Atinux** [comment]
Actually you can get the server env variables inside the `nuxtServerInit` action, and then you can set them in your app state:

`store/index.js`:
```js
export const state = () => ({
  myEnv: null
})

export const mutations = {
  setMyEnv(state, value) {
    state.myEnv = value
  }
}

export const actions = {
  nuxtServerInit({ commit }) {
    commit('setMyEnv', process.env.MY_ENV)
  }
}
```

Then, you can start your app like this `MY_ENV=hello nuxt start`

Into your pages, you can display `<h3>My env: {{ $store.state.myEnv }}</h3>` and it will change without having to rebuild your app ;)

**Comment by jakubsacha** [comment]
@Atinux is that possible to use $store.state in the asyncData()?
