### ISSUE TITLE
Question: any solid CMS using Nuxt?

### ISSUE THREAD

**Issue by derekshull** [nuxt/nuxt.js#2002]
Is there a solid CMS out there thats built using Nuxt?  Needs to be SEO friendly, still fun to develop with, and have good page editing tools in the admin/backoffice.

P.S. If there isn't a good option out there, is anyone interested in starting a project to create one?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1777">#c1777</a>)</em></sub></div>

**Comment by derekshull** [comment]
I've decided to take the headless CMS approach like https://getdirectus.com/

**Comment by alexchopin** [comment]
Hi @derekshull, 
Actually, the closest project to answer your question from the community is [Nuxtent](https://nuxtent.now.sh/).

**Comment by alidcastano** [comment]
I believe @medfreeman, one of the maintainers of nuxtent, is working on something similar to this: https://github.com/medfreeman/nuxt-netlify-cms-module

**Comment by Atinux** [comment]
If you need headless CMS, there is also [CosmicJS](https://cosmicjs.com) with an example with Nuxt.js: https://github.com/cosmicjs/nuxt.js-website

**Comment by damienbeaufils** [comment]
In my team, we use another (french) headless CMS : https://prismic.io/

**Comment by dohomi** [comment]
@derekshull I am currently developing a CMS based on Nuxt, Vuetify and graphql + graph.cool. If you are interested send me a PM

**Comment by Almusamim** [comment]
I really which I can find this near perfect API-Based CMS which works hand in hand with NUXT.
Because for me NUXT is truly amazing and nearly perfect to work with!

But I have been really stuck on this same backend dilemma for some time now.. trying to find something modern and open-source , at the same time self-hosted and cheap to host!

I guess there are many great CMSes out there like Cosmicjs, Prismic, Contentful, Contentstack, ButterCMS, GraphCMS, Storyblock, Sanity, etc.. these are the usual recommended CMSes most of the time for NUXT but for someone like me who focuses mainly on small businesses who are not willing to pay lots of money for a host then none of these are an option for me!

So is there any self-hosted headless CMS, api-driven and open-source that would work great with Nuxt ?

I have played around with Directus and Cockpit's latest version..
And I was impressed with Cockpit and liked it much more than Directus..

Both are open source and self hosted and API driven.
The problem with both for me that you can only use their control panels to add the content models and fields, I just prefer having the option to do this in code like in Json or yaml.

Also not much of documentation for Cockpit but it is under heavy development so keep your eyes on it!

I usually use OctoberCMS for my typical none Nuxt projects.. I love this CMS and its easy workflow.
October which is a Laravel 5.5 based can be used as a headless CMS and with some tweaks, it can become a great CMS to use with Nuxt.. the only thing it is not made to be used as a headless CMS.

So anyway for PHP based CMS I would vote for Cockpit or even OctoberCMS.
if we only could take from the two and makes them ONE! :(

Now if money is not a issue for you to host NodeJS and want a Nodejs based CMS which is also open source as well then my vote would easily go for STRAPI.
Their version 2 is still in beta as well but its workflow is a beauty and more than simple!

I believe many would enjoy working with Strapi.. 

I would really love to see how other people think about all this! 
We really need a backend/CMS which is free or at least not expensive and self-hosted!

**Comment by DominikAngerer** [comment]
We're currently working on a full guide to build a website with NuxtJs and [Storyblok](https://www.storyblok.com) - a headless CMS. We've already created a sample: https://www.storyblok.com/tp/headless-cms-nuxtjs (src linked in that tutorial). 

@Almusamim it's free to use for smaller projects but not self-hosted.

**Comment by Almusamim** [comment]
@DominikAngerer thanks I will look into it :)

**Comment by justin-schroeder** [comment]
I'm very interested in developing a CMS that integrates directly with Nuxt. In particular I would love to create a package that can be installed directly on top of an existing Nuxt installation as a dependency and expose a seamless editing experience. It would require Nuxt to be run as a server rather than a statically generated site, but I've begun doing that more and more recently anyway.

If anyone is interested in helping create a project like that let me know (DM). I'm pretty sure my company would be happy to help sponsor its development, at least in terms of hours.

**Comment by derekshull** [comment]
@dohomi and @justin-shroeder 
Both interesting ideas. What would it entail to create something like that? Are there “basic building blocks” that all CMSs have that we would develop?

@Almusamim
Thanks for the info!

@DominikAngerer Storyblok looks great but I’m really looking for something self-hosted and hackable.

**Comment by justin-schroeder** [comment]
@derekshull less building blocks and more key features, but I think theres an interesting opportunity to build a component-based editor. Some key features for an MVP would be: rich edit-in-place editor (probably wrapping [quill](https://quilljs.com/)), image uploading, and basic page structure.

I think the goal in building something like this would not be a one-click install wordpress style CMS, but something that exposes a persistence api, and a simple out of the box editing experience for developers who want to use nuxt but also offer a simple/good editing experience.

**Comment by lindseybradford** [comment]
Anybody heard of Craft 3? They're vamping up their content API w/ the release of 3. Their content editing and structuring experience for both users and devs has always been 👌🏻. I'd be _really_ curious to see an integration with Nuxt…

**Comment by Almusamim** [comment]
@justin-schroeder @derekshull 

What about having something like [ng-admin](https://github.com/marmelab/ng-admin) and [Admin on rest](https://github.com/marmelab/admin-on-rest) but built with NuxtJS.

This approach makes perfect sense for quicker development and for decoupling frontend from the backend. As for the backend, one can choose whichever backend framework they like. Let it be AdonisJS, Express, Laravel, Slim or whatever to build the RESTful API.

**Comment by joernroeder** [comment]
anyone already played around with [strapi.io](https://strapi.io)? their roadmap seems promising…

**Comment by Bulletninja** [comment]
@justin-schroeder like wagtail (Django-based CMS framework, which can be used headless) but for nuxt.

**Comment by uptownhr** [comment]
it'd be best if this nuxt-cms is serverless!

**Comment by Almusamim** [comment]
I came across a very promising open source headless CMS which is relatively new called [Daptin](https://github.com/daptin/daptin)

The CMS seems easy to work with and addresses many of the points I made earlier like using YAML or JSON to define the schema.

What do you guys think? anyone of you used it?



## Key Features

* JSON APIs
  - create, read, update, delete
* GraphQL APIs
  - work in progress
* Client libraries for all platforms
* Rich data types
* Websocket support
* Sub sites hosting
* Oauth token and connections
* Cloud storage sync
* Action APIs and Relational data APIs
* Validation and conformation support
* Daptil will expose all APIs for easy use
* Fully featured dashboard
  - Responsive to desktop, mobile and table
* Cross platform
  - Windows, Mac and Linux ready.

**Daptin** is an open-source backend development framework to develop and deploy production-ready JSON API based applications. With Daptin you can design your data model and have a production ready JSON API online in minutes.

- Relational database backed persistent data
- CRUD JSON API
- User registration and login system
- Social login with oauth2: tested with google, github, linkedin
- Extensive state tracking APIs
- Enable Data Auditing from a single switch
- Market place enabling a variety of features
- Cloud storage sync like gdrive, dropbox, b2, s3 and more
- Manage multiple websites under separate sub-domain/sub-paths
- Connect with external APIs by using internal extension points
- Database to easily evolves your data schema & migrates your database [Postgres/MySQL/SQLite]
- Flexible auth using the JWT-based authentication & permission system
- Works with all frontend frameworks like React, Vue.js, Angular, Android, iOS
- **Very low memory requirement and horizontally scalable**
- Can be deployed on a wide range of hardware arm5,arm6,arm7,arm64,mips,mips64,mips64le,mipsle (or build for your target using go)



## Tech stack
Backend | Frontend | Standards | Frameworks
---|---|---|---
[Golang](golang.org) | [BootStrap](http://getbootstrap.com/) | [RAML](https://raml.org) | [CoPilot Theme](https://copilot.mistergf.io)
[Api2go](https://github.com/manyminds/api2go) |  | [JsonAPI](jsonapi.org) | [VueJS](https://vuejs.org/v2/guide/)
[rclone](https://github.com/ncw/rclone) |  [grapesJs](https://grapesjs.com) | | [Element UI](https://element.eleme.io)

**Comment by manniL** [comment]
Because this issue seems to be inactive for quite some time, I'll close it now. If you feel like it deserves some attention because it's not fixed, feel free to ping me and I'll reopen it.
