### ISSUE TITLE
Server-side rendering and native html incompatibility issues

### ISSUE THREAD

**Issue by surmon-china** [nuxt/nuxt.js#209]
When I use nuxt.js for server-side rendering,
I will encounter the following two issues, it now appears that these two issues are caused by vue.js:

1: I used the swiper component in the project. Since this component depends on the window object, I used the process.BROWSER_BUILD object judgment in nuxt.js to render the component only on the server side. When the page loads, the component renders correctly , The correct rendering, view the source code, you can see the corresponding swiper component code is not compiled before the component call code, such as: <swiper> ... </ swiper>, then the console by vue.js abnormal

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. And performing full client-side render.

This should not have existed

2: When I use the datalist element in html5 in a project, vue also throws an error like the one above

So I think, vue on the original html tags may not be sufficient to judge the rich, while rendering for the server, some judge is not perfect

Can there be improvements, or temporary solutions? Thank you!

**Comment by Atinux** [comment]
@surmon-china we are aware about this but we cannot do anything since the error is thrown by Vue.js itself.

The actual workaround is to use `process.BROWSER_BUILD` indeed but the warning is displayed by vue.js, but at least it works.

The only solution is that the libraries your are using start to be compatible with the server-side rendering.

For this, this libraries should use the `window` object only when accessible or directly inside the browser hooks event (https://vuejs.org/v2/api/#Options-Lifecycle-Hooks):
- beforeMount
- mounted
- beforeUpdate
- updated
- activated
- deactivated
- beforeDestroy
- destroyed

**Comment by surmon-china** [comment]
@Atinux thanks!
 I have solved it
