### ISSUE TITLE
Current page component is created again when switching layout

### ISSUE THREAD

**Issue by Capati** [nuxt/nuxt.js#214]
When you change to a page with a different layout the current page component is created again. This does not seems to be intentional? Let's say the current page will fetch some data using the `created` method, the problem is the the fetch will happen again when switching layout.

Example from custom layouts:

![layouts](https://cloud.githubusercontent.com/assets/15007761/22703709/34aec472-ed4c-11e6-9ece-fedc17a017c8.gif)

**Comment by Atinux** [comment]
Associated to this bug:

By @mkv27 on #237 
> How can I get layout switch at the same time of page content switch?.
> Currently when I use the layout switch is immediately, but the previous page content wait for new page content is loaded.
> 
> Example: When I routing for a new page with an async data, the layout change but the previous page content still alive(with "glitch" new layout) until new page data its ready.

**Comment by Atinux** [comment]
Good news, it will be fixed in the new release `0.9.10`!

Before:
![layout-bug](https://cloud.githubusercontent.com/assets/904724/23163062/d978a6b2-f828-11e6-8fe5-e09fa9271543.gif)

After:
![aftereach-layout](https://cloud.githubusercontent.com/assets/904724/23163051/d15d9244-f828-11e6-8686-04c6391c90d5.gif)

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋
