### ISSUE TITLE
nuxt.config.js with ava

### ISSUE THREAD

**Issue by wandarkaf** [nuxt/nuxt.js#2170]
I'm following the steps in the documentation to integrate ava and jsdom for testing and I hit a wall...
I have a project with a _nutx.config.js_ configuration file. And it seems you need to do some configuration that on this file that is not properly documented on [nuxt testing](https://nuxtjs.org/examples/testing/). When I run `yarn run test` I got a bunch of 

`
ERROR in app.4a0e11cc86875998f2bc.js from UglifyJs
Unexpected token: punc (() [./.nuxt/components/no-ssr.js:8,2][app.4a0e11cc86875998f2bc.js:148,6]`

type errors. Anyone knows or can help on the proper way of configure the _nutx.config.js_ to make ava and jsdom?  I can help to update the documentation of nuxt if needed.

Thanks :)

**Comment by clarkdo** [comment]
Try below config in your `package.json`.

```js
"ava": {
    "require": [
      "babel-register"
    ]
  }
```

**Comment by sinoon** [comment]
I also find this problem , and maybe caused by ava,if ava <=22 , It will be fine...I still finding hot to fix

**Comment by sinoon** [comment]
I find the reason : 
1. Nuxt build use babel with `presets:['vue-app']` 
2. `ava@0.23.0` will now set process.env.NODE_ENV to 'test', as long as the NODE_ENV environment variable has not already been set.

However,`vue-app`will change `targets` when  process.env.NODE_ENV to 'test' , It caused the error.

So, we can pass a `NODE_ENV` variable **NOT** equal when `npm test` , It will build success.

Like:`"test": "NODE_ENV=pro ava --serial --verbose"`,as long as `NODE_ENV` not equal to `test`,it's ok.

There is a very interesting thing that Error caused by `vue-app` with `ava`,but issue opened in `nuxt.js`:)

It maybe strange , so I will continue find a reasonable way to fix it.

**Comment by guersam** [comment]
Related to: https://github.com/vuejs/babel-preset-vue-app/issues/12

**Comment by wandarkaf** [comment]
This is so helpful, Thanks guys for the info and feedback. @clarkdo  @sinoon @guersam
