### ISSUE TITLE
vue version of the problem

### ISSUE THREAD

**Issue by roywuyy** [nuxt/nuxt.js#2194]
Is it possible to customize nuxt built vue version?
Because I want to use element-ui 2.0 but vue requires version 2.5.2 or later

**Comment by clarkdo** [comment]
https://github.com/nuxt/nuxt.js/issues/2142

**Comment by yuchonghua** [comment]
Looking forward to a faster solution, looking forward to the next nuxt version, I am very grateful to nuxt can be updated, but released a new version of the long time interval, so that many problems can only wait, which makes me more confused, but still very grateful to nuxt team, Nuxt also look forward to faster release

**Comment by yuchonghua** [comment]
/ping @Atinux @pi0 Looking forward to a faster solution, looking forward to the next nuxt version, I am very grateful to nuxt can be updated, but released a new version of the long time interval, so that many problems can only wait, which makes me more confused, but still very grateful to nuxt team, Nuxt also look forward to faster release
