### ISSUE TITLE
Wrong css order after build for production

### ISSUE THREAD

**Issue by danieloprado** [nuxt/nuxt.js#2211]
After build for production some styles get wrong order and it's affecting the aspect of the page.

Here an example, during the development:
![image](https://user-images.githubusercontent.com/7683575/33184808-bdadf50c-d065-11e7-9bb8-9162229a24a0.png)

At the production:
![image](https://user-images.githubusercontent.com/7683575/33184812-c41b2720-d065-11e7-93f2-89b95ad88dce.png)

**Comment by 0pt1m1z3r** [comment]
@danieloprado Because in dev mode scoped styles add after load js file of page.

**Comment by danieloprado** [comment]
It's bad because the behavior of dev environment should be same of the production's, to make that you develop is what you launch. There is any way to make it more consistent?

**Comment by husayt** [comment]
This seems like a webpack issue. 

Closing this issue for now. Let us know if you have anything to add.

**Comment by qm3ster** [comment]
Well, without this you wouldn't have hot css reload. In production, route css is extracted, while in development it is loaded in the order of component loading (and reapplied when reloading)
Try to structure your css selectors so that these don't come from two places with comparable specificity, it will benefit you in the long run.
