### ISSUE TITLE
These dependencies were not found:

### ISSUE THREAD

**Issue by duqigit** [nuxt/nuxt.js#2222]
I introduced vux, but there was a loader error when it started
The code is detailed below

nuxt.confg.js

![6fa49efece1d661e32032a2a067b333](https://user-images.githubusercontent.com/25985156/33198704-a6ceede2-d127-11e7-87d2-d732d1d403f9.png)

package.json
![6f7a20ceef65053d582fb4fd1ac4cd0](https://user-images.githubusercontent.com/25985156/33198708-ae84e58c-d127-11e7-9ed6-05a0ce56831a.png)

error

![0534d21464d61af3555b46b1d5b65ea](https://user-images.githubusercontent.com/25985156/33198711-b3c33d78-d127-11e7-94b1-695623baa779.png)

Thanks

**Comment by rhwilr** [comment]
I get the same error. It seems to have been introduced in 259f26bd4fc8d562ddd7ef90420c00949582afcd
Once I added `modulesDir: ['node_modules'],` to my nuxt.config.js it worked.

**Comment by pi0** [comment]
@18717700273 I think you need to add appreciate loaders for less language support. (`yarn add less less-loader`)

**Comment by pi0** [comment]
@rhwilr That's strange. First, the recent changes are not officially released yet. So that just maybe with your special case which are using custom builds.

Also `modulesDir` should be defaulting to `node_modules` too. Would you please help to track issue if really exists before 1.0.0? A new PR or Issue would be nice, as i think is not related to this one :)
