### ISSUE TITLE
The fetch method does not have a callback param.

### ISSUE THREAD

**Issue by nekdolan** [nuxt/nuxt.js#2255]
In the documentation it states:

> The fetch method is used to fill the store before rendering the page, it's like the asyncData method except it doesn't set the component data.

The asyncData has a callback for the case someone doesn't want to use promises, however the fetch method seems to lack this function parameter. I think the fetch method should be able to handle a callback with a possible error parameter even if it does not return any data.

**Comment by pauldariye** [comment]
You can wrap the promise call in a `try/catch` if you use `async/await`

**Comment by nekdolan** [comment]
@pauldariye thanks but the try catch block will catch my mistakes I make as well so I do not want to use that. I think the point of the callback in the asyncData is that you can use whichever you prefer (promise or callback). Right now I am using asyncData that returns an empty object.

**Comment by clarkdo** [comment]
@nekdolan 
You can use both `promise` and `async/await` on `fetch`, just don't forget to return a promise for caller to wait.

Just like https://nuxtjs.org/api/pages-fetch#the-fetch-method, 'axios.get' is a promise.

`asyncData` provides a `callback` is because that no matter use promise or await/async, it must return `value` for populating the `data` , but `fetch` doesn't have this requirement, so callback is unnecessary on it 😸

**Comment by nekdolan** [comment]
@clarkdo asyncData doesn't need the callback either. You could use a promise or async just like in the case of the fetch method. I think the reason why asyncData has a callback is because having the last parameter as a callback (like nodejs libs) and at the same time returning a promise has been the best practice in modern api libraries.
