### ISSUE TITLE
nuxt@next - plugins suddenly bundled in vendor.js file

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#2394]
Hy all,
I just have updated the nuxt@next branch to get the new Vue version :) Looks good so far, but now I've seen that my vendor file grew up to over 300kb (which gives me a warning that it is too big now).

This wasn't the case with rc11 or the nuxt@next branch I had before (1.0.0-gh-b31b0f2). Is this intended?

thanks
Simon

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2079">#c2079</a>)</em></sub></div>

**Comment by pi0** [comment]
Hey @simllll. Thanks for your early adoption and testing. Yes actually the reason is that we strictly move every lib into vendor chunk. Until now and in recent RCs strategy was to not do this if it was used in less than 1/2 of the pages. But it seemed something unreasonable for plugins which *by design* are included once. Actually, until now some of those libs were wrongly included in `app` chunk which just hides the warn but in practice prevents long-term caching. BTW we are always open for ideas and comments if we can improve the approach.

**Comment by sebastianmacias** [comment]
Async plugins support might really help lowering the initial load, great idea.

Quick question if I import a library on a plugin I don't need to add it to vendors under nuxt.conf.js unless I need to import it again on a different module, is that correct?

**Comment by pi0** [comment]
@sebastianmacias Indeed now vendor config is not needed anymore for everything inside node_modules. It will automatically caught using Commonchunks plugin.

**Comment by pi0** [comment]
We can have an option to disable Commonchunks to manually cherry-pick vendors too.

**Comment by tonyrewin** [comment]
If it is the only way to reduce now vendor.js size then we need so

**Comment by sebastianmacias** [comment]
@pi0 thanks for the clarification. Amazing work!

**Comment by mcquiggd** [comment]
Interesting information.

We were discussing this on a thread (linked to above), regarding Axios and Veutify as dependencies.

To clarify, is it correct to say that:

1. Any library included as a **dependency** in package.json will be automatically included in the **vendor** bundle, exactly once, and, therefore does not need to be specified to be included in the vendor section of the nuxt.config.

2. Any library included as a **devDependency** in package.json will be **not** be automatically included in the **vendor** bundle, **unless** it is explicitly included in the vendor section of the nuxt.config, and if it is, it will be then be added to the vendor bundle exactly once.

3. Any library described by a **plugin**, e.g. a plugin that _imports_ Axios, irrespective if it is a _dependency_ or a _devDependency_, will be automatically included in the **vendor** bundle, exactly once, and, therefore does not need to be specified to be included in the vendor section of the nuxt.config.

4. If we are performing SSR, and therefore a package (e.g.) Axios, is only used server side, it is  **not** required to be included in the **vendor** bundle. If this is the case, we can exclude it from the **vendor** bundle by making it a _devDependency_, rather than a _dependency_? What if it is configured via a Plugin, or _imported_ by a Middleware?

Essentially, I would really like to understand how to correctly structure packages / plugins/ dependencies / devDependencies for correct operation in both Development and Production builds, in SSR / SPA / Generated scenarios... and to not send unnecessary files to the client. 

There is a little more background info including observed behaviour, in the linked thread.

Any input really welcome!

**Comment by bovas85** [comment]
I'd like a good answer to @mcquiggd question as well, that'd really help!

**Comment by rbwilcoxon11** [comment]
@mcquiggd, did you ever figure out number 4? I am running into the problem where fontawesome and prism are close to 2MB, and being thrown into my vendor.js, though they are only used during nuxt generate...

**Comment by bovas85** [comment]
if they are required in the client side they will be added as static site will need to bundle those up to work.
It will be slightly smaller if you build in node

**Comment by mcquiggd** [comment]
@rbwilcoxon11 

No, I was hoping to get 'official' guidance from the team rather than try to infer what the current situation was, as obviously with new releases behaviour can (and has) changed.

**Comment by rbwilcoxon11** [comment]
@bovas85  I don't follow... I am building in node. Are you saying if I serve from nuxt directly instead of SSR?

@mcquiggd  
Ah, I understand. If I come across / up with anything I will let you know. I tried webpack externals but I kept breaking my builds because it would strip them out before ssr.

I'm going to try and put everything I know isn't needed at run time into a separate vendor chunk, and try to stop it from loading there. If not, I think I'm going to have to go with a custom workaround that injects the modules I need during generate.

**Comment by bovas85** [comment]
@rbwilcoxon11 if you bundle as a static site, it will add dependancies that can otherwise be removed with SSR (due to it not having a server) so it's obviously going to be bigger.
2MB is quite too much though, can you do --analyze while doing npm run generate?

(to do so add:
```
analyze: {
      analyzerMode: "static"
    },
```
to your build section in nuxt

**Comment by rbwilcoxon11** [comment]
![2018-04-10_22-59-58](https://user-images.githubusercontent.com/6274893/38630109-320ec726-3d73-11e8-984e-748e4d4385fe.png)

**Comment by bovas85** [comment]
Hmm can you show how you load those and are they in dev dependancies in package.json?

**Comment by rbwilcoxon11** [comment]
## Loading Prism

Prism is loaded by the nuxt community module markdownit

_nuxt.config.js_
```javascript
module.exports = {
...
  modules: [
    ...
    '@nuxtjs/markdownit',
    ...
  ],
...
  markdownit: {
    injected: true,
    preset: 'default',
    linkify: true,
    breaks: true,
    use: [
      'markdown-it-container',
      'markdown-it-attrs',
      'markdown-it-prism'
    ]
  },
...
}
```

## Loading Fontawesome

I load fontawesome myself through a plugin; all fontawesome modules are in devDependencies

_plugins/font-awesome.js_
```javascript
import Vue from 'vue'

import FontAwesome from '@fortawesome/fontawesome';
import FontAwesomeIcon from '@fortawesome/vue-fontawesome'
import { 
  faBars,
  faLockOpenAlt, faLockAlt, faUnlockAlt
} from '@fortawesome/fontawesome-pro-light';
import { 
  faChevronDown
} from '@fortawesome/fontawesome-pro-regular';

export default () => {
  FontAwesome.library.add(
    faBars,
    faLockOpenAlt, faLockAlt, faUnlockAlt,
    faChevronDown
  )
  Vue.component('fa-icon', FontAwesomeIcon)
}
```
_nuxt.config.js_
```javascript
module.exports = {
...
  plugins: [
    ...
    'plugins/font-awesome.js',
    ...
  ],
...
}
```

**Comment by rbwilcoxon11** [comment]
Well, I solved the font awesome problem by manually importing each svg definition. Fontawesome still ends up in the vendor, but at a workable 75KB versus the previous 1.5MB
_plugins/font-awesome_
```javascript
// from
import FontAwesome from '@fortawesome/fontawesome';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { 
  faBars,
  faLockOpenAlt, faLockAlt, faUnlockAlt
} from '@fortawesome/fontawesome-pro-light';
import { 
  faChevronDown
} from '@fortawesome/fontawesome-pro-regular';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// to
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import { faBars } from '@fortawesome/fontawesome-pro-light/faLockOpenAlt.js';
import { faLockOpenAlt } from '@fortawesome/fontawesome-pro-light/faBars.js';
import { faLockAlt } from '@fortawesome/fontawesome-pro-light/faLockAlt.js';
import { faUnlockAlt } from '@fortawesome/fontawesome-pro-light/faUnlockAlt.js';

import { faChevronDown } from '@fortawesome/fontawesome-pro-light/faChevronDown.js';
```

I also found that without the "injected" option turned on, prism and markdown it are excluded from the vendor. Only problem is, this causes all markdown in asyncData not to be processed... guess I'll take the issue up with them...

**Comment by bovas85** [comment]
Why don't you use fontello rather than that? 

It seems like it's not an issue of Nuxt, it's just you imported 3rd party libraries that are polluting vendor and are included with a reason.

I suggest opening an issue in their relevant github

**Comment by theleebriggs** [comment]
Hi there, bit late to this thread, and having read through it I can't see a way to stop modules that are imported by `serverMiddleware` scripts from being bundled into the `vendor` file.

In my case I have a piece of middleware set up to send an email when hit, this means the middleware imports a mail library - this library then ends up in `vendor` file. It is under `devDependencies`rather than `deps`. I assume the act of `require`ing it causes it to go in `vendor`?

It sounds like this is intentional...are there any workarounds config wise?

**Comment by manniL** [comment]
`vendor` won't be used in `nuxt-edge` as webpack4 handles chunking more intelligent now.
