### ISSUE TITLE
How can I separated public website from authenticated website

### ISSUE THREAD

**Issue by ricardopolo** [nuxt/nuxt.js#2533]
Hi.

I am starting with vue and nuxt. I usted to work in old style ASP.NET MVC Apps.

I am not able to find how should I manage the "app" vs the landing page. 
How can I be sure that the internal site is not "generated" and cached by the server?

Excuse me for the open question. Any advice about the correct approach will be appreciated.

Thanks

**Comment by cesasol** [comment]
I'm currently starting my career and to tackle this problem I choose to have a static or cms+nuxt dynamic website in one codebase and another for the backend or app.

To manage shared styles I use sass and submodules and build it like a framework in order to cherrypick what I need in each case without having to maintain two sets of stylesheets

**Comment by neonerd** [comment]
If you are using `nuxt generate` and want the users to be able to visit the "app",  you have to have the static files generated in order for it to work. You can then of course check if the user is logged in and redirect him if he's not, but the file will be there.

If you are using nuxt in the "server" or "single page app" only mode, you can use middleware (https://nuxtjs.org/guide/routing#middleware) to always redirect user out of the "authenticated" part of application if he is not logged in.

**Comment by ricardopolo** [comment]
thanks!
