### ISSUE TITLE
Insert svg spritemap after <body>

### ISSUE THREAD

**Issue by vinjegaard** [nuxt/nuxt.js#2539]
I've created a script to generate a spritemap (.svg file) in assets that I want to insert right after `<body>`. Is it possible to insert the content of that svg-file in some way?

**Comment by microcipcip** [comment]
Indeed [you can](https://nuxtjs.org/guide/views/#document), create a `app.html` file in the root of your project with the content from this content:

```
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
<head>
  {{ HEAD }}
</head>
<body {{ BODY_ATTRS }}>
<svg></svg>
{{ APP }}
</body>
</html>
```

**Comment by vinjegaard** [comment]
@microcipcip Thank you, I did this as a temporary solution. My question is if it's possible to inject the file in the template when building, the spritemap is generated when building and I don't want to have to copy paste the content of the file manually to the template file.

**Comment by microcipcip** [comment]
I don't know how you build the svg, if you are generating that with node, maybe you can append it with regex directly into the html file? Otherwise I guess you could do something like this `<svg v-html="require('~/assets/sprite.svg')"></svg>` but I guess you won't be able to append it outside the vue app. Maybe [this example](https://github.com/osudio-erik/svg-icons) may help you.
