### ISSUE TITLE
Loader completes prematurely if middleware returns a redirect

### ISSUE THREAD

**Issue by silverbackdan** [nuxt/nuxt.js#2563]
It appears that if I return a redirect from router middleware, the loader completes, instead of continuing while the page that is being redirected to loads and that routes middleware are executed.

Please let me know if you'd like a repro. Cheers.

**Comment by clarkdo** [comment]
It should be a expected behavior in `vue-router`, if you have nested `router.push`, hook in `beforeEach` and  `afterEach` will only be executed once.

If it can execute middleware after redirect, may lead to multiple data fetching or infinite loop in redirecting, and if you want to do some validations, you may use [validate method](https://nuxtjs.org/api/pages-validate#the-validate-method).

We can discuss about this to figure out an appropriate solution, /cc @Atinux @pi0

**Comment by silverbackdan** [comment]
Thanks for the fast response @clarkdo 

I think I may not have explained well or have misunderstood the answer.

The middleware is executed twice, that's all fine. The issue is the loading bar. It stops after the first request and does not start again. So once the middleware calls redirect, the default loading bar finishes instead of starting again for the redirected route.

**Comment by Atinux** [comment]
Hi @silverbackdan 

I just pushed a fix about it (https://github.com/nuxt/nuxt.js/commit/e33d5026966e23d71dc33078a9122bf4a9fccd61), we will release a new version of Nuxt.js next week.

It also handle when a redirect is to himself or to another page :)

**Comment by silverbackdan** [comment]
That's awesome, thanks @Atinux - you rock!

**Comment by Atinux** [comment]
@silverbackdan I just pushed `v1.1.0` :)
