### ISSUE TITLE
How can I watch a folder routes (for express api)?

### ISSUE THREAD

**Issue by phenrigomes** [nuxt/nuxt.js#258]
I added a folder in the project root, but when I change some file in this folder the reload does not run. In my project structure I have also a folder called services to put ajax services, etc.

**Comment by Atinux** [comment]
Are these files for the server-side or the web app?

**Server-side files:** make sure to watch the folder with `nodemon` too
**Web App: ** Are you importing these files in your application, so webpack can watch them?

**Comment by pistacchio** [comment]
Hi,
I see there are no replies to this is issue, but it's exactly the one I'm facing.
I have my express api in `~/api/`. I would expect Nuxt to reload when I make some changes to the files in that dir, but it doesn't.

In you reply you suggest nodemon + webpack, but since I'm simply using `npm run dev` that fires nuxt, I don't have any direct control on either nodemon (if it's used internally) or on webpack (that I'm pretty sure is). I tried adding `watch: [ '~/api/*.js']`, `watch: [ '~/api/index.js']`, `watch: [ '~/api/**/*.js']` to `build` in `nuxt.conf.js` but with no luck.

Any suggestion? Thanks
