### ISSUE TITLE
noscript Tag

### ISSUE THREAD

**Issue by do-web** [nuxt/nuxt.js#2582]
If i add a noscript tag i get a warning. In the compiled version i get a js error message.

"The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render."

I have tried to add this to a plugin file, but it do not work.

`
Vue.config.ignoredElements.push('noscript');
`

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2247">#c2247</a>)</em></sub></div>

**Comment by Wei12345** [comment]
How do you add your noscript tag

**Comment by mayognaise** [comment]
@do-web @Wei12345 this works:
https://github.com/nuxt/nuxt.js/pull/2674/commits/8b634c210d1fb0ccfe7e1172242b9771b374efa8

**Comment by wayz-of-chang** [comment]
By adding inline-template (e.g. <noscript inline-template>...</noscript>), I was able to get nuxt/vue to ignore parsing that tag.  It's a hack, but it works, and nuxt doesn't throw an error, and the browser renders everything correctly with or without JS enabled.  I'm posting this here, because I stumbled upon this thread in my quest to search for an answer, and so, hopefully this will help people in the future who are looking for something similar.  For reference, https://vuejs.org/v2/guide/components.html#Inline-Templates

**Comment by morimi** [comment]
Setting a noscript tag in meta will be added to body.
However, in SPA mode and static file, it works only when JavaScript is ON.
To display the contents of noscript to a user with JavaScript turned OFF,
Even in these two situations, you need to change to "Show noscript tags even if JavaScript is OFF".
( Anyway in SPA mode and static files, content is not displayed at all if JavaScript is turned off )

**Comment by manniL** [comment]
You can set `noscript` through meta.

See [this example](https://github.com/Developmint/developmint.de/blob/18ef75f63b58967d0567fd8a6802f0c26b7a9215/nuxt.config.js#L64) for a production solution.
