### ISSUE TITLE
How to add nuxt to an already existing project?

### ISSUE THREAD

**Issue by AlexLomm** [nuxt/nuxt.js#2596]
Is there an official guide on enabling nuxt for already existing projects?

**Comment by NicoPennec** [comment]
can you explain more what is an existing project for you?

if you talk about to add Nuxt in a node.js project with express, you can use Nuxt.js as a middleware: https://nuxtjs.org/api/nuxt-render/

**Comment by AlexLomm** [comment]
Thanks for replying.

I have an existing Vue(v2.5.2) project and want to add Nuxt to it.

**Comment by maurodollinger** [comment]
I'm on the same thing here. I build a project in Vue, and now I have to add Nuxt for SEO reasons.

**Comment by AlexLomm** [comment]
I guess there is no such way, currently I'm rewriting my app to fit into nuxt's guidelines

**Comment by NicoPennec** [comment]
I think the simplest solution is to rewrite from scratch ;-)

Read the doc carefully.

Create a new project from nuxt-community/starter-template,
then you copy your Stores and Components, in to the corresponding folders.
For routing, you have to re-create each route by convention of fichiers in Pages folder.

Afterward, for each Page you have to rethink and refactor you loading and data strategy (asyncData() instead of data()).
Finally don't forget for each elements /vendor lib  check if it can be rendering on Server Side.

Finally take a look to all official examples: https://github.com/nuxt/nuxt.js/tree/dev/examples
probably the best ressources to start a Nuxt project

**Comment by AlexLomm** [comment]
Doing just that, thanks.

**Comment by maurodollinger** [comment]
thanks for your answer, really helpful

**Comment by AndrianD** [comment]
Great, however I got a question,
So i got a project made with symfony4 and vuejs2 with webpack Encore
. The question is: How can i make nuxtjs working with symfony 4 and handle my `.vue` components ?
Thanks for your suggestions.
