### ISSUE TITLE
Duplicate layout when happen some error

### ISSUE THREAD

**Issue by joaocarvalhowd** [nuxt/nuxt.js#2600]
![screenshot from 2018-01-15 15-01-12](https://user-images.githubusercontent.com/7674544/34953826-2a3f5d46-fa05-11e7-8723-4e5791412d7c.png)

**Comment by javialon26** [comment]
Same here. This happen if the error page is customized with layout/error.vue with nuxt version >= 1.

**Comment by joaocarvalhowd** [comment]
Can someone help me? @Atinux @alexchopin @pi0

**Comment by javialon26** [comment]
Any update on this? @Atinux @pi0

**Comment by paulgv** [comment]
Could you please provide a repo so we can reproduce the bug?

**Comment by javialon26** [comment]
@paulgv thank you for the response, i made this repo https://github.com/javialon26/nuxt-error-layout

I found the problem, the error layout is not like other layouts because by default use default.vue as base layout and if you put common components (ex.: header, footer) in the error layouts that already exist in default.vue everything's shown duplicated.

The solution is remove common components from error.vue and treat it like a common page not as layout.

Thank you!

**Comment by joaocarvalhowd** [comment]
exactly, thanks! @javialon26
