### ISSUE TITLE
Nuxt abnormal stop online

### ISSUE THREAD

**Issue by yyyuuu777** [nuxt/nuxt.js#2629]
hi~, I use nginx as a reverse proxy and pm2 run nuxt,  My server config  is Xeon E5 1410， my server receive 100000 request one hour, the nuxt server abnormal stop, I don't know why, if node have any error log ? or node can not suffer too many request ? 

                                                                                         Wish your answer and best regards

**Comment by Meeeeow** [comment]
You can get latest logs by run `pm2 logs **you-app-name**`, if it ends with something like "Killed" or "Out of memory", it mean your system does not have enough memory to keep it running.

This could caused by many reason, such as your application memory leak, other application memory leak,  some action takes too many memory and react V8 memory limit
