### ISSUE TITLE
Define layout dynamically

### ISSUE THREAD

**Issue by Ca4tkin** [nuxt/nuxt.js#265]
Hi! Is there a way to define layout dynamically by variable or with a ternary expression? I need to change the layout if mobile device is detected.

**Comment by Atinux** [comment]
Hi @Ca4tkin 

Could you provide an example of how you would like to set a dynamic layout?

**Comment by Ca4tkin** [comment]
Something like this:
layout: this.$store.state.isMobile ? 'mobile' : 'default'

**Comment by awronski** [comment]
I am looking for the same solution.

Could you change layout property to a function that receive context, eg:

```javascript
layout: (context) => context.isMobile ? 'mobile' : 'desktop'
```

**Comment by OlzhasAlexandrov** [comment]
+1 for the dynamic layout switching

**Comment by Atinux** [comment]
+1

**Comment by awronski** [comment]
Hi Guys!

Can we go further? Is it technically possible to add context to the layouts?

Because of no context now all the conditions needs to be put in the pages.
This causes code duplication in the pages and the layouts are only sufficient for very simple cases.

For example what I would like to do:
- switching components depends on the user-agent, user location, language, headers etc
- switching components depends on the application state
- switching components depends on the external environments variables
- switching themes (css) depends on the requested domains (domain.com, domain.fr, domain.de ...)
- and so on.

Now all the code I moved to the pages and I don't use layouts at all :(

@alexchopin What do you think about it?

**Comment by Atinux** [comment]
@awronski you can add all of these variables (location, user-agent, etc.) in the `nuxtServerInit` directly in your global state via the store.

Then, you can access `$store` everywhere in your layouts, pages and components.

The actual difficulty of setting a layout dynamically was the fact that a layout also have middleware attached to it, but I think I found a way of doing it.

**Comment by awronski** [comment]
@Atinux 
Thanks, it works. I wrote an example. Maybe it will helps someone else:

https://github.com/awronski/nuxtjs-examples/tree/master/mobile-desktop-with-store

**Comment by Atinux** [comment]
Small overview 😄 

![dynamic-layout](https://cloud.githubusercontent.com/assets/904724/24052942/8beb03d2-0b37-11e7-93b9-1633f47d0e67.gif)

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋

**Comment by kodekrendel** [comment]
@Atinux still unclear how to use it?

**Comment by ausir0726** [comment]
@kodekrendel 
defined layout function at your vue file in pages folder

```js
// index.vue
export default {
  layout () {
    return checkSomethingYouWant ? 'layout_a' : 'layout_b' ;
  }
}
```

https://nuxtjs.org/api/pages-layout/#the-layout-property

**Comment by kodekrendel** [comment]
@ausir0726 thanks, will try, but lack of examples is frustrating.

**Comment by Atinux** [comment]
@kodekrendel see https://github.com/nuxt/nuxt.js/tree/master/examples/dynamic-layouts

**Comment by kodekrendel** [comment]
I saw that example, but it's not informative for me:

```
  asyncData ({ req }) {
    return {
      name: req ? 'server' : 'client'
    }
  }
```

**Comment by Atinux** [comment]
You should check this line: https://github.com/nuxt/nuxt.js/blob/master/examples/dynamic-layouts/pages/index.vue#L10

**Comment by kodekrendel** [comment]
And live demo is broken by the way - https://nuxt-custom-layouts.glitch.me

**Comment by kodekrendel** [comment]
@Atinux hm, I didn't saw that. 
This is confusing - https://nuxtjs.org/examples/layouts/

**Comment by kodekrendel** [comment]
Note that on https://nuxtjs.org/examples/layouts/ you don't have this lines

```
<script>
export default {
  layout: ({ isMobile }) => isMobile ? 'mobile' : 'default',
}
</script>
```

**Comment by Atinux** [comment]
Yes, there is 2 examples: `custom-layout`s and `dynamic-layouts`, the live example and the documentation example use only `custom-layouts`.

**Comment by Atinux** [comment]
See the live examples:
- Custom layouts: https://glitch.com/edit/#!/nuxt-custom-layouts ([demo](https://nuxt-custom-layouts.glitch.me/))
- Dynamic layouts: https://glitch.com/edit/#!/nuxt-dynamic-layouts ([demo](https://nuxt-dynamic-layouts.glitch.me/))

**Comment by kodekrendel** [comment]
@Atinux tnx. Also first example with error `TypeError: Cannot read property 'req' of undefined`

**Comment by ausir0726** [comment]
@kodekrendel 

that because 0.10.0 have breaking change ,
should change data to asyncData

**Comment by Atinux** [comment]
Fixed @kodekrendel @ausir0726

**Comment by kodekrendel** [comment]
Ok, But what if I don't want to change whole layout, but some styles in components? Is there's the way to do that?

For example. I have Header Component with white background. When I go to `/some-page` I want Header with black background. How to do that the best? Note, that this Components are from `default.vue` layout, so I can't assign a simple CSS class for this, since I doesn't import Components in every page manually.

Not sure if it's related to topic, but still curious about the options.

**Comment by Atinux** [comment]
You can $watch the route and update the CSS classes applied, you don't need to use custom layouts for this @kodekrendel 

I recommend you to carefully read the Vue.js and Vue-router documentation :)

**Comment by FieryCod** [comment]
@Atinux I want to split the layouts to `layouts/desktop/*` and `layouts/mobile/*`.
I did a change in an `/pages/index.vue` which points to `layouts/desktop/mainpage.vue` if user agent is desktop and `layouts/mobile/mainpage.vue` if user ager is desktop. The problem is that it does not work. simply my `pages/index.vue` looks like this:
```
<template>
  <section class="container">
    <h1> hello there </h1>
  </section>
</template>

<script>
export default {
  layout: ({ isMobile }) => isMobile ? 'mobile/mainpage' : 'desktop/mainpage'
};
</script>
```
In my layouts I got folders `/desktop` `/mobile` in which I want to store my layouts according to type of content. The problem is that the when I put my `mainpage.vue` layout in `layouts/desktop` nothing renders, but when I put `mainpage.vue` in `/layouts` and then I change 
`pages/index.vue` like so
```
<template>
  <section class="container">
    <h1> hello there </h1>
  </section>
</template>

<script>
export default {
  layout: ({ isMobile }) => isMobile ? 'mainpage' : 'mainpage'
};
</script>
```
it works correctly. 
It seems that layouts should not be nested in folders. Is there a quick fix for it? I dont want to name my layouts like `mainpageMobile.vue` I would rather keep those files in separate folders.

**Comment by sudhir600** [comment]
Hi, is there any possibility to set the layout in middleware based on the route.
my some or pages will be always /admin/anything and some are domain.com/page
so for /admin/anything I want to use a different layout. this is currently possible by adding layout in each page but I want to set it once in middleware and it should be accessed automatically.

**Comment by MariusRossouw** [comment]
I have 4 or more different layouts. How would I set the layout dynamically to any one of the four based on a single variable ? The above allows for 2 layouts and I am struggling to implement it for more layouts. Any help would be greatly appreciated
