### ISSUE TITLE
Is it possible to recall actions from asyncData?

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/nuxt.js#2684]
So, I have some axios call in `asyncData`, after while i would like to recall this action again, is it possible to call asyncData as a one big function again from `created` hook e.g.? Something like `this.asyncData()` ?

**Comment by Atinux** [comment]
This is a tricky question @lukasborawski 

It is possible but kind of tricky since you need to pass the context to the `asyncData` method, here how you can do it:

```js
 async mounted() {
    const data = await this.$options.asyncData(this.$root.$options.context)
    console.log('data', data)
 }
```

`this.$root.$options.context` is actually the last context given to `asyncData`, but keep in mind that `redirect` won't work for example.

**Comment by pi0** [comment]
REALLY useful workaround @atinux 👍

**Comment by roqsantacruz** [comment]
Hi guys,

This works after nuxt generate command??

**Comment by Atinux** [comment]
Well that should be @roqsantacruz
