### ISSUE TITLE
Should nuxtServerInit run before middleware?

### ISSUE THREAD

**Issue by corsen2000** [nuxt/nuxt.js#273]
I was surprised to see `nuxtServerInit` running before my projects middleware. I was attempting to add some information to the `context` within my middleware and then make use of it inside `nuxtServerInit`.

I was able to work around this by moving my middleware logic directly inside of `nuxtServerInit`.

Is the order in which these run currently intentional?

**Comment by Atinux** [comment]
Hi @corsen2000 

This is an intended behaviour since the nuxtServerInit is there to prepare the store with data from the server-side regardless of the middlewares.

Here the schema of how it works:
![nuxt-schema](https://cloud.githubusercontent.com/assets/904724/23069400/94ec52a4-f527-11e6-94c2-3c985c0e2fc0.png)

What you can do is to call your middleware from your `nuxtServerInit` action directly:

`store/index.js`:
```js
import userAgent from '~/middleware/user-agent'

export const state = {}

export const actions = {
  async nuxtServerInit ({ commit }, context) {
    await userAgent(context)
    // here my context is updated :)
  }
}
```

The `~middleware` alias will be added in the next release, but you can use `~/middleware` as seen in my code above.

**Comment by corsen2000** [comment]
@Atinux thanks for the explanation. I was able to do what I wanted using code similar to what you provided.
