### ISSUE TITLE
$toast is available in mounted but not in created function after browser refresh

### ISSUE THREAD

**Issue by mirhat** [nuxt/nuxt.js#2845]
I am getting this error 'Cannot read property 'error' of undefined' after refreshing page in browser.
It works fine if I navigate to page with nuxt-link. 
It also works fine if i use $toasted in mounted function instead of created.

- nuxt@1.3.0
- vue@2.5.13

mycomponent.vue
```
  created() {
    // This does not work
    this.$toast.error('Error')
  },
  mounted() {
    // This works
    this.$toast.error('Error')
  }
```

nuxt.config.js
```
modules: [
    '@nuxtjs/toast',
  ],
  toast: {
    position: 'bottom-right'
  },
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2471">#c2471</a>)</em></sub></div>

**Comment by paulgv** [comment]
This kind of module is client-side only since you can't display a toast notification on the server-side. This means you should not try to use it in the `created()` hook in Nuxt context since this hook is called on the server while rendering your components. Limiting the use to the `mounted()` (or any other other client-side only hook/method) hook seems like the best option.
