### ISSUE TITLE
I need some explanation on Nuxt app context.

### ISSUE THREAD

**Issue by chanlito** [nuxt/nuxt.js#2908]
The `app` object `context` object which contain `app` ... itself and so on 🤔

<img width="691" alt="screen shot 2018-02-27 at 7 55 59 pm" src="https://user-images.githubusercontent.com/15667259/36729962-6b92b026-1bf8-11e8-8359-71b97ab375fe.png">

**Comment by qm3ster** [comment]
Objects in JS are passed by reference (pointer). So all this means is that:
- the context object has a reference to the "app" object under key "app" and 
- the app object has a reference to the "context" object under key "context"

This is useful because in setup and plugins you have the "app" object available, but in _contexts_(:laughing:) such as the vue template you have the "context" object as the global object and `this`
