### ISSUE TITLE
Add 'async' to manifest.js, vendor.js, and app.js?

### ISSUE THREAD

**Issue by moso** [nuxt/nuxt.js#2926]
Hey,

I know how to add the `async`-attribute to external scripts through the config, but how do I add it to the files generated by Nuxt that resides just before the closing `</body>`-tag?

I can't seem to find it anywhere in the docs.

**Comment by manniL** [comment]
Why would you add async to `app.js`, `vendor.js` or `manifest.js`? You need those files for your whole NuxtJS application to work.

Besides, Nuxt already uses the code split technique (per page) and loads each page asynchronously.

**Comment by moso** [comment]
It was just an attempt to optimize for silly Google PageSpeed.

I'm not sure how to optimize further. The app itself is on 107.03 kB, and loads within 192 ms according to Pingdom. But it still gets 46/100 on mobile on PageSpeed Insights because of "render-blocking content". However, there's only 1 `

**Comment by moso** [comment]
It was just an attempt to optimize for silly Google PageSpeed.

I'm not sure how to optimize further. The app itself is on 107.03 kB, and loads within 192 ms according to Pingdom. But it still gets 46/100 on mobile on PageSpeed Insights because of "render-blocking content". However, there's only one `<script>`-tag in `<head>`, and that, as pointed out, has the `async=""`-attribute attached to it. So yeah, I'm testing whether it would have an impact or not, and was missing the opportunity to do so.

**Comment by qm3ster** [comment]
Can you link me your test?
It usually points to the thing it's complaining about, unless it's gotten much worse somehow.

**Comment by manniL** [comment]
@moso PageSpeed is often moaning about render-blocking above-the-fold content, caching (though your SW is doing it for you), or prioritizing visible content.

My best score with a (quite simple) Nuxt.JS page was 93 on mobile (https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flichter.io), but PageSpeed still complained about caching (though my SW is set-up correctly and caches everything) and above-the-fold content (which is only the CSS that isn't scoped).

Don't worry about that too much and cross-validate your site with [GTMetrix](http://gtmetrix.com/) and/or [WebPageTest](http://webpagetest.org/)

**Comment by moso** [comment]
@manniL Yeah, and Nginx is even set up to cache every asset for 30 days, so in those 'real life' usecases, my site is loading pretty fast and satisfactory.

I'm getting 100% on GTMetrix, with some minor complaints about the Vary header not set correctly on svg's, however Nginx is set to gzip everything including svgs.

I could probably eliminate those by inserting those svgs inline, and eliminate a request pr svg in the process.

So the conclusion is that PageSpeed is shite and still not a good enough tool to test Vue sites?

**Comment by manniL** [comment]
@moso Well, third-party assets (fonts, analytics etc.) might be the reason for the caching "issue" then.
100% on GTMetrix is definitely a good sign! So nothing is "wrong" with your site.

I think PageSpeed is just very strict. You could go with code splitting everything below the fold, so only content above the fold will be loaded first (like I did in https://github.com/manniL/lichter.io/blob/master/pages/index.vue) and load critical path CSS first so nothing is "blocking". 

There is always room for improvements and optimization

The question is: **Are they worth it?**

Decent code splitting is definitely a thing worth trying because it leads to a faster "first meaningful paint" (resulting in better user experience usually).

Modularizing CSS can be useful to a certain degree, but when using a framework like Bootstrap or an atomic CSS framework like TailwindCSS, you likely can't avoid loading the core first.

**Comment by moso** [comment]
@manniL: Cheers, appreciate the advice.
