### ISSUE TITLE
nuxt如何压缩静态站点资源的html代码

### ISSUE THREAD

**Issue by Jv-Juven** [nuxt/nuxt.js#2939]
`nuxt`项目跑`npm run generate`命令之后，生成的`dist`目录里，相关的`html`代码如何压缩？或者说nuxt有没有现成的方案在跑`npm run generate`命令的同时能做到压缩`html`的代码？

**Comment by qm3ster** [comment]
Compress as in html-minify, or compress as in gzip?

**Comment by Jv-Juven** [comment]
是的，是不是需要开发者另外自己做压缩？

**Comment by qm3ster** [comment]
I'm not sure which one you mean.
In production, by default, javascript and css are fully minified, and the HTML is quite minimal.
gzip is not applied, because that's usually handled by the server, but if you want to apply static gzip and brotli to your files, you can just do that to the `dist` directory at the end.

**Comment by yoyo837** [comment]
@qm3ster I think Jv-Juven means dist `html-minify`.
@Jv-Juven 默认production是压缩过的；

**Comment by clarkdo** [comment]
@Jv-Juven 
`dist` 目录的内容默认已通过`html-minifier`进行压缩, 可以通过`generate.minify`进行自定义配置
https://nuxtjs.org/api/configuration-generate#minify

**Comment by qm3ster** [comment]
@yoyo837 knowing the language is cheating.
