### ISSUE TITLE
After the page is changed does has a hook in the layout to listen？

### ISSUE THREAD

**Issue by HadiChen** [nuxt/nuxt.js#2975]
Is there a hook in the layouts to listen after each page change？I want to do something after each page loaded and listen in the layouts

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2578">#c2578</a>)</em></sub></div>

**Comment by paulgv** [comment]
You could use a middleware to execute some function before each page is rendered: https://nuxtjs.org/guide/routing#middleware

Another way would be to watch the `$route` property in your layout:

```es6
// layout/default.vue
export default {
  watch: {
    $route () {
      console.log('route changed', this.$route)
    }
  },
}
```

**Comment by usb248** [comment]
I search the same but not when the route change, rather after the page is rendered.
I did not find anything in doc or forum ...
I need this because i need to apply css class according to the current page in order to apply different style.
So i need to apply these class juste when the dom is rendered.

Any idea ?

**Comment by paulgv** [comment]
@usb248 you could add some logic to your pages `mounted` hook to do this.
If you still have this issue, I'd recommend you open another thread as this is unrelated to the original issue.
Closing this now as there was no more follow up by the original poster.
