### ISSUE TITLE
What about progressive rendering?

### ISSUE THREAD

**Issue by dschewchenko** [nuxt/nuxt.js#2979]
In SSR mode using NodeJS [Stream API](https://nodejs.org/api/stream.html).
E.g. send to client each component in ready status 

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2582">#c2582</a>)</em></sub></div>

**Comment by KindWizzard** [comment]
https://ssr.vuejs.org/en/streaming.html

However, when the first data chunk is emitted, the child components may not even be instantiated yet, neither will their lifecycle hooks get called. This means if the child components need to attach data to the render context in their lifecycle hooks, these data will not be available when the stream starts. Since a lot of the context information (like head information or inlined critical CSS) needs to be appear before the application markup, we essentially have to wait until the stream to complete before we can start making use of these context data.

**It is therefore NOT recommended to use streaming mode if you rely on context data populated by component lifecycle hooks.**
