### ISSUE TITLE
'Window is not defined' where do I put client-side only scripts?

### ISSUE THREAD

**Issue by 7ammer** [nuxt/nuxt.js#30]
I'm trying to run [a-frame](https://aframe.io) in one of my vue pages but I'm getting an error in my browser:
`ReferenceError: window is not defined`

I'm guessing this is because nuxt is trying to run the aframe module while rendering the page on the server.

```
<template>
    <div>
        <a-scene a-node fog="type: linear; color: #FFEBDE; far:190"  debug>
            <a-entity>
                <a-collada-model src="/obj/banner.dae"></a-collada-model>
                <a-ring color="teal" radius-inner="1" radius-outer="2"></a-ring>
            </a-entity>

            <a-entity position="0 -1 10">
                <a-camera>
                    <a-cursor color="#2E3A87"></a-cursor>
                </a-camera>
            </a-entity>
            <a-entity camera="userHeight: 1.6" look-controls></a-entity>
        </a-scene>
    </div>
</template>

<script>
import 'aframe';

export default {
    mounted() {

    }
}
</script>

```

**Comment by alexchopin** [comment]
Hi,
Yes, this is exactly due to the server-side rendering.
If you need to specify that you want to import a ressource only on the client-side inside, you need to you process.BROWSER_BUILD variable.

```
<script>
if (process.BROWSER_BUILD) {
  require('aframe')
}
export default {

}
</script>
```

Thanks for your report, the documentation of the website will be completed soon.

**Comment by 7ammer** [comment]
Ah ha, brilliant! Thanks!

**Comment by 7ammer** [comment]
Hmm a-frame doesn't play nice with vue. It doesn't load properly.

**Comment by andyhu** [comment]
I have experinced similar issues as well. I was trying to import a vue UI framework `element-ui`. However, it references window object and several native browser functions like `addEventListener` etc., so it breaks the server rendering. I'm thinking if there is a way to polyfill it somehow. Because for such kind of UI framework, if we cannot render it on server side, it's probably not good for SEO.
I've treid `next.js` with `antd` ( a UI framework built on `React.js` which similar to `element-ui` ) and it worked almost perfectly ( except `next.js` is using `glamor` as a `css-in-js` solution which is pretty hacky). When I have time I'll dig more for the reason why it's working in `next.js` but not `nuxt.js`.

**Comment by Atinux** [comment]
I think that every vue plugin should be able to work both client-side and server-side since the version 2.0 of Vue.js.

I asked the team behind `element-ui` but they said it's not their priority, but I don't think it will be complicated to make it compatible with server-side rendering, since we will only have to add `if` statement where a client-side only function is called.

@andyhu what library are you talking about which is working with next.js but not nuxt.js?

**Comment by andyhu** [comment]
@Atinux I mean I'm pretty sure that `antd` has some windows object references as well. But when I tried it, it does work in `next.js`. However it probably because that `antd` is more modular and I missed the browser specific part of the variable references. Anyway I'm going to test more.

**Comment by Atinux** [comment]
I hope they will add theses check so `element-ui` could be used on the server-side too and render the proper HTML code!

I'm closing this issue since the question has been answer by @alexchopin by using `process.BROWSER_BUILD`.

**Comment by declandewet** [comment]
I know this issue is closed and all, but I just want to point out an alternate solution - Vue's [lifecycle hooks](https://vuejs.org/v2/api/#Options-Lifecycle-Hooks). All hooks except for `beforeCreate` and `created` do not even run on the server. If you're doing any client-side manipulation or inspection and referencing built-in browser globals like `window` or `document`, then you should do those things in these methods. This solution removes the need to inspect environment variables.

**Comment by lmj0011** [comment]
https://github.com/nuxt/nuxt.js/issues/30#issuecomment-264348589
>Hi,
Yes, this is exactly due to the server-side rendering.
If you need to specify that you want to import a ressource only on the client-side inside, you need to you process.BROWSER_BUILD variable.[...]

why is this still not in the docs? I followed what was there and was still having issue importing a vue component. this solution cleared things up

**Comment by alexchopin** [comment]
[Documentation](https://nuxtjs.org/faq/window-document-undefined)

**Comment by thedamon** [comment]
The official [instructions on including Google analytics](https://nuxtjs.org/faq/google-analytics/) fail because of this

**Comment by dkushner** [comment]
I have a follow up to this inquiry and didn't want to clutter up the project with another issue. There is another use for client-specific code within a component and that would be querying client browser capabilities. For instance, I have a component that must query the media capabilities of the platform and obviously this operation only makes sense from the client side. How is something like this generally handled? 

I imagine this is also an issue for the people using WebGL, etc?

**Comment by dkushner** [comment]
I have a follow up question that is a bit relevant to this issue and didn't want to clutter up the project by opening another one. I have code that needs to query browser-specific media and streaming capabilities. Where would that code best be located such that it is guaranteed to run when the component appears on the client side (whether it has previously been rendered by the server or not). I imagine this is also an issue for anyone trying to integrate with WebGL and other WebAPI technologies. Anyone have some advice?

**Comment by Atinux** [comment]
@dkushner we have a special option for JS to be run only on client-side with `ssr: false` option: https://nuxtjs.org/guide/plugins#client-side-only

**Comment by dkushner** [comment]
@Atinux, perfect thanks! Just happened to miss that portion of the docs.

**Comment by dkushner** [comment]
@Atinux, actually I'm sorry it looks like that documentation is explicitly for Vue plugins. Do I need to wrap every external library I use as a Vue plugin in order to leverage this? For instance THREE and SocketIO will both rely on UA-specific objects being present like `document` and `window`. So do each of these libraries then become a separate plugin?

**Comment by lmj0011** [comment]
@dkushner yep

**Comment by sj82516** [comment]
Excuse me, I call window inside `mounted` function which should be run only in browser, still throw "window is not defined error"

**Comment by dotnetCarpenter** [comment]
Currently, nuxt.js `1.0.0-rc11`, it is **`process.browser`** and not `process.BROWSER_BUILD` inside a component.

**Comment by yun313350095** [comment]
Vue-FullCalendar 
app/plugins/vue-fullcalendar.js
```
import Vue from 'vue'

if (process.BROWSER_BUILD) {
  window.onNuxtReady(() => {
    const VueFullCalendar = require('vue-fullcalendar')
    Vue.use(VueFullCalendar)
  })
}
```

**Comment by MontageD** [comment]
This is the best answer I've ever seen. Thanks

**Comment by andrewharvey** [comment]
> I'm closing this issue since the question has been answer by @alexchopin by using process.BROWSER_BUILD.

How would that work if we are using import instead of require? If I put my import inside the if statement I get:

`NuxtServerError
Module build failed: SyntaxError: 'import' and 'export' may only appear at the top level`

**Comment by Atinux** [comment]
You have to use `require` at the moment @andrewharvey and ask for the library author to add SSR support (by giving him this link if it's a Vue.js library: https://ssr.vuejs.org/en/universal.html)

**Comment by andrewharvey** [comment]
> You have to use require at the moment @andrewharvey and ask for the library author to add SSR support (by giving him this link if it's a Vue.js library: https://ssr.vuejs.org/en/universal.html)

Thanks @Atinux. I also found I can use import by moving my code out from the page into a component and use `ssr: false` when loading that plugin in the nuxt.config.js.

**Comment by sudhir600** [comment]
@yun313350095  I tried `process.browser` but it didn't work. However, process.browser is working fine for me.

But is this real solution? i mean i have to put this if block every method, where i want to something for client-side interaction.

**Comment by EmixMaxime** [comment]
Hello, I'm very confused and having really bad times :disappointed: 

What if, I have to add some components after the first contentful paint ?

I've something like this:

```
    <no-ssr>
      <div id="post-footer">

        <post-share/>

        <div class="post-footer-suggestions" v-if="suggestionToShow">
          <p class="h2">ToRead</p>

          <post-suggestion/>

        </div>

      </div>
    </no-ssr>
```
But I can't figure out how to load these components in front...
```javascript
// vue instance
components: {
  // What I have to do?
}
```
Any help would be appreciated

**Comment by sudhir600** [comment]
@EmixMaxime  
```
<script>
import postShare from '~/components/anotherFolder/postShare.vue'

export default {
      components: {
           postShare
      }
</script>
```

in HTML,

```
<div id="post-footer">
        <postShare />
</div>
```
**Hope this will help**

**Comment by EmixMaxime** [comment]
@sudhir600 Hum, that load the component in the server side, I have the `window undefined` error.

**Comment by pbastowski** [comment]
You have to lazy-import your components like this:

```js
<script>
export default {
      components: {
           postShare: process.client && import('~/components/anotherFolder/postShare.vue')
      }
</script>
```
