### ISSUE TITLE
I'm confused when to use server side rendering vs generate

### ISSUE THREAD

**Issue by scottgrayson** [nuxt/nuxt.js#302]
Nuxt generate is so easy! But there must be downsides. Do you have some example scenarios of when server rendering is the better choice?

I'm not really sure how generate works. If you....
- make an a call to /api/users/index
-  v-for users as user {{ user.name }}

Does this api call and render happen on the server? Or on the client?
The quote below makes me think answer is both

> every time a product is out of stock or back in stock, we regenerate the web app. But if the user navigates through the web app in the meantime, it will be up to date thanks to the API calls made to the e-commerce API. No need to have multiple instances of a server + a cache anymore!

I was also reading pre-render vs srr information in this readme
https://github.com/chrisvfritz/prerender-spa-plugin

Can dynamic content pages like /my-profile be ignored by nuxt generate? Could requesting url /my-profile directly 404 or redirect, but navigating via login -> menu -> my-profile fetch the data from api?

Are all these possible with `nuxt generate`? If so, then when is server side rendering better?

**Comment by alexchopin** [comment]
Server side rendering is better to use on a project with data changing often, on the opposite static generated is better for data not changing so much.
The goal of Nuxt generate option is to be able to have a serverless Vue application, like the example you mentioned before.
However, that's not so easy to do for some project with a string dependancies with server.
That's why you can do both with Nuxt, start your project server rendered and then try to external more and more services.
Finally only use static generated project and triggers changes to regenerate you project.
