### ISSUE TITLE
Feature req: config option to disable pretty output

### ISSUE THREAD

**Issue by moltar** [nuxt/nuxt.js#3071]
I'd like to be able to supress and/or have control over formatting of this output. It is very unfriendly in a sense that it clears screen and is not friendly with other loggers when running in SSR mode via another server.

```
  nuxt:build Building... +0ms
  nuxt:build App root: .../resources +0ms
  nuxt:build Generating .../.nuxt files... +0ms
  nuxt:build Generating files... +38ms
  nuxt:build Generating routes... +14ms
  nuxt:build Building files... +24ms
  ████████████████████ 100%

Build completed in 16.844s



 WARNING  Compiled with 1 warnings                                                                                                                                                                  3:15:53 p.m.

 warning

asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
This can impact web performance.
Assets:
  vendor.447480b3225e78edb007.js (598 kB)



  nuxt:build Building done +20s
```

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2658">#c2658</a>)</em></sub></div>

**Comment by manniL** [comment]
A minimal output will be provided when setting the environment variable `CI=true` (example: `CI=true npm run dev`). Fine-grained settings can be changed with `webpack options` (warnings/assets) and [webpackbar](https://github.com/nuxt/webpackbar#minimal)

**Comment by moltar** [comment]
Starting in which version? Thanks.

**Comment by moltar** [comment]
Also does not solve the problem of:

> running in SSR mode via another server

**Comment by moltar** [comment]
During development, I want to have Nuxt log and my server log in one stream. Currently Nuxt clears screen on every run.

**Comment by manniL** [comment]
@moltar For webpackbar: starting with `nuxt-edge`, can't tell you the exact version though. Webpack configuration itself should work in 1.4.X IIRC. 

Clearing the screen when the application has been built successfully makes sense. Important messages (eg. errors) should be captured though. Could you elaborate on your problem?

**Comment by moltar** [comment]
@manniL But I don't think the feature request changes... I think there should be a way to disable that pretty output completely. E.g. in `CI` environment and, optionally, in dev environment. I am not sure what else to say in a new issue...?

@pi0 I am sorry, but I am not fully understanding your explanation. I have looked into the package that handles stdout log before, and it was not possible to disable/customize it. Unless something has changed in the last few months.

**Comment by Ratismal** [comment]
@pi0 How exactly are you supposed to configure the global behaviour of consola? I've been trying to disable the dev outputs for a long time since they are very annoying and completely disrupt my existing logger.

![please send help](https://stupid-cat.needs-to-s.top/35fbbb.png)

I cannot find any documentation in the [consola repo](https://github.com/nuxt/consola) that mentions anything about global configuration. I can't even glean anything useful from source - it says that it attaches consola to global, but it doesn't show up in my development scope (perhaps builder runs in a separate process?)

Setting `CI=true` is ***not*** a solution, as it does the exact same thing. 

![ci true doesnt work](https://stupid-cat.needs-to-s.top/95d43a.png)

Source mentions an env `minimalCLI` but setting this also has no effect.

> Clearing the screen when the application has been built successfully makes sense.

This is a design choice, and not one I agree with.
