### ISSUE TITLE
Vue 'watch' has different performance in SSR and SPA

### ISSUE THREAD

**Issue by fxxjdedd** [nuxt/nuxt.js#3088]
When enter a page for the **first** time, SSR and SPA perform different.

I know, SSR will return a static HTML for the first time, then Hydrate(active) the page.

But still I can't figure out 

**For SSR:**

```
export default {
  asyncData() {
    return {
      paramA: {}
    }
  },
  data() {
    return {
      paramB: {}
    }
  },
  watch: {
    paramA: function(newValue) {
       console.log('paramA', newValue) // won't print unless 'immediate: true' 
    },
    paramB: function(newValue) {
       // Here is what i'm confusing
       // will print whether 'immediate: true' or not, **Why?**
       console.log('paramB', newValue) 
    }
  }
}
```
**For Pure Vue SPA:**
```
export default {
  data() {
    return {
      paramC: {}
    }
  },
  watch: {
    paramC: function(newValue) {
       console.log('paramC', newValue) // won't print unless 'immediate: true' 
    }
  }
}
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2673">#c2673</a>)</em></sub></div>

**Comment by galvez** [comment]
@fxxjdedd I believe that's because when `paramB` is merged into the object in SSR, the watcher is already set up.

**Comment by qm3ster** [comment]
I think because in SSR there's a state object sent from the server, which is then applied (causing the watcher to fire)
### SPA:
1. `data()` 
1.  render on client
1. **done**

### SSR:
1. `asyncData()` on server
1. `data()` on server
1. render on server
1. state payload serialized
1. skipped `asyncData` on client (?)
1. `data()` on client
1. state payload applied **<- THIS IS YOUR PRINT**
1. render on client
1. hydrating the html

**Comment by hitao123** [comment]
so we can not watch data in ssr?

**Comment by qm3ster** [comment]
@hitao123 Of course you can. With all normal Vue usage there won't be any difference.
