### ISSUE TITLE
Is it safe to remove the __NUXT__ property when onNuxtReady gets called?

### ISSUE THREAD

**Issue by nallown** [nuxt/nuxt.js#3132]
I need to remove the `__NUXT__` property because it has a reference to the Vuex store and I don't want that.

My Vuex store has some sensitive information inside of it that I load asynchronously on the browser.

Can I get rid of it when `onNuxtReady` gets called?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2713">#c2713</a>)</em></sub></div>

**Comment by matsrietdijk** [comment]
People are already able to inspect your asynchronously made requests as a standard feature in most browsers. So you are already exposing this "sensitive information" anyways, removing `__NUXT__` isn't going to change that.

**Comment by nallown** [comment]
@matsrietdijk 

I can't control what they see in the network requests, that's build into the browser so what do you want me to do? Build a whole new browser as well so they can't see it? That's too much work.

I want to know if I can remove the `__NUXT__` object so that I can make at least a little bit of effort to make it harder for people to sniff that info out.

**Comment by matsrietdijk** [comment]
Obviously thats not what im trying to say, what I'm trying to make you realise is that there is probably a beter way to do this and no sensitive information is exposed at all. You did not explain why you're exposing this information now so I (or really any one at this point) am not able to give a fitting suggestion. You should get in contact with a software architect because obscuring is not a valid security solution by any means. If thats still the way you want to go though; you should also look into removing `window.$nuxt.$store.state` and probably many more references.

**Comment by matsrietdijk** [comment]
Ok, you seem to totally miss the point. Security and privacy are serious things. You are possibly hurting your user(s)/client(s), leaks might get really pricey too.

To answer your question; you can **_at this moment_** safely remove the `window.__NUXT__` reference with a `window.onNuxtReady` callback, its used for the setup and is copied to all relevant places in the process. There is no guarantee this might not change in the future though. You can't do the same with `window.$nuxt` as this will start crashing your app.

**Comment by matsrietdijk** [comment]
That changes things. I don't actually think your data is sensitive, its more of a copy right thing.

To start with I must say you are probably going to give yourself a really hard time hiding something "in plain sight". After you hid all the Nuxt references there is still the good old `document.querySelectorAll("video")[0].src`, someone who wants your videos is just going to use that instead of bothering about finding out how he/she can pull your Nuxt app apart.

Video platforms like Youtube and Vimeo are using Blob URLs to make it impossible to request the video source on its own, so I suggest you focus on that instead of corehacking Nuxt. So you probably want to fetch the source(s) you are going to actually display at that moment and convert those to (a) Blob URL(s).

**Comment by nallown** [comment]
They get the blobs by HLS and DASH streaming their videos and I would add it to my site as well if I had the extra storage space for it. That's the only way I can protect against someone using `document.querySelectorAll("video")[0].src` to get the video source.

If you look at youtube though, they don't expose their HLS and DASH stream links anywhere in the document. I need to do the same thing with my source links, not for the one that's inside the `video` tag, but the one that's stored inside the document. Because from the console you can get a array video links, like maybe 20-100 episodes depending on how many episodes the show has.

I don't mind if they have access to the video through `document.querySelectorAll("video")[0].src` cause I can only protect against that by using HLS and DASH. But even if I add HLS and DASH streaming, I still have obfuscate the HLS and DASH stream urls.

So I need to obfuscate my playlist array somehow. What do you recon?

**Comment by matsrietdijk** [comment]
I guess I would encrypt the urls server side with some "secret" (mind the quotes), then in the displaying component decrypt them through an inlined function or filter. This way your "bad guys" will see some random strings in the store and have to find your "secret" by digging in the source code which will be a lot harder to find as they don't know how it looks opposed to a string ending with ".mp4" or something.

Still I do not thing you should actually worry this much, if people really want your video they would probably inspect the network requests to begin with.

Anyways, as this has little to do with Nuxt at this point and the question which started this issue seems de be answered I think this should be closed. If you have any other questions for me feel free to send me an email (its on my profile page).

**Comment by nallown** [comment]
Thank you mat, I'll get in contact with you by email then and will close the issue.

Issue resolved in https://github.com/nuxt/nuxt.js/issues/3132#issuecomment-377366437
