### ISSUE TITLE
support nuxt organization by filename rather than directory name

### ISSUE THREAD

**Issue by alidcastano** [nuxt/nuxt.js#3209]
### What problem does this feature solve?

A more flexible app architecture.

### What does the proposed changes look like?

Find nuxt modules by `foo/foo.store.js` and `foo/foo.middleware.js` rather than `store/foo` and `middleware/foo`.

My current workaround is disabling router, store, etc and importing all modules independently, but it would be nice to take full advantage of Nuxt.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6874">#c6874</a>)</em></sub></div>

**Comment by galvez** [comment]
@alidcastano as you know, Nuxt has an opinionated setup and sticking to these conventions rather than trying to offer a multitude of configuration options is partly what keeps Nuxt lean. I can see some users wanting a specialized setup, but for these cases, I'd suggest trying to write a plugin that matches all your requirements. Plugins can load and register store and middleware files from custom locations.
