### ISSUE TITLE
[edge] Module build failed: TypeError: Cannot read property 'eslint' of undefined

### ISSUE THREAD

**Issue by tdhulster** [nuxt/nuxt.js#3216]
### Version

[edge](https://github.com/nuxt/nuxt.js/releases/tag/edge)

### Reproduction link

[https://github.com/tdhulster/nuxt-edge](https://github.com/tdhulster/nuxt-edge)

### Steps to reproduce

npm install -g vue-cli
vue init nuxt-community/starter-template nuxt-test
npm uninstall nuxt
npm install nuxt-edge -S
npm run dev

### What is expected ?

No error is thrown

### What is actually happening?

Following error is thrown: 
Module build failed: TypeError: Cannot read property 'eslint' of undefined
    at Object.module.exports (/node_modules/eslint-loader/index.js:148:18)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

### Additional comments?

All comments and steps can be found in Readme as well

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6888">#c6888</a>)</em></sub></div>

**Comment by syffs** [comment]
@tdhulster `isClient` was removed in `nuxt-edge`, it should be replaced by `process.client` in your `nuxt.config.js` as below:
```
extend (config, { isDev }) {
  if (process.client) {
	config.module.rules.push({
	  enforce: 'pre',
	  test: /\.(js|vue)$/,
	  loader: 'eslint-loader',
	  exclude: /(node_modules)/
	})
  }
}
```

**Comment by tdhulster** [comment]
AHA! Damn, so simple :) Thank you!

I didn't look into it since the [blogpost](https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67) stated that everything would be magically migrated.

> 💡 MIGRATION TIP: The good news is that you don’t need to change a single line of code in your project. Everything will be magically migrated as soon as you upgrade to Nuxt 2.

And therefore overlooked this one:
> Remove deprecated features from Nuxt 1.0 :  Removed context.isServer and context.isClient (Use process.client and process.server)

Issue can be closed I guess but might be usefull for other people having the same issue.

**Comment by amoshydra** [comment]
@tdhulster @syffs 
For some reason, `process.client` return `undefined` on my end. I was able to configure eslint correctly using `ctx.isClient` instead.

I believe the correct configuration should be using `ctx.isClient` instead of `process.client` inside the build extend function.

```
  build: {
    /*
    ** Run ESLint on save
    */
    extend (config, { isDev, isClient }) {
      if (isDev && isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
```

See the `nuxt.config` in the updated starter-template https://github.com/nuxt-community/starter-template/commit/a2d4038ef3ca1965cfce08d245b47936f305afd7

Related clarification regarding to this confusiong: https://github.com/nuxt/nuxt.js/issues/3145

Also, I believe that the reason `process.server`, `process.client`, `process.browser` being `undefined` at this stage is due to both [client.js](https://github.com/nuxt/nuxt.js/blob/5280e86/lib/builder/webpack/client.js) or [server.js](https://github.com/nuxt/nuxt.js/blob/3f1d634f/lib/builder/webpack/server.js) not being executed yet at the moment.

**Comment by Legym** [comment]
`process.server`, `process.client`, `process.browser` is undefined for me. In my `package.json` I have `"nuxt-edge": "latest",`

**Comment by XanderLuciano** [comment]
@syffs Your comment would inadvertently disable linting (and thus just disable any linting errors) because `process.client` is `undefined` at this point. The correct solution to this issue would be be to update dependencies according to this PR: https://github.com/nuxt-community/starter-template/pull/86

Since your comment is so popular (and ranks highly on google for 'nuxt eslint errors') it would be helpful if you could update your comment 🙂
