### ISSUE TITLE
[edge] Deployment of new version breaking site for live users. ( Loading chunk {n} failed error)

### ISSUE THREAD

**Issue by aldarund** [nuxt/nuxt.js#3389]
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[None](None)

### Steps to reproduce

This  happens on a live site, production deployed not a dev.  The sequence of events following:

User opened the site home page
New version of the app was deployed to web servers
User clicked a link to another page within the nuxt SPA
User saw Loading chunk {n} failed message instead of the new page content
https://i.imgur.com/AO7gX9h.png

Any site deploy could break the SPA for  live users and cause them to need a refresh.

This should be handled properly by nuxt, maybe something like automatically refresh in such cases. This is just really frustrating and bad behavior for users

### What is expected ?

No error displayed to user. Site autoreload or whatever will work here

### What is actually happening?

User see some cryptic error 

Afaik nuxt 1.4 have same behaviour 

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c7171">#c7171</a>)</em></sub></div>

**Comment by lucasmpaim** [comment]
Any update on this?

**Comment by Atinux** [comment]
Everytime you will rebuild your app, some filenames will change, the solution is to push your bundle to a CDN to avoid having not found file which lead a a chunk error.

We may try to find a solution to hard-reload the page when this error happens, any PR attemps will be really appreciated :)

**Comment by clarkdo** [comment]
Maybe we can add a feature that support `buildDir` config as a function:

```
buildDir: () => {
  return `dist-${new Date().getTime()}`
}
```

Through this way, every build is different and also add a options for `start`: start with `nuxt start --dir dist-1232131`.

**Comment by qm3ster** [comment]
@Atinux what are you talking about, "hard-reload" :scream: 
Only seamless hotModuleReloading without memory leaks and with Vuex migration!

**Comment by amorino** [comment]
Any update on this?

**Comment by ahus1** [comment]
For now I use the following workaround by adding this to the error template: it will reload the page. The user will be again on the page where she/he started the navigation. She/he can then retry the interaction.

It adds a hash to the URL to avoid infinite reloads. The hash will be automatically removed on the next successful navigation.

This will might work for you as well until #3940 is released. Tested with Nuxt 2.2, but should work with earlier versions as well.

```
    mounted: function () {
      if (this.error.statusCode === 500
        && /^Loading chunk [0-9]+ failed/.test(this.error.message)
        && window.location.hash !== '#retry') {
        // the chunk might no longer be available due to a recent redeployment of the page
        // mark the page to don't trigger reload infinitely
        window.location.hash = '#retry'
        window.location.reload(true)
      } 
```

**Comment by sumeshkmp** [comment]
Have seen this issue on V2.2.0

**Comment by magisters-org** [comment]
Up, one more.

**Comment by josepjaume** [comment]
This is definitely an issue.

**Comment by purpleow1** [comment]
Is this issue fixed in version 2.4.0?

**Comment by ahus1** [comment]
yes (i tried it, the nuxt SPA will reload once it doesn't find a JavaScript resource it tries to load. This way it will load the most recent app from the server that will have all needed resources available)

**Comment by ameistad** [comment]
I'm experiencing this on Nuxt version 2.4.5, but only in development.

**Comment by unr** [comment]
Currently experiencing this live on 2.4.5

Previously, I had used [this error/refresh solution](https://github.com/nuxt/nuxt.js/issues/742#issuecomment-393776050)

But this no longer seems to work? I'm simply having errors logged about chunks again, and I can't seem to get this working.

**Comment by wushan** [comment]
please reopen this issue, this is a serious problem on production apps.

**Comment by sskyu** [comment]
A CSS chunk error occurs in the production environment.
It seems that it can be fixed by changing the following line as a temporary countermeasure.
https://github.com/nuxt/nuxt.js/blob/2015140d1287bcf3701b170cd7d4000b01270c82/packages/vue-app/template/client.js#L160

```diff
- if (/^Loading chunk (\d)+ failed\./.test(message)) {
+ if (/^Loading( CSS)? chunk (\d)+ failed\./.test(message)) {
```

However, I am looking for a better solution than this patch.

**Comment by ahus1** [comment]
@ssku, maybe adding a snippet to your error page like in my comment https://github.com/nuxt/nuxt.js/issues/3389#issuecomment-431609130 with can serve until this is fixed in a Nuxt release. Of course the match condition needs to be changed to include CSS chunks like you described.

Are you willing to submit a pull request to change the line you mentioned in your comment?

**Comment by sskyu** [comment]
@ahus1 Yeah, thanks your work ;)

**Comment by zajca** [comment]
I'm having similar issue with 2.6.3 (also before this version) after deploy
```
Unhandled promise rejection Error: "Loading chunk 23 failed.
(missing: https://<www>/_nuxt/pages/<page>.js)"
```

**Comment by francoislevesque** [comment]
The best solution is to use a zero dowtime deployment flow.

More details here: “Nuxt & PM2: Zero Downtime Deployment” by Xander Luciano https://link.medium.com/yyfdzAE0aW

Basically, you want to build each release on a separate folder. You then create a symlink folder (eg: ./current) pointing to the latest release once the build process is completed.

This is called Capistrano Deployment, you can look this up here:

http://pm2.keymetrics.io/docs/tutorials/capistrano-like-deployments

This issue might also help:

https://github.com/nuxt/nuxt.js/issues/3078#issuecomment-405464005

**Comment by unr** [comment]
That is exactly how my app is deployed currently. Switching the current app during deploy is what seems to cause our chunking errors. 


In the process of switching to Now.sh for deployments... haven’t seen the issue on that platform yet.

**Comment by zajca** [comment]
I'm using dokku for deploy so each instance is in new container.

**Comment by AndrewBogdanovTSS** [comment]
Also having this issue although I also use zero time deployment described here https://link.medium.com/yyfdzAE0aW . The issue disappear only when hard page reset is done. Experiencing this with Nuxt 2.8.1

**Comment by AndrewBogdanovTSS** [comment]
I'm using `nuxt-polyfill` and I experience an issue of `Loading chunk {n} failed` for chunks that contain polyfill code  and which is loading dynamically

**Comment by buremba** [comment]
Did anyone find a solution to this problem? We don't want to use CDN as we deploy a few times to the prod during the day.  Most of the users keep the tab open most of the day so we're thinking of using PWA for this use-case but couldn't find any tutorial it yet. :/

**Comment by robyedlin** [comment]
@buremba Why does deployment multiple times during the day prevent you from using a CDN?

The only thing I've seen that really worked is to deploy js files to s3, then point the publicPath to cloudfront (which points to s3). This process is part of a post-deploy script, which heroku and other PaaS tend to offer.

If you don't want users fetching old versions of your app, then the best solution is to detect the chunk error and hard reload the page.

**Comment by buremba** [comment]
@robyedlin We currently hard-reload in case the assets return 404 but that's not reliable and convenient IMO.

1. Most of our users use the app as if they're using a desktop application, they open the app and use it occasionally during the day. Forcing them to reload the page breaks their workflow in some cases.

2. While we do offer the SaaS version, we also offer the on-premise version of the app so we want to keep the infrastructure as simple as possible. We don't want to force the customers to use S3 or any specific CDN just for this problem because it becomes hard to maintain for us and also for them. Instead, if that's possible to solve this issue in the browser, that would be the easiest and reliable solution for us.

**Comment by robyedlin** [comment]
@buremba What would an ideal user experience look like then?

**Comment by buremba** [comment]
@robyedlin Ideally, Nuxt can load all chunks into the browser's cache so that the user doesn't need to reload the page. There might be a service worker in the background that checks the new version and push a notification to the user to reload the page in order to update to the latest version. In fact, there are few apps that follow this approach. See https://medium.com/progressive-web-apps/pwa-create-a-new-update-available-notification-using-service-workers-18be9168d717

**Comment by robyedlin** [comment]
@buremba This is actually how nuxt `spa` mode works, so an option to allow this in universal mode might be cool.

@Atinux what do you think about a universal mode config option that allows downloading all js chunks async on first page load, similar to the way it works in spa mode?

**Comment by buremba** [comment]
I did not know about the PWA before, just started experimenting it for this use-case. Couldn't find any relevant information here though. https://github.com/nuxt-community/pwa-module

**Comment by josepjaume** [comment]
I kind of fixed this in the past by checking for a version file containing the SHA of the latest commit in the background, and then setting an `updated` state in the store if changed. Then I hooked into the router to check if `updated` was set, and instead of changing routes on the client-side, the app resorted to regular navigation, reloading the app "seamlessly".

Ugly hack, but it worked. Sure there's better ways to do this though.

**Comment by garineGiftagram** [comment]
OK so files starting with `.` will give `404 not found` error. This is happening to me with nested routes. Not sure what the solution is for now.

**Comment by AndrewBogdanovTSS** [comment]
@garineGiftagram why do you need to call your routes starting with . ?

**Comment by garineGiftagram** [comment]
@AndrewBogdanovTSS chunks/code splitting are created by my dynamic routes. 

Check my stackoverflow Question
https://stackoverflow.com/questions/59292564/nuxt-js-npm-run-build-results-in-some-js-files-being-not-found

**Comment by AndrewBogdanovTSS** [comment]
@garineGiftagram from the link I understood that the problem is not in generation but in the filename, there shouldn't be cases when your file don't have a name. You could at least put cache in front of it. Did you find what was causing empty names issue?

**Comment by garineGiftagram** [comment]
@AndrewBogdanovTSS  even when I change the filename settings in the config , this one particular file did not get updated. whatever I did,  I just got `.234dfg.js` But I fixed the issue by changing nuxt config as in the stackoverflow answer. thanks for the help though.

**Comment by khangal** [comment]
> For now I use the following workaround by adding this to the error template: it will reload the page. The user will be again on the page where she/he started the navigation. She/he can then retry the interaction.
> 
> It adds a hash to the URL to avoid infinite reloads. The hash will be automatically removed on the next successful navigation.
> 
> This will might work for you as well until #3940 is released. Tested with Nuxt 2.2, but should work with earlier versions as well.
> 
> ```
>     mounted: function () {
>       if (this.error.statusCode === 500
>         && /^Loading chunk [0-9]+ failed/.test(this.error.message)
>         && window.location.hash !== '#retry') {
>         // the chunk might no longer be available due to a recent redeployment of the page
>         // mark the page to don't trigger reload infinitely
>         window.location.hash = '#retry'
>         window.location.reload(true)
>       } 
> ```
> 
> Comments to improve the workaround are welcome!

This workaround is not working because layouts/error.vue is not rendered.
nuxt version: 2.11.0
build command: yarn generate

**Comment by cain** [comment]
@pi0 is it possible to get this issue reopened?

**Comment by cain** [comment]
@khangal Please let me know if you find a workaround :)

**Comment by reinoldus** [comment]
Has this been fixed? I keep getting the same error

**Comment by vivianifederico** [comment]
Do you have any update on this topic? we had to put in place a terrible workaround in order to avoid this situation.

**Comment by Bruno-Meowtel** [comment]
Just FYI, we were experiencing the same issue and found an article listing all the possible workarounds:
https://imrecsige.dev/garden/how-to-solve-missing-chunk-code-splitting-errors-after-deploy/

We will most likely go with the Websocket way on our end, but the Cache approach would most likely work as well unless you have a time-sensitive update to deploy.

**Comment by kingychiu** [comment]
Thanks @guska8 for the solution. I fixed my problem on CloudFront as well. Let's me share it in details here.

**Context**: 
First of all, I am deploying an SSR Nuxt.js application on AWS ECS (Fargate), for those who have experience with CDK, I am using `aws_ecs_patterns.ApplicationLoadBalancedFargateService`. Overall I have the following:

Route53 -> CloudFront -> EC2 Application Loadbalancer -> ECS (Fargate) <- ECR <- CodePipeline <- Github

**Problem**:
During the deployment, the code is pulled from GitHub and uploaded to ECR as a Docker Image; when the service with the old code is killed, the old assets (JS, CSS, Images) are gone. It is because all the assets' filename are hashed, the new assets won't have the same filename. Any users with the old version of the web app will hit 404 errors when their old web app requests some old assets. 

Based on @Bruno-Meowtel  website above, this should not be an issue because I have a CDN (CloudFront here). But by default, CloudFront has a setting of `Minimum TTL: 1 sec`. As a result, the old assets got removed from the CDN too quickly.

**Solution**:
The idea is basically the "Keep old versions" solution from the [page](https://imrecsige.dev/garden/how-to-solve-missing-chunk-code-splitting-errors-after-deploy/) @Bruno-Meowtel shared above.

Setting MinTTL to a large number fixes my issue. In particular, I have the following CloudFront setup:

[MinTTL Documenation](
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesMinTTL
)

I only cache the assets folder of my Nuxt.js app and disable caching of the pages:
<img width="968" alt="Screenshot 2023-02-18 at 11 25 32 PM" src="https://user-images.githubusercontent.com/11500136/219873996-1d2f3a30-8cab-410e-8c90-472930fbcac8.png">
There are 2 reasons why the pages are not cached:
1. I am using server-side authentication; if the CDN caches the pages, it will cache the authenticated pages... (with other users' information on it), which is super bad
2. This way, the HTML is not cached; only the JS, CSS, etc are cached, an updated version of the web app can be released quickly. Because the HTML is not cached, as long as the user got the latest HTML, they will get the latest assets.

The HashedAssetsCache policy is a customized policy with a large Minimum TTL.
