### ISSUE TITLE
[edge] Nuxt.js uses the local Vue instance in plugins

### ISSUE THREAD

**Issue by negezor** [nuxt/nuxt.js#3416]
### Version

[2.0.0-25468832.6578bd7](https://github.com/nuxt.js/releases/tag/2.0.0-25468832.6578bd7)

### Reproduction link

[https://github.com/negezor/nuxt-edge-plugins-error](https://github.com/negezor/nuxt-edge-plugins-error)

### Steps to reproduce

Clone the repository
Install modules
Run
Look in the console

### What is expected ?

In a global context, Vue should using mixin

### What is actually happening?

Mixing is added to the local Vue instance

### Additional comments?

Roughly, you can change the local version to global in the module.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7203">#c7203</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Thanks for reproduction repository.

About this:

> I think this problem is due to the use of esm

It is not. ESM is only required in the context of Nuxt itself, not for runtime. Webpack bundles everything.

Also, this is normal that requiring `vue` in a file inside of node_modules does not guaranty same versions. Nuxt copies every template into `.nuxt` directory.

This bug seems a regression with recent Webpack/Vuelidate releases. Trying to investigate...

**Comment by negezor** [comment]
After I renamed the files in the plugins from mjs to js, yes, now it works. @
