### ISSUE TITLE
Bug using SSL + $axios modules + asyncData

### ISSUE THREAD

**Issue by danielsalles** [nuxt/nuxt.js#3431]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[https://github.com/danielsalles/nuxt-bug-asyncData-Axios](https://github.com/danielsalles/nuxt-bug-asyncData-Axios)

### Steps to reproduce

npm install
npm run dev

Open browser:
Acess localhost:3000/usingssr
ctrl+f5
![Captura de tela de 2018-06-11 21-43-12.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/3d6323e0-6dd1-11e8-aeba-7bb80a0f6ed3.png)

Acess localhost:3000/usingnossr
ctrl+f5
![Captura de tela de 2018-06-11 21-44-03.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/62dec840-6dd1-11e8-aeba-7bb80a0f6ed3.png)

### What is expected ?

The answer is correct === /usingnossr

### What is actually happening?

Wrong response === /usingssr

### Additional comments?

This bug is referenced to this question (https://cmty.app/nuxt/nuxt.js/issues/c7224).

I'm basically trying to consume an API and I'm not getting it. If it is HTTP (without SSL) it works normally, but I need SSL enabled.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7225">#c7225</a>)</em></sub></div>

**Comment by zyxd** [comment]
The server responds with the header 'content-encoding': 'br'. Your code works if you clear the 'accept-encoding' header before the query:
> $axios.setHeader('accept-encoding', false);

**Comment by danielsalles** [comment]
@zyxd It worked. But is there any special reason to have to do this in SSR mode?

Thanks!

**Comment by zyxd** [comment]
By default, the 'proxyHeader' mode is enabled. In this mode, @nuxt/axios copies all properties of the 'context.request.headers' to axios request headers. Including 'accept-encoding' if your browser send it.

The Chrome browser sends 'accept-encoding: gzip deflate br', because it can decode all of them. But in JS code you must decode it manually or use 'identity' (raw content) encoding which is default if 'accept-encoding' not specified.
