### ISSUE TITLE
transition event no call

### ISSUE THREAD

**Issue by gotoin** [nuxt/nuxt.js#3675]
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

[http://no link](http://no link)

### Steps to reproduce

transition event no call in the layouts

### What is expected ?

call event

### What is actually happening?

this

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7527">#c7527</a>)</em></sub></div>

**Comment by manniL** [comment]
Please elaborate on your bug report. What code did cause that issue, which transition event have you tried?

**Comment by gotoin** [comment]
in the nuxt.config.js

```
transition: {
    mode: '',
    beforeLeave(el) {
      console.log(el) // there is call
    },
  },

```

in the layouts/default.vue

```
// there is no call
<transition @before-leave="beforeLeave"> 
      ...
</transition>
```

**Comment by gotoin** [comment]
And the before-leave life cycle is incorrect

**Comment by gotoin** [comment]
And nuxt transition default mode is 'out-in', the vue transition default mode is '' ("out-in" and "in-out")

Would it be better to keep vue's default Settings? thanks

**Comment by manniL** [comment]
**Can not reproduce** the missing call when having a transition in layouts/default.vue. My code using the latest `nuxt-edge`:

```
<template>
  <div>
    <nuxt/>
    <transition @before-enter="be">
      <pre :key="$route.fullPath">{{ $route.fullPath }}</pre>
    </transition>
  </div>
</template>

<script>
export default {
  methods: {
    be() {
      console.log('BE TRANSITION')
    }
  }
}
</script>
```

Be sure to `key` your transition objects correctly.

For the [`transition`](https://nuxtjs.org/api/configuration-transition#the-transition-property) object it's fine to use `out-in` mode by default because it'll set the default behavior for *page transitions* where you usually don't want to see both pages (new and old) simultaneously. You can change this mode as you like though.
