### ISSUE TITLE
Don`t work relative path url.

### ISSUE THREAD

**Issue by medve-dev** [nuxt/nuxt.js#3687]
I can not make paths relative to my url
I really need the paths of static files to be ./
I initially do not know which way will be issued by the server
```

router:{
mode:'hash',
base:'./'
},

```
DONT WORK!

**Comment by johnyluyte** [comment]
@cdunlap The solutions in both #2892 and #1052 work for me. (which are the essentially the same solution)

My asset paths are no broken with those settings.  Maybe you can try again. I'm using nuxt 1.4.2

**Comment by johnyluyte** [comment]
@cdunlap 
Here are my `nuxt.config.js` settings:

````
1. 
mode: "spa",

2. 
router: {
    mode: "hash"
},

3. 
build: {
    extend(config, { isDev, isClient }) {
        if (!isDev) {
            // relative links, please.
            config.output.publicPath = "./_nuxt/";
        }
        return config;
    }
}
````
The setting works for me because I'm fine with the "SPA mode", and because I'm fine with the "router hash mode".

The problem is that, just like you, I also had to implement a `catchall` rule to redirect all the missing routes to the front page of my SPA. 

The solution we have for **relative path** right now is not enough, and only works for certain situation. I really hope there's a general solution somewhere with Nuxt.

One the other hand, I haven't tried yet but maybe `nuxt generate` is a possible solution for this kind of problem? Since it is statically generated, the "routing problem" should be relatively easy to solve. Plus it can leverage the advantage of JAMStack. I'll try it out when I'm free.

**Comment by cdunlap** [comment]
I actually use `nuxt generate` to produce my builds. I'm in SPA mode with no server-side code at all, similar to you. Nuxt appears to still require the router regardless.

The only difference as far as I can tell, between your solution and mine, is that you're in hash mode. I bet if I went to hash mode I'd be ok since at that point the URL is broken apart by the `#` character and won't matter where the app is deployed since the server path won't be part of the router base. I'll keep this in mind for future apps I write with Nuxt.

Thanks for the insight!

**Comment by johnyluyte** [comment]
@cdunlap Yes, it should work since that's how hash mode works for vue-routers. 
But still there might be cases where hash mode is not desired, so a more general solution is always welcome.
