### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#37]
Took a look through the examples and couldn't find anything on creating/controlling error page (404, etc.)

**Comment by alexchopin** [comment]
Hi, that's right it not on the documentation yet but will comes soon but it's possible.

You juste need to create a /pages/_error.vue file.
You can see an example on nuxtjs.org website source code on github ;)

**Comment by MatthieuHPP** [comment]
Hi Nuxt community,

I have inserted the "_error.vue" file of the default page shown in https://github.com/nuxt/docs/blob/master/en/guide/views.md, 
in the "pages" directory of my project. 

I imagined this page should have been called automatically when errors occur, but that is not the case. I tried with error 500 and 404, modifying the _error.vue file accordingly, but nothing happens when error 404 or 500 are thrown (seen in the console).

What am I doing wrong ?

Many thanks

Matthieu

**Comment by InstanceOfMichael** [comment]
Which probably refer's to this now: https://github.com/nuxt/nuxtjs.org/blob/3d1d3d02616283b3001e638b44c8b99a2ad4a23f/layouts/error.vue

**Comment by ymatuhin** [comment]
Is it possible to somehow change the value of title meta tag on error page?

**Comment by jamesAtcodeninja** [comment]
I'm using `nuxt 1.1.1` and the following snippet does not work for me in error.vue. It works in other pages however. 

``` 
   head () {
      return {
        title: 'Error 404'
      };
    }
```

**Comment by qm3ster** [comment]
@jamesAtcodeninja probably no such hook in the error case, since it's a minimal setup.
(What if whatever caused the error runs when trying to render a page displaying the error)

**Comment by robinhuy** [comment]
`error.vue` is only work on 1 level route, ex: `/foo`. 
In multiple level route, the default page will display instead the `error.vue`, ex: `/foo/bar`.
If I use function `error({ statusCode: 404, message: 'Page not found' })`, `error.vue` is not working too.
