### ISSUE TITLE
Can't mutate a module's store state server-side

### ISSUE THREAD

**Issue by paulgv** [nuxt/nuxt.js#3757]
### Version

[any](https://github.com/nuxt.js/releases/tag/any)

### Reproduction link

[https://github.com/paulgv/nuxt-fetch-issue](https://github.com/paulgv/nuxt-fetch-issue)

### Steps to reproduce

```
git clone git@github.com:paulgv/nuxt-fetch-issue.git
cd nuxt-fetch-issue
yarn && yarn dev
```

[http://localhost:3000/](http://localhost:3000/)

### What is expected ?

When committing mutations in the `fetch()` or `nuxtServerInit()` methods page should render with mutated state. You should see `mutated` instead of `not mutated` on the homepage.

### What is actually happening?

The state is actually not mutated and stays at its original value (`not mutated`) unless the mutation is triggered via a client-side method or if you navigate yo another page then back to the page where `fetch()` is defined.
If you disable Javascript and refresh the page, you'll notice that the state IS mutated server-side but is then immediately reverted to its original value on the client-side.

### Additional comments?

- Tested with Nuxt 1.4.2 and nuxt-edge.
- No problem when the mutation happens in the main project's state and not in a module

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7598">#c7598</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hey @paulgv :)

I see what happens here, it is because the plugin is called (the one that register the Vuex module) on client-side after hydrating the store (See https://github.com/nuxt/nuxt.js/blob/dev/lib/app/index.js#L148-L163).

But Vuex offers a solution for preserving the state from server-side rendering: https://vuex.vuejs.org/guide/modules.html#dynamic-module-registration

![screen shot 2018-08-21 at 16 13 20](https://user-images.githubusercontent.com/904724/44406940-24a2f100-a55d-11e8-91ec-afa164ce4e3c.png)

So here your plugin code updated to works (I tested it):

```js
export default async function ({ router, store }) {
  store.registerModule('simpleModule', {
      namespaced: true,
      state: () => ({
        mutateMe: 'not mutated',
      }),
      actions: {
        mutate ({ commit }) {
          commit('mutate')
        }
      },
      mutations: {
        mutate (state) {
          console.log(state)
          state.mutateMe = 'mutated';
        }
      }
    }, { preserveState: process.browser })
}
```

**Comment by paulgv** [comment]
Awesome! Thanks @Atinux !

**Comment by Atinux** [comment]
With https://github.com/nuxt/nuxt.js/pull/3909, you won't have to give the 3rd option with Nuxt 2.0 @paulgv :)
