### ISSUE TITLE
[edge] imported lib in nuxt.config.js is missing in generated files

### ISSUE THREAD

**Issue by zajca** [nuxt/nuxt.js#3767]
### Version

[2.0.0-25578134.eb114a4](https://github.com/nuxt.js/releases/tag/2.0.0-25578134.eb114a4)

### Reproduction link

[https://github.com/zajca/nuxt-bug-5b98c1c](https://github.com/zajca/nuxt-bug-5b98c1c)

### Steps to reproduce

run npm run dev
there is router config for parseQuery/stringifyQuery using qs lib

### What is expected ?

qs will be imported in .nuxt/router.js

### What is actually happening?

function in router config is copied to router.js but not dependency

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7602">#c7602</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Actually it's hard to analyse which import and resource is for `parseQuery` function at building time.

So currently Nuxt doesn't handle the scenario of parseQuery is a external function, sorry for the inconvenience.

You may try to use `require` like:

```js
export default {
  router: {
    parseQuery: (...args) => {
      return require('qs').parse(...args)
    }
  }
}

```

**Comment by luishdz1010** [comment]
There should be another way to extend the router, having to do hacks like this just because Nuxt doesn't expose a proper way to tap into the router construction is not good. 

parsing/stringifying a query is *not* configuration, is behavior written in code. A way to extend/configure the router in a plugin or similar will be ideal. I assure you that nobody is writing an inline function in `parseQuery`, parsing is hard and requires a dedicated library, and we shouldn't care about the library dependencies. Nuxt is breaking a basic assumption of how modules/dependencies work in Node.

**Comment by manniL** [comment]
This would be a nice integration for https://github.com/nuxt-community/router-module I think 🤔
