### ISSUE TITLE
exposed some data

### ISSUE THREAD

**Issue by fengjiel** [nuxt/nuxt.js#3858]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[http://no-link](http://no-link)

### Steps to reproduce

I think I found an unsafe factor when I typed '$nuxt' into the console that exposed some data, like the store, all the router and configurations, or whether it could be encapsulated like the vueJs

### What is expected ?

No relevant data is displayed

### What is actually happening?

when I typed '$nuxt' into the console that exposed some data

### Additional comments?

I don't know if this is a loophole. Forgive my poor English,

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7701">#c7701</a>)</em></sub></div>

**Comment by manniL** [comment]
Related: https://github.com/nuxt/nuxt.js/issues/3132#issuecomment-377366437

**Comment by manniL** [comment]
This reference (to the root instance) is needed to emit the `triggerScroll` event which is important for the `scrollBehavior` of the app.

If someone finds a better way to provide such an interface while not leaking that much data, we'd surely accept a PR for it.

But as everyone can simply set breakpoints in the browser and inspect variables, code ("obfuscated") and state, this shouldn't be a severe issue.

**Comment by aldarund** [comment]
I dont think its issue.  Everything that is on client can be debugged, there no real way to protect what u pass to client

**Comment by tolgap** [comment]
Exactly. It is the programmer's responsibility to not leak anything clientside. Any secrets should be handled serverside and returned clientside without leaking those secrets.

Nothing is stopping a visitor on your site to just run breakpoints on variables and exposing those secrets otherwise 🙂.

**Comment by pimlie** [comment]
To be fair, normally I am the one who says 'obscurity is not security' but this time I disagree with the above opinions that we shouldnt hide it _because_ there are other ways to get the data. The fact that there are other ways doesnt mean we should make it easy for wrong-doers.
And yes, to obscure certainly doesnt mean its secure but obscuring is still a completely valid technique to at least lower the attack surface. 

We could go in to lengthy discussions about this, but that would take much more of everyone's time then just fixing this issue. We can use the amazing power of javascript scopes to only expose the nuxt features on the window object we really need :grinning: 

```js
// App.js
      window.nuxtTriggerScroll = () => {
        this.$nextTick(() => {
          this.$emit('triggerScroll')
        })
      }
      window.nuxtListenScroll = (fn) => {
        this.$once('triggerScroll', fn)
      }
```
Removing window.$nuxt does break the e2e browser tests as those require the window.$nuxt object. So probably it would be best to either still add window.$nuxt but only in development mode or the e2e browser tests need to be rewritten.

**Comment by aldarund** [comment]
So basically obscuring will protect sites that have exposed something they shouldnt from script kiddies?

**Comment by pimlie** [comment]
Well its not black or white of course but in general I would say yes.

In this case there is also the difference between getting the static data and providing a functioning low-level API. Actually, I think I could even make a strong case for this issue to be a major security issue. Luckily nowadays browsers provide a lot of protection against cross-frame scripting attacks, but lets say you have a webshop written in Nuxt with an advertisement component through an iframe. If a user visting that webshop uses an old browser that lacks csf protection an attacker has access to the full $nuxt Vue-component and its children and can overwrite a lot of properties/methods or inject new VueRouter routes etc. Of course, there are also otherways maybe to do this but $nuxt should be protected as much as possible from direct access. 
Only expose features to the global scope if you really need to, otherwise keep them in a local scope.

I mean, I guess there is a reason Vue DevTools only work in development mode and not in production ;)

**Comment by pimlie** [comment]
Offtopic: Its annoying I cant hide my commit mistakes anymore, it took me 3 tries to get `$nuxt` in the commit message ;)
