### ISSUE TITLE
Nuxt servermiddleware route /api is ignored when deployed or served on Firebase

### ISSUE THREAD

**Issue by fgian1969** [nuxt/nuxt.js#3955]
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/fgian1969/TestApi](https://github.com/fgian1969/TestApi)

### Steps to reproduce

This happen also in 2.0.0 Nuxt version. 
Server middleware /api ignored in firebase hosting. When compiled with npm run dev or npm run build everithing work.
Launching with firebase serve --only functions,hosting  or firebase deploy route /api is ignored and result is 404 (not found)

### What is expected ?

![nuxt2 - OK.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/b8beab00-bffb-11e8-a51e-2d0fd5d9b771.png)

### What is actually happening?

![nuxt2 - KO.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/398f5a40-bffc-11e8-a51e-2d0fd5d9b771.png)

### Additional comments?

Converted firebase function to Node js 8 (beta). Results do not change

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7817">#c7817</a>)</em></sub></div>

**Comment by manniL** [comment]
I think this is a configuration and setup issue, rather than a `nuxt`-related issue :thinking: 

(Other people have [this issue](https://github.com/davidroyer/nuxt-ssr-firebase/issues/16) as well)

**Comment by fgian1969** [comment]
What do you mean? That is a firebase configuration issue? I've already ask support to firebase engineer and they say that is a nuxt problem.... If i transfer /api in google function is recognized but i use /api also to write cookies and session variables and after i have problem to decode it in nuxt and to transfer session. Do you know is this problem is only in the firebase environment or is common also in Heroku, Docker?

**Comment by manniL** [comment]
Did they mention any details, f.ex. *what* the exact problem is?

I'm not aware of issues when deploying on Heroku. With Docker (where you can essentially customize everything)  this shouldn't happen.

**Comment by rodrigomata** [comment]
Firebase hosting is intended for [static assets](https://firebase.google.com/docs/hosting/); therefore, you should use [Firebase functions](https://firebase.google.com/docs/functions/http-events#using_existing_express_apps) instead as Nuxt is made to support server side rendering.

**Comment by qm3ster** [comment]
This makes sense, because `serverMiddleware` registers middleware onto the built in `connect` server for cases when that is used.
As far as this outcome indicates, `nuxt.render(req, res)` doesn't go through those middlewares, it just runs the single final middleware that renders the HTML.

You should probably (~112% probability) not try to fix this by having the function actually apply the middlewares, but instead have a separately deployed function, that can scale independently, that just has the API. This way you have two leaner services with fewer dependencies and faster cold boot - the render service and the API service.
If you couple them, cold boot of render service (very critical for UX) would wait for whatever DB connections or state loading the API service (much less critical with optimistic UI) does on init for no benefit.

And yeah, as @rodrigomata said, the Functions are stateless and clients aren't sticky even if a function survives, so keeping sessions in server isn't possible in Functions. Consider stateless renderer and API, with JWT sessions.

**Comment by fgian1969** [comment]
Thanks to everyone that help me. Is there some example to use JWT with Nuxt and firebase?

**Comment by fgian1969** [comment]
Ok I found a perfect example here:
https://codeburst.io/nuxt-authentication-from-scratch-a7a024c7201b
Thanks for your collaboration.

**Comment by manniL** [comment]
Great 👌 
Will close the issue therefore.
