### ISSUE TITLE
Add login / authentication example

### ISSUE THREAD

**Issue by niallobrien** [nuxt/nuxt.js#4]
Hi, I think a lot of issues faced by Next.js apply to Nuxt.js also, and I believe that ultimately, such a feature will require a way to allow for custom server workflows, with session support etc.
Interested to discuss this.

https://github.com/zeit/next.js/issues/153

**Comment by Atinux** [comment]
Hi @niallobrien 

Thank you for using nuxt.js in it's alpha stage, it's already planned in nuxt.js: https://github.com/nuxt/nuxt.js/projects/1

It will be easier to do with nuxt.js since you can use it as a middleware in express, adonis, etc.

Also, nuxt.js is configurable with a `nuxt.config.js` file instead of next.js

**Comment by Atinux** [comment]
Hi @niallobrien 

You can see an example here: https://nuxtjs.org/examples/auth-routes

And the live demo on https://auth-routes.nuxtjs.org/

**Comment by vaggelis2018** [comment]
@Atinux what if we have a token which expires? I create a middleware on server which refreshes the token if it has been expired and reset the session but vuex isn't refreshed with the new token.

**Comment by awronski** [comment]
@vaggelis2018 you can check in client middleware if the token was refreshed on the server. 
and if so update the client store state.


client middleware :
```js
export default function ({ store }) {
   // check if server refreshed the token and retrive it
 store.dispatch('refreshToken', token)
}
```
