### ISSUE TITLE
How to link img src to a rendered list

### ISSUE THREAD

**Issue by tenjojeremy** [nuxt/nuxt.js#448]
Im trying to render a list with an image where the name of the images come from an array of objects. 

![error](https://cloud.githubusercontent.com/assets/25231946/24326635/f416a450-1188-11e7-97a7-2c6c964f9e0c.PNG)

How do I properly link it?

Thank you in advance.

**Comment by ausir0726** [comment]
vue file will pre load with vue loader
when vue load seen you vue file that don't know what is '~assets/img/' + item.logo
because item.logo when compile is undefined .

so , if you want use a variable with you image , you need move your image to static folder
that will copy to dist . ( even you never used )

if item.logo = 'logo.png' 
put the logo.png to static img
and in your vue file modify to
`<img :src="`img/${item.logo}`"/>`

that you logo should show on screen .

**Comment by alexchopin** [comment]
Hi @tenjojeremy,
Like @ausir0726 said for dynamic path, you can't use webpack assets, you need to use static assets and place your images in the static folder.

**Comment by tenjojeremy** [comment]
Thank you both for the solution,

Cheers.

**Comment by ubershmekel** [comment]
Note for future googlers - another way to solve this is to use `require`. E.g. `const imageUrl = require('~/assets/img/yourimage.png')` and dynamically using that url in js.

**Comment by dimitrieh** [comment]
for Googlers, I had success with:

`:style="{ backgroundImage: 'url(' + require(`@/assets/img/${page.image}`) + ')' }"`

**Comment by amitsingh19975** [comment]
thanks @dimitrieh it worked  for but your missing back tick marks though
:style="{ backgroundImage: 'url(' + require(`@/assets/img/${page.image}`) + ')' }"

**Comment by manniL** [comment]
For all people looking for the solution, I've written [a blog post about that topic](https://blog.lichter.io/posts/how-to-load-dynamic-images-in-vue-and-nuxt-with-ea/) :relaxed:
