### ISSUE TITLE
In SPA, hash mode, index page mounted is called when redirected twice in asyncData

### ISSUE THREAD

**Issue by eungkyu** [nuxt/nuxt.js#4500]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/rln512mjjq](https://codesandbox.io/s/rln512mjjq)

### Steps to reproduce

Create Nuxt project "spa" mode and set route mode "hash"
make redirect in asyncData of index.vue
make redirect again.

You can see mounted in index.vue called.

You can test in reproduction link

### What is expected ?

mounted hook in index.vue should not be called

### What is actually happening?

mounted hook in index.vue called

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8285">#c8285</a>)</em></sub></div>

**Comment by galvez** [comment]
@eungkyu Calling `redirect()` on a page's `asyncData()` is not supposed to cancel its `mounted()` event. Remember `asyncData()` is meant to return data to be merged with the page component's own `data()`. In a SSR context, you can use `asyncData()` to `redirect()` because `mounted()` is _never_ called in SSR *anyway*.

What you probably want to do is create your initialization code in a shared `mounted()` across all pages (perhaps through a mixin) and control route changes via `beforeRouteLeave` or `$route() { ... }` under `watch`.
