### ISSUE TITLE
IOS8.4 version of the click event is invalid

### ISSUE THREAD

**Issue by HadiChen** [nuxt/nuxt.js#463]
iphone5c
version:IOS8.4
description：all the event is invalid

**Comment by ausir0726** [comment]
just for test use iOS v8 had NUXT.js error
iOS v9 is working fine .

<img width="878" alt="2017-03-28 3 19 56" src="https://cloud.githubusercontent.com/assets/7247064/24393335/5532f020-13ca-11e7-942e-bd388b285780.png">

**Comment by pi0** [comment]
@ausir0726 Thats nice What emulator are you using? :)) (Anyway i can confirm too ios 8 on iphone 5 had same problems links where not working) Maybe it can resolved using `babel-polyfill` ...

**Comment by alexchopin** [comment]
That's weird because `nuxt-link` component is exactly the same as `router-link`.

**Comment by ausir0726** [comment]
@pi0 that cloud device test service browserstack
https://www.browserstack.com

**Comment by pi0** [comment]
@alexchopin Project that i was testing was just using `router-link`. It seems a deeper unsupported problem with Vue and Webpack stuff :) 

ausir0726 Thanks for that. I'll use it for more investigations :)

**Comment by ausir0726** [comment]
@pi0 yes ,
I will test it when develop mode . think that can get more information .

**Comment by ausir0726** [comment]
this is I test with `yarn run dev`
but I don't know where can I find `@program` line 474

<img width="678" alt="2017-03-28 4 13 49" src="https://cloud.githubusercontent.com/assets/7247064/24395421/30023128-13d2-11e7-861c-19ed123294e1.png">

**Comment by pi0** [comment]
@ausir0726 Won't clicking on (program) it work? (It seems should show a source-map)

**Comment by ausir0726** [comment]
@pi0 I can't get source-map , maybe because that is cloud device .
don't know where can see source-map .

**Comment by pi0** [comment]
Chrome dev tools has a feature attaching local source maps. Maybe if you can build assets using `nuxt build` Then you can attach them in sources tab.

**Comment by ausir0726** [comment]
when I use `yarn run build` and `yarn run start`
I got this , but can't be read ....

<img width="1248" alt="2017-03-28 4 50 22" src="https://cloud.githubusercontent.com/assets/7247064/24396734/cd3450c6-13d6-11e7-92ab-d89ae768d849.png">

**Comment by pi0** [comment]
I tried to reproduce error on a local 8.4 emulator: (this bug may actually affect 9.x versions of IOS too)
- Installed Xcode IOS simulator 8.4
- Used Safari developers tools
- Added `config.devtool='source-map'`  in order to get exact error line.
- Error comes from a try catch in `client.js`: so i locally hacked generated file: 
  - As it is a catch-all handler we cannot find exactly what component is producing the bug
  - Added this line in `resolveComponents` : 
```js 
      Component().then(_resolve).catch((err)=>{
          console.error("Cannot load component",Component);
          reject(err)
```

And this was the exact problem: 

![image](https://cloud.githubusercontent.com/assets/5158436/24496075/7e80af8e-154c-11e7-8953-d2ac1a8aa3d6.png)
![image](https://cloud.githubusercontent.com/assets/5158436/24496205/d2e08f86-154c-11e7-99ba-a3c2ab634f49.png)

```js
function _e00d9a46() {
  return __webpack_require__.e/* import() */(0).then(__webpack_require__.bind(null, 233));
}
```

Printing error's stacks trace also gives nothing.

**Comment by Atinux** [comment]
Wow, thanks so much @pi0 and @ausir0726 for helping us!

**Comment by alexchopin** [comment]
Should work now with the 0.10.6.

**Comment by Ca4tkin** [comment]
Hi! I have the same problem with nuxt 1.4.0 and ios 11.3 - no click events are triggered.
