### ISSUE TITLE
Is there a way to control the nuxt cache when deploying?

### ISSUE THREAD

**Issue by chars1205** [nuxt/nuxt.js#4764]
Site is built in spa mode using nuxt

The changed js, csss cannot be applied due to existing cache at the time of website distribution

Is there a way to control the cache when deploying?

**Comment by gahabeen** [comment]
I'm having the exact same issue..

Did you find a way?

**Comment by tranghaviet** [comment]
same here

**Comment by CedricRup** [comment]
Same here. Can this be requalified as an issue please?

**Comment by brolnickij** [comment]
+1 UP

**Comment by CedricRup** [comment]
Any of you got a setup where the problem can be reproduced? It's pretty random here :/
If so, it might be more effective to raise a correct issue

**Comment by hatimox** [comment]
i'm having the same issue , i need to wait between 1h and 1 day to have the website fully working after a build

**Comment by devon2018** [comment]
Same here

**Comment by retuner87** [comment]
+1 UP

**Comment by manniL** [comment]
This issue is **closed**. You won't find an answer here. Instead, please open a new one with the correct template.

**Comment by joelbqz** [comment]
Amazing support!!

**Comment by joelbqz** [comment]
Thanks for the help!! You are amazing

**Comment by patricktsg** [comment]
For anyone looking for a solution to this (I found this closed thread with no solution)...here's what I faced and the approach that worked and was easy to implement.

Issue: tHe HTML would not show changed from new deployments until the browser was refreshed.

Solution: 

1. Create a new file in the static folder called version.json - in mine I have one JSON object {version: 'x.x.x' }
2. Commit this file and remember to change the version number with each release.
3. In my default layout I have a beforeEach route that essentially makes an axios call to this file and gets the version number, then a simple if statement checks if 'version' is present in local storage, if it is and they don't match it executes window reload, executes the reload if it doesn't find version in local storage.

It turned out to be simple to implement and just works. I followed a medium post about using Pusher to do something similar albeit a lot more complex.

Hope this helps someone else facing these issues ✋

**Comment by prabodhana** [comment]
Is there any solution for this?

**Comment by mohammadnazari110** [comment]
I solved this problem this way
use this module https://github.com/arash16/nuxt-ssr-cache#readme
and in nuxt.config.js

```
build:{
filenames:{
            img: ({ isDev }) => isDev ? '[path][name].[ext]?v='+version : 'img/[name].[contenthash:7].[ext]?v='+version,
            app: ({ isDev, isModern }) => isDev ? `[name]${isModern ? '.modern' : ''}.js?v=`+version : `[contenthash:7]${isModern ? '.modern' : ''}.js?v=`+version,
            chunk: ({ isDev, isModern }) => isDev ? `[name]${isModern ? '.modern' : ''}.js?v=`+version : `[contenthash:7]${isModern ? '.modern' : ''}.js?v=`+version,
            css: ({ isDev }) => isDev ? '[name].css?v='+version : 'css/[contenthash:7].css?v='+version,
            img: ({ isDev }) => isDev ? '[path][name].[ext]?v='+version : 'img/[name].[contenthash:7].[ext]?v='+version,
            font: ({ isDev }) => isDev ? '[path][name].[ext]?v='+version : 'fonts/[name].[contenthash:7].[ext]?v='+version,
            video: ({ isDev }) => isDev ? '[path][name].[ext]?v='+version : 'videos/[name].[contenthash:7].[ext]?v='+version
          }
}
```

**Comment by kim00425** [comment]
@mohammadnazari110 is it can use in SPA?

**Comment by abdullah-336** [comment]
> For anyone looking for a solution to this (I found this closed thread with no solution)...here's what I faced and the approach that worked and was easy to implement.
> 
> Issue: The HTML would not show changed from new deployments until the browser was refreshed.
> 
> Solution:
> 
> 1. Create a new file in the static folder called version.json - in mine I have one JSON object {version: 'x.x.x' }
> 2. Commit this file and remember to change the version number with each release.
> 3. In my default layout I have a beforeEach route that essentially makes an axios call to this file and gets the version number, then a simple if statement checks if 'version' is present in local storage, if it is and they don't match it executes window reload, executes the reload if it doesn't find version in local storage.
> 
> It turned out to be simple to implement and just works. I followed a medium post about using Pusher to do something similar albeit a lot more complex.
> 
> Hope this helps someone else facing these issues ✋

Implementation here:
https://stackoverflow.com/questions/54191739/is-there-a-way-to-control-the-nuxt-cache-when-deploying/74861160#74861160
