### ISSUE TITLE
Why not use koa as the middleware mode of server middleware, but use connect

### ISSUE THREAD

**Issue by shangxinbo** [nuxt/nuxt.js#4769]
### What problem does this feature solve?

I found that the servermiddleware of nuxt.js uses the middleware of Connect mode. I don't understand why the mode of Koa is not used.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8482">#c8482</a>)</em></sub></div>

**Comment by manniL** [comment]
You can use Express/Koa/any other Node.js framework *in* `serverMiddleware`. Nuxt is based on `connect` because it's very lightweight and lean, so the core is not bloated ☺️ 

Further reaching blog posts:
https://blog.lichter.io/posts/my-take-on-using-nuxt-with-an-api/
https://blog.lichter.io/posts/sending-emails-through-nuxtjs
