### ISSUE TITLE
Head scripts not inited in mount when route with nuxt-link

### ISSUE THREAD

**Issue by zloylos** [nuxt/nuxt.js#4795]
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://codesandbox.io/s/wn8ovky868](https://codesandbox.io/s/wn8ovky868)

### Steps to reproduce

Open index page then click to link "Go to the test page".
In console will "undefined".
But when you just open "/test" in browser you will see "ace" object in console.

### What is expected ?

ace object in console

### What is actually happening?

ace object is undefined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8502">#c8502</a>)</em></sub></div>

**Comment by benoitemile** [comment]
Hi there,

I tried your code, as you can see in network tab, ace is correctly loaded and nuxt does its part.

You're trying to use an asynchronously loaded script which you don't know if it's actually really loaded at vue mounted lifecycle hook.

You could do this : 
https://codesandbox.io/s/jvp7o9z0ny

@Atinux I'll open an feature request in vue-meta because we can't simply put an onload event using a component method like : 
```js
{
  src: "https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.9/ace.js",
  async: true,
  onload: this.myMethod // method isn't window exposed so it's "normal" but it could be better
}
```

**Comment by manniL** [comment]
@benoitemile Feel free to raise an issue or send in a PR on https://github.com/nuxt/vue-meta :relaxed:
