### ISSUE TITLE
Vulnerability package dependency "defaults-deep"

### ISSUE THREAD

**Issue by i62navpm** [nuxt/nuxt.js#4971]
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://www.npmjs.com/advisories/778](https://www.npmjs.com/advisories/778)

### Steps to reproduce

Please fix this vulnerability in your dependency tree:

nuxt > @nuxt/core > @nuxt/server > serve-placeholder >  defaults-deep

### What is expected ?

0 vulnerabilities found when audit packages.

As no patch is currently available for this vulnerability it is our recommendation to select another module that can provide this functionality.

### What is actually happening?

All versions of defaults-deep are vulnerable to prototype pollution. Provided certain input defaults-deep can add or modify properties of the Object prototype. These properties will be present on all objects.

### Additional comments?

https://hackerone.com/reports/380878

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8618">#c8618</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi. Thanks for the report. This is being addressed fast.

- jonschlinkert/defaults-deep#5
- https://github.com/jsless/defu

**Comment by begueradj** [comment]
@pi0 Can you please explain shortly how you fixed that? (I followed the 2 links but ...)

**Comment by pi0** [comment]
For clarification as also described in [CVE-2018-16486](https://hackerone.com/reports/380878) the impact is _possibly more depending on the application._ and **no Nuxt.js users are affected** because options to the middleware are not from user input but only from `nuxt.config`.

For general:

I submitted the fix to prevent accepting `contructor.prototype` key on `defaults-deep` but as it is unlikely to fast merge and publish, I created an alternative package that only does what we want.
