### ISSUE TITLE
using require(redis) in serverMidleware causes error

### ISSUE THREAD

**Issue by dextherry** [nuxt/nuxt.js#4996]
Hi guys, please help with this, I am trying to use redis into a serverMiddleware, but it produces an error, in fact the only line that produces error is when I add a require(any package)  in the server middleware,

my server middleware looks like this:

//in  /middleware/api/file.js
`var redis = require('redis ');// this causes 
export default function (req, res, next) {
//using the redis here
var client = redis.createClient();
//etc
}`

//it is in config like this:
`serverMiddleware: [
    { path: '/api', handler: '~/middleware/file' },
  ],`

I suspect that that is not the way to use a package into the servermiddleware, so, how should to use? 
help with that please, 
Regards

**Comment by Krutie** [comment]
Hey @dextherry,  
I think this is because regular (route) middleware and serverMiddleware are mixed up. serverMiddleware cannot live in `middleware` directory. (i.e. `file.js` is misplaced) 

Although it's incorrect anyway, but in `nuxt.config` the location of `handler` doesn't really match with actual location of `file.js`. 

I'd rather create new `api` directory in the root folder with rest of the folders that comes default with fresh Nuxt installation. And create any subfolder in here to organise your files. Like, I have create `api/contact` subfolder below.

```
// api/contact/index.js

const express = require('express')

// Create express instnace
const app = express()

const contacts = [
  { name: 'James' },
  { name: 'Lorna' },
  { name: 'Winter' }
]

/* GET contacts list */
app.get('/list', function (req, res, next) {
  // res.send('API Example route')
  res.send(contacts)
})

// Export the serverMiddleware
module.exports = {
  path: '/api/contact',
  handler: app
}
```
And then register it in `nuxt.config.js` like below. See how the `handler` location matches exactly where the `index.js` is and `path` also includes subfolder `contact`.
```
// nuxt.config.js

  serverMiddleware: [
    { path: '/api/contact', handler: '~/api/contact/index.js' },
    // { path: '/api', handler: '~/api/index.js' } // without subfolder, in case index.js is created directly inside api folder
  ],
```
And finally test if it's working at `http://localhost:3000/api/contact/list`

Once this static, vanilla serverMiddleware works, you can gradually add other packages (i.e. redis, mongoose, etc )
