### ISSUE TITLE
Force asyncData and fetch in generated app

### ISSUE THREAD

**Issue by Palivonas** [nuxt/nuxt.js#5039]
### What problem does this feature solve?

My statically hosted app contains many static pages that make no network requests. `nuxt generate` is great for that. However some pages (let's call them dynamic) need to load up-to-date data from an API. This works fine when the app is already loaded in the browser and user navigates to a dynamic page, cause that triggers `asyncData` and `fetch`.

The issue is when user opens the dynamic page directly (or hits refresh in the browser), then it contains old data from when `nuxt generate` was run and does not update.

### What does the proposed changes look like?

I imagine the solution is not very difficult - it would be great to simply define a property on a component that would force asyncData and fetch to be run even if data was provided on app load, i.e. act as if the app was generated in SPA mode. Without such a feature (or some workaround, or implementing a new loading state), `nuxt generate` is not usable for apps involving any pages that need to load fresh data.

```js
{
  ignoreGeneratedData: true,
  async fetch({ store }) {
    await store.dispatch('loadSomeData');
  }
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8663">#c8663</a>)</em></sub></div>

**Comment by manniL** [comment]
I guess `generate.exclude` could suit your needs there.

**Comment by Palivonas** [comment]
@manniL is that an existing feature or a proposal? I did not find it documentation. Tried putting this into `nuxt.config.js`, no dice 🤔

```
generate: {
    exclude: [
      'my-page', // also '/my-page'
    ],
  },
```

**Comment by manniL** [comment]
@Palivonas It actually is but docs are still WIP :see_no_evil: 
https://github.com/nuxt/nuxt.js/pull/4754

Use a regex that matches the route. that should work

**Comment by Palivonas** [comment]
@manniL oh okay I was testing with an older version. Thanks, this will do!

**Comment by mattkaye** [comment]
This is exactly what I'm struggling with (I think). I have a single page scroll site that does one pull from a headless WordPress installation on load. I'm using nuxt generate because I want the SEO benefits. The API is called in /pages/index.vue. Using the asyncData method, the markup is generated on the server-side and delivered BUT on reloading the page doesn't reflect the new values saved in WordPress if I edited content. 

So I tried fetch. Using fetch(), the new WordPress values ARE reflected when I reload the page but there's no server markup. It seems to run as a SPA.

So I'm caught between two worlds. I need the SSR markup and the API to actually be called each time the page loads. Any help would be greatly appreciated!
