### ISSUE TITLE
Nuxt 2.4.5 removes custom methods from JS objects prototypes imported from node_modules

### ISSUE THREAD

**Issue by voronianski** [nuxt/nuxt.js#5178]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://github.com/voronianski/nuxt-2.4.5-prototype-issue](https://github.com/voronianski/nuxt-2.4.5-prototype-issue)

### Steps to reproduce

https://github.com/voronianski/nuxt-2.4.5-prototype-issue#whats-the-problem

### What is expected ?

https://github.com/voronianski/nuxt-2.4.5-prototype-issue#whats-the-problem

### What is actually happening?

https://github.com/voronianski/nuxt-2.4.5-prototype-issue#whats-the-problem

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8785">#c8785</a>)</em></sub></div>

**Comment by clarkdo** [comment]
This issue is due to that vue-ssr-renderer will be run in a new context which is different with Nuxt server.

You can try:
```js
// nuxt.config.js
render: {
  runInNewContext: false
}
```

But we recommend using `runInNewContext: true` in `dev` mode for avoiding potential memory leak.
So you can try to register the `vue-string-format` inside Vue context, for example: 
 `layout`:

```vue
<template>
  <Nuxt />
</template>
<script>
import Vue from 'vue';
import StringFormat from 'vue-string-format';
export default {
  created() {
    Vue.use(StringFormat);
  }
}
</script>
```

**Comment by clarkdo** [comment]
Sorry, please hold, I may need more investigation.

**Comment by clarkdo** [comment]
@voronianski If the comment resolved your problem, could please close this issue ?

**Comment by voronianski** [comment]
@clarkdo just FYI the solution you proposed doesn't work:

```js
// nuxt.config.js
render: {
  runInNewContext: false
}
```

**Comment by voronianski** [comment]
change was added into demo repo - https://github.com/voronianski/nuxt-2.4.5-prototype-issue/commit/481168b7951b97a05ca87fa83c62dac42ef86112

**Comment by clarkdo** [comment]
@voronianski I opend a pr in you repo for fixing it https://github.com/voronianski/nuxt-2.4.5-prototype-issue/pull/1

**Comment by voronianski** [comment]
@clarkdo thanks, your PR works.

regarding you 2nd proposal, it doesn't work for me:

```
<template lang="pug">
  .main-page
    h3 {{title}}
</template>

<script>
import Vue from 'vue';
import StringFormat from 'vue-string-format';

export default {
  created() {
    Vue.use(StringFormat);
  },

  computed: {
    title() {
      return 'Title - {0}'.format('index page');
    }
  }
};
</script>
```

**Comment by voronianski** [comment]
@clarkdo changes pushed into demo repo - https://github.com/voronianski/nuxt-2.4.5-prototype-issue/commit/16521101c27cfcd48f6ef63b7a32e528230adaeb

**Comment by voronianski** [comment]
@clarkdo updated to use in layout - https://github.com/voronianski/nuxt-2.4.5-prototype-issue/commit/04a5689216a9bf689c06d4e151e4a0d6d989188e

**Comment by clarkdo** [comment]
@voronianski I just looked into Vue src, it seemed that vue-ssr will run entry and async components in new context, other files like `vue-string-format` will be executed in main context, so the `String` is still a different one.

I suggest use some utility function (like register `stringFormat` on `Vue`) instead of touching any built-in prototype.

If you have to do it, use `runInNewContext: false`

**Comment by voronianski** [comment]
@clarkdo alright, thanks for explanation!
