### ISSUE TITLE
 Cannot read property 'hasOwnProperty' of undefined 

### ISSUE THREAD

**Issue by tomderudderetna** [nuxt/nuxt.js#5245]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[http://localhost:3000/](http://localhost:3000/)

### Steps to reproduce

After Ctr + R for refresh page without cache

### What is expected ?

Nuxt have the error
 Cannot read property 'hasOwnProperty' of undefined 

### What is actually happening?

Nuxt have the error
 Cannot read property 'hasOwnProperty' of undefined 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8838">#c8838</a>)</em></sub></div>

**Comment by tomderudderetna** [comment]
Dsl pour mon mauvais anglais

**Comment by tomderudderetna** [comment]
I have find the problems, then I remove `head` that stop problem

<script>
export default {
  asyncData(context) {},
  fetch() {},
  head() {}, <------ here
  props: ["title", "date", "description"]
};
</script>

**Comment by camonunez** [comment]
I deleted node_modules, reinstalled them and then the problem started.
I couldn't even log objects

 ERROR  Cannot read property 'options' of null     
  at node_modules/esm/esm.js:1:193448
  at ss (node_modules/esm/esm.js:1:193479)
  at node_modules/esm/esm.js:1:194718
  at node_modules/esm/esm.js:1:194754
  at node_modules/esm/esm.js:1:195527
  at node_modules/esm/esm.js:1:194263
  at Object.apply (node_modules/esm/esm.js:1:194053)
  at Proxy.<anonymous> (node_modules/@nuxtjs/sentry/node_modules/@sentry/node/dist/integrations/co
nsole.js:82:46)
  at verificarToken.then.catch.e (back/api.js:61:22)
  at process._tickCallback (internal/process/next_tick.js:68:7)

After many hours I edited yarn.lock to manually choose nuxt's dependency **esm version 3.1.4 instead of 3.2.17** 

IDK what's going on with that package, it just crashes.

Maybe it's a good idea to lock it at 3.1.4

**Comment by manniL** [comment]
Please add reproduction.
