### ISSUE TITLE
corejs option in @nuxt/babel-preset-app

### ISSUE THREAD

**Issue by shrpne** [nuxt/nuxt.js#5343]
### What problem does this feature solve?

Can you please expose `corejs` option in the `@nuxt/babel-preset-app` so it will be passed to the `@babel/preset-env` as other options?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8902">#c8902</a>)</em></sub></div>

**Comment by manniL** [comment]
cc @clarkdo

**Comment by clarkdo** [comment]
Will work on it

**Comment by clarkdo** [comment]
After talk to team, this feature may need more discussion and find a proper way to solve the root issue.

`core-js` 2 and 3 are not compatible and having totally different dir structure, so if a project contains both 2 and 3, user may have `files in specific core-js version cannot be found` issue in building or starting phase.

Benefits

1. An option to let users (who know exactly which version of core-js they should use and is installed in node_modules of their projects) fix core-js issue.

Disadvantages

1. Adding option and documenting it may cause community being more confused about core-js issue and facing more problems
1. For supporting core-js 2 or 3 will need different dependencies like `core-js@2/3`, `core-js-compat`, but dynamically choosing dependencies is hard in node.js since packages hoisting

**Comment by posva** [comment]
What do we do if we have `@babel/preset-env` installed for testing purposes, which includes core-js@3?

**Comment by pi0** [comment]
@posva True :( We are in the middle of a breaking change by babel. Some 3rd party packages still depending on `corejs@2` and some on `corejs@3` and can't have both on the same project. So decided to make `@3` opt-in and suggesting users that facing the problem to manually install one version in their `package.json`

**Comment by posva** [comment]
That has to be hard for you to handle, I'm sorry
For the moment installing core-js@3 seems to show the same problem. Maybe I need to downgrade nuxt or @babel/preset-env until @3 is an optin?

**Comment by pi0** [comment]
@posva See _core-js@3_ section of [release notes](https://github.com/nuxt/nuxt.js/releases/tag/v2.6.0)

**Comment by posva** [comment]
Thanks! It's weird, because I removed core-js from the package.json, removed node_modules and yarn.lock, reinstalled, and things work again

**Comment by clarkdo** [comment]
@posva It's probably because package hoisting due to yarn.lock.

The new generated yarn.lock may be more flat than old one, so the core-js in node_modules is expected version after re-install.

**Comment by posva** [comment]
It indeed changed to 2 different versions of core-js instead of 3 but there was still core-js@3 and core-js@2.

```
yarn why v1.15.2
[1/4] 🤔  Why do we have the module "core-js"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "core-js@2.6.5"
info Has been hoisted to "core-js"
info Reasons this module exists
   - Hoisted from "vue-jest#babel-plugin-transform-es2015-modules-commonjs#babel-runtime#core-js"
   - Hoisted from "nuxt#@nuxt#webpack#@nuxt#babel-preset-app#core-js"
info Number of shared dependencies: 0
=> Found "core-js-compat#core-js@3.0.1"
info This module exists because "@babel#preset-env#core-js-compat" depends on it.
info Number of shared dependencies: 0
```

**Comment by clarkdo** [comment]
core-js@2 is hoisted to the root `node_modules`.
core-js@3 is in `node_modules/@babel/preset-env/node_modules/core-js-compat/node_modules`

So the require('core-js') will get core-js@2 for all packages except `core-js-compat`

**Comment by clarkdo** [comment]
Has been release in [v2.6.0](https://nuxtjs.org/guide/release-notes#core-js)
