### ISSUE TITLE
Context app in types

### ISSUE THREAD

**Issue by orblazer** [nuxt/nuxt.js#5589]
### What problem does this feature solve?

The problem is, when we use `context.app` we could not use (in nuxt-i18n) the `context.app.i18n`, or `context.app.$t`.

This resolve the problem of types detection when use context.app.

### What does the proposed changes look like?

We can probably use interface for that with name like `AppContext`.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9094">#c9094</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@orblazer Did you add `vue-i18n` in your `types` of `tsconfig.json` ?

**Comment by orblazer** [comment]
@kevinmarrec Yes but this is beacause nuxt-i18n add i18 with app.i18n and the context reference is Vue instance.

**Comment by kevinmarrec** [comment]
@orblazer Alright but in which case do you need `app.i18n` over `app.$i18n` ?
And `app.$t` should arleady work.

**Comment by orblazer** [comment]
That is needed if you want use the i18n in middleware (like for get locale or some variables)

**Comment by kevinmarrec** [comment]
Isn't `context.app.$i18n.locale` enough ? Can you provide your middleware or a part of it to see what you're trying to achieve ?

**Comment by orblazer** [comment]
@kevinmarrec i don't have the code under my hand but this is doesn't work beacause the app is not fully initialized. try to log context.app and you can see only "i18n" and not "$i18n".

**Comment by rchl** [comment]
I know a bit of `nuxt-i18n` code so can chime in. `nuxt-i18n` indeed exposes `i18n` property on `context.app` (and some others). The `$i18n` property is added to Vue context by the `i18n` plugin itself (so not by the `nuxt-i18n` module) so obviously that one is not exposed on `context` or `context.app`.

It's IMO a mess and if it would be for me, I would create new major version with this stuff cleaned up -- probably by only exposing `$i18n` property using `inject` function.

But in any case, in current state of things at least, is it not fixable in `nuxt-i18n` module itself rather than here?

Some more info here https://github.com/nuxt-community/nuxt-i18n/issues/282

**Comment by rchl** [comment]
OK, I think I understand. `context.app` is defined as `Vue` so it's not possible to extend `app` without also extending Vue instance inside of components. And with messy way things are done in `nuxt-i18n`, those don't match.

So I guess defining `app` in nuxt as type that extends `Vue` would probably help with this issue.

**Comment by orblazer** [comment]
Yes exactly @rchl

**Comment by kevinmarrec** [comment]
@rchl @orblazer `app` from `context` already has `Vue` type : https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/types/index.d.ts#L17

Are you talking about having a dedicated interface extending `Vue` so that this interface can be altered by modules like `nuxt-i18n` ?

I'm pretty lost with all this stuff, I'm not mastering how `vue-i18n` is built, there is indeed confusion between `i18n` & `$i18n`.

`$i18n` refers to `vue-i18n` plugin, meanwhile `i18n` refers to the Nuxt module configuration, if I'm right.

I'm not really sure if adding properties to `app` is good practices, maybe some clean up with major version could be helpful, as suggested @rchl .

But anyway, this thread should be IMO on dedicated `nuxt-i18n` module.

/cc @paulgv

**Comment by orblazer** [comment]
@kevinmarrec this is not only for nuxt-i18n this is for all module whant add context app methods.
Only an interface extends of Vue is probably required.

**Comment by rchl** [comment]
@kevinmarrec
> Are you talking about having a dedicated interface extending Vue so that this interface can be altered by modules like nuxt-i18n ?

Yes. The pros are:
  - simple change
  - backwards compatible (hopefully)
  - makes it easy to fix types in current version of `nuxt-i18n`

> I'm not really sure if adding properties to app is good practices

Nothing really wrong with it. Official documentation has many examples with extending app and `inject` function also does that automatically. https://nuxtjs.org/guide/plugins#inject-in-root-amp-context

> $i18n refers to vue-i18n plugin, meanwhile i18n refers to the Nuxt module configuration, if I'm right.

Both refer to `vue-i18n` plugin instance (extended with `nuxt-i18n` properties) AFAIK but former is only exposed as a mixin and latter is only exposed on `context.app`. (Or something close to that ;))

> But anyway, this thread should be IMO on dedicated nuxt-i18n module.

That's true if decision is not to do decidacter interface in Nuxt. Fixing `nuxt-i18n` mess and just exposing `$i18n` universally (using nuxt's `inject` function) has pro of having nicer API in `nuxt-i18n` but:
  - is not backwards compatible
  - is quite a bit of work to clean up everything
  - not sure if @paulgv wants to take that leap

**Comment by rchl** [comment]
I did some investigation on what `context.app` really is, and came up with conclusion that it's not really a `Vue` instance. Created #5662 for that.
