### ISSUE TITLE
Strange behavior with applied styles in loaded page from server

### ISSUE THREAD

**Issue by massimilianomarini** [nuxt/nuxt.js#57]
I've installed nuxt.js using `vue init nuxt/starter nuxt-site`, all is fine, but when the page is loaded from the server, soon I see the page without styles, which are applied a fraction of second later.

I don't think (maybe I'm wrong), but is this the right behavior? :confused:

**Comment by alexchopin** [comment]
Hi,
If you are launching `npm run dev`, it's a normal behavior because you are in development mode.
You can see the difference by testing the project in production mode with `npm run buil && npm start`.
The development mode have more configuration like hot-reloading, so that why you see this difference during a fraction of second.
More information about the development mode will be describe on the documentation soon :)

**Comment by massimilianomarini** [comment]
Thanks @alexchopin, you're right, in *project mode* is absolutely awesome! :)

Keep up the good work! :+1:

**Comment by mikekidder** [comment]
@alexchopin if you are not already doing, may want to put that Getting Started docs.  I started reading through closed issues because figured it had been asked already. :)

 And just want to say you guys are doing great work.
