### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by vinayakkulkarni** [nuxt/nuxt.js#5721]
### Version

[v2.7.0](https://github.com/nuxt.js/releases/tag/v2.7.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/releases/tag/v2.7.0](https://github.com/nuxt/nuxt.js/releases/tag/v2.7.0)

### Steps to reproduce

- `npm up` to upgrade to nuxt 2.7.0
- have `"@nuxtjs/dotenv": "^1.3.0",` as dep in your project
- have `require('dotenv').config();` in your `nuxt.config.js` file

try to use `process.env` variables in your nuxt.config.js, and it'll throw a error

### What is expected ?

Ability to access .env variables inside the nuxt app

### What is actually happening?

Nuxt app breaks down squawking about the `process` error

### Additional comments?

Screenshot from @cannap on Discord
![unknown](https://user-images.githubusercontent.com/19776877/57699866-5ffac800-7676-11e9-96c2-02e55bc60f08.png)

Screenshot from me:
<img width="1680" alt="Screenshot 2019-05-14 at 6 30 52 PM" src="https://user-images.githubusercontent.com/19776877/57699898-6ee17a80-7676-11e9-81b2-22e89218edf6.png">

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9208">#c9208</a>)</em></sub></div>

**Comment by T0TProduction** [comment]
can confirm just updated my dependencies, including nuxt to 2.7, and this killed my app

**Comment by manniL** [comment]
Could one of you provide a minimal reproduction repo or codesandbox please?

**Comment by pi0** [comment]
`ci-info` is not a dependency of `@nuxtjs/dotenv` so the issue may be originating from somewhere else or `import`/`require` a Node.js lib in application code.

**Comment by sobolevn** [comment]
I have the same bug.

<img width="631" alt="Снимок экрана 2019-05-14 в 17 54 47" src="https://user-images.githubusercontent.com/4660275/57708074-6470b200-7671-11e9-94f0-eee82a015a8f.png">

I use ([source](https://github.com/wemake-services/wemake-vue-template/blob/master/template/nuxt.config.ts#L7):

```js
const envPath = path.resolve(__dirname, 'config', '.env')
require('dotenv').config({ 'path': envPath })
```

And also:

```ts
/**
   * Environment variables
   */
  'env': {
    'GOOGLE_MAPS_KEY': process.env.GOOGLE_MAPS_KEY,
  },
```

in my local `nuxt.config.ts`.

**Comment by clarkdo** [comment]
@sobolevn Could you chat with me on discord so that we can get response timely

**Comment by sobolevn** [comment]
@clarkdo sure. Texted you

**Comment by daniplaninc** [comment]
I have the same issue. 

output of npm list ci-info:

`+-- @nuxtjs/auth@4.5.3
| `-- consola@1.4.5
|   `-- std-env@1.3.1
|     `-- is-ci@1.2.1
|       `-- ci-info@1.6.0  deduped
`-- nuxt@2.7.0
  +-- @nuxt/cli@2.7.0
  | +-- @nuxt/config@2.7.0
  | | `-- std-env@2.2.1
  | |   `-- ci-info@1.6.0  deduped
  | `-- std-env@2.2.1
  |   `-- ci-info@1.6.0
  +-- @nuxt/core@2.7.0
  | `-- std-env@2.2.1
  |   `-- ci-info@1.6.0  deduped
  `-- @nuxt/webpack@2.7.0
    +-- std-env@2.2.1
    | `-- ci-info@1.6.0  deduped
    `-- webpackbar@3.2.0
      `-- std-env@2.2.1
        `-- ci-info@1.6.0  deduped`

**Comment by clarkdo** [comment]
Through the communication with @sobolevn , the issue is due to hoisted `consola` version, if you're having this issue, please install `consola 2.x` manually by:

```sh
$ npm i consola@^2.6.1

# or

$ yarn add consola@^2.6.1
```

We'll propose a fix ASAP

**Comment by pi0** [comment]
fixed in [v2.7.1](https://github.com/nuxt/nuxt.js/releases/tag/2.7.1)

**Comment by Skriptach** [comment]
@pi0 
I have `^2.10.2` and still reproduce

**Comment by jcat4** [comment]
> @pi0
> I have `^2.10.2` and still reproduce

Same, I'm running 2.11 and still can't access `process`...

**Comment by jcat4** [comment]
> > @pi0
> > I have `^2.10.2` and still reproduce
> 
> Same, I'm running 2.11 and still can't access `process`...

Okay, I think I was misunderstanding a few things. Defaults are indeed set (see [this commit](https://github.com/nuxt/nuxt.js/commit/742ea42f9737d2e7d98c42544a79297d305b0252#diff-bad63423433e9626a156a1e1250d2281))

My understanding in a nutshell (correct me if I'm wrong) is that **nuxt.config.js** has access to `process.env` but does not implicitly propagate that access to the rest of the code. 

So in order to have access to something like `process.env.NODE_ENV` from my components, I needed to do a few things.

First, in **nuxt.config.js**, you need to propagate your `process.env.whatever` values under an `env` key in your `module.exports` so that your components can access them too.  In this case, I want `NODE_ENV`.

#### nuxt.config.js
```javascript
module.exports = {
  ...
  env: {
    NODE_ENV: process.env.NODE_ENV
  },
  ...
}
```

Now, when _explicitly_ attempting to access `process.env.NODE_ENV` in any of my components, I get `production` or `development` depending on the command I run (`npm dev` produces "development", `npm start` produces "production")

#### YourComponent.vue
```javascript
...

mounted () {
  console.log(`process.env.NODE_ENV: ${process.env.NODE_ENV}`) // process.env.NODE_ENV: development
}

...
```

Something that was confusing me was that I couldn't access `process.env.NODE_ENV` **in the debugger in the browser**. I would set a debugger in the same methods/hooks I'm logging `process.env.NODE_ENV` in as an example, and I get `undefined` for `process.env.NODE_ENV` and an empty object `{}` for `process.env`. Before that, I was getting things like `process is undefined`.

Despite all that weirdness, I can now access env vars, including NODE_ENV vars that are generated by default (I don't set `NODE_ENV` or use `cross-env` or anything for my scripts in **package.json**).

Hopefully this helps someone!

**Comment by thomasdavis** [comment]
Could someone update the docs on this? Doesn't seem to work as intended on nuxt@2.12.0.

process is undefined.

**Comment by Edofre** [comment]
@thomasdavis Do you have the line `require('dotenv').config()` at the top of your nuxt.config.js? That has solved it for me.

**Comment by NotMoni** [comment]
@thomasdavis  try ```require('dotenv').config()``` first. If that doesnt work, try 
```const env = require('dotenv');
env.config();
```
This code has worked when ```require('dotenv').config()``` doesnt.

**Comment by augnustin** [comment]
Thanks @jcat4 for your useful comment.

What I understand is that the destructuring syntax doesn't work:

```
const { NODE_ENV } = process.env;
```

But this works:

```
const NODE_ENV = process.env.NODE_ENV;
```

I guess the build step parses `process.env.*` and statically replaces it by it's string value. While the former version was more elegant to me, it is not accessible.

**Comment by kingmaster772** [comment]
Issue raised again on Nuxt 3.1.2
![image](https://user-images.githubusercontent.com/29949806/216855659-39329087-b1d8-4f47-bdd0-42c11b52df4b.png)

**Comment by Maikpwwq** [comment]
Actually I had facing this error with Nuxt3. Because library implemented `@web3auth/...` has some [polyfill issues](https://web3auth.io/docs/troubleshooting/vite-issues) to solve. 

First I needed to install packages `pnpm add --save-dev buffer process`, Then I call them in my layout by default.

```
<script type="module" lang="ts">
// Global node polyfill.
import { Buffer } from "buffer";
import process from "process";
window.global = window;
window.Buffer = Buffer;
window.process = process;
</script>
```
