### ISSUE TITLE
URI malformed with dynamic route

### ISSUE THREAD

**Issue by yaniv51** [nuxt/nuxt.js#5827]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://codesandbox.io/s/examplehelloworld-quzpq](https://codesandbox.io/s/examplehelloworld-quzpq)

### Steps to reproduce

Navigate with dynamic route to:
https://quzpq.sse.codesandbox.io/90%25

### What is expected ?

Getting welcome page

### What is actually happening?

Getting server error page with URI malformed error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9278">#c9278</a>)</em></sub></div>

**Comment by yaniv51** [comment]
It is looks like it is Vue.js bug rather than Nuxt.js bug
![vue-router](https://user-images.githubusercontent.com/10440710/58536286-b6304500-81f8-11e9-8633-7b9b60ce12b3.JPG)

**Comment by pimlie** [comment]
Closing this as this is an upstream issue in vue-router, see already linked issue

**Comment by ThomasR** [comment]
As far as I understand, this affects URLs containing a (properly escaped) `%` character (`%25`).

I'm experiencing a similar issue where the `route` on the server side differs from the one on the client side (one is unescaped, the other one is escaped). Is that also caused by vue-router, or is this an actual Nuxt issue?

**Comment by pimlie** [comment]
@ThomasR not sure, could you show an example of what happens in your case?

**Comment by ThomasR** [comment]
What happens is that in
```
asyncData({ route: { path }}) {
    consola.log(path);
}
```
I get different log outputs server-side and client-side:

Server
```
path /foo bar
```

Browser
```
path /foo%20bar
```

However, I can't reproduce this bug when creating a new Vue app, so it must have something to do with my application config. (Can't publish that; it's not Free Software).

I'll try and come up with a minimal example, and file a new ticket.

**Comment by eddybrando** [comment]
I still experience this problem in Nuxt v2.10.2.

According to this issue https://github.com/vuejs/vue-router/issues/2708, the vue-router double DecodeURI was already fixed in vue-router v3.0.4.

Is this then an issue unique to Nuxt?

**Comment by eddybrando** [comment]
I tried to trace back the error and I believe the crash happens in **nuxt.js/packages/server/src/middleware/nuxt.js:14** on `await renderRoute(url, context)`.

The `url` parameter here gets decoded two lines above in `const url = decodeURI(req.url)`, which causes the `%25` to go back to `%`, which results in a malformed URI.

Nevertheless, removing the `decodeURI` results on a similar 500 error with the "URL malformed" message but just moved to another part.

Since the function `renderRoute` is method from a **vue-renderer** instance, could the problem maybe live somewhere deep in vue-renderer?

**Comment by manniL** [comment]
@eddybrando Yes, it could be a vue-server-render issue then I guess. Can you reproduce it with "just" the vue server renderer?

**Comment by eddybrando** [comment]
> @eddybrando Yes, it could be a vue-server-render issue then I guess. Can you reproduce it with "just" the vue server renderer?
> 
> (Example reproduction of another problem: [vuejs/vue#10733](https://github.com/vuejs/vue/issues/10733))

I can reproduce the error in both SSR and SPA rendering.

The SPA rendering just fails silently with a browser error log whilst the SSR returns the full error debug page.

I'm looking at the renderContext in vue-renderer to see if there is something there that could be fixed...

So far I found that `renderContext.url` in the `renderRoute` method has the decoded `/path/foo/bar%` version of the URL instead of the encoded one (`/path/foo/bar%25`), which can be found in all other URL references in said context.

But I'm still debugging...

**Comment by maunier** [comment]
> > @eddybrando Yes, it could be a vue-server-render issue then I guess. Can you reproduce it with "just" the vue server renderer?
> > (Example reproduction of another problem: [vuejs/vue#10733](https://github.com/vuejs/vue/issues/10733))
> 
> I can reproduce the error in both SSR and SPA rendering.
> 
> The SPA rendering just fails silently with a browser error log whilst the SSR returns the full error debug page.
> 
> I'm looking at the renderContext in vue-renderer to see if there is something there that could be fixed...
> 
> So far I found that `renderContext.url` in the `renderRoute` method has the decoded `/path/foo/bar%` version of the URL instead of the encoded one (`/path/foo/bar%25`), which can be found in all other URL references in said context.
> 
> But I'm still debugging...

I encounter this problem too. Have you got a solution?

**Comment by eddybrando** [comment]
> > > @eddybrando Yes, it could be a vue-server-render issue then I guess. Can you reproduce it with "just" the vue server renderer?
> > > (Example reproduction of another problem: [vuejs/vue#10733](https://github.com/vuejs/vue/issues/10733))
> > 
> > 
> > I can reproduce the error in both SSR and SPA rendering.
> > The SPA rendering just fails silently with a browser error log whilst the SSR returns the full error debug page.
> > I'm looking at the renderContext in vue-renderer to see if there is something there that could be fixed...
> > So far I found that `renderContext.url` in the `renderRoute` method has the decoded `/path/foo/bar%` version of the URL instead of the encoded one (`/path/foo/bar%25`), which can be found in all other URL references in said context.
> > But I'm still debugging...
> 
> I encounter this problem too. Have you got a solution?

Not really, I just avoided it by changing the way I constructed the URLs in my applications.

Do you encounter this still in the newest Nuxt version? Because I believe this is indeed a bug that should be addressed then.

**Comment by maunier** [comment]
i do this to solve my problem:  url.replace('%', '%25%25')

**Comment by mendicm** [comment]
@maunier Where did you put this replace? I'm facing this issue too…

**Comment by mendicm** [comment]
This is my current solution if you use a custom router:

In {root}/router.js:
```js
export function createRouter(ssrContext) {
  if (ssrContext) {
    ssrContext.url = ssrContext.url.replace(/%(?![0-9A-F]{2})/g, '%25')
  }
  ...
}
```

**Comment by bestark** [comment]
Are there any updates since Jul' 20? Seems like this issue is still occuring

**Comment by bestark** [comment]
I ran into that problem today. Nuxt Version was 2.14.11. Solving the problem with updating to 2.14.12.
