### ISSUE TITLE
Ava testing issue

### ISSUE THREAD

**Issue by smartbee** [nuxt/nuxt.js#5836]
Hello friends
I have problems with this example
https://nuxtjs.org/examples/testing
error occurred when index.vue import a components
![Screen Shot 2019-05-30 at 10 32 11 PM](https://user-images.githubusercontent.com/7590207/58644373-4e2e4b80-832b-11e9-9d5d-c4f9cd6ff79e.png)
In component header.vue, I used i18n
![Screen Shot 2019-05-30 at 10 34 19 PM](https://user-images.githubusercontent.com/7590207/58644294-2d65f600-832b-11e9-8945-efd6e8a6fceb.png)
When it runs, an error occurs
![Screen Shot 2019-05-30 at 10 46 32 PM](https://user-images.githubusercontent.com/7590207/58645083-d103d600-832c-11e9-94ff-209f2c3be07e.png)

Please help me!
Many thanks

**Comment by jfarellano** [comment]
Hey I had the exact same problem and just managed to fix it. The problem is that the nuxt instance that you are referencing does not have the nuxt-i18n module set up for you to fix it and also taking into account that it would happen with other modules is add it to the nuxt configuration before building it. Like this: 

`const config = {
    dev: false,
    rootDir: resolve(__dirname, '../../'),
    modules: [
      'nuxt-i18n'
    ]
  }
  nuxt = new Nuxt(config)`
