### ISSUE TITLE
yarn generate failing

### ISSUE THREAD

**Issue by bovas85** [nuxt/nuxt.js#5840]
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://github.com/bovas85/nunziellasalluce.com](https://github.com/bovas85/nunziellasalluce.com)

### Steps to reproduce

update nuxt to 2.8.0
run yarn generate

### What is expected ?

generates the static site

### What is actually happening?

 FATAL  ENOENT: no such file or directory, stat 'C:\Users\Leelium\Desktop\nunziellasalluce.com\.nuxt\dist\client'

╭───────────────────────────────────────────────────────────────────────╮
   │                                                                       │
   │   ✖ Nuxt Fatal Error                                                  │
   │                                                                       │
   │   Error: ENOENT: no such file or directory, stat                      │
   │   'C:\Users\Leelium\Desktop\nunziellasalluce.com\.nuxt\dist\client'  

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9287">#c9287</a>)</em></sub></div>

**Comment by bovas85** [comment]
apologies, it must have been an issue with greenkeeper. Reverted its PR and works fine now

**Comment by pi0** [comment]
Hi. Thanks for reproduction. We are investigating.

**Comment by pi0** [comment]
OK. I tracked down the issue to a wonderland!

Solution: You are mixing cjs with es syntax for `nuxt.config`. Simply using `export default` fixes issue. (Also consider using `export default` for `assets/config.js`)

----

Details: Seems esm package introduced a new regression when cjs is mixed with esm syntax in the same file. Resulting to when we do `Object.assign({}, options)` the dev field set to undefined and both generate and build was running in development mode!! Will try to make smaller reproduction to report to esm.

**Comment by sonnh58** [comment]
@pi0 i have same issue `build was running in development mode`
i have to add `dev: (process.env.NODE_ENV !== 'production')` to `nuxt.config.js`
..

**Comment by bovas85** [comment]
Thanks guys, I'll fix that for now but I suppose as it was working before we could add a warning in the docs or handle the error?

**Comment by bovas85** [comment]
should this be a breaking change or was it my error to have import + module.exports ?

**Comment by sonnh58** [comment]
seem only old projects have this issues

https://github.com/nuxt/create-nuxt-app/commit/4f9706f4e09cf5c88a4f86b87915c4d09d116f90#diff-f817453d8d74b9b596efd2ebf4d90c66

**Comment by AstralProgrammer** [comment]
I had the same issue but the fix for me was to run npm install. it seems that some dependency is not yet fully supported / still bugging in yarn :'(

**Comment by pi0** [comment]
@bovas85, not a breaking change from us it is a regression by esm not handling edge cases (mixed cjs and esm)

Everyone seeing this issue, adding `dev` to nuxt.config is **NOT A SOLUTION** but the correct fix is to avoid using cjs (module.exports, require) with esm (import, export). letter one is preferred.

I'll try to report and meanwhile, add protection in the core to detect this problem.

**Comment by bovas85** [comment]
Thanks @pi0, happy to close

**Comment by pi0** [comment]
just raised standard-things/esm#813

**Comment by pi0** [comment]
Workaround added in 2.8.1: https://github.com/nuxt/nuxt.js/releases/tag/v2.8.1

**Comment by bovas85** [comment]
Thanks @pi0

**Comment by seanaye** [comment]
i have tried everything above and am still getting `[Error: ENOENT: no such file or directory, stat '.../.nuxt/dist/client'` 

There are no require statements only import/export 
Ran `npm install` again
using lodash.deepclone to clone then modify config.
Dynamic routes are being added
added `dev: (process.env.NODE_ENV !== 'production')` (even though it isn't a solution)

not sure what the issue is here

running with `sudo node -r esm watchfile.js`

`import chokidar from 'chokidar'
import fs from 'fs'
import util from 'util'
import { debounce, cloneDeep } from 'lodash'
import { Nuxt ,Generator, Builder } from 'nuxt'
import config from './nuxt.config.js'

let newconfig = cloneDeep(config)

const filepath = './assets/img'

const readdir = util.promisify(fs.readdir)

let watcher = chokidar.watch(filepath, {
  ignored: /[\/\\]\./,
  persistent: true,
  cwd: '.',
  ignoreInitial: true
})

// Something to use when events are received.
const log = console.log.bind(console)
// Add event listeners.
watcher.on('all', debounce(async (path) => {
  let albums = await readdir(filepath)
  albums = albums.filter((file) => file.charAt(0) !== '.')
  const gallery = await Promise.all(albums.map( async (album) => {
    const photos = await readdir(${filepath}/${album})
    return {
      title: album,
      photos: photos.filter((photo) => photo.charAt(0) !== '.')
    }
  }))
  log('starting generate')
  newconfig.env.gallery = gallery
  newconfig.generate.routes = gallery.map(elem => /photo/${elem.title})
  log(newconfig)
  let nuxt = new Nuxt(newconfig)
  let builder = new Builder(nuxt)
  let generator = new Generator(nuxt, builder)
  await generator.generate({ build: false, init: true }).catch(e => log(e))
  log('generate complete')
}, 10000))`

Any hints are greatly appreciated.

**Comment by augnustin** [comment]
Thanks @pi0 ! I just cannot believe changing `module.export` to `export default` fixed it, but it did!

**Comment by palfaro91** [comment]
> Question regarding this: If I use Nuxt programmatically, my nuxt.config.js has to be CJS, correct? If I use Nuxt programmatically and use the Generaterator.generate() config.dev has to be false, otherwise it fails!? Thanks!

You saved my life. I was stuck and the missing piece was setting config.dev to false. Thank you!
