### ISSUE TITLE
Warning about TypeScript 3.5 occurred when execute `yarn dev`

### ISSUE THREAD

**Issue by haryu703** [nuxt/nuxt.js#5887]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/haryu703/ts_express](https://github.com/haryu703/ts_express)

### Steps to reproduce

```
git clone git@github.com:haryu703/ts_express.git
cd ts_express
yarn install
yarn dev
```

### What is expected ?

No warnings occur.

### What is actually happening?

Following warning has occurred.
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.5.0

YOUR TYPESCRIPT VERSION: 3.5.1

Please only submit bug reports when using the officially supported version.

=============
```

### Additional comments?

This warning has occurred when developing Nuxt.js+express application.

Related issues:
https://github.com/typescript-eslint/typescript-eslint/issues/577
https://github.com/facebook/create-react-app/issues/7160

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9324">#c9324</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@haryu703 I noticed that lately too, It's a `typescript-eslint` issue which is not a dependency of Nuxt TypeScript, it's something you manually add in your project, so there's unfortunately nothing we can do (unless revert typescript version but doesn't sound so good), you just need to wait `typescript-eslint` next release which should be really soon (issue fixed in https://github.com/typescript-eslint/typescript-eslint/pull/597)

As it's not a Nuxt direct issue, i'm closing this.

**Comment by haryu703** [comment]
@kevinmarrec Thank you for answering. It helped me to know the cause of this.
