### ISSUE TITLE
tsconfig.json does not reflect config.srcDir

### ISSUE THREAD

**Issue by nandenjin** [nuxt/nuxt.js#5949]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/nuxt-tsconfig-issue-sample-zkx3o](https://codesandbox.io/s/nuxt-tsconfig-issue-sample-zkx3o)

### Steps to reproduce

```
yarn dev
```

Note that this sandbox is in the state of before first run, so `tsconfig.json` is a just empty file.

### What is expected ?

Nuxt will create content of tsconfig.json automatically, and dev build will continue successfully.

### What is actually happening?

tsconfig.json is created with `"baseUrl": "."` even `config.srcDir` is set to `src`, and type check for `import MyComponent from '~/components/MyComponent.vue'` in `src/pages/index.vue` fails.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9375">#c9375</a>)</em></sub></div>

**Comment by kevinmarrec** [comment]
@nandenjin It's a limitation we have for now, the issue is that a `tsconfig.json`is needed to be able to read `ts` files, and `nuxt.config.ts` is one of them. So we can't read config before setup TypeScript.

Something we could do is generate `tsconfig.json`, read config, and then rewrite `tsconfig.json` to override `paths` property with right `srcDir`. /cc @pi0 `paths` override could be done by `@nuxt/typescript-build` module.


You can fix your project by manually edit the generated `tsconfig.json` `paths` property with :
```json
"paths": {
  "~/*": [
    "./src/*"
  ]
}
```

**Comment by nandenjin** [comment]
I understand, currently I fix `baseUrl` manually as you mentioned in all of my projects, and they work well for me. Thanks.

**Comment by kevinmarrec** [comment]
(Don't pay attention of the referenced pull-request, it's just to ping its author so he understand a little more why his PR can't work)

Alright, I'll see if we can ensure that `baseUrl` is automatically updated with right `srcDir` with upcoming TypeScript support externalizations.
