### ISSUE TITLE
Dynamically load components based on API response

### ISSUE THREAD

**Issue by bitfactory-angelo-vancleef** [nuxt/nuxt.js#6000]
Instead of loading 100 components, I would like to import them dynamically depending on the response of the API request. I make an API call and in the given response I get a list of all the modules that are needed. For example:

    [
        {
            type: 'SliderBlock',
            name: 'slider-block'
        },
        {
            type: 'QuotationBlock',
            name: 'quotation-block'
        },
        {
            type: 'ReferenceBlock',
            name: 'reference-block'
        }
    ]

Now I know which components I need, I would like to import then in my page (component), but I cannot seem to get it working completely. The below code works perfect until I reach the point where I define my components:

       export default {
            components: components,
            data() {
                return {
                    components: loadComponents()
                }
            }
        }

This is where I get the error:

> [Vue warn]: Unknown custom element: <test> - did you register the
> component correctly? For recursive components, make sure to provide
> the "name" option.

When I console.log the value of "components" right before my export default, I see a correct list of components that should work and would be identical to a hardcoded list i.e.

    {
        SliderBlock, QuoationBlock, ReferenceBlock
    }

Can anyone tell me what is wrong and how to get this working please?

My **_.vue** file displayed below.

<template>
        <div>
    
            <template v-if="components" v-for="(component, i) in components">
                <component :key="i" v-bind:is="component.name"></component>
            </template>
    
        </div>
    </template>
    
    <script>
        import axios from 'axios'
    
        let componentsList = []
        let components = {}
    
        /**
         * @internal This function will retrieve a list of needed components from the API
         * @returns {Promise<Array | never>}
         */
        function getList()
        {
            return axios.get('https://myapi/data.json').then(response => {
    
                response.data['response'].forEach(function (comp) {
                    componentsList.push({
                        "type": comp.component.toString(),
                        "name": comp.slug.toString()
                    });
                });
    
                return componentsList
    
            });
        }
    
        /**
         * @internal Import each needed component
         * @returns {Array}
         */
        function loadComponents()
        {
            getList().then(data => {
                data.map((component, index) => {
                    import(`~/components/${component.type}.vue`).then(comp => {
                        components[index] = comp.default
                    })
                });
            });
    
            return componentsList
        }
    
    
        export default {
            components: components,
            data() {
                return {
                    components: loadComponents()
                }
            }
        }
    
    </script>

**Comment by pimlie** [comment]
# Issue 6000!

You need to make sure that webpack knows about these components during build, because otherwise they wont be included in the build and you cant use them ofc dynamically on the client. You could either create a lib module in which you list all available components or use [webpack magic comments](https://webpack.js.org/api/module-methods/#magic-comments)

**Comment by kameas** [comment]
@bitfactory-angelo-vancleef, did you find a solution? webpack magic comments work only without ssr

**Comment by dzcpy** [comment]
Any updates?

**Comment by WhiteR4bbitt** [comment]
Im just speculating here as I am kind of playing with similar logic (but in `TS`/`Classes` so may be a bit different in my logic) and stumbled across this.

If you can load the components before using `data()` because you will already have the response there should be no point in making it reactive? So something like this should work.

```js
export default {
  components: loadComponents()
}
```

Also in `loadComponents()` you are returning `componentsList` which is an `array`. You want to make sure you are returning the `object` as that is what `components` is expecting. Perhaps your `return` is what is causing the problem in the first place and its not the reactive `data` call?

**Comment by kissu** [comment]
Is it still impossible as of today even with [Nuxt Components](https://nuxtjs.org/blog/improve-your-developer-experience-with-nuxt-components/) ?
