### ISSUE TITLE
is nuxt can provide a Feature that clear console at production environment

### ISSUE THREAD

**Issue by zw1371** [nuxt/nuxt.js#6069]
### What problem does this feature solve?

console.log may be useless or harmful on prodution environment

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9492">#c9492</a>)</em></sub></div>

**Comment by fengjiel** [comment]
hi， webpack can be configured.You can look at the documentation  ‘build > plugins’

**Comment by fengjiel** [comment]
![image](https://user-images.githubusercontent.com/19583816/61283262-71379080-a7ef-11e9-960d-06e2b5c95628.png)
I think this can be done.

**Comment by manniL** [comment]
Nuxt uses terser as minifier and we recommend to keep using it instead of UglifyJS for various reasons.

You can use the `build.terser.terserOptions` to remove console log statements (by setting `compress.drop_console` to true).

This is not done by default as console statements might be used for error tracking tools like Sentry

**Comment by manniL** [comment]
Nuxt uses terser as minifier and we recommend to keep using it instead of UglifyJS for various reasons.

You can use the `build.terser.terserOptions` to remove console log statements (by setting `compress.drop_console` to true).

This is not done by default as console statements might be used for error tracking tools like Sentry

**Comment by nelsonlarocca** [comment]
hi guys !

@manniL 
any way to set the log level ?
like filtering off console.log but keep console.warn and console.error sentences ?

**Comment by mornir** [comment]
@nelsonlarocca 
I haven't tried it, but I found this here: https://github.com/webpack-contrib/terser-webpack-plugin/issues/57#issuecomment-498549997
```js
export default {
  // ...
  build: {
    terser: {
      terserOptions: {
        compress: {
          pure_funcs: ['console.info', 'console.debug', 'console.warn']
        }
      }
    },
   // ...
  }
};
```
