### ISSUE TITLE
Server-Side Data

### ISSUE THREAD

**Issue by knpwrs** [nuxt/nuxt.js#61]
As it stands today, is there a good way to connect to a server-side database and render pages that work without JavaScript on the client, but can progressively enhance to use JavaScript on the client if available? Essentially that would mean not exposing a rest API, but instead having some sort of data provider mechanism that doesn't leak secrets to the client.

**Comment by Atinux** [comment]
Hi @knpwrs 

Actually, Nuxt.js already render a page that can work without the JS on the client-side (because it's server-renderer).

For connecting to a server-side database, I would not recommend it because when navigating in the client-side, your page will have to render the data as well and since you want to protect it for only the server-side, it won't work.

Nuxt.js is made to create web-application based on API so the API call (http request from the server-side or ajax request on the client-side) will work for both environments.

**Comment by knpwrs** [comment]
Unfortunately the API call won't work for a client without JavaScript which kinda makes server-side rendering moot except for the point of getting a fast initial render.

**Comment by alexchopin** [comment]
Hi, 
What if you use [Axios](https://github.com/mzabriskie/axios) to do API calls on the server-side ?

**Comment by Atinux** [comment]
@knpwrs if the client does not have JavaScript, it will reload the page, and you can use [axios](https://github.com/mzabriskie/axios) to make API call from the server-side as well.

**Comment by Mirodil** [comment]
Is it possible load data to nuxt.js without create additional http request from server-side, and send rendered html page to client?

**Comment by Atinux** [comment]
@Mirodil please take a look at this answer I wrote: https://github.com/nuxt/nuxt.js/issues/123#issuecomment-272246782

**Comment by Mirodil** [comment]
Thanks, from client side it works and looks perfect, but server side part bit odd.
