### ISSUE TITLE
endless reloads, weird clash with eslint-import-resolver-webpack

### ISSUE THREAD

**Issue by simllll** [nuxt/nuxt.js#6173]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/simllll/nuxt-monorepo-test](https://github.com/simllll/nuxt-monorepo-test)

### Steps to reproduce

Hi all,
I was looking into a super weird issue where nuxt does endless reloads. I was able to break it down to one depdendency: "eslint-import-resolver-webpack" which seems to cause this issue, but now I'm kinda stuck as I have no idea what exactly is causing it and why this results into something that weird.

My demo setup:
* super slim monorepo with lerna.js
* one package with a nuxt creater template
* root package.json has a "eslint-import-resolver-webpack" in it, if you remove this and run "npm run clean && npm run install && npm run bootstrap" it starts working, if you add it back again and rerun "npm run clean && .." (it's important to run clean because otherwiese package-lock is not removed) it breaks again.

The strange thing is: I do not use any eslint specific things in the nuxt project. 

Besides this, I really want to know why the reload is happening. I guess there is some hidden error, maybe we can even improve this for other related bugs too.

Regards
Simon

### What is expected ?

Just start the demo page, no endless reloads

### What is actually happening?

The demo start page (or actually all sub pages) are reloading endless. It looks like the server is still sending the nuxt loading page with a progerss of 100%,the client tires to reload the page afterwards but the server still sends the loading page.. therefore it causes an endless loop?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9593">#c9593</a>)</em></sub></div>

**Comment by clarkdo** [comment]
The error is a combined effect of learn hoist and `eslint-import-resolver-webpack`.

Because `eslint-import-resolver-webpack` depends on `enhanced-resolve@~0.9.0` which is far behind current wepback dependency `enhanced-resolve@^4.1.0` and learn hoisted `enhanced-resolve@0.9.0` to root node_modules, so webpack used old version enhanced-resolve and lead to missing resources and endless reloading error.

You can fix or verify by adding `"enhanced-resolve": "^4.1.0"` manually in your package.json.

I suggesting not using lerna hoist, if you have to use lerna, please use yarn workspaces together with lerna for implementing your hoisting requirement.

**Comment by simllll** [comment]
Thanks for looking into it and your response,
I found the same root cause and could easily "fix" it by moving the dev dependency to the lerna sub package. 
Regarding yarn, unfortunately we cannot move from npm to yarn due to our deployment environment and some other issues with yarn.

Anyway, what I was hoping that we can maybe find the cause of this to improve the error logging / behaviour. Endless reloads are just very hard to debug ;)

Regards
