### ISSUE TITLE
head title: undefined on loading

### ISSUE THREAD

**Issue by marvinroger** [nuxt/nuxt.js#624]
Given:

```js
// head
titleTemplate: '%s - Marvin ROGER'
```

And two pages `index.vue` and `about.vue` each containing its title as head `title`.

On ^0.10.0, if we're on the index page and click on the about link, the initial title is `Home` and, after the about page is loaded, the title is `About`. This is the correct and expected behavior.

On ^0.11.0 however, the initial title is `Home`, during loading it is `undefined`, and after it is `About`. The issue being obviously that the page title is `undefined` on loading.

Here is a link to a repo where the issue happens : https://github.com/marvinroger/www.marvinroger.fr
This repo is on ^0.10.0 and it works fine, but try changing to `^0.11.0` and you'll see the issue.

**Comment by alexchopin** [comment]
0.11.0 ?

**Comment by awronski** [comment]
I have the same problem. ```nuxt 0.10.6```

1. User click on the link.
2. Commit goes to the store to change the state.
3. Vue/Nuxt rerender the head of the old page with the new store value.
4. Vue/Nuxt push router to the chosen page.

Because the store change for the new page but the head is reendered for the old one it gives errors:
```
TypeError: Cannot read property 'id' of null
    at VueComponent.head (_slug.vue:46)
    at Watcher.get (vue.runtime.esm.js:2463)
    at Watcher.evaluate (vue.runtime.esm.js:2563)
    at VueComponent.computedGetter [as $metaInfo] (vue.runtime.esm.js:2807)
```

@alexchopin Could we block rerendering the head in the phase of loading new page?
This would solve the problem.

**Comment by marvinroger** [comment]
Oh my bad, I messed up with two deps. The issue does not appear on `0.10.5` but does on `0.10.6`

**Comment by paulopmx** [comment]
I'm using next 1.4.0 it seems to be still happening
