### ISSUE TITLE
DangerouslyDisableSanitizers not working in modern build

### ISSUE THREAD

**Issue by Breadbuddy** [nuxt/nuxt.js#6249]
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://nolinkneeded.com](https://nolinkneeded.com)

### Steps to reproduce

Load script in default template head config section and set there disableSanitizers for scripts ((I believe it would work the same if placed in nuxt config)). Example:

__dangerouslyDisableSanitizers: ['script'],
        __dangerouslyDisableSanitizersByTagID: {
          'cfg': ['innerHTML'],
          'myLib': ['src']
        },

### What is expected ?

Load my external script "myLib" once when i enter app for first time. Dynamic views should not reload as i have disabled sanitizers.

### What is actually happening?

Code will not work if we get modern build (at least in 'server' mode). My external script called "myLib" will be reloaded again and again on each page change. When i switch off modern build everything works fine and script is loaded once so sanitizers are disabled.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9657">#c9657</a>)</em></sub></div>

**Comment by pimlie** [comment]
Please create a reproduction which shows this happens in modern mode but not in classic mode.

Two remarks:
- Use either `__dangerouslyDisableSanitizers` or `__dangerouslyDisableSanitizersByTagID`, not both. The latter is strongly preferred.
- You can disable reactivity on a tag with [`once`](https://vue-meta.nuxtjs.org/api/#once). But note that this doesnt work when your component gets re-created. This is a catch 20/20 caused by relying on Vue's reactivity, if you really only need it to load once then define it somewhere in your app which doesnt get reloaded (eg nuxt.config)

But these are general remarks and your situation might be different. A repro would help
