### ISSUE TITLE
Missing core-js modules after upgrading to 2.9.1

### ISSUE THREAD

**Issue by command-tab** [nuxt/nuxt.js#6260]
### Version

[v2.9.1](https://github.com/nuxt.js/releases/tag/v2.9.1)

### Reproduction link

[https://github.com/command-tab/nuxt291bug](https://github.com/command-tab/nuxt291bug)

### Steps to reproduce

Upgrade from Nuxt 2.8.1 to Nuxt 2.9.1, `npm i`, then run `npm run dev`

### What is expected ?

A successful Nuxt build and dev server startup

### What is actually happening?

Errors reporting that a bunch of core-js modules are missing. See the README.md in the Reproduction Link for the full error list: https://github.com/command-tab/nuxt291bug/blob/master/README.md

### Additional comments?

I have run `rm -rf .nuxt node_modules package-lock.json` and re-run `npm i && npm run dev` in my actual project and observed no improvement. As well, I've extracted minimal test app which also exhibits the issue.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9663">#c9663</a>)</em></sub></div>

**Comment by pimlie** [comment]
Cannot reproduce this when using `yarn` instead of `npm`, but I can with `npm`. 

Manually installing the corejs runtime resolves the issue: `npm i -D core-js@2 @babel/runtime-corejs2`. Its a bit hidden but this is described in [the release notes of `v2.6.0`](https://nuxtjs.org/guide/release-notes#core-js)

**Comment by command-tab** [comment]
I've been using `npm` exclusively because it's slightly more convenient for my particular production deployment setup. Do you think it's worth switching to `yarn` to avoid dependency issues like this? Do Nuxt developers generally recommend `yarn` over `npm`?

**Comment by pimlie** [comment]
You should use the tool that works best for you, while keeping in mind another exists for when issues like this occurs. Both npm and yarn are good options but both sometimes fail. That said, in my personal experience it seems that stuff like this issue happens a bit less with yarn then with npm.

I am not gonna tell you which one to use, but if you look through the Nuxt eco-system on Github you will probably see `yarn.lock` more often then `package-lock.json` ;)

**Comment by command-tab** [comment]
I'm able to reproduce the error in nuxt 2.10.0 as well as nuxt-edge 2.10.0-26167690.0f8428fa

**Comment by shimy1984** [comment]
Is there a roadmap for corejs 3.x support?

**Comment by sebmor** [comment]
Yeah I still needed to install core-js@2 manually on 2.10.2 to get things working properly.

**Comment by command-tab** [comment]
I'm still able to reproduce the error in nuxt 2.10.2 as well as nuxt-edge@2.11.0-26265609.e7812bdb

**Comment by remychvn** [comment]
> Is there a roadmap for corejs 3.x support?

Core JS 3 is already supported but you need to change your nuxt.config.js according to the releases notes:
https://fr.nuxtjs.org/guide/release-notes/#-code-core-js-3-code-

These will be soon the default settings: https://github.com/nuxt/nuxt.js/pull/6721

**Comment by sdq-sts** [comment]
@remychvn can you paste the code needed here? The link you posted is not working.

**Comment by remychvn** [comment]
> @remychvn can you paste the code needed here? The link you posted is not working.

Yes absolutely ! 😃 

`nuxt.config.js`

```
  export default {
  build: {
    babel: {
      presets({ isServer }) {
        return [
          [
            require.resolve('@nuxt/babel-preset-app'),
            // require.resolve('@nuxt/babel-preset-app-edge'), // For nuxt-edge users
            {
              buildTarget: isServer ? 'server' : 'client',
              corejs: { version: 3 }
            }
          ]
        ]
      }
    }
  }
}
```

**Comment by nachogarcia** [comment]
The link doesn't work because it doesn't expand the version notes - look at here under Core-js https://nuxtjs.org/guide/release-notes#v2.6.0

Also, worth noting for someone like my trying to use Promise.allSettled with nuxt, you can add proposals by tweaking the above config to `corejs: { version: 3, proposals: true }`

**Comment by command-tab** [comment]
Still an issue with 2.11.0 release version 😞

**Comment by aparajita** [comment]
Honestly, is it the position of Nuxt to only support yarn 1.x? Because that means you're relying pretty heavily on the specific internal implementation of a specific package manager, which seems quite brittle. I'm betting yarn 2 breaks many of those assumptions, so what will your strategy be then? Just curious.
