### ISSUE TITLE
Nuxt head() does not wait asyncData in server side 

### ISSUE THREAD

**Issue by sagarlava** [nuxt/nuxt.js#6488]
I have a Nuxt code like this
`
    <template>
      <section>
        <div>Hello Nuxt</div>
      </section>
    </template>
    
    <script>
    const fetchTheme = () => {
      return new Promise(function(resolve, reject) {
        setTimeout(() => {
          resolve({
            title: "Fetched Title"
          });
        }, 100);
      });
    };
    
    export default {
      async asyncData() {
        const theme = await fetchTheme();
        return theme;
      },
    
      head() {
        if (this.theme) {
          return {
            title: this.theme.title
          };
        } else {
          return {
            title: "Default title"
          };
        }
      }
    };
    </script>
    
    <style scoped>
    </style>

`

While I do view source, it gives 'Default title' but I need the title fetched from API
Here is Code 

[Code Sandbox](https://codesandbox.io/s/codesandbox-nuxt-esfdr)

**Comment by ash-narola** [comment]
Had same issue where are on dedicated blog page and we need to share blog dynamic content before that we had ready to use meta tags where it can be populated by some live data for that it is resulting in some wait but head() take no arguments for dynamic or any asynchronous event data. even we can't use setTimeout in place of head() please help us with some resolution.

**Comment by ryanweal** [comment]
I was able to get this working by using the head() method inside a child component. The parent component does the asyncData call.

This seems to work fine both when running `npm run dev` and also outputs correctly when you `npm run generate`. Hope this helps!

**Comment by regnoh** [comment]
> I was able to get this working by using the head() method inside a child component. The parent component does the asyncData call.

Can you explain the details, how can you put data to child component. I tried some ways, only if I put data(form api) on route.query, can I make the head dynamic change, other ways such as store, props...can't work(even though 'console.log' show data)

**Comment by ryanweal** [comment]
> Can you explain the details, how can you put data to child component. I tried some ways, only if I put data(form api) on route.query, can I make the head dynamic change, other ways such as store, props...can't work(even though 'console.log' show data)

In the pages/index.vue file I do the asyncData call, which loads the results into the data() function. Inside the template section of that file I load a component which contains the head() function. I pass the data down to the head-component as props so that they are immediately available when the head-component loads. Inside the head-component I register my props in the props array (or object) and I refer to things in the head() function as normal (ie, this.item.title, making sure to use "this" because you are not in the template section).

Hopefully this helps? Sorry if I'm covering too many "obvious" things but it was frustrating to go around in circles figuring this out.

Another thing to consider: make sure you restart the "npm run dev" instance and do a full reload in the browser if you are really wanting to be sure things are working. I suspect that may have also been a factor in getting it going for me but it was awhile ago so it is hard to say what other debugging steps I may have taken. Good luck!

**Comment by regnoh** [comment]
Ryan Weal，thanks for your reply. I will try npm run dev tomorrow. Today I found that if i use context.$axios rather than app.$axios in asyncdata(), I could get the head change. Thanks again.

---Original---

**Comment by ryanweal** [comment]
> if i use context.$axios rather than app.$axios in asyncdata()

Interesting. I appear to be using context.$axios in my code as well so that sounds right to me. Good to hear you got it working!
