### ISSUE TITLE
Copy-Webpack-Plugin can not work?

### ISSUE THREAD

**Issue by chuoke** [nuxt/nuxt.js#6538]
there is my config
```javascript
import path from 'path'
import CopyWebpackPlugin from 'copy-webpack-plugin'

export default {
build: {
 extend(config, ctx) {
      config.plugins.push(
        new CopyWebpackPlugin([
          {
            from: 'node_modules/mavon-editor/dist/highlightjs',
            to: path.join(__dirname, 'static/plugins/highlightjs/')
          }
        ])
      )

      return config
    }
 }
}

```

**Comment by geethikavinam** [comment]
same issue fo me.. any updates?

**Comment by bjwieland** [comment]
Place your config above the extend section in a plugins section. That works fine!

**Comment by danielistyo** [comment]
Same here. I already tried to move it above `extend` section. It doesn't work. I use node 10.17.0 and nuxt 2.11.0

**Comment by underthecocotree** [comment]
Hope this helps someone

```js
import path from 'path'
const CopyPlugin = require('copy-webpack-plugin');

export default {
 build: {
        plugins: [
            new CopyPlugin({
                patterns: [
                    {
                        from: 'src/app',
                        to: path.join(__dirname, 'app/')
                    },
                ],
            })
        ],
    },
}
```

**Comment by sHoskens** [comment]
For anyone else encountering something similar:

I was attempting to copy a few node_modules packages for asynchronous fetching into the output folder, based on this tutorial: http://insightsoftwareconsortium.github.io/itk-js/examples/webpack.html 

My first attempt looked like this:

```
build: {
    plugins: [
      new CopyPlugin({
        patterns: [
          {
            from: path.join(__dirname, 'node_modules', 'itk', 'WebWorkers'),
            to: path.join(__dirname, 'itk', 'WebWorkers'),
          },
          {
            from: path.join(__dirname, 'node_modules', 'itk', 'ImageIOs'),
            to: path.join(__dirname, 'itk', 'ImageIOs'),
          },
          {
            from: path.join(__dirname, 'node_modules', 'itk', 'PolyDataIOs'),
            to: path.join(__dirname, 'itk', 'PolyDataIOs'),
          },
          {
            from: path.join(__dirname, 'node_modules', 'itk', 'MeshIOs'),
            to: path.join(__dirname, 'itk', 'MeshIOs'),
          },
        ],
      }),
    ],
    extend(config, { _isDev, _isClient }) {
      vtkRules.webpack.core.rules.forEach(rule => {
        config.module.rules.push(rule);
      });

      config.module.rules.push({
        test: /\.worker\.js$/,
        use: {
          loader: 'worker-loader',
          options: {
            inline: false,
          },
        },
      });

      config.resolve.alias['./itkConfig$'] = path.resolve(
        __dirname,
        'utility',
        'customWebpackConfig',
        `itkConfigOverride.${process.env.NODE_ENV}.js`,
      );
    },
  },
```
The referenced environment-based config file is, for example:
```
const itkConfig = {
  itkModulesPath: 'http://localhost:3000/itk',
};
export default itkConfig;
```

I integrated this in a previous app based on vue-cli, and everything worked fine. The files just disappeared in the nuxt environment and it was quite hard to find out what happened and even if copy-webpack-plugin ran at all. Moving it between extend or plugins did not seem to have any impact, and webpack bundle analyzer or debug output provided no clues.

Eventually discovered that the issue was __dirname. Nuxt has some weird ideas on what that should be apparently. If I removed it from the 'to' property but not the 'from', like so:

```
patterns: [
          {
            from: path.join(__dirname, 'node_modules', 'itk', 'WebWorkers'),
            to: path.join('itk', 'WebWorkers'),
          },
```

The files got correctly copied to the _nuxt folder. I also had to change the alias config to take the _nuxt folder into account:

```
const itkConfig = {
  itkModulesPath: 'http://localhost:3000/_nuxt/itk',
};
export default itkConfig;
```

Very specific case, but I hope it helps someone out down the line!

**Comment by kangchals** [comment]
I tried and below are some tips.
- Webpack version of nuxt is 4 so copy-webpack-plugin also need to be 4.6.0.
- ` build: {
    plugins: [
      new CopyPlugin([ // array required
          {
            from: '',
            to: path.join(__dirname, '')
          }
        ]
      )
    ]
  }`
