### ISSUE TITLE
Plain object state management causes mismatch between client and server rendered content with async work

### ISSUE THREAD

**Issue by theomjones** [nuxt/nuxt.js#6875]
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://codesandbox.io/s/gallant-cache-tqcpk?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/gallant-cache-tqcpk?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

I'm attempting to initialise some state using basic state management with a plain object (the reference being shared across components).

I want to initialise the state on the server with some async work, e.g. networking. This causes a mismatch between client and server node trees. I'm not sure how to solve it or if there's a better way of doing it. I've tried it in asyncData/fetch methods as well as the created hook but both result in the same outcome. I assume it's because the DOM tree is being constructed concurrently to asyncData/fetch method? Therefore when those promises have resolved, it will result in more nodes being present which will be different to what we see on the client...?

Check the code sandbox for reproduction.

- Create plain object for sharing state
- Add the object to data function
- Try to render something in template using that state.
- In asyncData or fetch methods try to initialise some state by accessing network or faking it.
- See the console errors

### What is expected ?

- I'd expect that the component is built on the server to match that on the client, even if I'm changing what the node tree might look like via changing state in asyncData or fetch methods. Not sure if I _should_ be expecting this though...

### What is actually happening?

A mismatch between server and client so can't hydrate.

### Additional comments?

As I said I'm not sure if this would be the correct way to achieve this.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10205">#c10205</a>)</em></sub></div>

**Comment by ncolletti** [comment]
Hey @theomjones  -- Had some time to look into this and was able to achieve what you are looking for. It doesn't seem to be a bug with Nuxt, there are just some slight configuration changes needed in your project. I followed the [Nuxt Vuex guide]( https://nuxtjs.org/guide/vuex-store)

The big changes were:

- Moving your shared-state.js file into store/index.js
- Using the Vuex module system to separate the todo state into store/todo.js
- Vue prefers to use commit / dispatch methods on store actions
- Vuex uses mutations to alter state within the state object instead of just accessing the object
- fetch needed state args to be passed through for us to manipulate from within the index.vue default page of the app 

Here is a fork of your codesandbox link that I worked on where you can see the code and this working properly. I also added the wait() async functionality on the addTodo so you can see how component/state interacts with these methods after server render:
https://codesandbox.io/s/purple-breeze-5u7ds

Let me know if this helps! 😁

**Comment by theomjones** [comment]
@ncolletti - Hi, thanks for your input. This isn't a resolution to the issue I reported you've just changed the implementation to Vuex which isn't what I'm trying to do. 

Thanks for your help though.

**Comment by aldarund** [comment]
The thing is that your custom state isnt serialized to client. Because you are filling it in fetch. And the only place where its stored is in that separate file. So nuxt have no idea it should be serialized.  Its not in nuxt render context

https://github.com/nuxt/nuxt.js/blob/af75aa86e1724a29c0e63b82b15cdb29e500f4a3/packages/vue-renderer/src/renderers/ssr.js#L138

**Comment by theomjones** [comment]
@aldarund - thanks for explaining. Do you know of a way of making nuxt aware of this state? It needs to be able to be fetched asynchronously. The reason for not using vuex is because it's not global state and there needs to be multiple instances of this state.

**Comment by aldarund** [comment]
>and there needs to be multiple instances of this state.

Are you that u are doing it right then? Your state will be shared on server for every client. 
And not quite get why vuex wont work? What stop you from creating multiple copies of objects inside vuex state?
