### ISSUE TITLE
Nuxt route meta is inaccessible inside Vue navigation guards

### ISSUE THREAD

**Issue by mzenz** [nuxt/nuxt.js#6915]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/github/mzenz/nuxt-router-meta](https://codesandbox.io/s/github/mzenz/nuxt-router-meta)

### Steps to reproduce

- Run 'yarn start' 
- Navigate to webpage (route '/')
- Look at console and observe that meta info is accessible inside middleware but not inside beforeEach() navigation guard.

### What is expected ?

Since Nuxt doesn't allow manually configuring Vue routes, each route's meta info should be accessible inside Vue's navigation guard beforeEach(), not just middleware.

### What is actually happening?

The page's meta info set inside 'pages/index.vue' is inaccessible inside Vue's router.beforeEach() navigation guard.

### Additional comments?

Please note that using a middleware is not a valid replacement for Vue.router.beforeEach() since redirection inside a middleware happens asynchronously, causing the destination route to render before redirection actually happens (unlike router.beforeEach() which works synchronously, allowing cancelling navigation before the destination route gets to render).

Upon closer inspection it looks like Nuxt's route meta mechanism is not the same as Vue router's meta, which is both misleading and constraining for the above reasons. I would hope Nuxt was able to expose the "native" meta mechanism instead of bypassing it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10235">#c10235</a>)</em></sub></div>

**Comment by IanAtDazed** [comment]
Completely agree with mzenz. It is "misleading and constraining"

I'm guessing Nuxt approaches this differently due to its ability to server-side render in 'universal' mode. However, it would be extremely beneficial if the 'native' Vue mechanism, would at least work as Vue intended when a project is configured for 'spa' mode.

I moved, from Vue, to Nuxt, in order to benefit from the extra 'bells & whistles', and although overall I am very pleased with that decision, this piece caused me real headaches (to hack a solution to), when in Vue, it was absolute simplicity!

**Comment by washanhanzi** [comment]
The page meta should be merged into `vue route`, it is really important for a generated static site. Now it's only available in `middlewares`.

**Comment by manniL** [comment]
@washanhanzi feel free to create a new issue / feature request
