### ISSUE TITLE
Global SCSS

### ISSUE THREAD

**Issue by fredckl** [nuxt/nuxt.js#6931]
Hi,

I am having a problem with global scss. When I define .nuxt-active-link or .page-enter-active, etc ..., it is not compiled when I run the nuxt build command.
Anyone know why?
Thank you

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10251">#c10251</a>)</em></sub></div>

**Comment by msacchetti** [comment]
I had a similar issue where certain css classes from my global scss file were not compiling into my prod build. I figured out that if the HTML element was not present on initial load (like if a div with class box was initially hidden with a v-if conditional) the .box class in global.scss would not compile.

 If I took the div class=box out of the v-if conditional so it was present on initial load the style would be complied from global.scss.

I found two solutions: 
1) move those styles into the main "default layout" component but that was annoying.
2) make an unused layout in /layouts/ called blah.vue and add empty divs with those classes that aren't being compiled. So my unused layout file had a `<div class=box></>` in it. Nuxt then recognizes that style being used and then compiles it from global.scss


This is super annoying and I think is a bug. I asked this question before and nobody responded so I just went with solution 2 because there were only a small handful of classes I needed
