### ISSUE TITLE
Undefined added at the end of every url

### ISSUE THREAD

**Issue by adrianwix** [nuxt/nuxt.js#7069]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/adrianwix/bug-nuxt-2.11](https://github.com/adrianwix/bug-nuxt-2.11)

### Steps to reproduce

- Yarn install
- Yarn run dev
- Open localhost:3000
- Open the console (I use Chrome)
- You should notice `GET http://localhost:3000/undefined net::ERR_ABORTED 404 (Not Found)`
- Travel to `/products/:product` (eg `products/car`)
- You should notice in the console `Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:3000/products/undefined".`
- In the node.js's server console you should see `Product hola. Product undefined`. 

### What is expected ?

There should not be any undefined at the end of the URL

### What is actually happening?

There is an undefined been appended at the end of the url

### Additional comments?

This happened after migrating from Nuxt 2.0.0 to 2.11.0. The problem is specially obvious in the home page. I tried to replicate as much as possible from the original repo (private). 

In the original repo if I have a URL like `products/:product` when I refresh the page and get a similar error  `GET http://localhost:3000/products/undefined net::ERR_ABORTED 404 (Not Found)`, which consequently triggers a type error because the parameter is undefined.
You can see the working page before the update here https://www.primasalud.xyz/.

Must be noted that travelling between pages does not trigger the error. Only when the page is being refreshed. So probably is a server-side error.

I hope I provided enough information. Thanks for helping in advance

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10374">#c10374</a>)</em></sub></div>

**Comment by movepixels** [comment]
I have same issue (v 2.12.0) and thought I was going crazy. I noticed its a 404 on a style sheet and the rendered HTML for me looks like:
```
<link data-n-head="ssr" rel="stylesheet" type="text/css" href="undefined">
```

I only have 1 style sheet defined in nuxt.config.js and thats working so no idea where this mystery ghost stylesheet is coming from.

Any help / ideas / suggestions.

**Comment by movepixels** [comment]
Ok I noticed (for me) the 404 was always happening after Dev Tools > Network line => css?family=Roboto:100,300,400,500,700,900&display=swap

So I did a quick find and sure enough in .nuxt/index.js is a line from the production build that follows the find that looks like
```
{"rel":"stylesheet","type":"text\u002Fcss","href":undefined}
```

I simply deleted that bit and error is now gone.

No clue why its getting put in there, but for now this is what I have done. Not a solution by any means as its only a temp solve, but for now. I will keep checking but I assume its a Vuetify plugin issue somewhere since I am not evening using Roboto font and Vuetify uses it as @nuxtjs\vuetify\dist\font.js line 2 has 
```
const family = `${options.family}:100,300,400,500,700,900&display=swap`;
```
And since a find for "display=swap" only found in this 1 file its safe to start trying to figure out from this point forward.
