### ISSUE TITLE
Bootstrap Vue Navbar Dropdown Not Working After Nuxt Generate But Works In Nuxt Dev

### ISSUE THREAD

**Issue by humbertoT2** [nuxt/nuxt.js#7075]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/humbertoT2/bootstrap-gen-test.git](https://github.com/humbertoT2/bootstrap-gen-test.git)

### Steps to reproduce

Building a webpage with Nuxt JS and Bootstrap Vue—Navbar dropdown functionality works as expected in dev mode but does not work when generated to static files. Clicking a dropdown item does nothing in the static files but drops down properly in development mode. 

Running npm run generate outputs expected static files with 0 errors but functionality is missing in navbar dropdown. 

> Steps to reproduce the bug

1. Clone my demo project: https://github.com/humbertoT2/bootstrap-gen-test.git

`cd /bootstrap-gen-test/
npm install
npm run generate
`
2. Open index.html in bootstrap-gen-test/dist
3. Click dropdown items in the bootstrap vue nav - they do not dropdown but html and css is loaded.

If you do not want to clone the project you can do the following. 

1. I generated this project from nuxtjs get started page with:
npx create-nuxt-app <project-name>

2. Simply choose bootstrap as your UI framework in the setup process

3. Add example dropdown nav code from bootstrap vue component docs in index.vue: 
4. npm run generate
5. open index.html in your-project-name/dist/

> Expected behavior

Navbar dropdown item functionality to work (dropdown) in static file setting

> Versions

nuxt: ^2.0.0
bootstrap-vue: ^2.0.0
bootstrap: ^4.1.3

**Environment:**

- Device:  Macbook
- Browser: Chrome

> Demo link

See below for a copy of my dist and navbar component in a static file

https://t2hwp.t2marcom.com/bootstrapvue/dist/index.html

### What is expected ?

Navbar dropdown from bootstrap vue to dropdown

### What is actually happening?

No dropdown is happening

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10377">#c10377</a>)</em></sub></div>

**Comment by azrikahar** [comment]
After you ran `npm run generate`, instead of opening the index.html directly, you should try using the `npm start` command instead to test your generated page(s).

The reason why your current copy as a static file [over here](https://t2hwp.t2marcom.com/bootstrapvue/dist/index.html) doesn't work is because the JS file inside the _nuxt folder are not served. You can verify this by:

1. Going to [your index page](https://t2hwp.t2marcom.com/bootstrapvue/dist/index.html)
2. Click on the dropdowns (and they should not work)
3. Open the Chrome DevTools (should be fn + F12 for mac)
4. On the Console tab, you can see there are multiple errors saying that the JS files are not found.

I have also downloaded your repo and verified using `npm run generate` + `npm start` that your project indeed works as usual once you have the JS files served.
