### ISSUE TITLE
Routes generation params and redirects

### ISSUE THREAD

**Issue by KonstantinVlasov** [nuxt/nuxt.js#710]
Hi, guys!

I have two issues with routes:
1.  All parameters generated as optional, even with index.vue files
pages:
![pages](https://cloud.githubusercontent.com/assets/2950641/25997615/6f891728-3725-11e7-9048-d33af5b99528.png)
generated routes:
![routes](https://cloud.githubusercontent.com/assets/2950641/25997650/9d0a8c40-3725-11e7-9a2d-6c123ddaf694.png)

2. extendRoutes option lead to empty import
I'm trying to add redirects like:
![extendroutes](https://cloud.githubusercontent.com/assets/2950641/25997706/f42edcd8-3725-11e7-9163-2f09ef7c4a2e.png)
and generated routes.js looks like:
```
const _29172c1a = () => import('' /* webpackChunkName: "pages/" */)
...
{
	path: "/icon",
	component: _29172c1a
},
{
	path: "/icon/new-icons",
	component: _29172c1a
}
```
and when I use 'npm run dev' I got:
```
This dependency was not found:
*  in ./.nuxt/router.js
To install it, you can run: npm install --save
```
Using nuxt 0.10.7

**Comment by Atinux** [comment]
Hi @KonstantinVlasov 

You cannot create route with `redirect`, instead, create a middleware for it which check the `route.path` to call `redirect` directly.

**Comment by KonstantinVlasov** [comment]
Thank you!

**Comment by andrade1379** [comment]
@Atinux I have a similar problem and I created a middleware but that does not work... Some background:

My site is static and we had a redirect set on the server and since been removed BUT some users might have had `/index.html` cached due to that redirect being `301`. So when someone visits my site they might get: http://mysite.com/index.html This causes an error due to page not being found. Is there a way I can check for that in the url before anything else happens?
