### ISSUE TITLE
Fetch in production truncate "this" reference properties

### ISSUE THREAD

**Issue by asterd** [nuxt/nuxt.js#7138]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://codesandbox.io/s/elegant-brattain-6x5gl](https://codesandbox.io/s/elegant-brattain-6x5gl)

### Steps to reproduce

Create a simple nuxt application with some plugins, create a page with new fetch api and try to use the plugin in the fetch method.
When compiled in dev, the this reference in fetch brings all it's properties (plugins, modules, mixins, etc). When compiled in prod, the 'this' reference lose all its props and maintains only the page structure (name, data, methods, computed, etc) but not refs to $axios or $vuetify or any other plugin.

### What is expected ?

The this reference in prod behave as in dev

### What is actually happening?

the this reference is "truncated"

### Additional comments?

I can't find a way to debug this on project because in production mode neither debugger nor console log works to me

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10445">#c10445</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @asterd thanks for reporting the issue. I tried the following steps:

- Add `plugins/test.js` and registered in `nuxt.config.js`:

```js
export default function (ctx, inject) {
  inject('test', () => Promise.resolve('plugin works'))
}
```

- Used in one of the pages, with new fetch method:

```js
export default {
  async fetch () {
    this.res = await this.$test()
  },
  data () {
    return {
      res: '...'
    }
  }
}
```

- Build with production mode: `nuxt build`
- Start in production mode `nuxt start`

And seems working. Would you please create a sample repro with [codesandbox](https://codesandbox.io/s/github/nuxt/codesandbox-nuxt/tree/master/) or somehow give access to your current project? Otherwise, it is hard to diagnose the problem.

**Comment by asterd** [comment]
Hi @pi0, thanks for your answer.
I've created an example of something like my code in this sandbox:

https://codesandbox.io/s/elegant-brattain-6x5gl

I don't be able to do a nuxt build but maybe you can do it.
My difference is probably in the nuxt.config.js configuration and I want to understand what is the cause of this "crop".. because I've tested in a lot of way and if I change the fetch with asyncData,all works as expected, when i put async fetch, it fails!

**Comment by pi0** [comment]
Hi @asterd I tried forking code sandbox. The issue is it was using nuxt 2.6.x after upgrading to 2.12 it works fine. I suggest cleaning up `.nuxt` , `yarn.lock` and `node_modules` also clean CI/CD caches if using. It should then go fine. To ensure make attention to production server banner:

![image](https://user-images.githubusercontent.com/5158436/78016352-f9909e00-734a-11ea-8a4a-72bab648c5f2.png)

**Comment by asterd** [comment]
Hi @pi0 unfortunately, the problem is not with codesandbox.. the problem is with my production env that has nuxt 2.12.1 installed from scratch and a config like the one I share... and the strange thing is the very different behavior between test and prod compilation (eg also the strip of console.log in nuxt code...)

**Comment by pi0** [comment]
@asterd I really want to help but without reproduction, it is not really possible. Do you mind sending me a DM in discord? We can go more in-depth through this and share outcome here :)

**Comment by asterd** [comment]
Thanks to @pi0 and it's suggestions I've found the problem: it was related to pm2 and reverse proxy cache and not to nuxt itself.  Thanks a lot for the support.
