### ISSUE TITLE
HMR for serverMiddleware fails if sub-app is registered without prefix

### ISSUE THREAD

**Issue by denilsonsa** [nuxt/nuxt.js#7145]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://codesandbox.io/s/nuxt-hmr-servermiddleware-bug-8v1pz](https://codesandbox.io/s/nuxt-hmr-servermiddleware-bug-8v1pz)

### Steps to reproduce

1. Open <https://codesandbox.io/s/nuxt-hmr-servermiddleware-bug-8v1pz>
    * I've created a minimal testcase that shows the issue.
    * You may need to fork the codesandbox, or download the files. In that case, run the nuxt dev server.
2. On the "browser preview" pane, click on the button.
    * That button will fetch the `/api` endpoint, implemented in a server middleware.
    * Alternatively, just open that URL directly on the browser.
3. Observe how it returns HTTP 200 response with the proper response body.
4. Open the `server_middleware/api.js` file and edit anything in there.
5. Save. Observe how nuxt detects the change and hot-reloads the module (and prints `HMR` on the terminal).
6. Click on the button again.
    * Or just try fetching `/api` endpoint again.

### What is expected ?

It should just work, with the new hot-reloaded code.

### What is actually happening?

It returns 404 not found.

This shows the HMR of server middlewares is not working correctly.

As a workaround, we can stop and restart the dev server, and then it works again (until the next HMR).

### Additional comments?

Maybe this happens when other middlewares are hot-reloaded. Maybe this happens more often when the list of middlewares is longer. I don't know what causes it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10450">#c10450</a>)</em></sub></div>

**Comment by pi0** [comment]
Thanks @denilsonsa for proper issue and repro. It seems an interesting issue. It is happening because connect removes trailing slash [src](https://github.com/senchalabs/connect/blob/master/index.js#L102):

![image](https://user-images.githubusercontent.com/5158436/77799391-fceb0780-7074-11ea-832c-7dfa1eb7fd38.png)


so when you register API and on first HMR a mismatch happend. I would suggest to simply expose prefix to default export of `app.js` like this:

```js
const app = connect()

export default {
  path: '/api',
  handler: app
}

app.use("/", function(req, res, next) { ...
```

This is also much better for performance as API middleware will be called only for /api/* routes.

I will try to investigate more for a possible edge case fix.

**Comment by pi0** [comment]
Update: #7146
