### ISSUE TITLE
new fetch with keep-alive being fetched while keeped-alive

### ISSUE THREAD

**Issue by MLDMoritz** [nuxt/nuxt.js#7156]
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

https://codesandbox.io/s/youthful-archimedes-l3by4

### Steps to reproduce

When you use the new fetch with `<nuxt keep-alive>` and a query watcher this watcher is called even though the component is not active (but keeped-alive)

### What is expected ?

It should not fetch

### What is actually happening?

It fetches on every route change

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10459">#c10459</a>)</em></sub></div>

**Comment by Atinux** [comment]
Please create a reproduction by forking https://template.nuxtjs.org

**Comment by MLDMoritz** [comment]
https://codesandbox.io/s/youthful-archimedes-l3by4

Fetch should only occur on index route, to see the problem please navigate forth and back on the About page.

**Comment by aaronransley** [comment]
Bump, running into this as well.

**Comment by enkot** [comment]
@Atinux, The same problem when use:
```js
watch: { 
  '$route.query': '$fetch' 
}
```
Reproduction link: https://codesandbox.io/s/elated-smoke-ht94h

It seems that `$fetch` runs for any route change, not only on current page query change. Check console and you will see "fetched" message while navigating between pages.

**Comment by Atinux** [comment]
Hi there, sorry for the delay.

Actually, it's directly due to Vue & Vue-Router watch system, it seems that watch on `$route.query` is triggered for any route changes (even if query is still the same...).

When you call `$fetch`, it won't care if you are using a keep-alive. It's only when doing navigation that it won't call `fetch` because the component is cached.

One solution would be to check if the query has changed, we can do this by using `JSON.stringify`:

```js
watch: {
    '$route.query': function(newQuery, oldQuery) {
      if (JSON.stringify(newQuery) !== JSON.stringify(oldQuery)) {
        console.log('Query changed')
        this.$fetch()
      }
    }
  }
```

Then, it seems that the function is called when leaving the page (because of `keep-alive`), you can check `this._inactive` to know if the component is inactive to avoid triggering fetch again:

```js
watch: {
    '$route.query': function(newQuery, oldQuery) {
      if (this._inactive === false && JSON.stringify(newQuery) !== JSON.stringify(oldQuery)) {
        console.log('Query changed')
        this.$fetch()
      }
    }
  }
```

One solution would be to directly watch the property you want to watch in `$route.query`:

```js
watch: {
    "$route.query.test": function(newQuery, oldQuery) {
      if (this._inactive === false) {
        console.log("Query changed");
        this.$fetch();
      }
    }
  },
```

Demo: https://codesandbox.io/s/empty-dream-xqjgv?file=/pages/test/index.vue

**Comment by MLDMoritz** [comment]
To be honest, this is not a solution, this is a workaround that will brick in the next release...

**Comment by Atinux** [comment]
You can always open an issue on vue-router repo since it's actually not directly related to Nuxt.

**Comment by enkot** [comment]
@Atinux Thanks for showing the right direction!

I found that the same router behaviour discussed in this issue - https://github.com/vuejs/vue/issues/5477. 
Maybe the cleaner solution would be using `activated`, `deactivated` lifecycle hooks:
```js
export default {
  data() {
    return {
      isActive: true
    };
  },
  watch: {
    "$route.query"() {
      if (this.isActive) this.$fetch()
    }
  },
  async fetch() {
    // ...
  },
  activated() {
    this.isActive = true
  },
  deactivated() {
    this.isActive = false
  }
}
```
In real world app it can be refactored using a mixin or composition api.
