### ISSUE TITLE
Generate: Meta and Embed Only config option

### ISSUE THREAD

**Issue by xeno** [nuxt/nuxt.js#7253]
### What problem does this feature solve?

Currently, each generated route contains page level CSS, HTML markup and data. Footers, headers, etc all repeat in each file. This leads to large file sizes for the repository which can be cumbersome to upload (my site generates 11GB of data for each build). When trying to generate large amounts of routes, this is not only a hindrance in generation speed, but also upload speed.

### What does the proposed changes look like?

I propose a config boolean in generate called metaOnly, which would generate the head/meta data only, as well as embed the SPA. Maybe a <generate-only> component to go with it, which would receive the payload, in case the user also wants to add some amount of pre-loaded content.

This method would allow faster generation in both file writes but also in the database queries etc used for payloads.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10550">#c10550</a>)</em></sub></div>

**Comment by pimlie** [comment]
Thanks for the suggestion, but I dont think this approach will give any benefits. If you care about SEO then your html content is as important as the meta tags, so you really should prerender those too.

Also I dont think this will result in a significant performance boost as due to how vue-meta works (and will keep working) all your Vue components needs to be fully created on SSR to determine which meta tags to use. This step is more perf intensive then the next step of rendering the html. In my experience the slowest step in generation is always calling your API, eg I assume you are using dynamic routes which are populated from an API call because of the large amount of data.

One tip I can give is to make sure to disable html minification when generating a lot of pages, this can result in a perf boost of up to 50%. Before disabling you should compare yourself what html the minification 'fixes' and try to fix your components to that and if you are unable to accept that the html isnt 'optimal'.

Also, if 11GB is too much just gzip all your pages after generating completes (`find ./dist -iname '*.html' -exec gzip {} \;` and make sure your webserver/proxy is configured to gunzip these pages to clients that dont support compression. But that is out of scope for this issue tracker ;)

**Comment by xeno** [comment]
@pimlie I am, and it does speed up route generation on my home computer, but my build setup (netlify) doesn't benefit from it. My site generates about 50k routes, most of them very simple pages, and it can take upward of 20 minutes. I have minification completely disabled.

Another idea would be incremental builds, which I've seen Nuxt has mentioned on twitter a few years ago but hasn't been introduced. Next and Gatsby both offer this feature, but that's off topic. Thank you for your feedback.

**Comment by xeno** [comment]
Another idea would be to take the global CSS and link it from each file instead of embedding it. Each of my 50,000 routes has the entire bootstrap library embedded in it. It's really weighing it down.

**Comment by manniL** [comment]
Highly agree with @pimlie here. The only possible benefit I see in such an option is that sharing previews are now working as wanted when using an SPA (at least for sites without dynamic titles/descriptions).

**Comment by pimlie** [comment]
@xeno Depending on your development setup you could also use CircleCI for CD and then just push the static files to Netlify from their platform. With CircleCI you can choose to have your deployment run with up to 20 cores

**Comment by xeno** [comment]
@pimlie thanks for the heads up. For the record, I got netlify to work by using extractCSS. It changed my output size from 11GB to 360MB, which made the upload process obviously a lot faster. And I can get the ~50k routes done in quiet mode.

I may use CircleCI anyways, though. Thanks again everyone.
