### ISSUE TITLE
Incorrect router generation for optional parameters

### ISSUE THREAD

**Issue by SebastiaanYN** [nuxt/nuxt.js#7298]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[http://localhost](http://localhost)

### Steps to reproduce

I have the following pages directory structure:
```
pages/
    nested/
        index.vue
    _key.vue
```

The generated router configuration is as follows
```js
  routes: [{
    path: "/nested",
    component: _7778415c,
    name: "nested"
  }, {
    path: "/:key",
    component: _f8b0477c,
    name: "key"
  }],
```

I would expect the generated router configuration to have `_key.vue` with an optional argument

When the directory structure doesn't contain the nested folder the `_key.vue` does get an optional argument
```
pages/
    _key.vue
```

```js
  routes: [{
    path: "/:key?",
    component: _f8b0477c,
    name: "key"
  }],
```

### What is expected ?

`_key.vue` gets an optional argument

### What is actually happening?

`_key.vue` is getting a required argument

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10600">#c10600</a>)</em></sub></div>

**Comment by silverbackdan** [comment]
Additionally I have the following page structure
```
pages/
    toolkits/
        workforce/
            _category/
                index.vue
```

And this should provide a required argument for `_category` however this is the output

```js
{
    path: "/toolkits/workforce/:category?",
    component: _10f10a5c,
    name: "toolkits-workforce-category"
}
```

I expect to have

```js
{
    path: "/toolkits/workforce/:category",
    component: _10f10a5c,
    name: "toolkits-workforce-category"
}
```

**Comment by pimlie** [comment]
This is because `nested/index.vue` is the same as `nested.vue`. Allthough the docs speak about adding a `index.vue` to make the param required, it looks like it should say _any_ other route on the same level. `nested/index.vue` is on the same level.

If instead you would add `nested/_nestedKey.vue` then that route is not on the same level and the first route will have an optional param again.

**Comment by SebastiaanYN** [comment]
> This is because `nested/index.vue` is the same as `nested.vue`. Allthough the docs speak about adding a `index.vue` to make the param required, it looks like it should say _any_ other route on the same level. `nested/index.vue` is on the same level.

I think this doesn't make a lot of sense. `_key.vue` and `nested/index.vue` shouldn't be on the same level, as `index.vue` is inside another folder. If `nested.vue` is on the same level as `_key.vue` router generation works fine.

```
pages/
	nested.vue
	_key.vue
```
gives
```
/nested
/:key?
```


> If instead you would add `nested/_nestedKey.vue` then that route is not on the same level and the first route will have an optional param again.

This doesn't result in the behavior I'm looking for, because it adds a slug where there shouldn't be one.

```
pages/
	nested/
		_test.vue
	_key.vue
```
gives
```
/nested/:test?
/:key?
```

---

The router structure I'm after is
```
/nested
/nested/test
/:key?
```
and I would expect that to be accomplished by
```
pages/
	nested/
		index.vue
		test.vue
	_key.vue
```

**Comment by pimlie** [comment]
Let me copy my comment from the linked issue ;)
---
Unfortunately using the file system to define your app routes comes at a cost, this is unfortunately one of them.

You can always 'hack' your way around the auto populated routes object yourself, either by using the [router-extras-module](https://github.com/nuxt-community/router-extras-module) or by manually manipulating the routes through [extendRoutes](https://nuxtjs.org/api/configuration-router#extendroutes)

**Comment by SebastiaanYN** [comment]
Is there a case where it's actually useful that an `index.vue` file in a nested folder makes a slug in the folder above required? To me, it seems like it's strange behavior that can be changed, but I could be missing something.

**Comment by pimlie** [comment]
Im not totally sure what the logic behind it is, but I agree it seems there might be an issue here. Either with the routing logic or at least with the docs.

The main problem with 'fixing' this is that any changes to the routing logic will probably [break](https://xkcd.com/1172/) someones workflow at the moment. So we can only do that for v3. I believe a revamp for the routing logic is already planned for v3 (also because of changes/new features that vue-router provides). Although I cant promise we will look at this issue specifically, Im sure we will improve the routing logic and make it more consistent.
