### ISSUE TITLE
Get the access-token and set it to the request header on ~plugins/axios.js

### ISSUE THREAD

**Issue by axu6705** [nuxt/nuxt.js#736]
In the refresh when i need to get `Access-Token` from the cookie or request header.

**Can i get the context?**

```js
import { getTokenFromHeader,  getTokenFromCookie } from '../utils/auth'
import axios from 'axios'

let loggedUser = context.isServer ? getTokenFromHeader(context.req) : getTokenFromCookie()
let options = {
  baseURL: 'https://example.com/api/v1',
  headers: {
    'Access-Token': loggedUser ? loggedUser.AccessToken : ''
  }
}
export default axios.create(options)
```

Someone to help? Thanks!

**Comment by axu6705** [comment]
@Atinux @alexchopin  help me~(⊙o⊙)

**Comment by pi0** [comment]
Hi @axu6705. This is not a you can export a method like `setToken` in axios plugin ([like this](https://github.com/nuxt/nuxt-modules/blob/master/modules/axios/plugin.js#L113)) and then call it from where needed (like [this](https://github.com/nuxt/nuxt-modules/blob/master/modules/auth/store.js#L53))

**Note** Such usage is for current Nuxt version and is subject to change starting from next Nuxt release. Because plugins should export a function which will accept context as well :)

**Comment by axu6705** [comment]
@pi0 Thanks!
