### ISSUE TITLE
rewrite Router.prototype.push lead to memory leak

### ISSUE THREAD

**Issue by tangdada** [nuxt/nuxt.js#7479]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://codesandbox.io/s/lingering-dew-wfjy9?file=/nuxt.config.js](https://codesandbox.io/s/lingering-dew-wfjy9?file=/nuxt.config.js)

### Steps to reproduce

1. I use `wkhtmltopdf` to generate pdf
2. call  `wkhtmltopdf localhost:3000 ./temp/out.pdf` in terminal constantly

### What is expected ?

![before.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/25a48e30-a95f-11ea-b7f8-5d30573d8cf5.png)

### What is actually happening?

![after.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/2987bbd0-a95f-11ea-b7f8-5d30573d8cf5.png)

### Additional comments?

I used `heapdump` to find out the reason of this problem in `.nuxt/router.js`

```
// TODO: remove in Nuxt 3
const emptyFn = () => {}
const originalPush = Router.prototype.push
Router.prototype.push = function push (location, onComplete = emptyFn, onAbort) {
  return originalPush.call(this, location, onComplete, onAbort)
}
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10742">#c10742</a>)</em></sub></div>

**Comment by clarkdo** [comment]
Hi @tangdada , thanks for the issue reporting.

From the screenshot for that issue, we can't say it's a memory leak, because 200mb may not reach GC threshold, we need to make sure if the memory can return to a stable value after GC, like from `80mb -> 400mb -> 90mb -> 400mb -> 85mb....`

Can you try to keep generating pdf for a while and monitor the memory change ? If there is memroy leak, the memory will be keep increasing and not reduced to a proper value, finally browser will be crashed when memory exceeds heap size.

If the memroy leak happned by testing with above way, can you please send us 2 heap snapshots before and after gs ?

**Comment by tangdada** [comment]
> Hi @tangdada , thanks for the issue reporting.
> 
> From the screenshot for that issue, we can't say it's a memory leak, because 200mb may not reach GC threshold, we need to make sure if the memory can return to a stable value after GC, like from `80mb -> 400mb -> 90mb -> 400mb -> 85mb....`
> 
> Can you try to keep generating pdf for a while and monitor the memory change ? If there is memroy leak, the memory will be keep increasing and not reduced to a proper value, finally browser will be crashed when memory exceeds heap size.
> 
> If the memroy leak happned by testing with above way, can you please send us 2 heap snapshots before and after gs ?

thank you for your reply, I will close this issue and do further analysis.
