### ISSUE TITLE
$route.$query will be empty with "target:static"

### ISSUE THREAD

**Issue by simplenotezy** [nuxt/nuxt.js#7572]
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://codesandbox.io/s/practical-fog-djg3u?file=/pages/index.vue](https://codesandbox.io/s/practical-fog-djg3u?file=/pages/index.vue)

### Steps to reproduce

1) Set "target: static" in nuxt.config.js
2) Set `console.log('query', this.$route.query);` in created/mounted hook
3) Go to any url with a query parameter, e.g: https://djg3u.sse.codesandbox.io/?hello=world

### What is expected ?

pages/index: Created! 
Object {hello: "world"}

### What is actually happening?

pages/index: Created! {} 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10820">#c10820</a>)</em></sub></div>

**Comment by pi0** [comment]
Hi @simplenotezy. Actually it is intentionally disabled only for server-side. If you check codesandbox "console' tab, logs are correct:

![image](https://user-images.githubusercontent.com/5158436/85220849-351d9000-b3af-11ea-9c37-6ce7ac1eab23.png)

I would suggest not using any query dependent code inside `created` (`mounted` is fine) because SSR process for static target only happens once without considering the query params.

**Comment by simplenotezy** [comment]
Thanks @pi0 :)
