### ISSUE TITLE
Adding babel plugin @babel/plugin-proposal-nullish-coalescing-operator

### ISSUE THREAD

**Issue by rstormsf** [nuxt/nuxt.js#7822]
I'm adding 
nuxt.config.js
```
build: {
  babel: {
      plugins: ['@babel/plugin-proposal-nullish-coalescing-operator', '@babel/plugin-proposal-optional-chaining']
  }
}
```
### Versions

- nuxt: 2.12.2
- node: 10

### Reproduction

when I add `yarn add module-with-nullish coalescing operator` I still get an error:

You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by manniL** [comment]
Please provide a reproduction. As showcased on https://twitter.com/TheAlexLichter/status/1058296116876320769, adding the plugins is working as expected 😋

**Comment by rstormsf** [comment]
@manniL try adding: `npm i fixed-merkle-tree@0.1.0` and apply plugins. it won't work

**Comment by manniL** [comment]
> @manniL try adding: `npm i fixed-merkle-tree@0.1.0` and apply plugins. it won't work

I've updated all dependencies in the codesandbox to the latest version and it still works as expected (same link).

If you use packages with "upcoming" syntax, you have to add them to `build.transpile` so that the code will be properly transpiled. You don't even need the babel plugins for nullish coalescing and optional chaining therefore because they are already included in the preset-env by now.

**Comment by rstormsf** [comment]
@manniL I'm using 2.13.0 nuxt version. I don't understand how you made it work.

**Comment by husayt** [comment]
There is indeed a problem and it might be the same as [this one](https://github.com/nuxt/nuxt.js/issues/7722)
