### ISSUE TITLE
Customize webpack to obfuscate CSS classes

### ISSUE THREAD

**Issue by frbuceta** [nuxt/nuxt.js#7851]
### Versions

- nuxt: v2.14.0
- node: v14.7.0

### Reproduction

https://codesandbox.io/s/dawn-firefly-m0hjs?file=/nuxt.config.js

### Steps to reproduce
We apply the code for webpack in nuxt and we can already see that the classes are not translated but in the CSS they are.
```js
  /*
   ** Build configuration
   ** Doc: https://nuxtjs.org/api/configuration-build
   */
  build: {
    /*
     ** You can extend webpack config here
     */
    extend(config, { isClient, isDev, loaders }) {
      if (isClient && isDev) {
        console.log(loaders.css);
      }
    },
    loaders: {
      css: {
        modules: {
          localIdentName: "[sha1:hash:hex:4]"
        }
      }
    }
  }
```

### What is Expected?
You should also translate the class names inside the class attribute

### What is actually happening?
Currently it does not translate the class attribute of each element, it only translates the css

**Comment by danielroe** [comment]
@frbuceta This is expected behaviour. I believe from our conversation on Discord that you are using scoped CSS, but class names are only customisable like this for CSS modules. (See [css-loader options](https://webpack.js.org/loaders/css-loader/).)

I do highly recommend using CSS modules, which you can do easily in Nuxt and which will get you your desired behaviour.

Simply use:
```vue
<template>
  <div :class="$style.myStyle" />
</template>

<style module>
.myStyle {
  // fully scoped CSS
}
</style>
```
The class name in both places will be obfuscated according to the localIdentName you pass in.

**Comment by frbuceta** [comment]
Using the cssModule only the css that I include in the .vue files is obfuscated, the ones that I import are not obfuscated

**Comment by danielroe** [comment]
@frbuceta Are you importing them using CSS module imports ([like this](https://github.com/css-modules/css-modules#dependencies)), or as regular CSS? I suspect the latter.

**Comment by frbuceta** [comment]
> @frbuceta Are you importing them using CSS module imports ([like this](https://github.com/css-modules/css-modules#dependencies)), or as regular CSS? I suspect the latter.

I guess last thing, because it is css that is hosted in npm packages like bootstrap-vue

**Comment by danielroe** [comment]
In order to do what you want, I think you would need to add a custom webpack loader (possibly integrated with vue loader so as to update class names in templates). I think this is probably out-of-scope for Nuxt, although of course such a custom loader could easily be *used* in Nuxt by customising the webpack config.

**Comment by frbuceta** [comment]
then, at the moment there is no solution for this? or can I configure webpack for myself?

**Comment by danielroe** [comment]
As far as I can tell, there is no solution to obfuscate normal CSS class names in your code and in npm imports - unless you write one 😄
