### ISSUE TITLE
Ability to remove $nuxt helper from window

### ISSUE THREAD

**Issue by saint777** [nuxt/nuxt.js#7988]
I know this discussed before,

Check this website [ozon.ru](url), it using Nuxt.js but doesn't have $nuxt inside window, how?

**Comment by manniL** [comment]
e.g. by using `delete window.$nuxt`. But be aware that:

1. This will likely have side effects and things can break
2. This won't stop users from having access to vue instances.

Related: https://github.com/nuxt/nuxt.js/issues/4720

**Comment by saint777** [comment]
> e.g. by using `delete window.$nuxt`. But be aware that:
> 
> 1. This will likely have side effects and things can break
> 2. This won't stop users from having access to vue instances.
> 
> Related: #4720

can you please show how to access to vue instances on ozon.ru ?
I can't find anything inside window

**Comment by saint777** [comment]
@pi0 can you answer this

**Comment by saint777** [comment]
the guy above got 2k for docs, can't even answer

https://i.imgur.com/PyWieji.png

**Comment by saint777** [comment]
haha marked  as spam, nuxt is trash

**Comment by pi0** [comment]
Dear @saint777, Your actions are totally against community guidelines and out of respect. Nuxt.js is an opensource project maintained and supported by people that use their free time and passion of contributing. No one is obligated to immediately answer to your questions or do support while you do not even respect issue template! And of course no one forced you to use a product that don't like for any reason.

I shouldn't have answered this issue but as respect and for your curiosity, yes! it is possible to access vue instance in your website. As you may already find my answer in #4720, even by using a `globalName`, i'm able to access your `$api` service using `document.querySelector('#__ozon').__vue__.$api`  and also vuex!  (mutation is possible of course)

![image](https://user-images.githubusercontent.com/5158436/91732380-74830c80-eba8-11ea-888f-1de0a5ba5943.png)

This is not nuxt specific or because global `$nuxt`. Same is possible for any frontend framework including react and vue if you have proper knowledge. With react devtools you can see structure of almost any react website: (this is twitter.com)

![image](https://user-images.githubusercontent.com/5158436/91732190-31289e00-eba8-11ea-8007-96008a4ff574.png)

Same is possible for any vue app via vue-devtools but it is intentionally disabled in published version.

**Comment by saint777** [comment]
> Dear @saint777, Your actions are totally against community guidelines and out of respect. Nuxt.js is an opensource project maintained and supported by people that use their free time and passion of contributing. No one is obligated to immediately answer to your questions or do support while you do not even respect issue template! And of course no one forced you to use a product that don't like for any reason.
> 
> I shouldn't have answered this issue but as respect and for your curiosity, yes! it is possible to access vue instance in your website. As you may already find my answer in #4720, even by using a `globalName`, i'm able to access your `$api` service using `document.querySelector('#__ozon').__vue__.$api` and also vuex! (mutation is possible of course)
> 
> ![image](https://user-images.githubusercontent.com/5158436/91732380-74830c80-eba8-11ea-888f-1de0a5ba5943.png)
> 
> This is not nuxt specific or because global `$nuxt`. Same is possible for any frontend framework including react and vue if you have proper knowledge. With react devtools you can see structure of almost any react website: (this is twitter.com)
> 
> ![image](https://user-images.githubusercontent.com/5158436/91732190-31289e00-eba8-11ea-8007-96008a4ff574.png)
> 
> Same is possible for any vue app via vue-devtools but it is intentionally disabled in published version.

thank you @pi0, i applreciate your answer, i wasn't really needed in immedeate answer (i could wait for weeks!) but this guy is core team member and he answering like "just delete this object" and closing issue

**Comment by pi0** [comment]
@saint777 I've checked their website closely, seems they are using a custom fork. All loading-bar and internals customized. Still as mentioned and manniL mentioned, it doesn't prevent to access internals:

![image](https://user-images.githubusercontent.com/5158436/91742173-1d843400-ebb6-11ea-8b7a-943485113e3c.png)

> "free time and passion of contributing", bruh

I'm sorry but i have to stop answering because you totally have a wrong opinion on how opensource works. If you continue i have to limit your access.

**Comment by saint777** [comment]
@pi0 just ban me i'll not use Issues tab again

**Comment by pi0** [comment]
Issue locked as already answered.

Feel free opening a new issue or [dicussion](https://github.com/nuxt/nuxt.js/discussions/new) if still having concerns regarding globalName. :green_heart:
