### ISSUE TITLE
middleware redirect - params discarded

### ISSUE THREAD

**Issue by rmirabelle** [nuxt/nuxt.js#8009]
The undocumented `redirect` function appears to support Vue `Location` as an argument.  But when attempting to set the `params` property of the target `Location`, even when ensuring the use of route `name` instead of `path`, the value of `params` seems to get swallowed/discarded. This can be confirmed by checking `this.$route` on the redirect page.

### Versions

- nuxt: 2.14.1

### Reproduction

1) Call `redirect` from middleware:

_/middleware/auth.js_
```js
export default function({ route, store, redirect }) {
	if(route.path === '/login') return //don't check if on login page
	if(store.state.user.token == null) {
		console.log('Auth middleware: Not logged in for route', route)
                //doesn't work, params swallowed and becomes null
                redirect({ name: 'login', params: {ref: 'whatever'} })
                //works fine
		redirect({ name: 'login', query: {ref: 'whatever'} })
	}
}
```

2) Verify route on redirect page:

/pages/login.vue

```js
methods: {
    checkRoute() {
        console.log(this.$route)
        //params: {} - always empty, even when setting params
        //query: {ref: 'whatever'} - works fine
    }
}

```

**Comment by rafail-dev** [comment]
I think that to create a page with a parameter "ref"
nessesary to use `/pages/login/_ref.vue` file
because `/pages/login.vue` is a page without params
https://nuxtjs.org/guide/routing/#dynamic-routes

1) create /pages/login/_ref.vue
2) redirect({ name: 'login-ref', params: {ref: 'whatever'} }). //!!!name === 'login-ref'

https://codesandbox.io/s/youthful-gould-bnn7y?file=/nuxt.config.js

**Comment by farnabaz** [comment]
Parameters are present in  the `$route` variable only if you did defined them in folder structure.

I close this, but if you have further questions feel free to ask.
