### ISSUE TITLE
Safari "Invalid regular expression: invalid group specifier name" Error

### ISSUE THREAD

**Issue by batuhanoztrk** [nuxt/nuxt.js#8027]
### Versions

- nuxt:  v2.13.0
- node:  v14.9.0

I cannot log in via Safari in spa mode in Nuxt's 2.13 version. Has an "Invalid regular expression: invalid group specifier name" error, has anyone ever gotten and solved this error?

<img width="1324" alt="Ekran Resmi 2020-09-07 14 14 22" src="https://user-images.githubusercontent.com/34206290/92389625-17e09e00-f122-11ea-95ce-95572604f829.png">

**Comment by dsegovia90** [comment]
I have the same issue, did you find a solution for this problem?

**Comment by owalid** [comment]
any update for this issue ? did you find a solution for this problem ? @batuhanoztrk

**Comment by batuhanoztrk** [comment]
@owalid @dsegovia90 I could not find any solution for this problem.

**Comment by floriandonod** [comment]
Any updates for this issue ? did you find a solution  ? @batuhanoztrk @danielroe

**Comment by owalid** [comment]
@floriandonod Hello ! :) 
I'm going to be vague because, I solved this problem a long time ago.
If I remember, it was not a nuxt issue but an incompatibility of type of regex with safari.

See around this, I hope it will be useful for your problem:

- https://caniuse.com/js-regexp-lookbehind
- https://stackoverflow.com/questions/3569104/positive-look-behind-in-javascript-regular-expression/3569116#3569116
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#browser_compatibility
