### ISSUE TITLE
Parameters failure in nested directory structure nuxt 2.14

### ISSUE THREAD

**Issue by MBeijer** [nuxt/nuxt.js#8091]
This is an odd issue I got on one of my customers websites after an update from Nuxt 2.12 to Nuxt 2.14.

Parameters are no longer working correctly in deeply nested directory structures.

### Versions

- nuxt: v2.14.5
- node: v12.18.3

### Reproduction

https://codesandbox.io/s/cocky-rosalind-rfzy0?file=/pages/test/nest/_param1/test/_param2/_param3/_param4/index.vue

https://rfzy0.sse.codesandbox.io/test/nest/param1/test/param2/param3 <-- Failure
https://rfzy0.sse.codesandbox.io/test/nest/param1/test/param2/param3/param4 <-- works correctly when last param is not omitted

### Steps to reproduce

Nested directory structure with parameters

### What is Expected?

Parameters in the right place

### What is actually happening?

When going to a deeply nested URL and omitting the last param, the next to last param gets moved to last param

**Comment by manniL** [comment]
Could it be related to https://github.com/nuxt/nuxt.js/pull/7843 ?

**Comment by MBeijer** [comment]
@manniL I think it's rather related to #7845

**Comment by MBeijer** [comment]
But I could be wrong

**Comment by manniL** [comment]
Seems more likely!

cc @farnabaz

**Comment by farnabaz** [comment]
I see, I believe despite that is works before, you were doing it in the wrong way. Let's assume you have pages structure like the image
<img width="280" alt="Screen Shot 2020-09-18 at 5 18 55 PM" src="https://user-images.githubusercontent.com/2047945/93599233-0b3a3080-f9d3-11ea-93c2-c7286575c4b5.png">

According to [official docs](https://nuxtjs.org/guide/routing/#dynamic-routes) `param4` will be required and other params (`params1..3`) will be optional, the generated route will be like `/test/nest/:param1?/test/:param2?/:param3?/param4`

Ok, now you are going to visit `/test/nest/1/test/2/3` path in the browser. Nuxt router expects that you provide a value for the `param4` (because it is required) and it picks `3` as the value of `param4`.

In case you want to catch urls with missing `param4` consider creating an index inside `param3` directory. Take a look at https://codesandbox.io/s/params-failure-forked-1d8se?file=/pages/test/nest/_param1/test/_param2/_param3/index.vue

**Comment by MBeijer** [comment]
It worked perfectly fine in 2.12, so it was unexpected when the website stopped working properly in 2.14.

In the real-world application the last parameter is an optional date. I'd rather not make a duplicate index file for this purpose, so how would I solve this otherwise?

**Comment by farnabaz** [comment]
> It worked perfectly fine in 2.12, so it was unexpected when the website stopped working properly in 2.14.

Yes, I agree with you. Your project was working perfect with 2.12 because of [a bug](https://github.com/nuxt/nuxt.js/issues/5874) inside route generation system. A bug sometimes may become usefull, in your case you were lucky back then that uses this bug to achieve your goal 🍀   
But [the docs](https://nuxtjs.org/guide/routing/#dynamic-routes) are our source of truth in this matter.

> In the real-world application the last parameter is an optional date. I'd rather not make a duplicate index file for this purpose, so how would I solve this otherwise?  

You could extract `params4/index` into a component and use that component in both `param4/index` and `param3/index`.  
Or you can possible ways to [extends nuxt router](https://nuxtjs.org/guide/routing/#extending-the-router).
