### ISSUE TITLE
Nuxt creating route based on relative href (I don't want it to)

### ISSUE THREAD

**Issue by cliffordh** [nuxt/nuxt.js#8105]
I am using Google Cloud Functions in a statically generated nuxt site. I have hrefs in the site which point to /myFunction1?someParam=foo.

Nuxt generate is creating a route for myFunction1 but it should not do that as myFunction1 is rewritten server side by Google Cloud Functions to execute a function. It should not be generating a page. I'm also getting a build error because myFunction1.vue does not exist (yet Nuxt generates a subdirectory of that name anyway with an index.html saying "page not found").

How can I make Nuxt ignore an href path?

**Comment by drewbaker** [comment]
Is that href on a nuxt-link? The crawler first generate income looks at nuxt links. 

Also, you can exclude routes using this: https://nuxtjs.org/api/configuration-generate/#exclude

**Comment by Knogobert** [comment]
I got the same issue when updating from nuxt@2.12.2 to nuxt@2.13.0. 
I get the error `Error generating route "/admin": This page could not be found ` because of this relative link in my `default.vue` layout.

```
<a href="/admin" target="_blank">Admin</a>
```

My solution was to add "/admin" to my excluded list of routes to generate. Just like @drewbaker said too look for in the [generate config docs](https://nuxtjs.org/api/configuration-generate/#exclude)

Add this in `nuxt.config.js`
```
generate: {
    exclude: ['/admin'],
},
```

Works like a charm! 

We can close this issue imo.
