### ISSUE TITLE
<nuxt-link> doesn't work in iOS Safari Nuxt v2.8.1

### ISSUE THREAD

**Issue by umamichi** [nuxt/nuxt.js#8114]
### Versions

- nuxt: 2.8.1
- node: 10.16.0
- vue-awesome-swiper: 3.1.3
- iOS: 13.7 (iPhone 8)

[Sample Code](https://github.com/umamichi/nuxt-sample-for-issue)

### Steps to reproduce

There are two pages.

`http://localhost:4000/list` ... `<nuxt-link>` page

`http://localhost:4000/detail/123/` ... detail page. `vue-awesome-swiper` element exist.

1. Simply tap `<nuxt-link>`

2. Even if you tap it once every 50 times, it may not respond. Tap it again to react.

[Video Link](https://gyazo.com/7d4cd458d01c8cfb67243fd66fb68459)

### What is Expected?

+ iOS Safari bug.
+ vue-router's bug in nuxt.
+ Interference bug between vue-awesome-swiper and vue-router.

I thought about upgrading the version of Nuxt, 

but in the actual project, there are many dependent modules and it is not realistic.

I would like to know the solution while keeping the same Nuxt version.

**Comment by Timures** [comment]
Hello, have same problem too - Nuxt, and Safari on Iphone 7.
Have u test, without using nuxt-link, just pure - a href link ? Maybe help.
P.s. Sorry for my English

**Comment by borusbillion** [comment]
Hi, a href link works well without using nuxt-link. 
nuxt-link doesnt' load the internal page

**Comment by devotion-sam** [comment]
In case anyone runs into this problem in future, this can happen if the dom changes and safari or vue thinks it's invalid. If you hook up your ios device to a laptop and look at console errors you may be getting an error saying HierarchyRequestError: The operation would yield an incorrect node tree.

For me this was happening because there was a set of numbers that safari was parsing as a phone number, and it was trying to create a tel: link around them. This caused every nuxt-link to stop working.

You can tell safari not to do this by using the meta tag:
<meta name="format-detection" content="telephone=no">

**Comment by swanandapps** [comment]
hey, i am recently facing the same issue. I am on Nuxt 3. I have two NuxtLink going to '/limited' in my homepage. Weirdly, first link works as expected but the second NuxtLink does take me to '/limited' but this time page is NON interactive.

Also, this is happening only on ios devices. Works smooth on rest. Any suggestions will be highly helpful

**Comment by paketaaa** [comment]
> hey, i am recently facing the same issue. I am on Nuxt 3. I have two NuxtLink going to '/limited' in my homepage. Weirdly, first link works as expected but the second NuxtLink does take me to '/limited' but this time page is NON interactive.
> 
> Also, this is happening only on ios devices. Works smooth on rest. Any suggestions will be highly helpful

@swanandapps let me know if you've solved that issue. I am facing the same issue in Nuxt 2 which appears only on ios aswell.
