### ISSUE TITLE
Emit event from page to layout 

### ISSUE THREAD

**Issue by steveDL** [nuxt/nuxt.js#8122]
Is it possible to emit an event from a page back up to default.vue layout?

`<nuxt @loading="loadingHandler" />`

**Comment by ontoneio** [comment]
@steveDL Can you clarify what the use case for this might be?

Just off top I'd imagine that there might be a different way to achieve the end goal you are looking for.
Do you have an example?

**Comment by tbrannt** [comment]
I actually tried to do this and found that the global event bus was actually what I was looking for.

Simply do 
```
this.$nuxt.$emit('eventName')
```

in any component (as opposed to `this.$emit('eventName')`)

and listen to it in any component with

```
created () {
  this.$nuxt.$on('eventName', () => {
    this.animateSecureHint = true
  })
}
```

**Comment by drewbaker** [comment]
This is amazing. Nuxt has a global event bus?! I didn't know this, only been using Nuxt for 3 years...

**Comment by ichaiwut** [comment]
This is awesome! thanks @tbrannt ! 🙏

**Comment by kissu** [comment]
It's strange that this works with `<nuxt-child></nuxt-child>` but not `<nuxt></nuxt>`.

I can even see the listener on `<nuxt></nuxt>` and the event emitted from the child but the method does not trigger. This solution may be good enough tho, thanks !

**Comment by oluudeh** [comment]
> 
> 
> I actually tried to do this and found that the global event bus was actually what I was looking for.
> 
> Simply do
> 
> ```
> this.$nuxt.$emit('eventName')
> ```
> 
> in any component (as opposed to `this.$emit('eventName')`)
> 
> and listen to it in any component (and also in your `default.vue` layout) with
> 
> ```
> created () {
>   this.$nuxt.$on('eventName', () => {
>     this.animateSecureHint = true
>   })
> }
> ```

Is there a way to do this using @nuxtjs/composition-api?

**Comment by Yvanov-N** [comment]
Thanks, Helpfull !

**Comment by ibrahimBeladi** [comment]
How could this be tackled with @nuxtjs/composition-api?

**Comment by viandwi24** [comment]
> How could this be tackled with @nuxtjs/composition-api?

I'm not very good at typescript and nuxt, but you can make this reference

- `composables/use-nuxt.ts`
```ts
import { getCurrentInstance } from '@nuxtjs/composition-api'

export const useNuxt = () => {
  const instance = getCurrentInstance()
  return (instance as { proxy: Vue }).proxy.$nuxt
}
```
- `parent.vue`
```ts
import { useNuxt } from '~/composables/use-nuxt'
const $nuxt = useNuxt()
onMounted(() => $nuxt.$on('test', () => alert('test')))
```
- `child.vue`
```ts
import { useNuxt } from '~/composables/use-nuxt'
const $nuxt = useNuxt()
$nuxt.$emit('test')
```

**Comment by hinst** [comment]
I tried the approach from the latest comment but it does not work anymore:

function `$nuxt.emit()` exists, but function `$nuxt.on()` does not exist in my latest Nuxt 3 installation.

I find it is pretty inconvenient overall, that existing functions get removed from the new version of the framework; because it creates headache for the users of the framework

**Comment by viandwi24** [comment]
> I tried the approach from the latest comment but it does not work anymore:
> 
> function `$nuxt.emit()` exists, but function `$nuxt.on()` does not exist in my latest Nuxt 3 installation.
> 
> I find it inconvenient overall, that existing functions get removed from the new version of the framework. This approach creates headache for the users of the framework


have you made it composable like in my comment? in my comment above I created a new composable namely $nuxt, this function doesn't exist, because of this I made it myself

**Comment by viandwi24** [comment]
> I tried the approach from the latest comment but it does not work anymore:
> 
> function `$nuxt.emit()` exists, but function `$nuxt.on()` does not exist in my latest Nuxt 3 installation.
> 
> I find it inconvenient overall, that existing functions get removed from the new version of the framework. This approach creates headache for the users of the framework

what version did you try it on?

**Comment by madhusudanbabar** [comment]
> > I tried the approach from the latest comment but it does not work anymore:
> > function `$nuxt.emit()` exists, but function `$nuxt.on()` does not exist in my latest Nuxt 3 installation.
> > I find it inconvenient overall, that existing functions get removed from the new version of the framework. This approach creates headache for the users of the framework
> 
> what version did you try it on?

Same here, I'm also unable to access `$nuxt.$on`, getting this error `TypeError: $nuxt.$on is not a function
    at default.vue:90:13`
I'm using `"nuxt": "^3.6.3"`

**Comment by Hebilicious** [comment]
The global event bus got removed in vue 3, here's the migration guide : 
https://v3-migration.vuejs.org/breaking-changes/events-api.html
In most cases this is not what you want, as vue docs say : 

In most circumstances, using a global event bus for communicating between components is discouraged. While it is often the simplest solution in the short term, it almost invariably proves to be a maintenance headache in the long term. Depending on the circumstances, there are various alternatives to using an event bus:

- Props and events should be your first choice for parent-child communication. Siblings can communicate via their parent.
- Provide / inject allow a component to communicate with its slot contents. This is useful for tightly-coupled components that are always used together.
- Provide / inject can also be used for long-distance communication between components. It can help to avoid 'prop drilling', where props need to be passed down through many levels of components that don't need those props themselves.
- Prop drilling can also be avoided by refactoring to use slots. If an interim component doesn't need the props then it might indicate a problem with separation of concerns. Introducing a slot in that component allows the parent to create the content directly, so that props can be passed without the interim component needing to get involved.
- [Global state management](https://vuejs.org/guide/scaling-up/state-management.html), such as [Pinia](https://pinia.vuejs.org/).
