### ISSUE TITLE
Node is removed during transition from one route to another

### ISSUE THREAD

**Issue by piyushchauhan2011** [nuxt/nuxt.js#813]
I have a use-case where I want to do a `slide enter/leave left/right transitions` like we see in vue hackernews 2.0 app. Currently I see that route nodes are removed when we transition from one route to another, we can see this if slow down the animation the previous route nodes will not be visible while current route node appears slowly with the animation. While this works for some cases, but we still want previous node like vue-hackernews-2.0 has.

An example can be seen here: https://waiting-direction.glitch.me/cards/2 and the code is here: https://glitch.com/edit/#!/waiting-direction?path=pages/cards/_page.vue:16:14

You can also try and slow down the transition in hackernews app here: https://vue-hn.now.sh/top/2 and see that the previous card is still there while the next card animates in.

Maybe I'm missing something or Nuxt.js is removing the nodes from one page to another during routing push ? @Atinux

**Comment by piyushchauhan2011** [comment]
Also I noticed that when we use `vue-devtools` to view the nodes, it appears like this.

![screen shot 2017-05-31 at 12 18 09 am](https://cloud.githubusercontent.com/assets/693487/26593537/05725644-4597-11e7-823e-6a3d6da7745d.png)

There is only `<RouteLink>` and no nodes inside ? while on other pages, child-nodes are visible in `vue-devtools`

**Comment by piyushchauhan2011** [comment]
@johnlindquist @alexchopin

**Comment by Atinux** [comment]
Hi @piyushchauhan2011 

This is a bit tricky with nuxt.js since we use `<router-view>` for every page, and since it's the same component, `vue-router` will not "duplicate" it so it removes the node when doing the transition.

You have to do like it does in https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/views/ItemList.vue

Futhermore, Nuxt.js calls `data` & `asyncData` every time `:page` is updated, so the transition is reset to 'slide-right', that's why you can see in my code `cachedTransition`.

Demo: https://fern-clerk.glitch.me/cards/1
Code: https://glitch.com/edit/#!/fern-clerk?path=pages/cards/_page.vue:3:21

**Comment by piyushchauhan2011** [comment]
Thanks @Atinux ! Love the community 😍
