### ISSUE TITLE
redirect to not found doest work in middleware

### ISSUE THREAD

**Issue by woodgates** [nuxt/nuxt.js#8198]
### Versions

- nuxt: 
- node: 

### Reproduction
Here is a sandbox that has a middleware 'notfound' on the about.vue page. 
https://codesandbox.io/s/practical-rhodes-bydcc

Im using nuxtjs/router from the community, it's loaded in the sandbox as dependency.
The router.js is in the sandbox.
The sandbox itself is not working as expected but the code is there.

<details open>
<summary>When using redirect({name: 'notFound'}) on middleware nuxt redirects to the home page instead of the page not found </summary>
<br>

</details>

### What is Expected?
To go to the not found page

### What is actually happening?
It's going to the main page.

**Comment by Geminii** [comment]
Hello @woodgates 👋 
I check your codesandbox code and yeah there is a lot of errors ^^ 🙄
Here is the new [codesandbox](https://codesandbox.io/s/fervent-thompson-un45z?file=/router.js) to redirect on your notFound page 😉

I think your problem is due to your `path` which has been set on `*`.
Hope this help you 😄
