### ISSUE TITLE
Middleware is not working in header component

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/nuxt.js#825]
I have some component which is `App-Header` and i need to check auth in it, so i'm using middleware for this. It's working on page, but there is no any reaction in this Header component.

This is middleware, running from nuxt-config:
```
import { getUser } from './../api/AuthService'

export default function ({ store }) {
  const user = getUser()
  user ? store.commit('SET_USER', user) : null
}
```
just checking cookie and set store object depend on it.

In Header component i'm trying to get info about authenticated user by catching the `isAuthenticated` getter:
```
data () {
  return {
    isAuthenticated: this.$store.getters.isAuthenticated
  }
},
```
Can anybody help or explain why it's not working? Is middleware is not corresponding with layout components?

**Comment by stephan281094** [comment]
I'm afraid middleware can only be used in the Nuxt config, layouts and pages.

**Comment by piyushchauhan2011** [comment]
Hmm, I feel like we can access in a component. Instead of using `data` use `computed` properties @lukasborawski 

I just mapped the getters using vuex's `mapGetters` on `computed` here: https://github.com/piyushchauhan2011/nuxt-component/blob/master/components/Logo.vue .
You can have a look at store and middleware:
1. Store: https://github.com/piyushchauhan2011/nuxt-component/blob/master/store/index.js
2. Middleware: https://github.com/piyushchauhan2011/nuxt-component/blob/master/middleware/auth.js

and `nuxt.config.js` : https://github.com/piyushchauhan2011/nuxt-component/blob/master/nuxt.config.js#L50

Not sure if this is what is required ? Let me know @lukasborawski

**Comment by lukasborawski** [comment]
@piyushchauhan2011 and this is working for you?

My store:

```
export const mutations = {
  SET_USER (state, user) {
    state.user = user || null
  }
}

export const getters = {
  isAuthenticated (state) {
    return !!state.user
  },
  isSignedup (state) {
    return !!state.isSignedup
  },
  loggedUser (state) {
    return state.user
  }
}
```
and if i'm using computed i have the same false response too, tried this before.

**Comment by piyushchauhan2011** [comment]
Hmm, @lukasborawski yup it correctly access the state in Logo component. You can click the repo link and see by running it.

**Comment by lukasborawski** [comment]
Well, i need to do this. Thx for help anyway 👍 .

**Comment by piyushchauhan2011** [comment]
Cheers, no worries mate ;)
