### ISSUE TITLE
Styles get multiple copies of themselves making CSS development a pain

### ISSUE THREAD

**Issue by UnderTheMoonspell** [nuxt/nuxt.js#8402]
# Versions

- nuxt: 2.14.0/2.10.0
- node: v11.15.0

### Reproduction
It only happens in the dev npm script (so with hot reloading enabled)

### Steps to reproduce
Load a page, inspect element, change any of the CSS properties/add new properties/remove properties

### What is Expected?
For the CSS Property to change

### What is actually happening?
The CSS property changes but the website becomes unusable because multiple copies of the CSS are added to the head tag.

![image](https://user-images.githubusercontent.com/10156878/100351051-1ae57f00-2feb-11eb-8afe-235e5b8aa0a1.png)

**Comment by UnderTheMoonspell** [comment]
@danielroe what type of code? This is a huge project and it happens everytime you change CSS, so theres not a specific code that fails

**Comment by danielroe** [comment]
@UnderTheMoonspell Ideally if you could replicate the error at https://template.nuxtjs.org. I'm particularly interested in your `nuxt.config`, whether you are using `@nuxtjs/style-resources` (and if so how you are configuring it) - and the CSS in a sample component that is triggering this issue.

**Comment by UnderTheMoonspell** [comment]
We are using @nuxtjs/style-resources yes but only including variables and mixins files like so:

`  nuxtStyleResources.scss = [`@/styles/platforms/${platform}/_style-resources.scss`]`

Also we have a main.scss file which we use in nuxt.config

`nuxtCss.push(`@/styles/platforms/${platform}/main.scss`)`

And this file will import all of the main scss files (so yes one of them being the deposit.scss you mentioned)

**Comment by UnderTheMoonspell** [comment]
@danielroe why would nuxt config run again during runtime?

**Comment by Qvatra** [comment]
hi there,
I'm coworker of @UnderTheMoonspell and after digging the git history of our project I discovered that the bug was introduced  by vuejs-clipper component that was registered in nuxt.config as a plugin.

so for the record the problem was in importig component as `import VuejsClipper from 'vuejs-clipper'` which contains sourse scss files that has to be compiled first by sass-loader (here I assume things went dirty).

As a workaround I did include already compiled css that also comes whithin the package:
```
import VuejsClipper from "vuejs-clipper/dist/vuejs-clipper.umd";
import "vuejs-clipper/dist/vuejs-clipper.css";
```

**Comment by danielroe** [comment]
@Qvatra Great to hear you found the issue 😊
