### ISSUE TITLE
Nuxtjs faster response when preload font and extract css

### ISSUE THREAD

**Issue by Besto** [nuxt/nuxt.js#8521]
### Versions
- nuxt: v2.14.5
- node: v12

I try to load test nuxt SSR app(universal mode). I found that If I add nuxt config preload font and extract css It improve the throughput number. I'm not sure what NuxtJS do about font loading and css in SSR process when we request to the nuxt app. 

### Result load test
<img width="1097" alt="Screen Shot 2563-12-22 at 13 18 42" src="https://user-images.githubusercontent.com/1130177/102855964-4035a380-4458-11eb-8592-f559a64c488d.png">

### Nuxt config that improve performance
<img width="503" alt="Screen Shot 2563-12-19 at 12 16 47" src="https://user-images.githubusercontent.com/1130177/102681456-14b27f00-41f4-11eb-9ffd-1272b8e4bb11.png">
<img width="209" alt="Screen Shot 2563-12-19 at 12 18 18" src="https://user-images.githubusercontent.com/1130177/102681484-4deaef00-41f4-11eb-9c3b-530d3b0d7460.png">

**Comment by klausXR** [comment]
When using the default configuration, the html file served from the server will include the globally available css and the scoped css for the components rendered on the requested page. 

If you use the default config and inspect the source code of the page ( right click on a page and look for an `View page source` ), you will see everything that has been included.

Since this is being serialized by the server in order to be included in the html file served by the server, it reduces the throughput of your server, as it increases the contents that need to be serialized. When you switch to preloading the styles, the server will not include them in the bundle, since preloading only works in the browser. 

So, as soon as the initial page hits the browser, its going to request the styles. This might cause your page to not be styled for some time, as only the raw html has been served and no styles. 

Since you are reducing the size of the initial file, you should also be experiencing improvements in TTFB ( Time To First Byte )

None of these are facts and come solely from observations and some minor research, so you might want to wait until somebody from the team responds.

The reason for this answer is, I am as well interested in optimizing this part of the rendering process and I'm not sure how I should proceed, as the serialization also includes the initial state send from the server to the client ( which, if not careful, is the entire Vuex state ). 

How should one approach this? Should I be careful with rendering svg icons on the server, as they are lengthy, keep Vuex state sent to the client to the bare minimum and skip parts of the page server-side, that are not essential?

**Comment by Besto** [comment]
I created a simple app that has the below code.
<img width="333" alt="Screen Shot 2563-12-20 at 12 22 54" src="https://user-images.githubusercontent.com/1130177/102705862-a38bce00-42be-11eb-996a-454977b21378.png">

And look at the build result. Nuxtjs could take time to push a scoped css in every request as @klausXR said.
<img width="556" alt="Screen Shot 2563-12-20 at 12 23 03" src="https://user-images.githubusercontent.com/1130177/102705907-36c50380-42bf-11eb-92d2-165d5de52b9a.png">

But in extract css mode. There is no code to push a scoped css. The scoped css will be extract to a file and it will be include in client.menifest.json (Not sure what the file made for).
<img width="550" alt="Screen Shot 2563-12-20 at 12 24 37" src="https://user-images.githubusercontent.com/1130177/102705940-aa671080-42bf-11eb-8b84-284fd2ff8306.png">

I doubt that why Nuxtjs not build each page of app as a html template like a index.spa.html and attach scoped css at <head>.
It could be reduce the server task (to push css).
<img width="1245" alt="Screen Shot 2563-12-20 at 12 52 24" src="https://user-images.githubusercontent.com/1130177/102706244-c61fe600-42c2-11eb-8965-25899e1c0831.png">

**Comment by Besto** [comment]
> Did you run Nuxt generate or Nuxt start and looked at the HTML rendered by the browser?

All things I talk about I run only nuxt start.

**Comment by klausXR** [comment]
@Atinux can one opt out of this mode and serve styles through cdn or whatever. It will cause a FOUC, but if it impacts in a dramatic way the throughput of the server, it might be worth it for a lot of people.
