### ISSUE TITLE
ERR_REDIRECT is thrown by default, leads to confusing behavior

### ISSUE THREAD

**Issue by th0rgall** [nuxt/nuxt.js#8594]
### Versions

- nuxt: 2.12.2 (in the codesandbox reproduction, but also on the latest locally)
- node: v10.23.0 (codesandbox)

### Reproduction

https://codesandbox.io/s/nuxt-redirect-problem-owxll

### Steps to reproduce

1. Make sure the CodeSandBox server runs in the above sandbox
2. Visit the vue app at https://owxll.sse.codesandbox.io/ (the effect is better seen when not loaded in the codesandbox iframe)
3. Click the button "Go to a redirecting page - error flashes"

See the reproduction: there are two vue pages to illustrate the problem and a workaround.

The [problematic case](https://codesandbox.io/s/nuxt-redirect-problem-owxll?file=/pages/redirect-problem-case.vue) handles some async task, then it redirects to a URL (which would in a real case be based on the async work from before). If a `catch` block is inserted, this catch block will also catch the `ERR_REDIRECT` that is being thrown on a client-side redirect: https://github.com/nuxt/nuxt.js/blob/c15078fa648ac5a4c77241700e9f1bd74a802af8/packages/vue-app/template/utils.js#L232. 

The `catch` block on it own triggers an error page with `error()`. Since it captures the `ERR_REDIRECT`, it briefly flashes an error page before the redirect completes. That's weird.

The workaround is to either:
- not have a `catch` block around a `redirect()` operation
- check that the `error.message !== 'ERR_REDIRECT'`, which is implemented in the ["Go to a redirecting page - no flash"](https://codesandbox.io/s/nuxt-redirect-problem-owxll?resolutionWidth=320&resolutionHeight=675&file=/pages/redirect-expected-case.vue) page

### What is Expected?

The redirection should not be throwing an error  in `redirect()` when there is actually no problem with the redirection (in this case, there is no redirection problem).

Why is a redirect seen as an error?

See also https://github.com/nuxt/nuxt.js/issues/5024, who asked this question before without response.

### What is actually happening?

An unnecessary (?) error is thrown where it is not expected.

**Comment by pi0** [comment]
Hi @th0rgall. Throwing error is intentional to avoid doing any tasks between the time redirect call happens until browser starts navigation because previously we had more untracable errors with this situation.

You may want to directly return `redirect()` after call so that nuxt internally handles errors (and also [gracefully handling redirect](https://github.com/nuxt/nuxt.js/blob/9681a8937d0c973bc685b757faa686023a4536fc/packages/vue-app/template/client.js#L586)). Using try/cache inside `asyncData` only makes sense if you have a custom error handler to modify error object. Also as a general coding style, i would recommend using error wrappers on specific calls not entire block.

See forked sandbox with suggested fix: 

- https://codesandbox.io/s/nuxt-redirect-problem-forked-ce1ep?file=/pages/redirect.vue
- https://ce1ep.sse.codesandbox.io/

**Comment by th0rgall** [comment]
Alright @pi0, thank you for explaining and for your code suggestions! They are cleaner than my workaround.

It seems you ended up with this behavior as a best possible compromise. But I'd still say it is not so intuitive for a Nuxt newcomer, so proposed an edit to the docs, see the linked PR above.

**Comment by Atinux** [comment]
Thank you for the linked PR to the docs @th0rgall, we can keep the discussion there since it is better to be documented :)

**Comment by johncastorina** [comment]
I am running into this, and it's blocking my production release. I checked the link for the sandbox, and it has become defunct. 

Please provide an example here, and if possible - update the documentation with the suggested fix for this.

Thank you.
