### ISSUE TITLE
Rendering to string is unsafe

### ISSUE THREAD

**Issue by bahmutov** [nuxt/nuxt.js#86]
Following the approach described in https://medium.com/node-security/the-most-common-xss-vulnerability-in-react-js-applications-2bdffbcc1fa0#.mup3jwgjq I have tried the following use data string in a page

```
<template>
  <div>
    <h1>Welcome</h1>
  </div>
</template>

<script>
export default {
  data () {
    return {
      whatever: '</script><script>console.log("xss")</script>'
    }
  }
}
</script>
```
which prints "xss" during server-side rendering on the server and in the browser console for client rendering. I believe this is due to unsafe object serialization in [self.renderToString](https://github.com/nuxt/nuxt.js/blob/master/lib/render.js#L73)

**Comment by Atinux** [comment]
Will work on it, thank you very much @bahmutov for spotting it!

**Comment by bahmutov** [comment]
My pleasure, great project! I forked it and thought you just need serialize-javascript but that one is already used correctly, so that is not the problem. BTW next.js uses `renderToStaticMarkup` to properly render and escape the data for this case.

**Comment by Atinux** [comment]
By looking into it, it's not due to `renderToString` neither `serialize-javascript` but from `vue-loader` which interprets your `'</script><script>console.log("xss")</script>'` as the closing tag of your template.

I uploaded a json on a server: https://api.myjson.com/bins/1a4fjr

And I created an example which get this data and set it: https://gomix.com/#!/project/nuxt-xss
Live demo: https://nuxt-xss.gomix.me/

As you can see, it works perfectly.

In the next release, I added the option `{ isJSON: true }` in [serialize-javascript](https://www.npmjs.com/package/serialize-javascript) to improve the performance.

**Comment by bahmutov** [comment]
the closest issue in vue-loader is this https://github.com/vuejs/vue-loader/issues/506 which to me sounds a little weird, but that's their choice. Thanks for looking at it though.
