### ISSUE TITLE
API getting called on nuxt generated pages on client-side navigation

### ISSUE THREAD

**Issue by aayushgoyal** [nuxt/nuxt.js#8614]
### Versions

- nuxt: v2.14.12 

### Steps to reproduce
It can be produced on any nuxt static app.

### What is Expected?
API present in asyncData() function should not be called on already generated pages on client-side navigation (clicking nuxt-link).

### What is actually happening?
APIs used to built the page in asyncData() function are getting called on nuxt generated pages on client-side navigation (clicking nuxt-link).

I am using following config in nuxt.config.js

`  ssr: true,
   target: 'static',
`

**Comment by danielroe** [comment]
Having looked at the site you emailed me, it seems likely that your issue is due to your links being to pages with a trailing slash, whereas the static payload is not encoded for trailing slash. However, this may well be fixed in `nuxt-edge` and in the upcoming `2.15` release. Would you check with `nuxt-edge` and see if this solves your issue?

**Comment by aayushgoyal** [comment]
Thanks @danielroe . I tried `nuxt-edge`, and issue is not occuring now. 😃
