### ISSUE TITLE
URL params format error

### ISSUE THREAD

**Issue by rombrandon** [nuxt/nuxt.js#8680]
### Versions

- nuxt@2.14.12

### Steps to reproduce

Open url like [/search/%2F](/search/%2F)

### What is Expected?

Throw error "TypeError: Cannot read property '_isDestroyed' of undefined"

### Temporary processing

Return to the version nuxt@2.14.3 , and there is no such problem.

By the way, the URL with "%25" will throw error "URIError: URI malformed", 
and I have to using a middleware translate to “%2525”.

**Comment by pi0** [comment]
Hi @rombrandon. Would you please try removing yarn.lock/node_modules? A dependency of nuxt has been updated to fix this issue. If still not fixed, a reproduction repo (or at least public URL) would be the best to investigate.

**Comment by jgrocha** [comment]
Maybe I have the same problem here. With `nuxt@2.14.7` my redirect requests are properly encoded:
```
http://localhost:3000/app/user/login/?redirect=%2Fhomologation%2Flist
```

Upgrading to `nuxt@2.14.12` my redirects are failing, since they are not encoded:
```
http://localhost:3000/app/user/login/?redirect=/homologation/list
```

**Comment by pi0** [comment]
@jgrocha Unless you have `URIError: URI malformed` error, i'm not sure this is same issue but indeed related to encoding changes we had to introduce due to `vue-router` changes...

BTW `http://localhost:3000/app/user/login/?redirect=/homologation/list` is a valid encoded URL (at least by whatwg). Can you please describe more why redirects are failing? (reproduction, sandbox, error, ..)

**Comment by jgrocha** [comment]
Thank you for the feedback @pi0. 

For my redirect purpose, I can handle both URLs, either encoded or not. But I need to know if nuxt encodes the `redirect` parameter or not.

My comment is more related with encoding consistency. I noticed that the behaviour has changed from `nuxt@2.14.7` to `nuxt@2.14.12`. The `redirect` parameter value is no longer encoded.

I can change my custom router logic if the behaviour changes to not encode the `redirect` parameter, for `nuxt >= 2.14.12`.

**Comment by pi0** [comment]
Hi @jgrocha. Query values are encoded but not with `encodeURIParam` (characters like `=` are encoded for example). Here is implementation for reference: https://github.com/nuxt-contrib/ufo/blob/5c6b320efd7b843dcc82543dd164548462d976bf/src/encoding.ts#L57

The reason why this happens is that since vue-router requires encoding, we do have to ensure URL is properly encoded but if it is already (partially) encoded double encoding happens so `ufo.normalizeURL` first parses and decoded url then encoded it with whatwg/vue-router compatible encoding

**Comment by lucianholt97** [comment]
@jgrocha how did you fix the issue?

I still have missing encoding when using redirect. It only appears when I input a fully qualified URL in redirect - it works correctly when using an internal path.
