### ISSUE TITLE
Query parameter decoding error in server rendering

### ISSUE THREAD

**Issue by Astlvk** [nuxt/nuxt.js#8690]
### Versions

- nuxt: 2.14.12
- node: 14.15.0

### Reproduction
Query parameter decoding error in SSR created hook and asyncData hook

### Steps to reproduce
https://vvw9q.sse.codesandbox.io/?str=%26&str2=%2526

### What is Expected?
Output:
```
In the asyncData hook on the server
str: &
str2: %26
In the mounted hook of the client
str: &
str2: %26
```

### What is actually happening?
Output:
```
In the asyncData hook on the server
str: &
str2: &
In the mounted hook of the client
str: &
str2: %26
```

**Comment by mapsgeek** [comment]
this breaks with me only on the server when i reload the page, can you explain the problem for me please?

**Comment by Astlvk** [comment]
> this breaks with me only on the server when i reload the page, can you explain the problem for me please?

I'm not very sure, it may be that the server has a problem with the processing of query parameters

**Comment by danielroe** [comment]
This is caused by the decoding of each query - so it's possible to fix this issue but not without breaking this test:
https://github.com/nuxt/nuxt.js/blob/fc51ca333062519d8376262eff93362e3a5739f9/test/dev/encoding.test.js#L24-L28

@pi0 - what do you think? As long as we've decoded the entire URL, I think it should be safe not to re-decode each query separately, but I'd need to tweak the test.
