### ISSUE TITLE
CSS of component with vue-loader is not being extracted and included

### ISSUE THREAD

**Issue by SoldierCorp** [nuxt/nuxt.js#876]
Hi!

Since I'm using `vue-loader` to have my template, script and style in the same .vue file, I'm having an issue about the CSS generated for production because the global file includes all the CSS except the ones that are included in my components so the production build is still flashing because the CSS is being included in a JS file.

So, I want to know how to extract that CSS of those componentes to include in the global one or which method should I use in order to don't have my web page flashing.

One more thing related... using `extractCSS: true` is generating a file like `common.764c59a21a9a8effd068.css` but, how can I include this file in all the pages?

Thanks!

**Comment by pi0** [comment]
Hi @SoldierCorp. Actually this is the expected behavior:  (When running `nuxt build` `nuxt start`)

### `extractCSS: true`

- A resource like `common.6d1aa5fdae9889963c5a.css` is emitted but **just** for global css imports not components `<style>` part.
- A link like `<link rel="stylesheet" href="/_nuxt/common.6d1aa5fdae9889963c5a.css">` is added to every page using vue bundle renderer.
- Component level styles are being bundled with each page js file. This helps keeping global CSS as minimum as possible.
- On Each SSR request, vue bundle renderer detects page component and should inline it on page header like this `<style data-vue-ssr-id="1f17c714:0 02c604cb:0">html...`

### `extractCSS: false`
- Component level styles are being bundled with each page js file. This helps keeping global CSS as minimum as possible.
- On Each SSR request, vue bundle renderer detects page component and should inline it + All common CSS to page header.

### When running with `nuxt dev`
- Global CSS is added to top of every page whether `extractCSS` is enabled or not.
- Inline CSS is injected by `vue-loader` so that hot reloading works correctly

**Comment by pi0** [comment]
Also this is exact behavour of vue-hn too. (See `view-source:https://vue-hn.now.sh/top`) as has to advantages:
- Only REAL common parts are being extracted to `common.css` so that we may save bandwidth by downloading them once.
- Page specific css are page specific it may be extra work including that in common too.
  - But for performance reasons you have said, they are being inlined in SSR so that page appears correctly just before executation of js

**Comment by SoldierCorp** [comment]
Great explanation! 

But if that behavior is completely usual.. why the production build of https://github.com/nuxt/starter works great adding the styles in the head and not in a js file, that build is not flashing?

**Comment by pi0** [comment]
Are you trying starter with alpha.4 version of nuxt? *production* builds should correctly add component css to head of page.

**Comment by SoldierCorp** [comment]
Yes, and in my project I'm also using the 1.0.0-alpha.4.

    build: {
      extractCSS: true,
      .....
    },
    ....
    css: [
      'normalize.css',
      { src: '~assets/styles/app.styl', lang: 'stylus' }
    ],

For example, I thought using that configuration, it wasn't necessary to import the app.styl in every component in the style section but actually is not working.

I just have that issue in my project related with the styles.. I built this project firstly without SSR but I had to include this SSR structure because the SEO.

**Comment by seekcx** [comment]
I used this problem when using starter today and later found that there was a css in `layouts / default.vue` that was not deleted. There is no problem after deleting.

L7-53
```html
<style>
html
{
  font-family: "Source Sans Pro", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  font-size: 16px;
  word-spacing: 1px;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  box-sizing: border-box;
}
*, *:before, *:after
{
  box-sizing: border-box;
  margin: 0;
}
.button--green
{
  display: inline-block;
  border-radius: 4px;
  border: 1px solid #3b8070;
  color: #3b8070;
  text-decoration: none;
  padding: 10px 30px;
}
.button--green:hover
{
  color: #fff;
  background-color: #3b8070;
}
.button--grey
{
  display: inline-block;
  border-radius: 4px;
  border: 1px solid #35495e;
  color: #35495e;
  text-decoration: none;
  padding: 10px 30px;
  margin-left: 15px;
}
.button--grey:hover
{
  color: #fff;
  background-color: #35495e;
}
</style>
```

**Comment by SoldierCorp** [comment]
Unfortunately, I'm not using layouts... for now.

**Comment by alexchopin** [comment]
Will be fixed in the next release
