### ISSUE TITLE
Sails.js & nuxt.js ?

### ISSUE THREAD

**Issue by irobayna** [nuxt/nuxt.js#877]
I can see that there are templates for other frameworks but not for ```Sails.js```

Anyone knows if the two frameworks can co-exists?

Thanks

**Comment by Atinux** [comment]
Hi @irobayna 

I don't see any problem to make Nuxt.js works with Sail.js since it can be used as a middleware.

If someone from the community wants to work on it, it could be really awesome!

**Comment by irobayna** [comment]
@Atinux I am researching the feasibility of this but my problem is that I know ```Sails.js``` but feel I am very green on ```nuxt.js```
If I could get some pointers I would be happy to contribute

**Comment by ImTheDeveloper** [comment]
Did anyone create a template for this?

**Comment by AngelMunoz** [comment]
hey guys i've made a little concept proof you can check it here
https://github.com/AngelMunoz/sails-nuxt
it is made with sails v1 (since that's the recommended version for new apps) just try to  lanuch it like this
`node app.js --dev --log.level=silly --port=3000` or adjust your `config/local.js`
relevant files for sails config are 
`config/nuxt.js`
`config/http.js`
I will try to polish it this weekend however if someone wants to add stuff feel free to pr :)

**Comment by ImTheDeveloper** [comment]
@AngelMunoz Excellent work so far. I've been watching your updates to this. I won't download/test until you have finished. I like the examples you are putting in, it's something I think a few of the other templates often miss out. I think it's going to be good to show policies against sails routes and also maybe handling an external API call within Sails that has some secret key required. This would show the distinction between using the server side calls for "private" calls rather than axios always being used on the client side to make API calls to external.

Do you plan on putting this on to the community templates? It would be great to just do a new nuxt install with the sails template with it.

I'll be forking once you have completed to show a vue-bootstrap example instead of vuetify. I like both frameworks and always good to show options.

**Comment by AngelMunoz** [comment]
Well I just made it for concept proof'ness but I would like to put it on the community templates.
and about other functionality examples it would be nice if you guys could list what you want to see there
and perhaps I could start working on them.

for the people that just want the endpoint + ajax calls to the api and some pages I think this is almost ready I just need to finish up the `post`, `put` and `delete` calls to the endpoint
to be fair I'm pretty much new to vue , don't need to say about nuxt hahaha but I've been finding pretty easy to learn/use

I'll keep you posted!

**Comment by AngelMunoz** [comment]
sorry didn't keep you posted guys, I did end up doing ajax calls and also added websockets to the sample
https://github.com/AngelMunoz/sails-nuxt
I just need to update to the 1.0 release which will be soon I guess perhaps on the weekend or if someone wants to do it you can pr there or raise an issue cheers!

**Comment by Tarrask** [comment]
Hi guys, I made a template targeting Sails v1.0. You can use it from https://github.com/Tarrask/sails-template

It use an sails hook to start Nuxt. Sails sockets are working and are accessible as `this.$socket` from a component or the store.
