### ISSUE TITLE
Access to the request in default.vue file

### ISSUE THREAD

**Issue by VincentLoy** [nuxt/nuxt.js#88]
Hi!

I'm currently working on a project with Nuxt as an Express Middleware with i18next support.
My problem is that I need to access the user browser language, I suppose via the `req` object SSR.

There is a way to access the request in the `layouts/default.vue` ? Or in a `plugin/customPlugin.js` file ? I know that we can access `req` object in `pages` vue files but no in layouts templates.

If you have any idea, you're welcome :)

Thanks :+1:

**Comment by Atinux** [comment]
Hi @VincentLoy 

Actually we restricted the layout to not have access of SSR data because their purpose has to be simple.

If you are using the store (and I believe you are is your are using 18next), you can add the `nuxtInitServer({ commit }, { req })` action in your store which get the context and is called before initialising the application, see [examples/vuex-store/)(https://github.com/nuxt/nuxt.js/tree/master/examples/vuex-store#action-nuxtserverinit).

**Comment by VincentLoy** [comment]
Thanks for your quick reply :)

**Comment by tomgrek** [comment]
Hi nuxtdevs,

I don't agree with your logic here. I wanted to create a page header (part of layout) that shows the user's username, but without access to `context.req.user.username` in the layout vue, I have to create the header component as a child of index.vue and pass down the username as $props. I hope you might reconsider.

Anyway, great work, thank you. Right now I'm just trying nuxt for a side project (SPA & REST API in one) but it has potential.
