### ISSUE TITLE
Production Build generates readable code

### ISSUE THREAD

**Issue by AllanOricil** [nuxt/nuxt.js#8819]
### Versions

- nuxt: 2.14.12
- node: v12.13.0

### Reproduction
![image](https://user-images.githubusercontent.com/55927613/107847785-75ba9580-6de6-11eb-8ad1-81ad5837d9cd.png)

### Steps to reproduce
- npm run build
- npm run generate

### What is Expected?
I thought it would output a uglified version of my app

### What is actually happening?
Js is not being uglified and functions/properties are not mangled

**Comment by pi0** [comment]
Hi @AllanOricil. Nuxt/Webpack uses [terser](https://github.com/terser/terser) in order to minify the code for the purpose of perf optimization not obfuscation. This means generated JavaScript code, can still be formatted with Devtools to a semi readable code.

Also terser uses a technique called name mangling to reduce size by renaming variables to a very shorter name (like `function (t)` or `Object(l.b)`). mangle flag is on by default but **property mangling** is disabled. A runtime javascript code (like vuex or vue) shuld be able to call a function thus terser cannot safely assume renaming properties like `methods` or action names is safe.

Only for demonstration what happens if property mangling is on:

```js
export default {
  build: {
    // https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build#terser
    terser: {
      // https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions
      // https://github.com/terser/terser#minify-options
      terserOptions: {
        /** CODE BELOW BREAKS NUXT PROJECT */
        mangle: { properties: true }
      }
    }
  }
}
```

**Comment by AllanOricil** [comment]
@pi0 I tried it and the app does not even start :/

**Comment by AllanOricil** [comment]
@pi0  you could add this to the doc for those who want to obfuscate their code. It works very well.


````json
"devDependencies": {
...
"webpack-obfuscator": "^2.6.0"
}
````

````
import WebpackObfuscator from 'webpack-obfuscator';

build: {
    extend(config, ctx) {
      if (!ctx.isDev && ctx.isClient && config.plugins) {
        config.plugins.push(
          new WebpackObfuscator({
            'compact': true,
            'identifierNamesGenerator': 'mangled',
            'selfDefending': true,
            'stringArray': true,
            'rotateStringArray': true,
            'shuffleStringArray': true,
            'stringArrayThreshold': 0.8,
            'splitStrings': true,
            'splitStringsChunkLength': 6,
            'transformObjectKeys': true,
          }, [])
        );
      }
    },
````

**Comment by pi0** [comment]
Adding manual above to the official docs is probably not a good idea:

- build dependencies like webpack plugins should not be directly imported in nuxt config
- `webpack-obfuscator` seems is disabling page chunk splitting and increasing base bundle size by ~%56
- Still after obfuscation, i could inspect app with a modified version of vue-devtools and code is not fully irreversible

Afterall i think it for sure worth to create a nuxt build module (nuxt-obfusticate maybe?) to make integration possible :) Feel free pinging me in discord if was interested and needed help to create it :)
