### ISSUE TITLE
Defining what a minor version vs a major version is. 

### ISSUE THREAD

**Issue by Phara0h** [nuxt/nuxt.js#8858]
If you ever need to use the words `**breaking changes. Update with caution**` in release notes. That is not a **minor** release that is a **major** one. Since most people use npm to install your packages which include a `^` so everyone with `"nuxt": "^2.14.6"` had their stuff break.

**Comment by pi0** [comment]
Hi @Phara0h. I understand this issue. 2.15 did not follow semver rules for versioning since we have to keep supporting nuxt 2.x for a longer term and some behavior changes was necessary to ensure this is possible. I would suggest for upgrading use a lock file and check changelogs to ensure it won't break project.
