### ISSUE TITLE
$refs empty in mounted callback when another component is a parent

### ISSUE THREAD

**Issue by mystrdat** [nuxt/nuxt.js#8879]
### Versions

- nuxt: v2.15.1
- node: v14.15.5

### Reproduction

In the following sandbox, you can see that the alert shows `undefined` due to `SectionTemplate` element being the parent of the referenced div. If there is no component parent, it will correctly show the HTMLElement reference. Possibly a @nuxt/components v2 issue.

```
// SectionTemplate.vue

<template>
  <section>
    <slot />
  </section>
</template>
```

```
<template>
  <SectionTemplate>
    <div ref="div">test</div>
  </SectionTemplate>
</template>

<script>
export default {
  mounted() {
    alert(this.$refs.div);
  },
};
</script>
```

https://codesandbox.io/s/trusting-shadow-tvc8e?file=/pages/index.vue

### Steps to reproduce

Make another Vue component a parent of your current component and `$refs` will be undefined. Worked as it should in 2.14 with @nuxt/components v1 (if it is relevant information).

### What is Expected?

Element references should be ready in mounted callback as there is no asynchronous behavior.

### What is actually happening?

Element references are not defined.

**Comment by pi0** [comment]
Hi @mystrdat

Unfortunately this is a change from components v1 to v2. Because of edge cases and development performance, we only use component loader for production build and by default components are globally installed via async imports / lazy. This means that if you try your example with `nuxt build` > `nuxt start` the ref has value and it works :)

It seems this is an expected behavior by vue.js that async component refs are undefined until initial render happens (see https://github.com/vuejs/vue/issues/2247)

So what you can do is:
- Use `updated` instead of `mounted` to ensure component is rendered
- Directly importing components that need access to `$refs` after being rendered
- Adding a check in mounted for `if (this.$refs.div)` existence
- Adding a generous delay with setTimeout in mounted before accessing `$refs` to ensure render happened

**Comment by mystrdat** [comment]
Hi @pi0 and thanks for the reply. Those seem to be rather unsatisfactory workarounds, it is possible to downgrade the components package Nuxt 2.15 uses? I've tried installing the older version and adding it to buildModules, but with no success.

**Comment by pi0** [comment]
@mystrdat Downgrading is not possible but you can force enable `loader` for development for 1.x behavior: (not recommanded nor guaranteed to always work)

```js
export default {
  components: {
    loader: true
  }
}
```

BTW regardless you should ensure rendering is done before accessing `$refs` as mentioned vue docs.

**Comment by minstn** [comment]
> Hi @mystrdat
> 
> Unfortunately this is a change from components v1 to v2. Because of edge cases and development performance, we only use component loader for production build and by default components are globally installed via async imports / lazy. This means that if you try your example with `nuxt build` > `nuxt start` the ref has value and it works :)
> 
> It seems this is an expected behavior by vue.js that async component refs are undefined until initial render happens (see [vuejs/vue#2247](https://github.com/vuejs/vue/issues/2247))
> 
> So what you can do is:
> 
> * Use `updated` instead of `mounted` to ensure component is rendered
> * Directly importing components that need access to `$refs` after being rendered
> * Adding a check in mounted for `if (this.$refs.div)` existence
> * Adding a generous delay with setTimeout in mounted before accessing `$refs` to ensure render happened

This works for me! Thanks!
