### ISSUE TITLE
Subscribe to store mutations OR Watch store

### ISSUE THREAD

**Issue by alexsonnay** [nuxt/nuxt.js#8888]
I didn't find anything related to Subscribing to mutations or to Watching a store module state in the NuxtJS documentation. 

Any idea how to do that from the component ? 

In that example : nothing is happening when subscribing to a mutation that is inside a store module called test.js. Same when trying with watch.

```

<script>

import { mapState } from 'vuex';

export default {

  computed: mapState(['test']),
  
  created() {
    this.unsubscribe = this.$store.test.subscribe((mutation, state) => {
      if (mutation.type === 'updateStatus') {
        console.log(`Updating to ${state.status}`);       
      }
    });
  },

  beforeDestroy() {
    this.unsubscribe();
  },

};
</script>
```

**Comment by hanneskuettner** [comment]
If I understood you correctly this feature is already supported since nuxt just exposes Vuex.

There are however a few problems with your code which result in your example not working like expected.

Without seeing how you setup your Vuex store I'm assuming you have created a Vuex module by creating a file called `test.js`.

This will create a [namespaced module](https://nuxtjs.org/docs/2.x/directory-structure/store#modules). As such the mutation type you want check for is namespaced as well. Again, assuming your module is `test` the mutation type is `test/updateStatus`.

Additionally Vuex subscriptions are [always global](https://forum.vuejs.org/t/vuex-subscribe-and-modules/36049/2). As such the subscribe code should be

```js
created() {
    this.unsubscribe = this.$store.subscribe((mutation, state) => {
      if (mutation.type === 'test/updateStatus') {
        console.log(`Updating to ${state.status}`);       
      }
    });
},
```
