### ISSUE TITLE
Err while using WeUI.js

### ISSUE THREAD

**Issue by aetherwu** [nuxt/nuxt.js#89]
I tried:

>npm install weui.js --save
>npm run dev

Then I imported in default.vue:

>import weui from 'weui.js';

It displays:

> Vue.js error
> 
> ReferenceError: window is not defined
>     at Object.<anonymous> (/node_modules/weui.js/dist/weui.min.js:6:6105)
>     at t (/node_modules/weui.js/dist/weui.min.js:6:318)
>     at Object.e.function.e.matches.e.matches.e.msMatchesSelector.e.mozMatchesSelector.e.webkitMatchesSelector.t (/node_modules/weui.js/dist/weui.min.js:6:2552)
>     at t (/node_modules/weui.js/dist/weui.min.js:6:318)
>     at Object.e.__esModule.default (/node_modules/weui.js/dist/weui.min.js:6:2042)
>     at t (/node_modules/weui.js/dist/weui.min.js:6:318)
>     at Object.e.__esModule.default (/node_modules/weui.js/dist/weui.min.js:6:547)
>     at t (/node_modules/weui.js/dist/weui.min.js:6:318)
>     at e.__esModule.default (/node_modules/weui.js/dist/weui.min.js:6:405)
>     at /node_modules/weui.js/dist/weui.min.js:6:410

So may I ask... how can I import packages dynamically like I did in vue.js?

**Comment by aetherwu** [comment]
OH wait, let me test this:
https://github.com/nuxt/nuxt.js/issues/21

**Comment by Atinux** [comment]
Hi @aetherwu 

This is because [weui.js](https://github.com/weui/weui.js) is not compatible with server-side rendering at the moment.

The library should check if window exists before using it, I think a PR to where they use window without checking should do the trick: https://github.com/weui/weui.js/search?utf8=%E2%9C%93&q=window

Otherwise you can require `weui.js` only inside `if (process.BROWSER_BUILD)` in the meantime the team behind weui.js make it compatible with server-side rendering.

**Comment by aetherwu** [comment]
I see. Thanks a lot for your lightning fast response:)
