### ISSUE TITLE
Hot module replacement (HMR) not working with serverMiddleware dependencies

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#8976]
Hot module replacement doesn't trigger when editing a file that is imported from server middleware.

Changing the server middleware file itself does trigger HMR for it but still doesn't reload imported modules.

### Versions

- nuxt: v2.15.3
- node: v14

### Reproduction

https://github.com/rchl/NuxtServerMiddlewareHMR

### Steps to reproduce

1. `yarn dev`
2. Change either the `test123` or `12345` values in `api/server-middleware-util.js`
3. Reload the page

### What is Expected?

The updated values are reflected on the page

### What is actually happening?

The page keeps showing values before the change.

**Comment by pi0** [comment]
Thanks for reproduction @rchl. I think issue is that, for HMR detection we depend on require.cache to create dependency graph (https://github.com/nuxt/nuxt.js/blob/f08f4efcde7bc174fd9b68a2a5a785d504659391/packages/utils/src/cjs.js#L47). Using jiti, we use `require.cache` for transpiled items but `children` is not being updated.

I will check to see if there is an easy fix. Otherwise we have to wait for nitro (or you can opt-in) since this method of HMR is unstable anyway...

**Comment by pi0** [comment]
Fixed in jiti @ 1.6.4. You have to use `yarn upgrade nuxt` or recreate lockfile to get update.

**Comment by rchl** [comment]
Awesome. Thanks!

**Comment by wemod123** [comment]
I confirmed on NUXT@2.15.6, NOT working.

I check the `yarn.lock` file, the jiti version is 1.9.2, Is this revert back?

**Comment by rchl** [comment]
It might be a different case. The issue I've reported is fixed. Feel free to report a new issue with more details.

(But I believe that CommonJS case still doesn't work. You have to use the ES Imports syntax for this to work.)

**Comment by wemod123** [comment]
Good, I got the point, thanks
