### ISSUE TITLE
Why you not say what nuxt is good for nothing!!!

### ISSUE THREAD

**Issue by nuxtdev** [nuxt/nuxt.js#9001]
### Versions

- nuxt: 
- node: 

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### What is Expected?
Why you not say what nuxt is good for nothing!!!

What server is need to run that miracle?
On local machine (budget laptop) with 4 core and 4 GB memory it work worst.
What are minimal system requests?

It make only one call to database

Document Length:        43388 bytes

Concurrency Level:      100
Time taken for tests:   62.127 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      44757000 bytes
HTML transferred:       43388000 bytes
Requests per second:    16.10 [#/sec] (mean)
Time per request:       6212.676 [ms] (mean)
Time per request:       62.127 [ms] (mean, across all concurrent requests)
Transfer rate:          703.53 [Kbytes/sec] received

**Comment by pengyouxian** [comment]
Can you describe in more detail the problem you encountered?

**Comment by nuxtdev** [comment]
> Can you describe in more detail the problem you encountered?
My nuxt app and next hacker news demo app can only offer only 10-30 requests per second win 100 concurrency 
Is very bad, big php site on ugly CMS work faster

**Comment by pi0** [comment]
Hi dear @pengyouxian thanks for mentioning your concerns. 

> Why you not say what nuxt is good for nothing!!!

Nuxt purpose is to bring a simple and consistent development environment to develop universal Vue.js applications. Hiding most of the complexity which we need to configure each project, ability to add new integrations with only install a module and avoiding boilerplate. See some of debbie talks: https://debbie.codes/resources/conference-talks

> What server is need to run that miracle?

For production using [nuxt-start](https://www.npmjs.com/package/nuxt-start) it is around `26 MB` for base project. Yet you can use [static site generation](https://nuxtjs.org/docs/2.x/concepts/static-site-generation/) to remove need of server at all.

![image](https://user-images.githubusercontent.com/5158436/111683688-1ce77e00-8826-11eb-8df6-0f3c8b60ef44.png)

For development, yes memory usage is not ideal. It is mostly because of webpack. That's why we are adding support for [Vite.js](https://vitejs.dev/) (see [nuxt/vite](https://github.com/nuxt/vite))

> Document Length: 43388 bytes

It is 43 kilobytes (which I assume without gzip). And it is bigger because we inline critical css for faster rendering. You might use a tool like [lighthouse](https://developers.google.com/web/tools/lighthouse) to measure client performance. And of course it depends on what libraries you use and how implemented actual project

> Concurrency Level: 100 ....

RPS of 16 is odd. For production if you care about performance, should use:
- A reverse proxy to cache requests (like nginx or varnish) or CDN (like alibaba, cloudflare, vercel, netlify)
- Using cluster to load balance. NodeJS is single threaded and designed to be scaled like this. SSR and Nuxt are no exception
- If it is an internal website, you can disable server-side rendering with `ssr: false`

**Comment by nuxtdev** [comment]
>RPS of 16 is odd (my guess is that you have a slow API call in server-side).
I have only one api call (from localhost with axios) what make a simply query to database!

**Comment by pi0** [comment]
It is sad to hear that nuxt was letting you down @nuxtdev. BTW as I mentioned above, you need less than 512 MB of ram to run nuxt in production (otherwise you probably configured something wrong). Feel free to send a message in [discord](https://discord.nuxtjs.org/) to me so we can figure out what's wrong. And best.

**Comment by nuxtdev** [comment]
> It is sad to hear that nuxt was letting you down @nuxtdev. BTW as I mentioned above, you need less than 512 MB of ram to run nuxt in production (otherwise you probably configured something wrong). Feel free to send a message in [discord](https://discord.nuxtjs.org/) to me so we can figure out what's wrong. And best.

It work but how good? How many request per second?  And what count can be considered acceptable?
I compare PHP production site (with 100+ request to databases) with unfinished (simplified because it have minimum features implemented now, that make 1-3 requests to database) app on nuxt and see that CMS on  Php work 3-10 time faster (use the same database).

**Comment by AndrewBogdanovTSS** [comment]
It's so sad to see that Nuxt team should respond to such immature reactions. @pi0 if I were you I would just ignore such tickets, admire your patience 🙂 
@nuxtdev I don't know how long you are in this business but I would like to remind you that it's open source world where no one owes you anything. If you don't like a project - don't use it. Besides, comparing Nuxt to PHP is like comparing monkeys to bananas, in other words - completely irrelevant.

**Comment by Cally99** [comment]
So many versions suffer with performance issues. Running nuxt in a docker container in dev mode is probably the worst decision I've ever made. Random crashes and when you need to restart the container it takes about 5 minutes to get a response on localhost.  I've tried different boilerplates changed configs. multi stage builds, disabled webpack watchers and it's still awfully slow in dev mode. Running on i7 mac with 8gb ram.  This will be the last project I'll use it for.

**Comment by AndrewBogdanovTSS** [comment]
@pi0 how about closing this one for further discussion?

**Comment by pi0** [comment]
> Running nuxt in a docker container in dev mode is probably the worst decision I've ever made.

Nor it is a recommendation way of using nuxt2 in development to use docker containers.

Nuxt first goal is to make developer life better and we are trying hard to keep doing this mission but of course it cannot make everyone happy with an OSS project and i respect your choice of opting-out if it is not fitting your requirements or preference ❤️ Hope nuxt3 can make you back and Best.

Limiting issue since while i can fully relate with all frustrations can happen during development, GitHub issues are ment to be collaborative or with actionable feedbacks and thanks for understanding.
