### ISSUE TITLE
Fails to apply class on on a custom component when relying on Components Discovery

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#9012]
When relying on components discovery to load components in the template, there is an issue with applying the css class on a custom component. Doesn't happen when importing explicitly.

### Versions

- nuxt: v2.15.3
- node: 14

### Reproduction

https://github.com/rchl/NuxtComponentsDiscoveryBug

### Steps to reproduce

1. Have a custom component that uses another custom component.

my-component.vue
```vue
<template>
    <my-sub-component />
</template>
```

my-sub-component.vue
```vue
<template>
    <div>
        This test should have green background
    </div>
</template>
```

index.vue
```vue
<template>
  <div class="container">
    <my-component class="pass" />
  </div>
</template>

<style>
.pass {
  background-color: green;
}
</style>
```

2. Set `class="pass"` on the outer component.

### What is Expected?

The ` class="pass"` should be applied to the custom my-component thus making its background green.

### What is actually happening?

The ` class="pass"` is getting lost on loading the page from the server.

**Comment by rchl** [comment]
You can see that explicitly importing in `my-component.vue` makes it work.
Uncomment the component registration there to test.

**Comment by pi0** [comment]
Hi @rchl thanks for sharing reproduction. I didn't have a chance to locally check it yet but it is most probably another issue with lazy components in vue2 (which we use in dev mode). You may try `components: { loader: true }` to force loader in dev that actually imports components instead of lazy loading.

**Comment by rchl** [comment]
That indeed fixes it. :)

Are the downsides to using that approach. If I understand you currently, it won't have affect on production at least?

**Comment by realityfilter** [comment]
This seems to me like the one I reported to vuejs https://github.com/vuejs/vue/issues/11837

But this is not only a problem in dev mode but has implications for ssr, too.

**Comment by pi0** [comment]
Thanks for pointing @realityfilter. Indeed it can also apply to production. Issues with async components are recently more visible since starting 2.15 we use async components for component discovery in development-mode (same as `global` for every component). I've added a bare reproduction there (https://github.com/vuejs/vue/issues/11837#issuecomment-811253552) hopefully we can figure out issue soon :)

**Comment by realityfilter** [comment]
The mentioned repl is still failing on vue 2.6.14.

**Comment by rchl** [comment]
I've re-checked my testcase after updating to latest dependencies (`@nuxt/core` 2.15.8, `@nuxt/components` 2.2.1) and it passes now so resolving.
