### ISSUE TITLE
Lazy Loading Routes

### ISSUE THREAD

**Issue by w550** [nuxt/nuxt.js#905]
https://router.vuejs.org/en/advanced/lazy-loading.html

**Comment by alexchopin** [comment]
It's already the case in Nuxt, we use code-splitting for each route component by default.

**Comment by w550** [comment]
@alexchopin 
Loading index.html page  for the first time ，all routes JS are loaded together

**Comment by elcontraption** [comment]
I'm also running into this problem while attempting to lazy-load Markdown files per route through middleware, using `import`. My Markdown files are in a root directory called `content`. What happens is *all* of these files are imported on every route, instead of just the one I'm looking for.

Here's `middleware/content.js` (my only middleware):
```js
/**
 * Content middleware
 * @param  {Object} route
 * @param  {Object} store
 * @param  {Function} error
 * @return {*}
 */
export default async function ({ route, store, error }) {
  let path = preparePath(route.path)

  try {
    let page = await import('~/content/' + path + 'index.md')

    delete page.frontmatter
    store.dispatch('pages/setPage', page)
    return
  } catch (err) {
    console.error(err)
  }

  return error({
    statusCode: 404,
    message: 'This page could not be found.'
  })
}

/**
 * Prepare path from full route path
 * @param  {String} path
 * @return {String}
 */
function preparePath (path) {
  // Remove leading and trailing slashes
  path = path.replace(/^\/|\/$/g, '')

  // Add back trailing slash for non-root paths
  if (path !== '') path += '/'

  return path
}
```

**Comment by elcontraption** [comment]
Looking into this further, I don't think it is an issue with Nuxt. It's because of the context webpack is building from what is known at the time of import. From the [webpack docs on import](https://webpack.js.org/api/module-methods/#import-):

> Every module that could potentially be requested on an import() call is included. For example, import(`./locale/${language}.json`) will cause every .json file in the ./locale directory to be bundled into the new chunk. At run time, when the variable language has been computed, any file like english.json or german.json will be available for consumption.

However, I did manage to get this working on another Vue-based, non-Nuxt project, but the reason it works there is eluding me.

**Comment by dts** [comment]
I am also having this problem with a `nuxt generate`-generated site.  I'm not sure what's going on

**Comment by Coletrane** [comment]
I'm having this same problem, go to [http://bikeva.com/](url) and look at the network tab, all the routes .js files are loaded on initial page load. I have in `nuxt-config.js`: https://github.com/Coletrane/mountain-bike-virginia/blob/posts-json-authors-json/nuxt.config.js#L114

`generate: {
    routes: routes.appRoutes
 }
`
