### ISSUE TITLE
Handling URL's ending with .ico extension

### ISSUE THREAD

**Issue by ysb** [nuxt/nuxt.js#9241]
### Versions

- nuxt: v2.15.4
- node: v15.4.0

### Reproduction

I have a URL that ends with a ".ico" extension. Nuxt handles it as a static file and returns 404 with content-type: image/gif.
https://storespy.net/android/us/game/action/app/magnetico-bomb-master-3d/ball.magnet.ico

### What is Expected?

I want to check routes first and accept as static file only if it's not defined in routes.

**Comment by danielroe** [comment]
@ysb This behaviour comes from [`serve-placeholder` middleware](https://github.com/nuxt-contrib/serve-placeholder) which is designed to provide a fast response for 404s on assets rather than hitting your Nuxt app to render a 404 page. See [docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-render#fallback) and [this comment](https://github.com/nuxt/nuxt.js/issues/8726#issuecomment-770249289) for how to disable this bheaviour:

```js
export default {
  render: {
    fallback: {
      static: {
        handlers: {
          '.ico': false
        }
      }
    }
  }
}
```

**Comment by ysb** [comment]
Thanks @danielroe
