### ISSUE TITLE
Runtime config type conversion

### ISSUE THREAD

**Issue by snakemastr** [nuxt/nuxt.js#9311]
nuxt: 2.14.12

I have an application that uses runtime config.
I noticed that primitive types are converted. In this case a number in a string is converted to a Number "2021" to 2021.

File snippets:
```
#base.config.js
export default {
  privateConfig() { return {}  },
  publicConfig() {
    return {
      year: "2021", // is converted to 2021
      years: ["2020", "2021"], // values remain string
      nextYear: {
        value: "2022" // is converted to 2022
      }
    }
  }
}
```

```
#nuxt.config 
import config from "./base.config";
export default {
  publicRuntimeConfig: config.publicConfig(),
  privateRuntimeConfig: config.privateConfig()
}
```

```
#Component.vue 
<script>
  mounted() {
     console.log(this.$config.year === 2021) // true
     console.log(this.$config.year === "2021") // false
     console.log(this.$config.years.indexOf(2021) !== -1) //false
     console.log(this.$config.years.indexOf("2021") !== -1) //true
  }
</script>
```

With the 'old' env properties this conversion didnt occur so it was predictable behaviour but this is not. 
Because the checks are done against fields that are of type string, I want the config value to remain a string.

Any thoughts on why/where this is happening?

**Comment by NIO-ADR** [comment]
noincoin 


Sent from the all new AOL app for iOS


On Wednesday, May 19, 2021, 9:06 AM, snakemastr ***@***.***> wrote:




nuxt: 2.14.12

I have an application that uses runtime config.
I noticed that primitive types are converted. In this case a number in a string is converted to a Number "2021" to 2021.

File snippets:
#base.config.js
export default {
  privateConfig() { return {}  },
  publicConfig() {
    return {
      year: "2021", // is converted to 2021
      years: ["2020", "2021"], // values remain string
      nextYear: {
        value: "2022" // is converted to 2022
      }
    }
  }
}
#nuxt.config 
import config from "./base.config";
export default {
  publicRuntimeConfig: config.publicConfig(),
  privateRuntimeConfig: config.privateConfig()
}
#Component.vue 
<script>
  mounted() {
     console.log(this.$config.year === 2021) // true
     console.log(this.$config.year === "2021") // false
     console.log(this.$config.years.indexOf(2021) !== -1) //true
     console.log(this.$config.years.indexOf("2021") !== -1) //true
  }
</script>

With the 'old' env properties this conversion didnt occur so it was predictable behaviour but this is not.
Because the checks are done against fields that are of type string, I want the config value to remain a string.

Any thoughts on why/where this is happening?
