### ISSUE TITLE
Customize jiti options

### ISSUE THREAD

**Issue by IlyaSemenov** [nuxt/nuxt.js#9350]
### Is your feature request related to a problem? Please describe.

My Nuxt server middleware relies on custom babel options. With Nuxt 2.15 and jiti my setup is broken.

I would like to be able to pass custom jiti options object (such as `{ transformOptions: ... }`) to fix that, however, currently Nuxt doesn't allow that. jiti is unilaterally called without any options whatsoever:

https://github.com/nuxt/nuxt.js/blob/2ec62617ced873fef97c73a6d7aa1271911ccfd5/packages/utils/src/cjs.js#L5-L7

### Describe the solution you'd like

I would like a new section in `nuxt.config.js`, either top-level `jiti` or `build.jiti`, with jiti options. This is similar to `build.babel` for that matter.

Example:

```ts
const config: NuxtConfig = {
  build: {
    jiti: {
      transformOptions: {
        babel: {
          babelrc: true,
        },
      },
    },
  },
}
```

### Describe alternatives you've considered

I'm going with this at the moment:

```ts
const config: NuxtConfig = {
  createRequire: p => {
    return jiti(typeof p === 'string' ? p : p.filename, {
      transformOptions: { ... }
    }
  }
}
```

This is:
a) undocumented
b) needs boilerplate copy/paste and unneeded knowledge about `p.filename`
c) possibly unreliable and/or will need more boilerplate for production build

**Comment by pi0** [comment]
Jiti is internally used in several places is also for loading nuxt.config itself. Supporting jiti customization in config can lead to caching issues and other problems since babel is only internally used and might be replaced in future versions with esbuild or swc transpilers. So I'm afraid we can never support this option. And specific use cases can be handled by replacing `createRequire` implementation.

The latest jiti release should cover declaration field support (https://github.com/unjs/jiti/issues/33) but feel free to open more feature requests in [jiti](https://github.com/unjs/jiti) repo if anything else missing.

**Comment by IlyaSemenov** [comment]
> Jiti is internally used in several globay places is also for loading nuxt.config itself.

Yes, and that's a pity, honestly. (I remember old times when I was able to simply run `NODE_OPTIONS='-r whatever-loader/register'` and Nuxt wasn't breaking this with its own runtime magic.)

Anyhow, as you've mentioned it, having optional `jiti.config.js` with *global* options (applied for loading `nuxt.config.ts` in particular) would be great then.

> babel is only internally used and might be replaced in future versions with esbuild or swc transpilers

Yes, I realise that, that is why I suggest to pass the entire jiti options and not only jiti babel options.

**Comment by pi0** [comment]
However, jiti is designed to be an opinioned solution that works out of the box (similar to prettier), supporting `jiti.config` makes sense :) Made https://github.com/unjs/jiti/issues/34 track.
