### ISSUE TITLE
Router Hooks define

### ISSUE THREAD

**Issue by k55k32** [nuxt/nuxt.js#94]
Can i do something when `router` is instantiated;
I wanne define a hook then like 'beforeEach';

Now I can do it in my component only.
```js
created () {
    this.$router.afterEach((r) => {
      console.log('after each', r);
    })
}
```
That's not a good way. I wanne a hook or callback in framework options. 
just like `require('my-custom-router-define.js')(router)` after `router` is instantiated.

I see the `plugins` options are require in `index.js`

Can you require some function we define after the `app` instantiated, and call the function use param `app`

**Comment by Atinux** [comment]
Hi @k55k32

Could you give me a use case of defining a beforeEach hook for you application?

**Comment by k55k32** [comment]
My project is a simple blog;
I wanne log the real pageview. 
The most simple way is use the beforeEach hook; When the route chagned send a log request to server; 
That's the case :)

**Comment by Atinux** [comment]
You can use the `routeChanged` from `$nuxt` (it's not explained yet in the documentation), but here an example of our website [nuxtjs.org](https://nuxtjs.org) to tell Google Analytics when a page changed: https://github.com/nuxt/nuxtjs.org/blob/master/plugins/ga.js

**Comment by ndarilek** [comment]
I wonder if it might be possible to expose the vue-router instance directly somehow so hooks might be defined the traditional way?

I'm looking to access the `afterEach` hook. It looks like this method will help me, but it seems like a good idea to stick as close to Vue as possible *where* possible.

Like, if you exposed the router instance somehow, you'd have less documentation to write, because you wouldn't need to document this custom event. You'd just note that the router is exposed somewhere, maybe on the `app` object passed into `onNuxtReady` or in the configuration.

In either case, thanks, I'll use the sample code to guide my implementation for now.

**Comment by Atinux** [comment]
You can include the router by:

import router from '~router'

See https://nuxtjs.org/guide/directory-structure#aliases

**Comment by gridsystem** [comment]
@Atinux if I were to import from ~router and set a beforeEach hook, e.g. to animate a scroll to the top of the page before the route transition, and I wanted that to take affect globally instead of defining it on a per-page basis, where would you suggest is the most nuxt-like way to add this code? I don't want to go into business for myself if there's already a recommended area for adding such things.

**Comment by nicroto** [comment]
In my case I am trying to add a beforeEach hook in order to guard navigations away from unsaved content. With the default hooks, page middleware or a plugin - I can handle the in-app navigations.

The problem is hard refresh of the page (Cmd/Ctrl + R) or navigating to another url from the browser uri field can't be caught if the beforeEach hook is attached after the instantiation of Vue.

@Atinux any suggestions?

**Comment by Atinux** [comment]
For the hard refresh, you need to use `window.onunload` (https://stackoverflow.com/questions/7080269/javascript-before-leaving-the-page) since vue-router does not listen on it.

**Comment by nicroto** [comment]
@Atinux Thanks for the reply. Are you sure this is the case? ([ref](https://forum.vuejs.org/t/router-beforeeach-if-manually-input-adress-in-browser-it-does-not-work/12461/3))

If Guillaume69 is correct the feature we would need to handle this would be to have a way to tap into vue-router before Vue is instantiated. I suspect this may be a useful feature for other things as well, but that's my only scenario right now.

Do you think such a feature would be reasonable thing to request?

**Comment by Atinux** [comment]
Actually you can use middleware for this and plugins for the `window.onunload` event ;)

**Comment by nicroto** [comment]
Oh, really? That's great!

So I can access the vue-router before the Vue instance is created?
Would you care to point me to some docs or an example I can see for this?

**Comment by Atinux** [comment]
This is a nice example: https://nuxtjs.org/faq/google-analytics

**Comment by nicroto** [comment]
Yeah, I've tried this already. I think I saw a comment of yours somewhere and I tried creating a plugin but it doesn't manage to catch the `Cmd + R` nor navigation through the browser uri field. I guess I will keep the low-level (window event) solution, for now.
