### ISSUE TITLE
GH-pages hosting with custom domain leads to error 404 on refresh

### ISSUE THREAD

**Issue by tasticad** [nuxt/nuxt.js#9436]
### Versions

- nuxt: 2.15.6
- node: 16.1.0

### Reproduction

https://lutherieurbaine93.com/

<details open>
<summary>Additional Details</summary>
<br>
nuxt.config.js contains:
<br>
<code>export default {
  router: {
    base: '/nuxt/'
  },
}</code>
<br><br>
Domain name (lutherieurbaine93.com) has an entry pointing to the Github account
</details>

### Steps to reproduce
- get to the website
- /nuxt/ (repo name) slug is added automatically
- refresh anywhere in the site → gives error 404

### What is Expected?
Refresh the page

### What is actually happening?
I have to remove manually `/nuxt` from the url to get to the page.

**Comment by Hanziness** [comment]
I'm not 100% sure, but I think I'm having the same issue, though it is probably more (or also) related to `vue-server-renderer`. I started experiencing it after a `yarn upgrade` and I couldn't pinpoint the issue as the error is very cryptic. The symptoms are what you say: the page can be loaded when navigated to using a `<nuxt-link />`, but the generated static site throws a 404 when the page is refreshed or if I directly navigate to said page. Running `yarn generate` after I upgrade `vue` (and `vue-template-compiler` and `vue-server-renderer` from `2.6.12` to `2.6.14`), I get this in the console (and thus in my Netlify build log):

<details>
<summary>Output</summary>

```
[ ... ]
Entrypoint app = server.js server.js.map
ℹ Merging Tailwind config from ~/tailwind.config.js                                                                                   nuxt:tailwindcss 17:32:34
ℹ Full static generation activated                                                                                                                     17:32:36
ℹ Generating output directory: dist/                                                                                                                   17:32:36
ℹ Generating pages with full static mode                                                                                                               17:32:37

 ERROR   /timer                                                                                                                                        17:32:37

TypeError: _vm._ssrAttr is not a function
    at render (node_modules/vue-material-design-icons/Stop.vue?6e70:1:0)
    at renderWithStyleInjection (node_modules/vue-loader/lib/runtime/componentNormalizer.js:83:0)
    at /home/<redacted>/Projects/Web/AnotherPomodoro/node_modules/@nuxt/vue-renderer/node_modules/vue-server-renderer/build.prod.js:1:65616
    at Ki (/home/<redacted>/Projects/Web/AnotherPomodoro/node_modules/@nuxt/vue-renderer/node_modules/vue-server-renderer/build.prod.js:1:65797)
    at i (/home/<redacted>/Projects/Web/AnotherPomodoro/node_modules/@nuxt/vue-renderer/node_modules/vue-server-renderer/build.prod.js:1:68813)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)

✔ Generated route "/"                                                                                                                                  17:32:37
✔ Generated route "/setup"                                                                                                                             17:32:37
✔ Client-side fallback created: 200.html                                                                                                               17:32:37
✔ Static manifest generated                                                                                                                            17:32:37
ℹ Generating sitemaps                                                                                                                                  17:32:37
✔ Generated /sitemap.xml                                                                                                                               17:32:37
Done in 26.98s.
```

</details>

## The error

`TypeError: _vm._ssrAttr is not a function` is the error I get when I refresh `/timer` while running `yarn dev`, which is also the reason why `/timer` is not getting generated.

The error seems to occur in the very first `.vue` file on the very first used component (removing said component makes the error point to the next component). Since the error occurs in `@nuxt/vue-renderer`, I'm guessing that the issue also has something to do with NuxtJS (and not `vue-material-design-icons` as the issue would make it seem so, though I'll try to check if it is indeed the culprit).

## Note on reproduction and a workaround

I could not reproduce this issue in a fresh project made with `create-nuxt-app`, but I'm experiencing it in [my project](https://github.com/Hanziness/AnotherPomodoro), which (unfortunately) has quite a lot of dependencies and is quite complex, so it might be that something entirely else is interfering. Though, if you wish, you can clone `master`, do `yarn install` and `yarn generate` without errors, then add

```
"vue": "2.6.14",
"vue-server-renderer": "2.6.14",
"vue-template-compiler": "2.6.14",
```

to `package.json`, do `yarn install` and observe the error thrown when running `yarn generate`.

Upgrading `nuxt` to `2.15.7` while pinning the aforementioned `vue`-related packages to `2.6.12` does not throw an error (even after `yarn upgrade`!). So for **a temporal workaround**, add

```
"vue": "2.6.12",
"vue-server-renderer": "2.6.12",
"vue-template-compiler": "2.6.12",
```

to your `package.json`.

Any hints regarding where to start looking (besides the, to me, not so helpful error messages) to find the root cause are welcome! Should I post this to the Vue issue tracker?

**Comment by tasticad** [comment]
Thank you @Hanziness for your reply! 

My `/dist` folder was firstly deployed on a repository branch (named `gh-pages`) so I've solved the problem by creating a [_user site_](https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site) repo dedicated to this folder.

Pointed the custom domain, cleaned up the cache (to avoid redirect loop issues) and voilà it is working all fine now 👍
