### ISSUE TITLE
How do you create a default page template for new pages to use

### ISSUE THREAD

**Issue by k16e-me** [nuxt/nuxt.js#9440]
Hi, can you take a look at my detailed (hopefully) explanation of this thorny issue I've had a while now with Nuxt? To summarize, I wanna be able to create a default page template under /pages say _slug.vue for new pages from a dir under /content to use to render. However, if no matching route (matching with filename in .md) is found then I still want the error 404 layout/template to load.

https://www.loom.com/share/30b0aef7fab24d35a09fc01409e35afe

Help appreciated. Gracias

**Comment by MichealPearce** [comment]
If you have a dynamic page in the root of the pages folder (I.e. `pages/_slug.vue`) then you won't get a 404 because technically every route will match that one. 

`$content` returns a promise you can catch like so:
```
async asyncData({$content, error, route}) {
	try {
		const data = await $content(route.pathname)
		return {data}
	} catch (error) {
		return error({
			statusCode: 404,
			message: 'page not found'
		})
	}
}
```
or simpler
```
asyncData({$content, error, route}) {
	return $content(route.pathname)
		.then(data => ({data}))
		.catch(() => error({
			statusCode: 404,
			message: 'page not found'
		})
}
```

Also a note on making layouts for child pages. This can be done by adding a `pages/example.vue`, a `pages/example` folder, and using `nuxt-child` like so:

```vue
<script>
// pages/admin.vue
export default {}
</script>

<template>
	<div class="admin-layout">
		<nuxt-child />
	</div>
</template>
```

```vue
<script>
// pages/admin/index.vue
export default {}
</script>

<template>
	<div class="admin-index">
		<h1>Admin Index</h1>
	</div>
</template>
```

`div.admin-index` will be wrapped in `div.admin-layout`. This could possibly work for `_slug.vue` and `_slug/index.vue` but I am not sure. Hoped this helped @k16e-me

**Comment by k16e-me** [comment]
Hi @MichealPearce thanks for taking the time. I've tried with your suggestions as best I know, tried a couple of things as I imagine it might look right but I'm not getting desired results.
