### ISSUE TITLE
With Tailwind: adding <style> to SFC breaks HMR

### ISSUE THREAD

**Issue by Akryum** [nuxt/nuxt.js#9546]
### Versions

- nuxt: 2.15.7
- node: 16.3.0

### Reproduction

https://github.com/Akryum/nuxt-issue-9546

(Project created from create-nuxt-app with Tailwind selected.)

### Steps to reproduce

- Open `components/home/Test.vue` and make changes to the template
- Save

### What is Expected?

- The component is updated on the page with HMR

### What is actually happening?

- The component is not updated on the page
- Need to do a full page refresh

---

Everything works correctly with `components/home/Test2.vue` (without the style block).

**Comment by HenrijsS** [comment]
Same here. It's updating some other file for me too. I'm using SCSS with Scoped styling in the component.
The first build isn't updating anything, then it updates again seeing a numeric file and then does a full page refresh.

This is the console output.
```
↻ Updated pages/any-page.vue                                                                                                        20:43:44

✔ Client
  Compiled successfully in 691.80ms

✔ Server
  Compiled successfully in 868.90ms

↻ Updated 1626457426452                                                                                                                  20:43:46

✔ Client
  Compiled successfully in 387.20ms

✔ Server
  Compiled successfully in 557.48ms
  ```
  
  ** This also happens when completely removing the style tag on the bottom of the page file.
  
  Also it sometimes replaces the numeric file with .eslintcache. Maybe that's the problem?

**Comment by ViniciusMoreira33** [comment]
same problem. have to do a full page refresh . also using Tailwind.

**Comment by Luffyyy** [comment]
Happening to me too. I'm using tailwind, but disabling it seems to not really help I think.

**Comment by Luffyyy** [comment]
After some testing, if you remove tailwind **and** delete the .nuxt folder it seems to fix itself so for now I too assume it's something to do with tailwind.

**Comment by manniL** [comment]
Possibly related: https://github.com/tailwindlabs/tailwindcss/issues/4968 and https://github.com/nuxt/postcss8/issues/18

**Comment by Luffyyy** [comment]
Only downgrading seems to help for now

**Comment by productfrontenddeveloper** [comment]
> Possibly related: [tailwindlabs/tailwindcss#4968](https://github.com/tailwindlabs/tailwindcss/issues/4968) and [nuxt/postcss8#18](https://github.com/nuxt/postcss8/issues/18)
> 
> Can someone try using `TAILWIND_MODE=watch nuxt dev`? ☺️

Hi @manniL When will you solve this problem, because we are working inefficiently.

**Comment by bezin** [comment]
@manniL Thanks for taking the time to look into this. However, setting `TAILWIND_MODE=watch` does not make it work.

**Comment by IsraelOrtuno** [comment]
I wonder if it has something to do with eslint too. I am facing the same issue as @HenrijsS and sometimes I see `.eslintcache` is triggering a new build. This works:

```
  buildModules: [
    ...
    ['@nuxtjs/eslint-module', { cache: false}],
    ...
  ],
```

In the other hand, I guess disabling eslint cache will result in slower build times.

Anyone with a better solution? Since Tailwiund 3 only works on PostCSS8, downgrading doesn't seem to be a solution anynore.

**Comment by slavanossar** [comment]
Also experiencing the issue where `.eslintcache` is triggering a hot reload, causing an endless loop. It's also being triggered by [Tailwind's Config Viewer](https://tailwindcss.nuxtjs.org/tailwind/viewer/), which is generating a timestamp file:

```
✔ Client
  Compiled successfully in 589.52ms

✔ Server
  Compiled successfully in 287.45ms

↻ Updated .eslintcache                                                                                                                                                                                                                                                                                                                                            22:44:04

✔ Client
  Compiled successfully in 563.40ms

✔ Server
  Compiled successfully in 217.34ms

↻ Updated 1646048646793
```

Similar to @IsraelOrtuno's solution, it can be fixed with

```js
export default {
  buildModules: [
    ['@nuxtjs/tailwindcss', { viewer: false }]
  }
}
```

Any idea why these files are suddenly triggering the hot reload? I haven't had any issues with this before, including on projects that use `.eslintcache` and have Tailwind's Config Viewer enabled.

**Comment by IsraelOrtuno** [comment]
I tried @slavanossar solution and enabling estlint cache:

```
export default {
  buildModules: [
    ['@nuxtjs/tailwindcss', { viewer: false }]
  }
}```

But still experiencing the infinite loop, this solution didn't work for me which makes this issue even more weird. Wondering if it has something with Tailwind 3 or PostCSS 8

**Comment by duboiss** [comment]
I have an infinite loop during my builds since my update of @nuxtjs/tailwindcss which contains tailwind 3.
<details>
<summary>Console logs</summary>
ℹ Listening on: http://localhost:3000/                                19:24:34

↻ Updated layouts/default.vue                                         19:25:02

✔ Client
  Compiled successfully in 1.61s

✔ Server
  Compiled successfully in 1.68s

↻ Updated .eslintcache                                                19:25:05

✔ Client
  Compiled successfully in 770.87ms

✔ Server
  Compiled successfully in 774.74ms

↻ Updated 1646072707762                                               19:25:07

✔ Client
  Compiled successfully in 642.74ms

✔ Server
  Compiled successfully in 778.50ms

↻ Updated .eslintcache                                                19:25:09

✔ Client
  Compiled successfully in 786.75ms

✔ Server
  Compiled successfully in 641.37ms

↻ Updated 1646072711588                                               19:25:11

✔ Client
  Compiled successfully in 621.53ms

✔ Server
  Compiled successfully in 731.45ms

↻ Updated .eslintcache                                                 19:25:13
</details>

Sometimes its ".eslintcache", other times random numbers.
By setting the `cache` property of eslint module to `false`, it works perfectly again. I see this as a temporary fix...
```js
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    ['@nuxtjs/eslint-module', { cache: false }],
    // https://go.nuxtjs.dev/stylelint
    '@nuxtjs/stylelint-module',
    // https://go.nuxtjs.dev/tailwindcss
    '@nuxtjs/tailwindcss',
  ],
```
Thanks a lot @IsraelOrtuno , even if it is not ideal it is better than removing all eslint packages.

**Comment by slavanossar** [comment]
> I tried @slavanossar solution and enabling estlint cache:
> 
> ```
> export default {
>   buildModules: [
>     ['@nuxtjs/tailwindcss', { viewer: false }]
>   }
> }
> ```
> 
> But still experiencing the infinite loop, this solution didn't work for me which makes this issue even more weird. Wondering if it has something to do with Tailwind 3 or PostCSS 8

Sorry I meant both your solution along with mine fixed my endless loop. However I just realised that I only needed my solution because the `.eslintcache` file was still present – deleting the `.eslintcache` file first and only using `{ cache: false }` is sufficient.

**Comment by gaodeng** [comment]
any news?
