### ISSUE TITLE
Integration with Meteor

### ISSUE THREAD

**Issue by alexandesigner** [nuxt/nuxt.js#955]
Guys.. I should very much praise the Nuxtjs I have been using extensively in my projects .. I would like to know the difficulty in integrating with Meteor as a data API?

We could use [Meteor client bundler](https://github.com/Urigo/meteor-client-bundler), but I could not configure it together. I think we need some small settings, can anyone help me understand how we can do it? 

_See article:_
[Leverage the power of Meteor with any client-side framework](https://blog.meteor.com/leverage-the-power-of-meteor-with-any-client-side-framework-bfb909141008)

**Comment by trusktr** [comment]
The title of that article is "Leverage the power of Meteor with any client-side framework".

Nuxt isn't a client-side framework, it's a full-stack framework. It's easy to import just Vue into a Meteor app.

But Nuxt includes it's own backend (obviously because SSR). How would we merge it with Meteor?

One way could be to use a DDP client to communicate with an external Meteor server.

You could also try `require()`ing the result made with Meteor Client Bundler, as that will execute it. Then maybe that will load all the Meteor stuff into the `global` of your Nuxt app (f.e. the global `Meteor` variable and other things). It might possibly work, then you could use publications, reactive vars, etc, like you normally would, along with Nuxt stuff. I haven't tried that yet though, it might break. You'd also need to learn which ENV vars Meteor would expect to see, and make sure you have your Nuxt app setting those up.

**Comment by trusktr** [comment]
That article's title was a misnomer. It **_does_** show how to import on the server side too!

Action doesn't seem to be needed here in this issue, it seems that you can import the APIs that you need using meteor-client-bundler, then just put all your Meteor code inside your custom-built project.

If you give it a shot, let us know how it goes.

**Comment by alexandesigner** [comment]
@trusktr Excellent!! Thank you very much for this explanation.

Just another little question, how do I use [externals](https://webpack.js.org/configuration/externals/)? in Nuxt.

Why in case I need to set this external:

```
externals: function (context, request, callback) {
   var match = request.match(/^meteor\/(.+)$/);
   var pack = match && match[1];
   if (pack) {
     callback(null, ‘Package[“‘ + pack + ‘“]’);
   }
 }
```

I have not tried this integration either, but I will do so now this weekend.

**Comment by trusktr** [comment]
If Nuxt uses Webpack, then yeah something like that should help. I haven't tried myself yet though.

**Comment by victorlambert** [comment]
I'm also trying to make [meteor-client-bundler](https://github.com/Urigo/meteor-client-bundler) working with nuxt.

@alexandesigner for the externals, you have to use the [extend](https://nuxtjs.org/api/configuration-build#extend) function in your config file.

`  
...
build: {
    extend(config, ctx) {
      config.resolve.alias['api'] = resolve(__dirname, 'api/server');
      config.externals = [resolveExternals];
    }
  },
...
function resolveExternals(context, request, callback) {
  return resolveMeteor(request, callback) ||
    callback();
}

function resolveMeteor(request, callback) {
  var match = request.match(/^meteor\/(.+)$/);
  var pack = match && match[1];

  if (pack) {
    callback(null, 'Package["' + pack + '"]');
    return true;
  }
}
`
