### ISSUE TITLE
nuxtServerInit - how to handle errors?

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#964]
Hi!

I need to initialize store with the data from the remote server.
I do it in the nuxtServerInit.

How can I handle error (eg. no connection to the remote server) in the nuxtServerInit?

I ask becouse documentation says that there in no error in the context:

> The context is given to nuxtServerInit as the 2nd argument, it is the same as the data or fetch method **except that context.redirect() and context.error() are omitted**.

**Comment by dohomi** [comment]
@awronski just an idea: can you redirect to an error page? I think redirect is part of the context.. but I'm not sure. This is how I handle errors in middleware, not sure if the context is correct for onServerInit

**Comment by awronski** [comment]
No, I cannot. Redirect is not available in the context in the nuxtServerInit.

I would like to show a page that service is not available right now.
Any ideas?


Thanks!

**Comment by awronski** [comment]
@alexchopin Alex, would it be possible to add context.error to the nuxtServerInit?

**Comment by alexchopin** [comment]
Hi @awronski, 
We can't because the nuxtServerInit is called before we get access to the router instance.
What I'm usually doing in this case, is set an error variable in the store and check with a middleware the state variable.
It allows me to use redirect or error page.
![](https://nuxtjs.org/nuxt-schema.png)

**Comment by awronski** [comment]
@alexchopin Thank you, great idea.
