### ISSUE TITLE
Is it possible to watch server-side code without re-rendering client-side code?

### ISSUE THREAD

**Issue by jamesAtcodeninja** [nuxt/nuxt.js#983]
Every time I make changes to server-side code in `/app`, the entire project rebuilds itself from scratch, including `/resources`. Is there a way to prevent this so that changes in `/app` only rebuilds `/app`?

**Comment by uptownhr** [comment]
Been dealing with this as well. I assume you are using nuxt as a middleware.

First off, I don't think there is a direct solution to this, because you're entire app does restart on file change and that in turn restarts webpack/nuxt. You do want the app to restart but not nuxt, and unfortunately not possible. 

However, I tackled this problem by creating another server and  proxying requests from the client-server where nuxt lives. I did this for more than the restarting issue but something to consider for yourself. I've thought about using HMR on the server-side to tackle this as well but ended becoming too complicated. Maybe the nuxt team can try it out :)

Lastly, you can add --ignore=dir if you're using nodemon. If you're starting from the nuxt-express templates that use `backpack`, i cant help you... There docs dont mention how to exclude watch dirs.

**Comment by jamesAtcodeninja** [comment]
I'm using the `adonuxt` framework and I also ended up taking the route you took, albeit there's a few more `if` statements throughout the code now.

**Comment by alexchopin** [comment]
https://github.com/nuxt-community/adonuxt-template/issues/53

**Comment by alanaasmaa** [comment]
@uptownhr @jamesAtcodeninja Do you have any examples, i tried to to that aswell but not by splitting servers
